// World gazetteer — the six kingdoms, 7,250 BR.
// Coordinates are pixels in the atlas image space (7680 x 3962), origin top-left.
// Names & lore cross-checked against "Map of the world during the 7,250 BR" (canon doc).
// cat: region | capital | city | town | water | river | island | forest | territory | landmark
// k: kingdom the place belongs to (omitted for open seas / neutral sites)

const PLACES = [
  { n: "Gherci", cat: "region", x: 4120, y: 1840, k: "Gherci", d: "Largest and most central kingdom of the pre-Empire era. Capital: Tarmet." },
  { n: "Coelum", cat: "region", x: 4235, y: 975, k: "Coelum", d: "The northern 'Forsaken Land'. Capital: Atriki, beside Lake Trang." },
  { n: "Vikitsv", cat: "region", x: 6055, y: 1830, k: "Vikitsv", d: "Mountain kingdom of the eastern peninsula, radiating from Mount Aicren. Capital: Berlailia." },
  { n: "Equateiy", cat: "region", x: 6515, y: 1185, k: "Equateiy", d: "Highland kingdom of the northeast. Capital: Ociyaran." },
  { n: "Ociyaran", cat: "capital", x: 6605, y: 1245, k: "Equateiy", d: "Capital of Equateiy, in the central highlands." },
  { n: "Aicruae", cat: "region", x: 2170, y: 1920, k: "Aicruae", d: "Westernmost of the six kingdoms of the pre-Empire era. Capital: Lajazer." },
  { n: "Lajazer", cat: "capital", x: 2270, y: 1785, k: "Aicruae", d: "Capital of Aicruae, at the center of the kingdom." },
  { n: "Pireaynea", cat: "region", x: 3020, y: 2230, k: "Pireaynea", d: "South-central kingdom directly east of Aicruae, across the Demon's Pit. Capital: Civer." },
  { n: "Berlailia", cat: "capital", x: 6795, y: 2300, k: "Vikitsv", d: "Capital of Vikitsv, on the shoulder of Mount Aicren." },
  { n: "Caduto", cat: "region", x: 6590, y: 1565, k: "Vikitsv", d: "Trade crossing on the Vikitsv-Equateiy border." },
  { n: "Atriki", cat: "capital", x: 3925, y: 710, k: "Coelum", d: "Capital of Coelum, beside Lake Trang." },
  { n: "Tarmet", cat: "capital", x: 4145, y: 2040, k: "Gherci", d: "Capital of Gherci, ringed by Greater Gherci, the Outer Walls, Asmeta, Tanya Beka and Mother's Hip." },
  { n: "Civer", cat: "capital", x: 3165, y: 2420, k: "Pireaynea", d: "Capital of Pireaynea, on its southern lake along the central river." },
  { n: "Greater Gherci", cat: "region", x: 4200, y: 2170, k: "Gherci", d: "Core province ringing the capital Tarmet." },
  { n: "Lower Gherci", cat: "region", x: 3775, y: 2390, k: "Gherci", d: "The southwestern river country of Gherci, draining to the Fetora Sea." },
  { n: "Melert", cat: "region", x: 1850, y: 1990, k: "Aicruae", d: "Western coastal province of Aicruae; export region." },
  { n: "Eynora", cat: "city", x: 3555, y: 105, k: "Coelum", d: "In the Kingdom of Coelum, about 575 mi northwest of Atriki, near Lagora and Tilnyeau." },
  { n: "Lagora", cat: "city", x: 3500, y: 205, k: "Coelum", d: "In the Kingdom of Coelum, about 525 mi northwest of Atriki, near Eynora and Tilnyeau." },
  { n: "Tilnyeau", cat: "city", x: 3665, y: 255, k: "Coelum", d: "In the Kingdom of Coelum, about 425 mi northwest of Atriki, near Skya and Lagora." },
  { n: "Port Rebadeen", cat: "city", x: 4535, y: 135, k: "Coelum", d: "In the Kingdom of Coelum, about 675 mi northeast of Atriki, near Niarn and Ricna." },
  { n: "Port Aresca", cat: "city", x: 3195, y: 875, k: "Gherci", d: "In the Kingdom of Gherci, about 1200 mi northwest of Tarmet, near Corocco and Etanda." },
  { n: "Port Theli", cat: "city", x: 3610, y: 905, k: "Coelum", d: "In the Kingdom of Coelum, about 300 mi southwest of Atriki, near Neaea and Seppegiu." },
  { n: "Port Vsar", cat: "city", x: 2900, y: 1110, k: "Aicruae", d: "In the Kingdom of Aicruae, about 725 mi northeast of Lajazer, near Raiya and Linjat." },
  { n: "Port Esery", cat: "city", x: 2625, y: 1115, k: "Aicruae", d: "In the Kingdom of Aicruae, about 600 mi northeast of Lajazer, near Linjat and Kunus." },
  { n: "Port Vento", cat: "city", x: 2370, y: 1230, k: "Aicruae", d: "In the Kingdom of Aicruae, about 450 mi north of Lajazer, near Sreton and Waeca." },
  { n: "Port Volpa", cat: "city", x: 6505, y: 900, k: "Equateiy", d: "In the Kingdom of Equateiy, about 275 mi north of Ociyaran, near Foce and Querceta." },
  { n: "Port Quale", cat: "city", x: 1860, y: 2200, k: "Aicruae", d: "In the Kingdom of Aicruae, about 475 mi southwest of Lajazer, near Teyetes and Bareta." },
  { n: "Port Ols", cat: "city", x: 2595, y: 2765, k: "Pireaynea", d: "In the Kingdom of Pireaynea, about 525 mi southwest of Civer, near Vasco and Sindbir." },
  { n: "Port Pontesa", cat: "city", x: 3995, y: 2780, k: "Gherci", d: "In the Kingdom of Gherci, about 600 mi south of Tarmet, near Aoin and Pontata." },
  { n: "Port Linnos", cat: "city", x: 4915, y: 2900, k: "the far-eastern territories", d: "In the far-eastern territories beyond Gherci's border, about 175 mi southwest of Mireb, near Dordbin and Limn." },
  { n: "Port Sael", cat: "city", x: 7215, y: 2780, k: "Vikitsv", d: "In the Kingdom of Vikitsv, about 500 mi southeast of Berlailia, near Qunag and Cael'mu." },
  { n: "Onmore", cat: "city", x: 5075, y: 440, k: "Coelum", d: "In the Kingdom of Coelum, about 950 mi east of Atriki, near Riyen and Niarn." },
  { n: "Gondes", cat: "city", x: 3870, y: 1315, k: "Gherci", d: "In the Kingdom of Gherci, about 625 mi north of Tarmet, near Adani and Resia." },
  { n: "Aishae", cat: "region", x: 2240, y: 1555, k: "Aicruae", d: "Northern port region of Aicruae." },
  { n: "Haleker", cat: "region", x: 2460, y: 1970, k: "Aicruae", d: "Eastern Aicruae, seat of House Vika, on the Pireaynea border." },
  { n: "Baeistic", cat: "region", x: 2920, y: 1895, k: "Pireaynea", d: "Northern region of Pireaynea." },
  { n: "Urdeio", cat: "region", x: 3390, y: 2105, k: "Pireaynea", d: "Eastern region of Pireaynea, toward the Lower Gherci." },
  { n: "Aseraga", cat: "region", x: 2520, y: 2215, k: "Pireaynea", d: "Southwestern region of Pireaynea." },
  { n: "Feacener", cat: "region", x: 2920, y: 2425, k: "Pireaynea", d: "Southern coastal region of Pireaynea." },
  { n: "Coelys", cat: "city", x: 3125, y: 1605, k: "Coelum", d: "In the Kingdom of Coelum, about 950 mi southwest of Atriki, near Ezon and Croco. As labeled on the Pireaynea map — canon names this northern kingdom Coelum." },
  { n: "Rietha", cat: "city", x: 3670, y: 1660, k: "Gherci", d: "In the Kingdom of Gherci, about 475 mi northwest of Tarmet, near Nyes and Kessa." },
  { n: "Kessa", cat: "city", x: 3715, y: 1775, k: "Gherci", d: "In the Kingdom of Gherci, about 400 mi northwest of Tarmet, near Rietha and Belune." },
  { n: "Loria", cat: "city", x: 5040, y: 2180, k: "Gherci", d: "In the Kingdom of Gherci, about 725 mi east of Tarmet, near Lethe and Maru." },
  { n: "Mireb", cat: "city", x: 5015, y: 2710, k: "the far-eastern territories", d: "In the far-eastern territories beyond Gherci's border, about 175 mi northeast of Port Linnos, near Dordbin and Demre." },
  { n: "Amba", cat: "city", x: 5455, y: 2640, k: "the far-eastern territories", d: "In the far-eastern territories beyond Gherci's border, about 350 mi east of Mireb, near Selvet and Hagiore." },
  { n: "Gai", cat: "city", x: 5150, y: 2530, k: "Gherci", d: "In the Kingdom of Gherci, about 900 mi southeast of Tarmet, near Demia and Maru." },
  { n: "Reskt", cat: "city", x: 6420, y: 2130, k: "Vikitsv", d: "In the Kingdom of Vikitsv, about 325 mi northwest of Berlailia, near Daltsen and Sehrok." },
  { n: "Qunag", cat: "city", x: 6990, y: 2890, k: "Vikitsv", d: "In the Kingdom of Vikitsv, about 500 mi south of Berlailia, near Gjen and Namilna." },
  { n: "Murok", cat: "city", x: 6355, y: 2920, k: "Vikitsv", d: "In the Kingdom of Vikitsv, about 600 mi southwest of Berlailia, near Junjeo and Bohan." },
  { n: "Tagrim", cat: "city", x: 4495, y: 2910, k: "Gherci", d: "In the Kingdom of Gherci, about 750 mi south of Tarmet, near Oskba and Esku." },
  { n: "Basar Tari", cat: "city", x: 2150, y: 2640, k: "Aicruae", d: "In the Kingdom of Aicruae, about 700 mi south of Lajazer, near Laona and Audin. The royal prison and unofficial UIB criminal hub, in the southern badlands." },
  { n: "Oscan", cat: "city", x: 3480, y: 1520, k: "Coelum", d: "In the Kingdom of Coelum, about 725 mi southwest of Atriki, near Cardoric and Lujian." },
  { n: "Nabuchan", cat: "city", x: 4795, y: 1060, k: "Coelum", d: "In the Kingdom of Coelum, about 750 mi east of Atriki, near Sebrof and Nalchal." },
  { n: "Sebrof", cat: "city", x: 4815, y: 1195, k: "Coelum", d: "In the Kingdom of Coelum, about 800 mi southeast of Atriki, near Nabuchan and Ridal." },
  { n: "Bohan", cat: "city", x: 6005, y: 2880, k: "Vikitsv", d: "In the Kingdom of Vikitsv, about 775 mi southwest of Berlailia, near Gilsa and Ompol." },
  { n: "Kuldar", cat: "city", x: 4255, y: 2735, k: "Gherci", d: "In the Kingdom of Gherci, about 550 mi south of Tarmet, near Esku and Drun." },
  { n: "Hadiber", cat: "region", x: 2065, y: 1690, k: "Aicruae", d: "Western region of Aicruae." },
  { n: "The Quather Sea", cat: "water", x: 2080, y: 565, d: "near Port Vento and Veric." },
  { n: "The Oberya Sea", cat: "water", x: 7400, y: 790, d: "near Ys and Tesora." },
  { n: "The Fetora Sea", cat: "water", x: 3190, y: 3180, d: "near Sindbir and Port Ols." },
  { n: "Henem Bay", cat: "water", x: 4775, y: 295, d: "Coelum's northern coast; also Gherci's northern port access." },
  { n: "Rium Harbor", cat: "water", x: 4860, y: 700, k: "Coelum", d: "In the Kingdom of Coelum, about 750 mi east of Atriki, near Noramec and Riyen. Coelum's northeastern harbor." },
  { n: "Lake Trang", cat: "water", x: 4110, y: 805, k: "Coelum", d: "In the Kingdom of Coelum, about 175 mi southeast of Atriki, near Maharg and Erygal. The great lake at Coelum's heart, beside the capital Atriki." },
  { n: "Honlo Lake", cat: "water", x: 4345, y: 1455, k: "Gherci", d: "In the Kingdom of Gherci, about 500 mi north of Tarmet, near Inqua and Hoan. The great lake of north-central Gherci, below the Coelum border." },
  { n: "The Quather Islands", cat: "island", x: 1845, y: 1460, d: "Island cluster off Aicruae's northwest; canon also calls these the Northern Isles." },
  { n: "The Cidet", cat: "island", x: 1395, y: 2145, d: "The temple of the gods — a sacred isle west of Aicruae, never colonized." },
  { n: "The Mystic Isles", cat: "island", x: 1300, y: 2730, d: "Far southwestern archipelago." },
  { n: "Gogla", cat: "town", x: 7025, y: 2125, k: "Vikitsv", d: "In the Kingdom of Vikitsv, about 225 mi northeast of Berlailia, near Negiet and Gaedu. Settlement of Vikitsv's eastern wall." },
  { n: "Tigrrei Forest", cat: "forest", x: 3320, y: 1670, k: "Gherci", d: "In the Kingdom of Gherci, about 725 mi northwest of Tarmet, near Olune and Shaer. Western border forest shared by Aicruae, Pireaynea and Gherci." },
  { n: "Abren Forest", cat: "forest", x: 3785, y: 1470, k: "Gherci", d: "In the Kingdom of Gherci, about 550 mi northwest of Tarmet, near Nyes and Adani. Woodland belt along Gherci's northern marches, below the Coelum border." },
  { n: "Aro Forest", cat: "forest", x: 6725, y: 1090, k: "Equateiy", d: "In the Kingdom of Equateiy, about 150 mi northeast of Ociyaran, near Doresi and Neska. The great forest belt along Equateiy's eastern reaches, by the Oberya cliffs." },
  { n: "Nedi Forest", cat: "forest", x: 6095, y: 1685, k: "Equateiy", d: "In the Kingdom of Equateiy, about 525 mi southwest of Ociyaran, near Esteraia and Velsa. Southwestern woodland of Equateiy, sloping toward the Vikitsv frontier." },
  { n: "Silora Forest", cat: "forest", x: 6705, y: 2550, k: "Vikitsv", d: "In the Kingdom of Vikitsv, about 200 mi south of Berlailia, near Sahla and Galmun. The Silora foothills of Vikitsv." },
  { n: "Tehr Tari Naos", cat: "territory", x: 5020, y: 1385, k: "the far-eastern territories", d: "In the far-eastern territories beyond Gherci's border, about 1050 mi north of Mireb, near Hagiora and Semhol." },
  { n: "Dor Tari Naos", cat: "territory", x: 5320, y: 1885, k: "the far-eastern territories", d: "In the far-eastern territories beyond Gherci's border, about 600 mi north of Amba, near Tehron and Tusjin." },
  { n: "Anthela Naosic", cat: "territory", x: 5320, y: 1760, k: "the far-eastern territories", d: "In the far-eastern territories beyond Gherci's border, about 700 mi north of Amba, near Bellaria and Tehron." },
  { n: "Aryanara's territory", cat: "territory", x: 5310, y: 1790, k: "the far-eastern territories", d: "In the far-eastern territories beyond Gherci's border, about 700 mi north of Amba, near Tehron and Bellaria. Far-eastern territory beyond Gherci's dashed border." },
  { n: "Vekta's territory", cat: "territory", x: 5065, y: 1650, k: "the far-eastern territories", d: "In the far-eastern territories beyond Gherci's border, about 850 mi north of Mireb, near Semhol and Belnara. Far-eastern territory beyond Gherci's dashed border." },
  { n: "Amberactserun", cat: "territory", x: 5150, y: 1560, k: "the far-eastern territories", d: "In the far-eastern territories beyond Gherci's border, about 900 mi north of Amba, near Hagiora and Semhol." },
  { n: "Naos Adwe", cat: "territory", x: 5345, y: 2345, k: "the far-eastern territories", d: "In the far-eastern territories beyond Gherci's border, about 250 mi north of Amba, near Hagn and Tsir." },
  { n: "Hagia Demre", cat: "territory", x: 5215, y: 2425, k: "the far-eastern territories", d: "In the far-eastern territories beyond Gherci's border, about 250 mi northwest of Amba, near Tsir and Demre." },
  { n: "The Magic Tower", cat: "landmark", x: 6770, y: 2410, k: "Vikitsv", d: "In the Kingdom of Vikitsv, about 90 mi south of Berlailia, near Sahla and Gaedu. On the terraces just below Berlailia." },
  { n: "Mount Aicren", cat: "landmark", x: 6685, y: 2435, k: "Vikitsv", d: "In the Kingdom of Vikitsv, about 150 mi southwest of Berlailia, near Sahla and Byeola. The central massif of Vikitsv; the whole kingdom radiates from it." },
  { n: "Mother's Hip", cat: "landmark", x: 4275, y: 2040, k: "Gherci", d: "In the Kingdom of Gherci, about 100 mi east of Tarmet, near Malin and Tanya Beka." },
  { n: "Outer Walls", cat: "landmark", x: 4085, y: 2095, k: "Gherci", d: "In the Kingdom of Gherci, about 60 mi southwest of Tarmet, near Asmeta and Lendara." },
  { n: "Skya", cat: "town", x: 3805, y: 160, k: "Coelum", d: "In the Kingdom of Coelum, about 450 mi north of Atriki, near Tilnyeau and Eynora." },
  { n: "Yleka", cat: "town", x: 4040, y: 370, k: "Coelum", d: "In the Kingdom of Coelum, about 275 mi north of Atriki, near Eryte and Slaia." },
  { n: "Ricna", cat: "town", x: 4340, y: 420, k: "Coelum", d: "In the Kingdom of Coelum, about 400 mi northeast of Atriki, near Snurb and Gorma." },
  { n: "Niarn", cat: "town", x: 4615, y: 425, k: "Coelum", d: "In the Kingdom of Coelum, about 600 mi east of Atriki, near Gorma and Riyen." },
  { n: "Eryte", cat: "town", x: 4020, y: 535, k: "Coelum", d: "In the Kingdom of Coelum, about 150 mi northeast of Atriki, near Yleka and Nisclair." },
  { n: "Snurb", cat: "town", x: 4280, y: 520, k: "Coelum", d: "In the Kingdom of Coelum, about 325 mi northeast of Atriki, near Ricna and Ortuqil." },
  { n: "Gorma", cat: "town", x: 4465, y: 520, k: "Coelum", d: "In the Kingdom of Coelum, about 450 mi east of Atriki, near Ortuqil and Ricna." },
  { n: "Ortuqil", cat: "town", x: 4420, y: 620, k: "Coelum", d: "In the Kingdom of Coelum, about 400 mi east of Atriki, near Gorma and Snurb." },
  { n: "Riyen", cat: "town", x: 4685, y: 605, k: "Coelum", d: "In the Kingdom of Coelum, about 600 mi east of Atriki, near Eskert and Niarn." },
  { n: "Nisclair", cat: "town", x: 3895, y: 650, k: "Coelum", d: "In the Kingdom of Coelum, about 50 mi northwest of Atriki, near Eryte and Eskol." },
  { n: "Maharg", cat: "town", x: 4215, y: 710, k: "Coelum", d: "In the Kingdom of Coelum, about 225 mi east of Atriki, near Snurb and Ortuqil." },
  { n: "Eskert", cat: "town", x: 4610, y: 715, k: "Coelum", d: "In the Kingdom of Coelum, about 550 mi east of Atriki, near Riyen and Noramec." },
  { n: "Noramec", cat: "town", x: 4785, y: 825, k: "Coelum", d: "In the Kingdom of Coelum, about 700 mi east of Atriki, near Nalchal and Eskert." },
  { n: "Eskol", cat: "town", x: 3890, y: 870, k: "Coelum", d: "In the Kingdom of Coelum, about 125 mi south of Atriki, near Erygal and Nisclair." },
  { n: "Nalochl", cat: "town", x: 4435, y: 895, k: "Coelum", d: "In the Kingdom of Coelum, about 425 mi east of Atriki, near Eskert and Ridal." },
  { n: "Nalchal", cat: "town", x: 4935, y: 900, k: "Coelum", d: "In the Kingdom of Coelum, about 825 mi east of Atriki, near Noramec and Nabuchan." },
  { n: "Erygal", cat: "town", x: 3995, y: 940, k: "Coelum", d: "In the Kingdom of Coelum, about 200 mi south of Atriki, near Eskol and Lagowyal." },
  { n: "Negel", cat: "town", x: 4210, y: 1100, k: "Coelum", d: "In the Kingdom of Coelum, about 375 mi southeast of Atriki, near Lagowyal and Camruthar." },
  { n: "Ridal", cat: "town", x: 4585, y: 1105, k: "Coelum", d: "In the Kingdom of Coelum, about 625 mi southeast of Atriki, near Camruthar and Nabuchan." },
  { n: "Lagowyal", cat: "town", x: 4080, y: 1165, k: "Coelum", d: "In the Kingdom of Coelum, about 375 mi south of Atriki, near Negel and Erygal." },
  { n: "Camruthar", cat: "town", x: 4445, y: 1195, k: "Coelum", d: "In the Kingdom of Coelum, about 575 mi southeast of Atriki, near Ridal and Negel." },
  { n: "Inqua", cat: "town", x: 4415, y: 1325, k: "Gherci", d: "In the Kingdom of Gherci, about 600 mi north of Tarmet, near Oryur and Garen." },
  { n: "Resia", cat: "town", x: 4035, y: 1370, k: "Gherci", d: "In the Kingdom of Gherci, about 550 mi north of Tarmet, near Adani and Inqwe." },
  { n: "Corocco", cat: "town", x: 3270, y: 955, k: "Gherci", d: "In the Kingdom of Gherci, about 1100 mi northwest of Tarmet, near Port Aresca and Etanda." },
  { n: "Etanda", cat: "town", x: 3115, y: 1010, k: "Gherci", d: "In the Kingdom of Gherci, about 1150 mi northwest of Tarmet, near Port Aresca and Corocco." },
  { n: "Neaea", cat: "town", x: 3425, y: 1000, k: "Coelum", d: "In the Kingdom of Coelum, about 450 mi southwest of Atriki, near Seppegiu and Coloni." },
  { n: "Seppegiu", cat: "town", x: 3475, y: 1095, k: "Coelum", d: "In the Kingdom of Coelum, about 475 mi southwest of Atriki, near Coloni and Neaea." },
  { n: "Linjat", cat: "town", x: 2725, y: 1175, k: "Aicruae", d: "In the Kingdom of Aicruae, about 600 mi northeast of Lajazer, near Baramq and Port Esery." },
  { n: "Osegri", cat: "town", x: 3145, y: 1155, k: "Coelum", d: "In the Kingdom of Coelum, about 725 mi southwest of Atriki, near Rioda and Tenda." },
  { n: "Rioda", cat: "town", x: 3280, y: 1140, k: "Coelum", d: "In the Kingdom of Coelum, about 625 mi southwest of Atriki, near Tenda and Osegri." },
  { n: "Coloni", cat: "town", x: 3500, y: 1185, k: "Coelum", d: "In the Kingdom of Coelum, about 500 mi southwest of Atriki, near Seppegiu and Tropie." },
  { n: "Tiamma", cat: "town", x: 3680, y: 1180, k: "Coelum", d: "In the Kingdom of Coelum, about 425 mi southwest of Atriki, near Masotom and Coloni." },
  { n: "Tenda", cat: "town", x: 3265, y: 1220, k: "Coelum", d: "In the Kingdom of Coelum, about 675 mi southwest of Atriki, near Gelona and Rioda." },
  { n: "Tropie", cat: "town", x: 3410, y: 1220, k: "Coelum", d: "In the Kingdom of Coelum, about 575 mi southwest of Atriki, near Coloni and Gelona." },
  { n: "Buion", cat: "town", x: 2520, y: 1250, k: "Aicruae", d: "In the Kingdom of Aicruae, about 475 mi northeast of Lajazer, near Waeca and Birmya." },
  { n: "Kunus", cat: "town", x: 2635, y: 1255, k: "Aicruae", d: "In the Kingdom of Aicruae, about 525 mi northeast of Lajazer, near Baramq and Buion." },
  { n: "Baramq", cat: "town", x: 2725, y: 1250, k: "Aicruae", d: "In the Kingdom of Aicruae, about 550 mi northeast of Lajazer, near Linjat and Paler." },
  { n: "Raiya", cat: "town", x: 2825, y: 1245, k: "Aicruae", d: "In the Kingdom of Aicruae, about 625 mi northeast of Lajazer, near Baramq and Linjat." },
  { n: "Waeca", cat: "town", x: 2440, y: 1285, k: "Aicruae", d: "In the Kingdom of Aicruae, about 425 mi north of Lajazer, near Borgest and Buion." },
  { n: "Sreton", cat: "town", x: 2330, y: 1300, k: "Aicruae", d: "In the Kingdom of Aicruae, about 400 mi north of Lajazer, near Borgest and Port Vento." },
  { n: "Gelona", cat: "town", x: 3310, y: 1280, k: "Coelum", d: "In the Kingdom of Coelum, about 675 mi southwest of Atriki, near Tenda and Eloe." },
  { n: "Brielega", cat: "town", x: 3515, y: 1285, k: "Coelum", d: "In the Kingdom of Coelum, about 575 mi southwest of Atriki, near Coloni and Egodi." },
  { n: "Masotom", cat: "town", x: 3690, y: 1265, k: "Coelum", d: "In the Kingdom of Coelum, about 475 mi southwest of Atriki, near Tiamma and Renzolo." },
  { n: "Birmya", cat: "town", x: 2555, y: 1345, k: "Aicruae", d: "In the Kingdom of Aicruae, about 425 mi northeast of Lajazer, near Buion and Kunus." },
  { n: "Borgest", cat: "town", x: 2385, y: 1350, k: "Aicruae", d: "In the Kingdom of Aicruae, about 350 mi north of Lajazer, near Sreton and Lera Mea." },
  { n: "Rachia", cat: "town", x: 2900, y: 1325, k: "Coelum", d: "In the Kingdom of Coelum, about 950 mi southwest of Atriki, near Tagre and Anaan." },
  { n: "Mossina", cat: "town", x: 3155, y: 1310, k: "Coelum", d: "In the Kingdom of Coelum, about 775 mi southwest of Atriki, near Lioe and Anaan." },
  { n: "Anaan", cat: "town", x: 3020, y: 1340, k: "Coelum", d: "In the Kingdom of Coelum, about 875 mi southwest of Atriki, near Tophercris and Rachia." },
  { n: "Paler", cat: "town", x: 2720, y: 1335, k: "Aicruae", d: "In the Kingdom of Aicruae, about 500 mi northeast of Lajazer, near Liviao and Baramq." },
  { n: "Eloe", cat: "town", x: 3350, y: 1345, k: "Coelum", d: "In the Kingdom of Coelum, about 675 mi southwest of Atriki, near Vannigio and Gelona." },
  { n: "Lioe", cat: "town", x: 3235, y: 1360, k: "Coelum", d: "In the Kingdom of Coelum, about 750 mi southwest of Atriki, near Mossina and Gelona." },
  { n: "Egodi", cat: "town", x: 3440, y: 1365, k: "Coelum", d: "In the Kingdom of Coelum, about 650 mi southwest of Atriki, near Cardoric and Eloe." },
  { n: "Renzolo", cat: "town", x: 3635, y: 1360, k: "Coelum", d: "In the Kingdom of Coelum, about 575 mi southwest of Atriki, near Selve and Masotom." },
  { n: "Tagre", cat: "town", x: 2830, y: 1375, k: "Coelum", d: "In the Kingdom of Coelum, about 1025 mi southwest of Atriki, near Rachia and Giagior." },
  { n: "Veric", cat: "town", x: 2245, y: 1300, k: "Aicruae", d: "In the Kingdom of Aicruae, about 375 mi north of Lajazer, near Sreton and Lera Mea." },
  { n: "Lera Mea", cat: "town", x: 2320, y: 1390, k: "Aicruae", d: "In the Kingdom of Aicruae, about 325 mi north of Lajazer, near Fordege and Borgest." },
  { n: "Senalda", cat: "town", x: 6390, y: 845, k: "Equateiy", d: "In the Kingdom of Equateiy, about 350 mi northwest of Ociyaran, near Cala and Port Volpa." },
  { n: "Cala", cat: "town", x: 6300, y: 925, k: "Equateiy", d: "In the Kingdom of Equateiy, about 350 mi northwest of Ociyaran, near Senna and Senalda." },
  { n: "Senna", cat: "town", x: 6300, y: 990, k: "Equateiy", d: "In the Kingdom of Equateiy, about 325 mi northwest of Ociyaran, near Cala and Sye." },
  { n: "Lidresa", cat: "town", x: 6195, y: 1055, k: "Equateiy", d: "In the Kingdom of Equateiy, about 350 mi northwest of Ociyaran, near Breno and Vallaforta." },
  { n: "Vallaforta", cat: "town", x: 6300, y: 1085, k: "Equateiy", d: "In the Kingdom of Equateiy, about 275 mi northwest of Ociyaran, near Lun and Sye." },
  { n: "Breno", cat: "town", x: 6145, y: 1140, k: "Equateiy", d: "In the Kingdom of Equateiy, about 375 mi west of Ociyaran, near Oa and Lidresa." },
  { n: "Brae", cat: "town", x: 6060, y: 1235, k: "Equateiy", d: "In the Kingdom of Equateiy, about 425 mi west of Ociyaran, near Stagna and Oa." },
  { n: "Stagna", cat: "town", x: 6130, y: 1270, k: "Equateiy", d: "In the Kingdom of Equateiy, about 375 mi west of Ociyaran, near Ilvo and Brae." },
  { n: "Ilvo", cat: "town", x: 6150, y: 1325, k: "Equateiy", d: "In the Kingdom of Equateiy, about 375 mi west of Ociyaran, near Stagna and Movo." },
  { n: "Reda", cat: "town", x: 6040, y: 1350, k: "Equateiy", d: "In the Kingdom of Equateiy, about 450 mi west of Ociyaran, near Larida and Ilvo." },
  { n: "Cira", cat: "town", x: 6270, y: 1265, k: "Equateiy", d: "In the Kingdom of Equateiy, about 275 mi west of Ociyaran, near Roi and Cresp." },
  { n: "Roi", cat: "town", x: 6250, y: 1335, k: "Equateiy", d: "In the Kingdom of Equateiy, about 300 mi west of Ociyaran, near Cira and Movo." },
  { n: "Lun", cat: "town", x: 6275, y: 1130, k: "Equateiy", d: "In the Kingdom of Equateiy, about 275 mi west of Ociyaran, near Vigila and Vallaforta." },
  { n: "Oa", cat: "town", x: 6165, y: 1200, k: "Equateiy", d: "In the Kingdom of Equateiy, about 350 mi west of Ociyaran, near Breno and Stagna." },
  { n: "Vigila", cat: "town", x: 6260, y: 1165, k: "Equateiy", d: "In the Kingdom of Equateiy, about 275 mi west of Ociyaran, near Lun and Gora." },
  { n: "Sye", cat: "town", x: 6340, y: 1050, k: "Equateiy", d: "In the Kingdom of Equateiy, about 250 mi northwest of Ociyaran, near Vallaforta and Senna." },
  { n: "Zattera", cat: "town", x: 6700, y: 740, k: "Equateiy", d: "In the Kingdom of Equateiy, about 400 mi north of Ociyaran, near Latso and Paro." },
  { n: "Tesora", cat: "town", x: 6925, y: 785, k: "Equateiy", d: "In the Kingdom of Equateiy, about 450 mi northeast of Ociyaran, near Chiozza and Muralto." },
  { n: "Chiozza", cat: "town", x: 6820, y: 805, k: "Equateiy", d: "In the Kingdom of Equateiy, about 400 mi northeast of Ociyaran, near Tesora and Latso." },
  { n: "Paro", cat: "town", x: 6620, y: 810, k: "Equateiy", d: "In the Kingdom of Equateiy, about 350 mi north of Ociyaran, near Pampira and Latso." },
  { n: "Latso", cat: "town", x: 6700, y: 825, k: "Equateiy", d: "In the Kingdom of Equateiy, about 350 mi north of Ociyaran, near Pampira and Paro." },
  { n: "Pampira", cat: "town", x: 6650, y: 865, k: "Equateiy", d: "In the Kingdom of Equateiy, about 300 mi north of Ociyaran, near Paro and Latso." },
  { n: "Jhera", cat: "town", x: 6750, y: 920, k: "Equateiy", d: "In the Kingdom of Equateiy, about 275 mi northeast of Ociyaran, near Vinalta and Alpena." },
  { n: "Muralto", cat: "town", x: 6885, y: 935, k: "Equateiy", d: "In the Kingdom of Equateiy, about 325 mi northeast of Ociyaran, near Alpena and Ys." },
  { n: "Querceta", cat: "town", x: 6590, y: 955, k: "Equateiy", d: "In the Kingdom of Equateiy, about 225 mi north of Ociyaran, near Uvenza and Vinalta." },
  { n: "Foce", cat: "town", x: 6455, y: 970, k: "Equateiy", d: "In the Kingdom of Equateiy, about 250 mi northwest of Ociyaran, near Malamo and Port Volpa." },
  { n: "Vinalta", cat: "town", x: 6680, y: 975, k: "Equateiy", d: "In the Kingdom of Equateiy, about 225 mi north of Ociyaran, near Doresi and Uvenza." },
  { n: "Alpena", cat: "town", x: 6820, y: 995, k: "Equateiy", d: "In the Kingdom of Equateiy, about 275 mi northeast of Ociyaran, near Muralto and Jhera." },
  { n: "Ys", cat: "town", x: 7000, y: 975, k: "Equateiy", d: "In the Kingdom of Equateiy, about 375 mi northeast of Ociyaran, near Chiavanto and Muralto." },
  { n: "Malamo", cat: "town", x: 6470, y: 1030, k: "Equateiy", d: "In the Kingdom of Equateiy, about 200 mi northwest of Ociyaran, near Gabbia and Foce." },
  { n: "Uvenza", cat: "town", x: 6605, y: 1015, k: "Equateiy", d: "In the Kingdom of Equateiy, about 175 mi north of Ociyaran, near Querceta and Neska." },
  { n: "Doresi", cat: "town", x: 6700, y: 1055, k: "Equateiy", d: "In the Kingdom of Equateiy, about 175 mi northeast of Ociyaran, near Vinalta and Neska." },
  { n: "Chiavanto", cat: "town", x: 6950, y: 1050, k: "Equateiy", d: "In the Kingdom of Equateiy, about 325 mi northeast of Ociyaran, near Riy and Ys." },
  { n: "Gabbia", cat: "town", x: 6495, y: 1085, k: "Equateiy", d: "In the Kingdom of Equateiy, about 150 mi northwest of Ociyaran, near Malamo and Esio." },
  { n: "Neska", cat: "town", x: 6610, y: 1080, k: "Equateiy", d: "In the Kingdom of Equateiy, about 125 mi north of Ociyaran, near Uvenza and Esio." },
  { n: "Corsa", cat: "town", x: 6420, y: 1120, k: "Equateiy", d: "In the Kingdom of Equateiy, about 175 mi northwest of Ociyaran, near Gabbia and Gora." },
  { n: "Esio", cat: "town", x: 6545, y: 1140, k: "Equateiy", d: "In the Kingdom of Equateiy, about 100 mi northwest of Ociyaran, near Gabbia and Neska." },
  { n: "Riy", cat: "town", x: 6975, y: 1110, k: "Equateiy", d: "In the Kingdom of Equateiy, about 325 mi east of Ociyaran, near Chiavanto and Colle." },
  { n: "Squero", cat: "town", x: 6835, y: 1150, k: "Equateiy", d: "In the Kingdom of Equateiy, about 200 mi east of Ociyaran, near Burane and Mira." },
  { n: "Colle", cat: "town", x: 6950, y: 1170, k: "Equateiy", d: "In the Kingdom of Equateiy, about 275 mi east of Ociyaran, near Riy and Mira." },
  { n: "Gora", cat: "town", x: 6345, y: 1185, k: "Equateiy", d: "In the Kingdom of Equateiy, about 225 mi west of Ociyaran, near Nelva and Vigila." },
  { n: "Burane", cat: "town", x: 6855, y: 1210, k: "Equateiy", d: "In the Kingdom of Equateiy, about 200 mi east of Ociyaran, near Mira and Squero." },
  { n: "Nelva", cat: "town", x: 6370, y: 1265, k: "Equateiy", d: "In the Kingdom of Equateiy, about 200 mi west of Ociyaran, near Cresp and Gora." },
  { n: "Claieso", cat: "town", x: 6745, y: 1235, k: "Equateiy", d: "In the Kingdom of Equateiy, about 100 mi east of Ociyaran, near Dragse and Burane." },
  { n: "Mira", cat: "town", x: 6905, y: 1240, k: "Equateiy", d: "In the Kingdom of Equateiy, about 250 mi east of Ociyaran, near Burane and Colle." },
  { n: "Dragse", cat: "town", x: 6785, y: 1280, k: "Equateiy", d: "In the Kingdom of Equateiy, about 150 mi east of Ociyaran, near Claieso and Brentola." },
  { n: "Cresp", cat: "town", x: 6345, y: 1325, k: "Equateiy", d: "In the Kingdom of Equateiy, about 225 mi west of Ociyaran, near Nelva and Roi." },
  { n: "Sarn", cat: "town", x: 6480, y: 1330, k: "Equateiy", d: "In the Kingdom of Equateiy, about 125 mi southwest of Ociyaran, near Vin and Nelva." },
  { n: "Pell'oro", cat: "town", x: 6650, y: 1330, k: "Equateiy", d: "In the Kingdom of Equateiy, about 80 mi southeast of Ociyaran, near Brentola and Pelefer." },
  { n: "Kanghol", cat: "town", x: 6980, y: 1315, k: "Vikitsv", d: "In the Kingdom of Vikitsv, about 800 mi north of Berlailia, near Hanora and Tsenmar." },
  { n: "Brentola", cat: "town", x: 6735, y: 1365, k: "Equateiy", d: "In the Kingdom of Equateiy, about 150 mi southeast of Ociyaran, near Pell'oro and Dragse." },
  { n: "Yitara", cat: "town", x: 2195, y: 1485, k: "Aicruae", d: "In the Kingdom of Aicruae, about 250 mi north of Lajazer, near Fordege and Belei." },
  { n: "Fordege", cat: "town", x: 2300, y: 1455, k: "Aicruae", d: "In the Kingdom of Aicruae, about 275 mi north of Lajazer, near Belei and Lera Mea." },
  { n: "Belei", cat: "town", x: 2305, y: 1520, k: "Aicruae", d: "In the Kingdom of Aicruae, about 225 mi north of Lajazer, near Alben and Fordege." },
  { n: "Alben", cat: "town", x: 2350, y: 1560, k: "Aicruae", d: "In the Kingdom of Aicruae, about 200 mi north of Lajazer, near Belei and Valea." },
  { n: "Atanio", cat: "town", x: 2170, y: 1600, k: "Aicruae", d: "In the Kingdom of Aicruae, about 175 mi northwest of Lajazer, near Tericaer and Hashrin." },
  { n: "Hashrin", cat: "town", x: 2280, y: 1610, k: "Aicruae", d: "In the Kingdom of Aicruae, about 150 mi north of Lajazer, near Vern and Valea." },
  { n: "Tericaer", cat: "town", x: 2105, y: 1640, k: "Aicruae", d: "In the Kingdom of Aicruae, about 175 mi northwest of Lajazer, near Atanio and Deyara. Future capital of Tanan." },
  { n: "Vern", cat: "town", x: 2265, y: 1660, k: "Aicruae", d: "In the Kingdom of Aicruae, about 100 mi north of Lajazer, near Hashrin and Uiedenai." },
  { n: "Jasereiey", cat: "region", x: 2295, y: 1700, k: "Aicruae", d: "Central heartland province of Aicruae." },
  { n: "Deyara", cat: "town", x: 2115, y: 1735, k: "Aicruae", d: "In the Kingdom of Aicruae, about 125 mi west of Lajazer, near Macerino and Neribec." },
  { n: "Nyeo", cat: "town", x: 2290, y: 1745, k: "Aicruae", d: "In the Kingdom of Aicruae, about 40 mi northeast of Lajazer, near Uiedenai and Vern. Site of Harnua's betrayal." },
  { n: "Fayedi", cat: "town", x: 1965, y: 1760, k: "Aicruae", d: "In the Kingdom of Aicruae, about 250 mi west of Lajazer, near Rewqo and Lene." },
  { n: "Neribec", cat: "town", x: 2050, y: 1770, k: "Aicruae", d: "In the Kingdom of Aicruae, about 175 mi west of Lajazer, near Rewqo and Deyara." },
  { n: "Macerino", cat: "town", x: 2150, y: 1780, k: "Aicruae", d: "In the Kingdom of Aicruae, about 100 mi west of Lajazer, near Deyara and Aseri Gai Oshana." },
  { n: "Lene", cat: "town", x: 1945, y: 1810, k: "Aicruae", d: "In the Kingdom of Aicruae, about 250 mi west of Lajazer, near Rewqo and Fayedi." },
  { n: "Aseri Gai Oshana", cat: "town", x: 2210, y: 1845, k: "Aicruae", d: "In the Kingdom of Aicruae, about 70 mi southwest of Lajazer, near Orcon and Macerino." },
  { n: "Dushrer", cat: "town", x: 1890, y: 1805, k: "Aicruae", d: "In the Kingdom of Aicruae, about 300 mi west of Lajazer, near Lene and Fayedi." },
  { n: "Caleo", cat: "town", x: 1890, y: 1895, k: "Aicruae", d: "In the Kingdom of Aicruae, about 325 mi west of Lajazer, near Dushrer and Dira." },
  { n: "Heusal", cat: "town", x: 1990, y: 1890, k: "Aicruae", d: "In the Kingdom of Aicruae, about 250 mi west of Lajazer, near Leyoni and Lene." },
  { n: "Thalyn", cat: "town", x: 1815, y: 1955, k: "Aicruae", d: "In the Kingdom of Aicruae, about 375 mi west of Lajazer, near Caleo and Hepeno." },
  { n: "Dira", cat: "town", x: 1940, y: 1975, k: "Aicruae", d: "In the Kingdom of Aicruae, about 300 mi southwest of Lajazer, near Ostoki and Bosletero." },
  { n: "Leyoni", cat: "town", x: 2030, y: 1950, k: "Aicruae", d: "In the Kingdom of Aicruae, about 225 mi southwest of Lajazer, near Bosletero and Heusal." },
  { n: "Lowec", cat: "town", x: 2125, y: 1980, k: "Aicruae", d: "In the Kingdom of Aicruae, about 200 mi southwest of Lajazer, near Begai and Leyoni." },
  { n: "Avego", cat: "town", x: 2270, y: 1960, k: "Aicruae", d: "In the Kingdom of Aicruae, about 150 mi south of Lajazer, near Comej and Orcon." },
  { n: "Comej", cat: "town", x: 2265, y: 2000, k: "Aicruae", d: "In the Kingdom of Aicruae, about 175 mi south of Lajazer, near Avego and Meprin." },
  { n: "Bosletero", cat: "town", x: 2010, y: 2010, k: "Aicruae", d: "In the Kingdom of Aicruae, about 275 mi southwest of Lajazer, near Leyoni and Dira." },
  { n: "Begai", cat: "town", x: 2130, y: 2015, k: "Aicruae", d: "In the Kingdom of Aicruae, about 225 mi southwest of Lajazer, near Lowec and Meprin." },
  { n: "Meprin", cat: "town", x: 2220, y: 2040, k: "Aicruae", d: "In the Kingdom of Aicruae, about 200 mi south of Lajazer, near Comej and Tineb." },
  { n: "Ostoki", cat: "town", x: 1910, y: 2025, k: "Aicruae", d: "In the Kingdom of Aicruae, about 350 mi southwest of Lajazer, near Dira and Hepeno." },
  { n: "Hepeno", cat: "town", x: 1825, y: 2065, k: "Aicruae", d: "In the Kingdom of Aicruae, about 425 mi southwest of Lajazer, near Teyetes and Ostoki." },
  { n: "Jani", cat: "town", x: 2365, y: 2045, k: "Aicruae", d: "In the Kingdom of Aicruae, about 225 mi south of Lajazer, near Caesro and Comej." },
  { n: "Tineb", cat: "town", x: 2265, y: 2110, k: "Aicruae", d: "In the Kingdom of Aicruae, about 250 mi south of Lajazer, near Meprin and Nayen." },
  { n: "Caesro", cat: "town", x: 2370, y: 2115, k: "Aicruae", d: "In the Kingdom of Aicruae, about 275 mi south of Lajazer, near Jani and Tineb." },
  { n: "Teyetes", cat: "town", x: 1890, y: 2130, k: "Aicruae", d: "In the Kingdom of Aicruae, about 400 mi southwest of Lajazer, near Port Quale and Hepeno." },
  { n: "Loeru", cat: "town", x: 2075, y: 2140, k: "Aicruae", d: "In the Kingdom of Aicruae, about 325 mi southwest of Lajazer, near Bareta and Nayen." },
  { n: "Nayen", cat: "town", x: 2170, y: 2135, k: "Aicruae", d: "In the Kingdom of Aicruae, about 300 mi south of Lajazer, near Honete and Loeru." },
  { n: "Bareta", cat: "town", x: 1995, y: 2170, k: "Aicruae", d: "In the Kingdom of Aicruae, about 375 mi southwest of Lajazer, near Loeru and Teyetes." },
  { n: "Honete", cat: "town", x: 2145, y: 2205, k: "Aicruae", d: "In the Kingdom of Aicruae, about 350 mi south of Lajazer, near Nayen and Mepria." },
  { n: "The Santie", cat: "town", x: 2240, y: 2225, k: "Aicruae", d: "In the Kingdom of Aicruae, about 350 mi south of Lajazer, near Teisho and Honete." },
  { n: "Liazen", cat: "region", x: 2005, y: 2085, k: "Aicruae", d: "Southern province of Aicruae, toward the badlands." },
  { n: "The Aoner", cat: "region", x: 2010, y: 1845, k: "Aicruae", d: "The 'Granary of the West' — Aicruae's western granary coast." },
  { n: "Mepria", cat: "town", x: 2140, y: 2295, k: "Aicruae", d: "In the Kingdom of Aicruae, about 425 mi south of Lajazer, near Honete and Teisho." },
  { n: "Teisho", cat: "town", x: 2250, y: 2300, k: "Aicruae", d: "In the Kingdom of Aicruae, about 400 mi south of Lajazer, near The Santie and Laona." },
  { n: "Audin", cat: "town", x: 1990, y: 2345, k: "Aicruae", d: "In the Kingdom of Aicruae, about 500 mi southwest of Lajazer, near Mepria and Bareta." },
  { n: "Laona", cat: "town", x: 2270, y: 2390, k: "Aicruae", d: "In the Kingdom of Aicruae, about 475 mi south of Lajazer, near Teisho and Mepria." },
  { n: "Loriga", cat: "town", x: 2630, y: 2155, k: "Pireaynea", d: "In the Kingdom of Pireaynea, about 475 mi northwest of Civer, near Olbi and Vasco." },
  { n: "Rosca", cat: "town", x: 3020, y: 2150, k: "Pireaynea", d: "In the Kingdom of Pireaynea, about 250 mi northwest of Civer, near Pantari and Olbi." },
  { n: "Drino", cat: "town", x: 3410, y: 2170, k: "Pireaynea", d: "In the Kingdom of Pireaynea, about 275 mi northeast of Civer, near Pantari and Rosca." },
  { n: "Pantari", cat: "town", x: 3190, y: 2360, k: "Pireaynea", d: "In the Kingdom of Pireaynea, about 50 mi northeast of Civer, near Rosca and Sindbir." },
  { n: "Vasco", cat: "town", x: 2455, y: 2455, k: "Pireaynea", d: "In the Kingdom of Pireaynea, about 575 mi west of Civer, near Port Ols and Loriga." },
  { n: "Sindbir", cat: "town", x: 3000, y: 2555, k: "Pireaynea", d: "In the Kingdom of Pireaynea, about 175 mi southwest of Civer, near Pantari and Rosca." },
  { n: "Croco", cat: "town", x: 3210, y: 1735, k: "Coelum", d: "In the Kingdom of Coelum, about 1000 mi southwest of Atriki, near Ezon and Coelys." },
  { n: "Alsea", cat: "town", x: 3395, y: 1745, k: "Coelum", d: "In the Kingdom of Coelum, about 925 mi southwest of Atriki, near Oradi and Drenia." },
  { n: "Oradi", cat: "town", x: 3360, y: 1800, k: "Coelum", d: "In the Kingdom of Coelum, about 975 mi southwest of Atriki, near Alsea and Croco." },
  { n: "Ezon", cat: "town", x: 3270, y: 1600, k: "Coelum", d: "In the Kingdom of Coelum, about 875 mi southwest of Atriki, near Lasten and Lujian." },
  { n: "Drenia", cat: "town", x: 3395, y: 1610, k: "Coelum", d: "In the Kingdom of Coelum, about 825 mi southwest of Atriki, near Lujian and Oscan." },
  { n: "Lujian", cat: "town", x: 3375, y: 1555, k: "Coelum", d: "In the Kingdom of Coelum, about 800 mi southwest of Atriki, near Drenia and Oscan." },
  { n: "Lasten", cat: "town", x: 3260, y: 1505, k: "Coelum", d: "In the Kingdom of Coelum, about 825 mi southwest of Atriki, near Ezon and Lujian." },
  { n: "Olune", cat: "town", x: 3555, y: 1710, k: "Gherci", d: "In the Kingdom of Gherci, about 550 mi northwest of Tarmet, near Rietha and Shaer." },
  { n: "Nyes", cat: "town", x: 3685, y: 1550, k: "Gherci", d: "In the Kingdom of Gherci, about 525 mi northwest of Tarmet, near Rietha and Belune." },
  { n: "Shaer", cat: "town", x: 3550, y: 1870, k: "Gherci", d: "In the Kingdom of Gherci, about 500 mi west of Tarmet, near Lage and Zerpe." },
  { n: "Zerpe", cat: "town", x: 3700, y: 1920, k: "Gherci", d: "In the Kingdom of Gherci, about 375 mi west of Tarmet, near Cerby and Lage." },
  { n: "Lage", cat: "town", x: 3605, y: 2010, k: "Gherci", d: "In the Kingdom of Gherci, about 425 mi west of Tarmet, near Zerpe and Cerby." },
  { n: "Cerby", cat: "town", x: 3750, y: 2025, k: "Gherci", d: "In the Kingdom of Gherci, about 325 mi west of Tarmet, near Zerpe and Keba." },
  { n: "Golan", cat: "town", x: 3650, y: 2150, k: "Gherci", d: "In the Kingdom of Gherci, about 400 mi west of Tarmet, near Lage and Cerby." },
  { n: "Vaia", cat: "town", x: 2595, y: 1490, k: "Coelum", d: "In the Kingdom of Coelum, about 1225 mi southwest of Atriki, near Tellas and Annagi." },
  { n: "Liviao", cat: "town", x: 2715, y: 1405, k: "Aicruae", d: "In the Kingdom of Aicruae, about 475 mi northeast of Lajazer, near Paler and Baramq." },
  { n: "Annagi", cat: "town", x: 2725, y: 1495, k: "Coelum", d: "In the Kingdom of Coelum, about 1150 mi southwest of Atriki, near Noraho and Tellas." },
  { n: "Giagior", cat: "town", x: 2905, y: 1450, k: "Coelum", d: "In the Kingdom of Coelum, about 1000 mi southwest of Atriki, near Iaga and Tagre." },
  { n: "Mema", cat: "town", x: 3025, y: 1485, k: "Coelum", d: "In the Kingdom of Coelum, about 950 mi southwest of Atriki, near Tophercris and Giagior." },
  { n: "Tophercris", cat: "town", x: 3065, y: 1415, k: "Coelum", d: "In the Kingdom of Coelum, about 875 mi southwest of Atriki, near Mema and Anaan." },
  { n: "Vannigio", cat: "town", x: 3355, y: 1420, k: "Coelum", d: "In the Kingdom of Coelum, about 725 mi southwest of Atriki, near Eloe and Egodi." },
  { n: "Selve", cat: "town", x: 3580, y: 1425, k: "Coelum", d: "In the Kingdom of Coelum, about 625 mi southwest of Atriki, near Renzolo and Cardoric." },
  { n: "Cardoric", cat: "town", x: 3455, y: 1455, k: "Coelum", d: "In the Kingdom of Coelum, about 700 mi southwest of Atriki, near Oscan and Egodi." },
  { n: "Noraho", cat: "town", x: 2755, y: 1555, k: "Coelum", d: "In the Kingdom of Coelum, about 1150 mi southwest of Atriki, near Lanmi and Annagi." },
  { n: "Tellas", cat: "town", x: 2675, y: 1580, k: "Coelum", d: "In the Kingdom of Coelum, about 1225 mi southwest of Atriki, near Resate and Noraho." },
  { n: "Lanmi", cat: "town", x: 2775, y: 1595, k: "Coelum", d: "In the Kingdom of Coelum, about 1150 mi southwest of Atriki, near Noraho and Noju." },
  { n: "Resate", cat: "town", x: 2700, y: 1630, k: "Coelum", d: "In the Kingdom of Coelum, about 1225 mi southwest of Atriki, near Tellas and Noju." },
  { n: "Noju", cat: "town", x: 2780, y: 1645, k: "Coelum", d: "In the Kingdom of Coelum, about 1175 mi southwest of Atriki, near Lanmi and Apric." },
  { n: "Thevia", cat: "town", x: 2895, y: 1630, k: "Coelum", d: "In the Kingdom of Coelum, about 1100 mi southwest of Atriki, near Apric and Iaga." },
  { n: "Apric", cat: "town", x: 2840, y: 1680, k: "Coelum", d: "In the Kingdom of Coelum, about 1150 mi southwest of Atriki, near Noju and Thevia." },
  { n: "Iaga", cat: "town", x: 2855, y: 1540, k: "Coelum", d: "In the Kingdom of Coelum, about 1075 mi southwest of Atriki, near Lanmi and Thevia." },
  { n: "Meliwit", cat: "town", x: 2580, y: 1620, k: "Aicruae", d: "In the Kingdom of Aicruae, about 275 mi northeast of Lajazer, near Braiston and Casqen Gai Zaeri." },
  { n: "Braiston", cat: "town", x: 2545, y: 1675, k: "Aicruae", d: "In the Kingdom of Aicruae, about 225 mi east of Lajazer, near Casqen Gai Zaeri and Meliwit." },
  { n: "Maenen", cat: "town", x: 2455, y: 1655, k: "Aicruae", d: "In the Kingdom of Aicruae, about 175 mi northeast of Lajazer, near Wistin and Peisk." },
  { n: "Casqen Gai Zaeri", cat: "town", x: 2590, y: 1720, k: "Aicruae", d: "In the Kingdom of Aicruae, about 250 mi east of Lajazer, near Braiston and Zagaro." },
  { n: "Zagaro", cat: "town", x: 2540, y: 1785, k: "Aicruae", d: "In the Kingdom of Aicruae, about 225 mi east of Lajazer, near Casqen Gai Zaeri and Masein." },
  { n: "Masein", cat: "town", x: 2485, y: 1870, k: "Aicruae", d: "In the Kingdom of Aicruae, about 175 mi east of Lajazer, near Oahiat and Jiegoa." },
  { n: "Jiegoa", cat: "town", x: 2405, y: 1895, k: "Aicruae", d: "In the Kingdom of Aicruae, about 150 mi southeast of Lajazer, near Masein and Oahiat." },
  { n: "Oahiat", cat: "town", x: 2510, y: 1915, k: "Aicruae", d: "In the Kingdom of Aicruae, about 225 mi southeast of Lajazer, near Masein and Jiegoa." },
  { n: "Benalo", cat: "town", x: 2480, y: 2050, k: "Aicruae", d: "In the Kingdom of Aicruae, about 275 mi southeast of Lajazer, near Jani and Caesro." },
  { n: "Kanidon", cat: "river", x: 2540, y: 1535, k: "Aicruae", d: "In the Kingdom of Aicruae, about 300 mi northeast of Lajazer, near Isecia and Meliwit. River on Aicruae's northeastern frontier." },
  { n: "Gengo", cat: "river", x: 2655, y: 1680, k: "Aicruae", d: "In the Kingdom of Aicruae, about 325 mi east of Lajazer, near Casqen Gai Zaeri and Meliwit. River on Aicruae's northeastern frontier." },
  { n: "Holwe", cat: "town", x: 2425, y: 1500, k: "Aicruae", d: "In the Kingdom of Aicruae, about 250 mi northeast of Lajazer, near Melerbo and Isecia." },
  { n: "Isecia", cat: "town", x: 2455, y: 1545, k: "Aicruae", d: "In the Kingdom of Aicruae, about 250 mi northeast of Lajazer, near Wistin and Holwe." },
  { n: "Wistin", cat: "town", x: 2440, y: 1590, k: "Aicruae", d: "In the Kingdom of Aicruae, about 200 mi northeast of Lajazer, near Isecia and Maenen." },
  { n: "Olbi", cat: "town", x: 2815, y: 1965, k: "Pireaynea", d: "In the Kingdom of Pireaynea, about 450 mi northwest of Civer, near Loriga and Rosca." },
  { n: "Uiedenai", cat: "town", x: 2310, y: 1690, k: "Aicruae", d: "In the Kingdom of Aicruae, about 80 mi northeast of Lajazer, near Vern and Nyeo." },
  { n: "Peisk", cat: "town", x: 2405, y: 1730, k: "Aicruae", d: "In the Kingdom of Aicruae, about 125 mi east of Lajazer, near Madu and Maenen." },
  { n: "Madu", cat: "town", x: 2400, y: 1770, k: "Aicruae", d: "In the Kingdom of Aicruae, about 125 mi east of Lajazer, near Peisk and Masein." },
  { n: "Adani", cat: "town", x: 3925, y: 1410, k: "Gherci", d: "In the Kingdom of Gherci, about 525 mi north of Tarmet, near Cyme and Gondes." },
  { n: "Inqwe", cat: "town", x: 4135, y: 1470, k: "Gherci", d: "In the Kingdom of Gherci, about 450 mi north of Tarmet, near Resia and Malie." },
  { n: "Cyme", cat: "town", x: 3950, y: 1505, k: "Gherci", d: "In the Kingdom of Gherci, about 450 mi north of Tarmet, near Malie and Adani." },
  { n: "Oryur", cat: "town", x: 4550, y: 1410, k: "Gherci", d: "In the Kingdom of Gherci, about 600 mi northeast of Tarmet, near Garen and Inqua." },
  { n: "Nyedal", cat: "town", x: 4755, y: 1420, k: "Gherci", d: "In the Kingdom of Gherci, about 700 mi northeast of Tarmet, near Tasfen and Garen." },
  { n: "Hagiora", cat: "town", x: 5080, y: 1455, k: "the far-eastern territories", d: "In the far-eastern territories beyond Gherci's border, about 1000 mi north of Amba, near Semhol and Belnara." },
  { n: "Garen", cat: "town", x: 4645, y: 1510, k: "Gherci", d: "In the Kingdom of Gherci, about 575 mi northeast of Tarmet, near Oryur and Nyedal." },
  { n: "Tasfen", cat: "town", x: 4795, y: 1510, k: "Gherci", d: "In the Kingdom of Gherci, about 675 mi northeast of Tarmet, near Nyedal and Garen." },
  { n: "Malie", cat: "town", x: 3990, y: 1585, k: "Gherci", d: "In the Kingdom of Gherci, about 375 mi north of Tarmet, near Cyme and Ostra." },
  { n: "Hoan", cat: "town", x: 4280, y: 1590, k: "Gherci", d: "In the Kingdom of Gherci, about 375 mi north of Tarmet, near Lokea and Inqwe." },
  { n: "Belune", cat: "town", x: 3820, y: 1680, k: "Gherci", d: "In the Kingdom of Gherci, about 375 mi northwest of Tarmet, near Kessa and Rietha." },
  { n: "Ostra", cat: "town", x: 4050, y: 1690, k: "Gherci", d: "In the Kingdom of Gherci, about 300 mi north of Tarmet, near Malie and Bayen." },
  { n: "Ralt", cat: "town", x: 4535, y: 1635, k: "Gherci", d: "In the Kingdom of Gherci, about 450 mi northeast of Tarmet, near Elemie and Iel." },
  { n: "Iel", cat: "town", x: 4675, y: 1705, k: "Gherci", d: "In the Kingdom of Gherci, about 500 mi northeast of Tarmet, near Lujia and Ralt." },
  { n: "Lokea", cat: "town", x: 4265, y: 1720, k: "Gherci", d: "In the Kingdom of Gherci, about 275 mi north of Tarmet, near Cula and Hoan." },
  { n: "Cula", cat: "town", x: 4305, y: 1795, k: "Gherci", d: "In the Kingdom of Gherci, about 225 mi northeast of Tarmet, near Lokea and Vashon." },
  { n: "Elemie", cat: "town", x: 4450, y: 1735, k: "Gherci", d: "In the Kingdom of Gherci, about 350 mi northeast of Tarmet, near Vashon and Ralt." },
  { n: "Lujia", cat: "town", x: 4820, y: 1755, k: "Gherci", d: "In the Kingdom of Gherci, about 575 mi northeast of Tarmet, near Inen and Iel." },
  { n: "Kidaris", cat: "town", x: 5100, y: 1815, k: "the far-eastern territories", d: "In the far-eastern territories beyond Gherci's border, about 725 mi northwest of Amba, near Semhol and Medhuk." },
  { n: "Vashon", cat: "town", x: 4440, y: 1850, k: "Gherci", d: "In the Kingdom of Gherci, about 275 mi northeast of Tarmet, near Elemie and Laiya." },
  { n: "Laiya", cat: "town", x: 4580, y: 1830, k: "Gherci", d: "In the Kingdom of Gherci, about 375 mi northeast of Tarmet, near Vashon and Iel." },
  { n: "Inen", cat: "town", x: 4760, y: 1865, k: "Gherci", d: "In the Kingdom of Gherci, about 500 mi east of Tarmet, near Avani and Lujia." },
  { n: "Muri", cat: "town", x: 4950, y: 1915, k: "Gherci", d: "In the Kingdom of Gherci, about 375 mi east of Tarmet, near Inen and Avani." },
  { n: "Bayen", cat: "town", x: 3895, y: 1825, k: "Gherci", d: "In the Kingdom of Gherci, about 275 mi northwest of Tarmet, near Treas and Belune." },
  { n: "Treas", cat: "town", x: 3905, y: 1965, k: "Gherci", d: "In the Kingdom of Gherci, about 200 mi west of Tarmet, near Keba and Bayen." },
  { n: "Lendara", cat: "town", x: 4140, y: 1960, k: "Gherci", d: "In the Kingdom of Gherci, about 60 mi north of Tarmet, near Asmeta and Malin." },
  { n: "Malin", cat: "town", x: 4270, y: 1960, k: "Gherci", d: "In the Kingdom of Gherci, about 125 mi northeast of Tarmet, near Lendara and Cula." },
  { n: "Ristia", cat: "town", x: 4520, y: 1980, k: "Gherci", d: "In the Kingdom of Gherci, about 300 mi east of Tarmet, near Vashon and Calye." },
  { n: "Avani", cat: "town", x: 4720, y: 1965, k: "Gherci", d: "In the Kingdom of Gherci, about 450 mi east of Tarmet, near Inen and Amies." },
  { n: "Asmeta", cat: "town", x: 4055, y: 2015, k: "Gherci", d: "In the Kingdom of Gherci, about 70 mi west of Tarmet, near Lendara and Treas." },
  { n: "Keba", cat: "town", x: 3890, y: 2045, k: "Gherci", d: "In the Kingdom of Gherci, about 200 mi west of Tarmet, near Treas and Doka." },
  { n: "Amies", cat: "town", x: 4820, y: 2040, k: "Gherci", d: "In the Kingdom of Gherci, about 550 mi east of Tarmet, near Avani and Menejel." },
  { n: "Oermat", cat: "town", x: 5080, y: 2005, k: "Gherci", d: "In the Kingdom of Gherci, about 750 mi east of Tarmet, near Lethe and Loria." },
  { n: "Calye", cat: "town", x: 4435, y: 2110, k: "Gherci", d: "In the Kingdom of Gherci, about 250 mi east of Tarmet, near Thelia and Ristia." },
  { n: "Lethe", cat: "town", x: 4990, y: 2095, k: "Gherci", d: "In the Kingdom of Gherci, about 675 mi east of Tarmet, near Loria and Oermat." },
  { n: "Doka", cat: "town", x: 3890, y: 2130, k: "Gherci", d: "In the Kingdom of Gherci, about 225 mi west of Tarmet, near Keba and Granosa." },
  { n: "Tanya Beka", cat: "town", x: 4235, y: 2155, k: "Gherci", d: "In the Kingdom of Gherci, about 125 mi southeast of Tarmet, near Nords and Malin." },
  { n: "Yvenna", cat: "town", x: 4665, y: 2170, k: "Gherci", d: "In the Kingdom of Gherci, about 425 mi east of Tarmet, near Saltie and Anye." },
  { n: "Menejel", cat: "town", x: 4850, y: 2175, k: "Gherci", d: "In the Kingdom of Gherci, about 575 mi east of Tarmet, near Saltie and Amies." },
  { n: "Granosa", cat: "town", x: 3965, y: 2205, k: "Gherci", d: "In the Kingdom of Gherci, about 200 mi southwest of Tarmet, near Doka and Tarl." },
  { n: "Thelia", cat: "town", x: 4485, y: 2215, k: "Gherci", d: "In the Kingdom of Gherci, about 300 mi southeast of Tarmet, near Calye and Orin." },
  { n: "Cosar", cat: "river", x: 3745, y: 2200, k: "Gherci", d: "In the Kingdom of Gherci, about 350 mi west of Tarmet, near Golan and Tarl. River of the Lower Gherci system, draining to the Fetora Sea." },
  { n: "Saltie", cat: "town", x: 4745, y: 2255, k: "Gherci", d: "In the Kingdom of Gherci, about 500 mi east of Tarmet, near Yvenna and Menejel." },
  { n: "Tarl", cat: "town", x: 3880, y: 2285, k: "Gherci", d: "In the Kingdom of Gherci, about 300 mi southwest of Tarmet, near Anjelie and Granosa." },
  { n: "Caspra", cat: "town", x: 4040, y: 2305, k: "Gherci", d: "In the Kingdom of Gherci, about 225 mi south of Tarmet, near Granosa and Nords." },
  { n: "Nords", cat: "town", x: 4190, y: 2290, k: "Gherci", d: "In the Kingdom of Gherci, about 200 mi south of Tarmet, near Pelia and Tanya Beka." },
  { n: "Maru", cat: "town", x: 4950, y: 2290, k: "Gherci", d: "In the Kingdom of Gherci, about 675 mi east of Tarmet, near Loria and Menejel." },
  { n: "Anye", cat: "town", x: 4625, y: 2320, k: "Gherci", d: "The eastern of the two Anyes. In the Kingdom of Gherci, about 450 mi southeast of Tarmet, near Saltie and Orin." },
  { n: "Anye", cat: "town", x: 4300, y: 2545, k: "Gherci", d: "The southwestern of the two Anyes. In the Kingdom of Gherci, about 425 mi south of Tarmet, near Pelia and Drun." },
  { n: "Anjelie", cat: "town", x: 3905, y: 2395, k: "Gherci", d: "In the Kingdom of Gherci, about 350 mi southwest of Tarmet, near Rietra and Tarl." },
  { n: "Orin", cat: "town", x: 4445, y: 2370, k: "Gherci", d: "In the Kingdom of Gherci, about 350 mi southeast of Tarmet, near Thelia and Pelia." },
  { n: "Vagn", cat: "town", x: 4760, y: 2445, k: "Gherci", d: "In the Kingdom of Gherci, about 575 mi southeast of Tarmet, near Anye and Saltie." },
  { n: "Pelia", cat: "town", x: 4265, y: 2405, k: "Gherci", d: "In the Kingdom of Gherci, about 300 mi south of Tarmet, near Nords and Orin." },
  { n: "Forea", cat: "town", x: 4090, y: 2460, k: "Gherci", d: "In the Kingdom of Gherci, about 350 mi south of Tarmet, near Pontata and Rietra." },
  { n: "Rietra", cat: "town", x: 3945, y: 2495, k: "Gherci", d: "In the Kingdom of Gherci, about 400 mi southwest of Tarmet, near Pontata and Anjelie." },
  { n: "Demia", cat: "town", x: 4970, y: 2505, k: "Gherci", d: "In the Kingdom of Gherci, about 750 mi southeast of Tarmet, near Gai and Maru." },
  { n: "Pontata", cat: "town", x: 3985, y: 2565, k: "Gherci", d: "In the Kingdom of Gherci, about 450 mi south of Tarmet, near Rietra and Aoin." },
  { n: "Aoin", cat: "town", x: 3925, y: 2640, k: "Gherci", d: "In the Kingdom of Gherci, about 500 mi south of Tarmet, near Pontata and Rietra." },
  { n: "Drun", cat: "town", x: 4450, y: 2625, k: "Gherci", d: "In the Kingdom of Gherci, about 525 mi southeast of Tarmet, near Esku and Trask." },
  { n: "Trask", cat: "town", x: 4630, y: 2680, k: "Gherci", d: "In the Kingdom of Gherci, about 650 mi southeast of Tarmet, near Oskba and Drun." },
  { n: "Esku", cat: "town", x: 4425, y: 2750, k: "Gherci", d: "In the Kingdom of Gherci, about 600 mi south of Tarmet, near Drun and Kuldar." },
  { n: "Talu", cat: "town", x: 6070, y: 1755, k: "Equateiy", d: "In the Kingdom of Equateiy, about 600 mi southwest of Ociyaran, near Esteraia and Velsa. Town at the edge of the Nedi Forest." },
  { n: "Ombretta", cat: "town", x: 5930, y: 1445, k: "Equateiy", d: "In the Kingdom of Equateiy, about 550 mi west of Ociyaran, near Reda and Larida." },
  { n: "Larida", cat: "town", x: 6080, y: 1440, k: "Equateiy", d: "In the Kingdom of Equateiy, about 450 mi west of Ociyaran, near Reda and Movo." },
  { n: "Movo", cat: "town", x: 6185, y: 1390, k: "Equateiy", d: "In the Kingdom of Equateiy, about 350 mi west of Ociyaran, near Ilvo and Lezna." },
  { n: "Murra", cat: "town", x: 6320, y: 1440, k: "Equateiy", d: "In the Kingdom of Equateiy, about 275 mi southwest of Ociyaran, near Velo and Lezna." },
  { n: "Lezna", cat: "town", x: 6210, y: 1470, k: "Equateiy", d: "In the Kingdom of Equateiy, about 375 mi southwest of Ociyaran, near Movo and Grotta." },
  { n: "Velo", cat: "town", x: 6375, y: 1520, k: "Equateiy", d: "In the Kingdom of Equateiy, about 275 mi southwest of Ociyaran, near Murra and Lezna." },
  { n: "Grotta", cat: "town", x: 6180, y: 1555, k: "Equateiy", d: "In the Kingdom of Equateiy, about 425 mi southwest of Ociyaran, near Pratesi and Ravia." },
  { n: "Ravia", cat: "town", x: 6100, y: 1580, k: "Equateiy", d: "In the Kingdom of Equateiy, about 475 mi southwest of Ociyaran, near Velsa and Grotta." },
  { n: "Pratesi", cat: "town", x: 6220, y: 1600, k: "Equateiy", d: "In the Kingdom of Equateiy, about 425 mi southwest of Ociyaran, near Grotta and Uada." },
  { n: "Velsa", cat: "town", x: 6060, y: 1620, k: "Equateiy", d: "In the Kingdom of Equateiy, about 525 mi southwest of Ociyaran, near Ravia and Esteraia." },
  { n: "Uada", cat: "town", x: 6185, y: 1660, k: "Equateiy", d: "In the Kingdom of Equateiy, about 475 mi southwest of Ociyaran, near Aslwal and Esteraia. Town of the Nedi Forest reaches; the smaller towns Aslwal and Esteraia sit within it." },
  { n: "Nurida", cat: "town", x: 6390, y: 1640, k: "Vikitsv", d: "In the Kingdom of Vikitsv, about 625 mi northwest of Berlailia, near Tsenmar and Reskt." },
  { n: "Bellaria", cat: "town", x: 5265, y: 1705, k: "the far-eastern territories", d: "In the far-eastern territories beyond Gherci's border, about 750 mi north of Amba, near Norabea and Tehron." },
  { n: "Norabea", cat: "town", x: 5350, y: 1680, k: "the far-eastern territories", d: "In the far-eastern territories beyond Gherci's border, about 775 mi north of Amba, near Bellaria and Tehron." },
  { n: "Semhol", cat: "town", x: 5110, y: 1725, k: "the far-eastern territories", d: "In the far-eastern territories beyond Gherci's border, about 775 mi north of Amba, near Kidaris and Belnara." },
  { n: "Medhuk", cat: "town", x: 5215, y: 1855, k: "the far-eastern territories", d: "In the far-eastern territories beyond Gherci's border, about 650 mi north of Amba, near Tehron and Kidaris." },
  { n: "Tehron", cat: "town", x: 5330, y: 1840, k: "the far-eastern territories", d: "In the far-eastern territories beyond Gherci's border, about 650 mi north of Amba, near Medhuk and Tusjin." },
  { n: "Tusjin", cat: "town", x: 5285, y: 1980, k: "the far-eastern territories", d: "In the far-eastern territories beyond Gherci's border, about 550 mi north of Amba, near Dremk and Denkay." },
  { n: "Vagusi", cat: "town", x: 5455, y: 1975, k: "the far-eastern territories", d: "In the far-eastern territories beyond Gherci's border, about 525 mi north of Amba, near Denkay and Aspardo." },
  { n: "Denkay", cat: "town", x: 5390, y: 2040, k: "the far-eastern territories", d: "In the far-eastern territories beyond Gherci's border, about 475 mi north of Amba, near Vagusi and Rudeth." },
  { n: "Aspardo", cat: "town", x: 5525, y: 2035, k: "the far-eastern territories", d: "In the far-eastern territories beyond Gherci's border, about 475 mi north of Amba, near Vagusi and Allisto." },
  { n: "Dremk", cat: "town", x: 5225, y: 2080, k: "the far-eastern territories", d: "In the far-eastern territories beyond Gherci's border, about 475 mi north of Amba, near Tusjin and Tsir." },
  { n: "Allisto", cat: "town", x: 5585, y: 2115, k: "the far-eastern territories", d: "In the far-eastern territories beyond Gherci's border, about 425 mi north of Amba, near Brall and Aspardo." },
  { n: "Rudeth", cat: "town", x: 5410, y: 2140, k: "the far-eastern territories", d: "In the far-eastern territories beyond Gherci's border, about 400 mi north of Amba, near Denkay and Dugwil." },
  { n: "Brall", cat: "town", x: 5610, y: 2160, k: "the far-eastern territories", d: "In the far-eastern territories beyond Gherci's border, about 400 mi north of Amba, near Allisto and Dugwil." },
  { n: "Tsir", cat: "town", x: 5235, y: 2210, k: "the far-eastern territories", d: "In the far-eastern territories beyond Gherci's border, about 375 mi northwest of Amba, near Dremk and Rudeth." },
  { n: "Dugwil", cat: "town", x: 5515, y: 2200, k: "the far-eastern territories", d: "In the far-eastern territories beyond Gherci's border, about 350 mi north of Amba, near Brall and Allisto." },
  { n: "Hagn", cat: "town", x: 5410, y: 2285, k: "the far-eastern territories", d: "In the far-eastern territories beyond Gherci's border, about 275 mi north of Amba, near Hauk and Dugwil." },
  { n: "Sevq", cat: "town", x: 5615, y: 2290, k: "the far-eastern territories", d: "In the far-eastern territories beyond Gherci's border, about 300 mi northeast of Amba, near Dahn and Hauk." },
  { n: "Hauk", cat: "town", x: 5535, y: 2330, k: "the far-eastern territories", d: "In the far-eastern territories beyond Gherci's border, about 250 mi north of Amba, near Sevq and Dahn." },
  { n: "Dahn", cat: "town", x: 5625, y: 2365, k: "the far-eastern territories", d: "In the far-eastern territories beyond Gherci's border, about 250 mi northeast of Amba, near Sevq and Hauk." },
  { n: "Hagiore", cat: "town", x: 5540, y: 2510, k: "the far-eastern territories", d: "In the far-eastern territories beyond Gherci's border, about 125 mi northeast of Amba, near Dahn and Hauk." },
  { n: "Ompol", cat: "town", x: 6115, y: 2595, k: "Vikitsv", d: "In the Kingdom of Vikitsv, about 600 mi southwest of Berlailia, near Bohan and Torad." },
  { n: "Demre", cat: "town", x: 5295, y: 2650, k: "the far-eastern territories", d: "In the far-eastern territories beyond Gherci's border, about 125 mi west of Amba, near Limn and Dordbin." },
  { n: "Selvet", cat: "town", x: 5510, y: 2745, k: "the far-eastern territories", d: "In the far-eastern territories beyond Gherci's border, about 90 mi southeast of Amba, near Maryos and Limn." },
  { n: "Tsenmar", cat: "town", x: 6710, y: 1505, k: "Vikitsv", d: "In the Kingdom of Vikitsv, about 650 mi north of Berlailia, near Hanora and Kanghol." },
  { n: "Hanora", cat: "town", x: 6985, y: 1645, k: "Vikitsv", d: "In the Kingdom of Vikitsv, about 550 mi north of Berlailia, near Tsenmar and Kanghol." },
  { n: "Daltsen", cat: "town", x: 6600, y: 2225, k: "Vikitsv", d: "In the Kingdom of Vikitsv, about 175 mi west of Berlailia, near Sehrok and Byeola." },
  { n: "Negiet", cat: "town", x: 6765, y: 2195, k: "Vikitsv", d: "In the Kingdom of Vikitsv, about 90 mi north of Berlailia, near Daltsen and Sehrok." },
  { n: "Sehrok", cat: "town", x: 6545, y: 2305, k: "Vikitsv", d: "In the Kingdom of Vikitsv, about 200 mi west of Berlailia, near Byeola and Daltsen." },
  { n: "Byeola", cat: "town", x: 6550, y: 2380, k: "Vikitsv", d: "In the Kingdom of Vikitsv, about 200 mi west of Berlailia, near Sehrok and Sahlen." },
  { n: "Sahlen", cat: "town", x: 6520, y: 2455, k: "Vikitsv", d: "In the Kingdom of Vikitsv, about 250 mi southwest of Berlailia, near Byeola and Torad." },
  { n: "Sahla", cat: "town", x: 6690, y: 2490, k: "Vikitsv", d: "In the Kingdom of Vikitsv, about 175 mi southwest of Berlailia, near Sahlen and Byeola." },
  { n: "Gaedu", cat: "town", x: 6880, y: 2535, k: "Vikitsv", d: "In the Kingdom of Vikitsv, about 200 mi south of Berlailia, near Yula and Sahla." },
  { n: "Torad", cat: "town", x: 6515, y: 2555, k: "Vikitsv", d: "In the Kingdom of Vikitsv, about 300 mi southwest of Berlailia, near Galmun and Sahlen." },
  { n: "Yula", cat: "town", x: 6860, y: 2585, k: "Vikitsv", d: "In the Kingdom of Vikitsv, about 225 mi south of Berlailia, near Gaedu and Sahla." },
  { n: "Galmun", cat: "town", x: 6580, y: 2630, k: "Vikitsv", d: "In the Kingdom of Vikitsv, about 325 mi southwest of Berlailia, near Junjeo and Torad." },
  { n: "Junjeo", cat: "town", x: 6620, y: 2705, k: "Vikitsv", d: "In the Kingdom of Vikitsv, about 350 mi southwest of Berlailia, near Vekit and Galmun. Town of the Torad valleys; the smaller town Vekit sits within it." },
  { n: "Oskba", cat: "town", x: 4595, y: 2840, k: "Gherci", d: "In the Kingdom of Gherci, about 725 mi southeast of Tarmet, near Tagrim and Trask." },
  { n: "Limn", cat: "town", x: 5330, y: 2785, k: "the far-eastern territories", d: "In the far-eastern territories beyond Gherci's border, about 150 mi southwest of Amba, near Demre and Dordbin." },
  { n: "Dordbin", cat: "town", x: 5185, y: 2835, k: "the far-eastern territories", d: "In the far-eastern territories beyond Gherci's border, about 175 mi southeast of Mireb, near Limn and Demre." },
  { n: "Maryos", cat: "town", x: 5445, y: 2905, k: "the far-eastern territories", d: "In the far-eastern territories beyond Gherci's border, about 200 mi south of Amba, near Limn and Selvet." },
  { n: "Gilsa", cat: "town", x: 5715, y: 2970, k: "Vikitsv", d: "In the Kingdom of Vikitsv, about 1025 mi southwest of Berlailia, near Bohan and Ompol." },
  { n: "Namilna", cat: "town", x: 6750, y: 2930, k: "Vikitsv", d: "In the Kingdom of Vikitsv, about 500 mi south of Berlailia, near Gjen and Vekit." },
  { n: "Gjen", cat: "town", x: 6895, y: 2940, k: "Vikitsv", d: "In the Kingdom of Vikitsv, about 525 mi south of Berlailia, near Qunag and Namilna." },
  { n: "Cael'mu", cat: "town", x: 7245, y: 3070, k: "Vikitsv", d: "In the Kingdom of Vikitsv, about 700 mi southeast of Berlailia, near Orjin and Port Sael." },
  { n: "Orjin", cat: "town", x: 6980, y: 3165, k: "Vikitsv", d: "In the Kingdom of Vikitsv, about 700 mi south of Berlailia, near Gjen and Qunag." },
  { n: "Vin", cat: "town", x: 6540, y: 1415, k: "Equateiy", d: "In the Kingdom of Equateiy, about 150 mi south of Ociyaran, near Pelefer and Sarn. Southern reaches of Equateiy." },
  { n: "Pelefer", cat: "town", x: 6605, y: 1420, k: "Equateiy", d: "In the Kingdom of Equateiy, about 150 mi south of Ociyaran, near Vin and Pell'oro. Southern reaches of Equateiy." },
  { n: "Orcon", cat: "town", x: 2280, y: 1895, k: "Aicruae", d: "In the Kingdom of Aicruae, about 90 mi south of Lajazer, near Avego and Aseri Gai Oshana. Haleker frontier town." },
  { n: "Valea", cat: "town", x: 2345, y: 1635, k: "Aicruae", d: "In the Kingdom of Aicruae, about 125 mi northeast of Lajazer, near Uiedenai and Hashrin." },
  { n: "Melerbo", cat: "town", x: 2445, y: 1450, k: "Aicruae", d: "In the Kingdom of Aicruae, about 300 mi northeast of Lajazer, near Holwe and Isecia." },
  { n: "Slaia", cat: "town", x: 3800, y: 435, k: "Coelum", d: "In the Kingdom of Coelum, about 250 mi northwest of Atriki, near Tilnyeau and Nisclair. Henem Bay coast." },
  { n: "Belnara", cat: "town", x: 5000, y: 1745, k: "the far-eastern territories", d: "In the far-eastern territories beyond Gherci's border, about 775 mi north of Mireb, near Semhol and Kidaris. Far-eastern band, beyond Gherci's border." },
  { n: "Rewqo", cat: "town", x: 2400, y: 1830, k: "Aicruae", d: "In the Kingdom of Aicruae, about 110 mi east of Lajazer, near Madu and Peisk." },
  { n: "Vekit", cat: "town", x: 6650, y: 2720, k: "Vikitsv", d: "In the Kingdom of Vikitsv, about 350 mi south of Berlailia, near Junjeo and Galmun. A smaller town inside Junjeo. (Approximate placement.)" },
  { n: "Aslwal", cat: "town", x: 6215, y: 1675, k: "Equateiy", d: "In the Kingdom of Equateiy, about 475 mi southwest of Ociyaran, near Uada and Esteraia. A smaller town inside Uada. (Approximate placement.)" },
  { n: "Esteraia", cat: "town", x: 6155, y: 1685, k: "Equateiy", d: "In the Kingdom of Equateiy, about 500 mi southwest of Ociyaran, near Uada and Aslwal. A smaller town inside Uada. (Approximate placement.)" },
  { n: "Loedesca", cat: "river", x: 2370, y: 2210, k: "Aicruae", d: "In the Kingdom of Aicruae, about 350 mi south of Lajazer, near Caesro and The Santie. River of southeastern Aicruae, near the southern Pireaynea border." },
  { n: "The Demon's Pit", cat: "landmark", x: 2700, y: 2150, k: "Aicruae", d: "In the Kingdom of Aicruae, about 450 mi southeast of Lajazer, near Benalo and Oahiat. Canon name for the Aicruae-Pireaynea border. (Approximate placement.)" },
];

const KINGDOMS = [
  { n: "Aicruae", capital: "Lajazer", d: "Westernmost of the six kingdoms of the pre-Empire era.", biomes: ["Grassland", "Cold desert (dry interior)", "Temperate deciduous forest", "Temperate rainforest (west coast)"] },
  { n: "Pireaynea", capital: "Civer", d: "South-central kingdom directly east of Aicruae, across the Demon's Pit.", biomes: ["Grassland", "Savanna", "Tropical seasonal forest (Fetora coast)", "Wetland (river lowlands)"] },
  { n: "Gherci", capital: "Tarmet", d: "Largest and most central kingdom of the pre-Empire era.", biomes: ["Grassland", "Savanna (dry central plains)", "Temperate deciduous forest", "Wetland (Honlo shores)"] },
  { n: "Coelum", capital: "Atriki", d: "The northern 'Forsaken Land'.", biomes: ["Taiga", "Tundra (far north)", "Temperate deciduous forest", "Grassland"] },
  { n: "Equateiy", capital: "Ociyaran", d: "Highland kingdom of the northeast.", biomes: ["Grassland", "Temperate deciduous forest", "Temperate rainforest (Oberya cliffs)", "Taiga (highlands)"] },
  { n: "Vikitsv", capital: "Berlailia", d: "Mountain kingdom of the eastern peninsula, radiating from Mount Aicren.", biomes: ["Tundra", "Glacier (high massif)", "Taiga", "Temperate rainforest (coastal slopes)"] }
];

const BIOMES = [
  { name: "Hot desert", color: "#fbe79f" },
  { name: "Cold desert", color: "#b5b887" },
  { name: "Savanna", color: "#d2d082" },
  { name: "Grassland", color: "#c8d68f" },
  { name: "Tropical seasonal forest", color: "#b6d95d" },
  { name: "Temperate deciduous forest", color: "#29bc56" },
  { name: "Tropical rainforest", color: "#7dcb35" },
  { name: "Temperate rainforest", color: "#409c43" },
  { name: "Taiga", color: "#4b6b32" },
  { name: "Tundra", color: "#96784b" },
  { name: "Glacier", color: "#d5e7eb" },
  { name: "Wetland", color: "#0b9131" }
];
