// Empire-era gazetteer (Early Empire -> Golden Millennia, ~7160 BR - ~1852 AR).
// Extracted from the Azgaar SVG "Bela 2026-08-23-23-09"; coordinates are atlas pixels (SVG x5).
// Names taken verbatim from the SVG label text; countries assigned by point-in-polygon of state borders.
// cat: region | capital | city | town | water | river | island | forest | territory | landmark

const PLACES_EMPIRE = [
  { n: "Aoim", cat: "region", x: 4826, y: 1655, k: "The Caporiolan Kingdom", d: "A region in the Caporiolan Kingdom." },
  { n: "Aserag", cat: "region", x: 2682, y: 2211, k: "Lingia", d: "A region in Lingia." },
  { n: "Baest", cat: "region", x: 3217, y: 1897, k: "Lingia", d: "A region in Lingia." },
  { n: "Bavienna", cat: "region", x: 4127, y: 2202, k: "The Caporiolan Kingdom", d: "A region in the Caporiolan Kingdom." },
  { n: "Caduto", cat: "region", x: 6526, y: 1537, k: "The Uxridian Grand Duchy", d: "A region in the Uxridian Grand Duchy." },
  { n: "Feacen", cat: "region", x: 3216, y: 2425, k: "Lingia", d: "A region in Lingia." },
  { n: "Halkere", cat: "region", x: 2434, y: 1988, k: "The Tanan Grand Duchy", d: "A region in the Tanan Grand Duchy." },
  { n: "Hikai", cat: "region", x: 4083, y: 1010, k: "Hikai", d: "Formerly the kingdom of Coelum, the bankrupt 'Forsaken Land'. Capital: Osenki." },
  { n: "Lingia", cat: "region", x: 3190, y: 2248, k: "Lingia", d: "Formerly the kingdom of Pireaynea, its warlord anarchy subdued by imperial troops. Capital: Haleret." },
  { n: "Lower Cosar", cat: "region", x: 3814, y: 2403, k: "Lingia", d: "A region in Lingia." },
  { n: "The Aoner", cat: "region", x: 2028, y: 1831, k: "The Tanan Grand Duchy", d: "A region in the Tanan Grand Duchy." },
  { n: "The Caporiolan Kingdom", cat: "region", x: 4209, y: 1869, k: "The Caporiolan Kingdom", d: "Formerly the kingdom of Gherci; the theocratic heartland and seat of the Solisian Empire. Capital: Baviet." },
  { n: "The Senagai", cat: "region", x: 1615, y: 2236, k: "The Tanan Grand Duchy", d: "A region in the Tanan Grand Duchy." },
  { n: "The Tanan Grand Duchy", cat: "region", x: 2375, y: 1946, k: "The Tanan Grand Duchy", d: "Formerly the kingdom of Aicruae, the western breadbasket. One of the great powers of the Early Empire. Capital: Lajazer." },
  { n: "The Uxridian Grand Duchy", cat: "region", x: 6636, y: 1220, k: "The Uxridian Grand Duchy", d: "Formerly the kingdom of Equateiy, the wealthy banking oligarchy that joined the empire by treaty. Capital: Ociyaran." },
  { n: "Theolisseia", cat: "region", x: 6379, y: 1793, k: "Theolisseia", d: "Formerly the kingdom of Vikitsv, the mountain magocracy of Mount Aicren. Capital: Hadirel." },
  { n: "Urdey", cat: "region", x: 3396, y: 2104, k: "Lingia", d: "A region in Lingia." },
  { n: "Baviet", cat: "capital", x: 4130, y: 2087, k: "The Caporiolan Kingdom", d: "Capital of the Caporiolan Kingdom." },
  { n: "Hadirel", cat: "capital", x: 6790, y: 2348, k: "Theolisseia", d: "Capital of Theolisseia." },
  { n: "Haleret", cat: "capital", x: 3160, y: 2468, k: "Lingia", d: "Capital of Lingia." },
  { n: "Lajazer", cat: "capital", x: 1808, y: 2175, k: "The Tanan Grand Duchy", d: "Capital of the Tanan Grand Duchy." },
  { n: "Ociyaran", cat: "capital", x: 6593, y: 1313, k: "The Uxridian Grand Duchy", d: "Capital of the Uxridian Grand Duchy." },
  { n: "Osenki", cat: "capital", x: 3918, y: 763, k: "Hikai", d: "Capital of Hikai." },
  { n: "Port Absey", cat: "city", x: 3614, y: 2616, k: "Lingia", d: "In Lingia, about 375 mi east of Haleret, near Durk and Brannik." },
  { n: "Port Aresca", cat: "city", x: 3539, y: 871, k: "Hikai", d: "In Hikai, about 325 mi west of Osenki, near Port Theli and Corocco." },
  { n: "Port Esserey", cat: "city", x: 2574, y: 1132, k: "The Tanan Grand Duchy", d: "In the Tanan Grand Duchy, about 1025 mi northeast of Lajazer, near Baram and Linjet." },
  { n: "Port Linnos", cat: "city", x: 5160, y: 2894, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 1050 mi southeast of Baviet, near Dordbin and Mireb." },
  { n: "Port Naole", cat: "city", x: 1783, y: 2104, k: "The Tanan Grand Duchy", d: "In the Tanan Grand Duchy, about 60 mi north of Lajazer, near Lajazer and Ostoke." },
  { n: "Port Ols", cat: "city", x: 2878, y: 2764, k: "Lingia", d: "In Lingia, about 325 mi southwest of Haleret, near Hulber and Drosk." },
  { n: "Port Pontes", cat: "city", x: 4335, y: 2776, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 575 mi south of Baviet, near Kuldara and Druun." },
  { n: "Port Qual", cat: "city", x: 1809, y: 2228, k: "The Tanan Grand Duchy", d: "In the Tanan Grand Duchy, about 40 mi south of Lajazer, near Lajazer and Tericaer." },
  { n: "Port Rebadeen", cat: "city", x: 4780, y: 134, k: "Hikai", d: "In Hikai, about 850 mi northeast of Osenki, near Ricna and Niarn." },
  { n: "Port Sael", cat: "city", x: 7254, y: 2759, k: "Theolisseia", d: "In Theolisseia, about 500 mi southeast of Hadirel, near Qunag and Caelmu." },
  { n: "Port Theli", cat: "city", x: 3632, y: 894, k: "Hikai", d: "In Hikai, about 250 mi southwest of Osenki, near Corocco and Port Aresca." },
  { n: "Port Vente", cat: "city", x: 2383, y: 1224, k: "The Tanan Grand Duchy", d: "In the Tanan Grand Duchy, about 875 mi northeast of Lajazer, near Weca and Sretan." },
  { n: "Port Vessar", cat: "city", x: 3218, y: 1111, k: "Hikai", d: "In Hikai, about 625 mi southwest of Osenki, near Osegri and Etanda." },
  { n: "Port Volpa", cat: "city", x: 6723, y: 898, k: "The Uxridian Grand Duchy", d: "In the Uxridian Grand Duchy, about 350 mi north of Ociyaran, near Querceta and Cala." },
  { n: "Aanye", cat: "town", x: 4928, y: 2322, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 675 mi east of Baviet, near Yvenna and Orim." },
  { n: "Acin", cat: "town", x: 3978, y: 2642, k: "Lingia", d: "In Lingia, about 675 mi east of Haleret, near Pondata and Riedra." },
  { n: "Adaani", cat: "town", x: 4204, y: 1409, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 550 mi north of Baviet, near Resia and The Maadun." },
  { n: "Alben", cat: "town", x: 2381, y: 1560, k: "The Tanan Grand Duchy", d: "In the Tanan Grand Duchy, about 675 mi northeast of Lajazer, near Atanie and Wisten." },
  { n: "Allisto", cat: "town", x: 5951, y: 2111, k: "Theolisseia", d: "In Theolisseia, about 700 mi west of Hadirel, near Bralk and Sevq." },
  { n: "Alpena", cat: "town", x: 7105, y: 995, k: "The Uxridian Grand Duchy", d: "In the Uxridian Grand Duchy, about 475 mi northeast of Ociyaran, near Muralto and Jhera." },
  { n: "Alsea", cat: "town", x: 3350, y: 1738, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 675 mi northwest of Baviet, near Croco and Maadol." },
  { n: "Aluun", cat: "town", x: 4128, y: 1554, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 425 mi north of Baviet, near Belune and Malea." },
  { n: "Amba", cat: "town", x: 5651, y: 2638, k: "Theolisseia", d: "In Theolisseia, about 925 mi west of Hadirel, near Selvet and Limn." },
  { n: "Amberactserun", cat: "town", x: 5148, y: 1588, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 900 mi northeast of Baviet, near Tasfen and Bellaria." },
  { n: "Amesa", cat: "town", x: 4760, y: 2026, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 500 mi east of Baviet, near Calyea and Ristea." },
  { n: "Anaan", cat: "town", x: 3254, y: 1339, k: "Hikai", d: "In Hikai, about 700 mi southwest of Osenki, near Tophercris and Giagior." },
  { n: "Anjelea", cat: "town", x: 4226, y: 2374, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 250 mi south of Baviet, near Pelea and Caspara." },
  { n: "Annagi", cat: "town", x: 2730, y: 1495, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 1200 mi northwest of Baviet, near Noraho and Lanmi." },
  { n: "Anthela", cat: "town", x: 5250, y: 1754, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 925 mi east of Baviet, near Bellaria and Semhol." },
  { n: "Anye", cat: "town", x: 4652, y: 2548, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 550 mi southeast of Baviet, near Druun and Eskua." },
  { n: "Apric", cat: "town", x: 2995, y: 1682, k: "Lingia", d: "In Lingia, about 650 mi north of Haleret, near Noju and Corvane." },
  { n: "Arona", cat: "town", x: 6727, y: 1134, k: "The Uxridian Grand Duchy", d: "In the Uxridian Grand Duchy, about 175 mi northeast of Ociyaran, near Gabbia and Neska." },
  { n: "Aseri Minqa", cat: "town", x: 2321, y: 1841, k: "The Tanan Grand Duchy", d: "In the Tanan Grand Duchy, about 500 mi northeast of Lajazer, near Orcan and The Razane." },
  { n: "Aseri Oshana", cat: "town", x: 2161, y: 1850, k: "The Tanan Grand Duchy", d: "In the Tanan Grand Duchy, about 375 mi northeast of Lajazer, near Cale and Macerin." },
  { n: "Asmeta", cat: "town", x: 4042, y: 2009, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 90 mi northwest of Baviet, near Cerby and Tereas." },
  { n: "Aspardo", cat: "town", x: 5536, y: 2034, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 1125 mi east of Baviet, near Tusjin and Vagust." },
  { n: "Atanie", cat: "town", x: 2382, y: 1592, k: "The Tanan Grand Duchy", d: "In the Tanan Grand Duchy, about 650 mi northeast of Lajazer, near Alben and Wisten." },
  { n: "Audine", cat: "town", x: 1993, y: 2344, k: "The Tanan Grand Duchy", d: "In the Tanan Grand Duchy, about 200 mi southeast of Lajazer, near Barete and Port Qual." },
  { n: "Avaani", cat: "town", x: 4647, y: 1964, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 425 mi east of Baviet, near Ristea and Amesa." },
  { n: "Avege", cat: "town", x: 2232, y: 1973, k: "The Tanan Grand Duchy", d: "In the Tanan Grand Duchy, about 375 mi northeast of Lajazer, near Dira and Comei." },
  { n: "Awq Tari", cat: "town", x: 3042, y: 2036, k: "Lingia", d: "In Lingia, about 350 mi north of Haleret, near Rosk and Jurva." },
  { n: "Baram", cat: "town", x: 2724, y: 1250, k: "The Tanan Grand Duchy", d: "In the Tanan Grand Duchy, about 1050 mi northeast of Lajazer, near Bion and Kunes." },
  { n: "Barete", cat: "town", x: 2026, y: 2173, k: "The Tanan Grand Duchy", d: "In the Tanan Grand Duchy, about 175 mi east of Lajazer, near Hepen and The Aonesse." },
  { n: "Basar Tari", cat: "town", x: 2487, y: 2629, k: "Lingia", d: "In Lingia, about 550 mi west of Haleret, near Thya and Laone." },
  { n: "Bayen", cat: "town", x: 4141, y: 1838, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 200 mi north of Baviet, near Teirenna and Tarmet." },
  { n: "Belei", cat: "town", x: 2253, y: 1516, k: "The Tanan Grand Duchy", d: "In the Tanan Grand Duchy, about 625 mi northeast of Lajazer, near Fordei and Hashren." },
  { n: "Bellaria", cat: "town", x: 5248, y: 1690, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 950 mi east of Baviet, near Anthela and Semhol." },
  { n: "Belnara", cat: "town", x: 4972, y: 1742, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 725 mi east of Baviet, near Iela and Luja." },
  { n: "Belune", cat: "town", x: 4064, y: 1619, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 375 mi north of Baviet, near Aluun and Nyes." },
  { n: "Benale", cat: "town", x: 2416, y: 2056, k: "The Tanan Grand Duchy", d: "In the Tanan Grand Duchy, about 500 mi east of Lajazer, near Jani and Tineb." },
  { n: "Bion", cat: "town", x: 2741, y: 1252, k: "The Tanan Grand Duchy", d: "In the Tanan Grand Duchy, about 1050 mi northeast of Lajazer, near Baram and Kunes." },
  { n: "Birme", cat: "town", x: 2546, y: 1342, k: "The Tanan Grand Duchy", d: "In the Tanan Grand Duchy, about 900 mi northeast of Lajazer, near Borgeste and Melerb." },
  { n: "Bohan", cat: "town", x: 6177, y: 2882, k: "Theolisseia", d: "In Theolisseia, about 650 mi southwest of Hadirel, near Murok and Ompol." },
  { n: "Boletre  Begai", cat: "town", x: 2171, y: 2020, k: "The Tanan Grand Duchy", d: "In the Tanan Grand Duchy, about 325 mi northeast of Lajazer, near Lovec and Mepren." },
  { n: "Borgeste", cat: "town", x: 2470, y: 1366, k: "The Tanan Grand Duchy", d: "In the Tanan Grand Duchy, about 825 mi northeast of Lajazer, near Birme and Melerb." },
  { n: "Brae", cat: "town", x: 6251, y: 1232, k: "The Uxridian Grand Duchy", d: "In the Uxridian Grand Duchy, about 275 mi west of Ociyaran, near Oa and Cresp." },
  { n: "Bralk", cat: "town", x: 5971, y: 2160, k: "Theolisseia", d: "In Theolisseia, about 675 mi west of Hadirel, near Allisto and Sevq." },
  { n: "Brannik", cat: "town", x: 3337, y: 2490, k: "Lingia", d: "In Lingia, about 150 mi east of Haleret, near Gorst and Civer." },
  { n: "Breno", cat: "town", x: 6142, y: 1138, k: "The Uxridian Grand Duchy", d: "In the Uxridian Grand Duchy, about 375 mi west of Ociyaran, near Oa and Lun." },
  { n: "Brentola", cat: "town", x: 6742, y: 1366, k: "The Uxridian Grand Duchy", d: "In the Uxridian Grand Duchy, about 125 mi east of Ociyaran, near Vin and Pelefer." },
  { n: "Breston", cat: "town", x: 2707, y: 1679, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 1175 mi west of Baviet, near Genga and Lanmi." },
  { n: "Brielega", cat: "town", x: 3738, y: 1278, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 725 mi northwest of Baviet, near Masotom and Coloni." },
  { n: "Burane", cat: "town", x: 7033, y: 1208, k: "Theolisseia", d: "In Theolisseia, about 925 mi north of Hadirel, near Squero and Dragse." },
  { n: "Byeola", cat: "town", x: 6550, y: 2379, k: "Theolisseia", d: "In Theolisseia, about 200 mi west of Hadirel, near Sehrok and Sahlen." },
  { n: "Caelmu", cat: "town", x: 7239, y: 3068, k: "Theolisseia", d: "In Theolisseia, about 675 mi southeast of Hadirel, near Orjin and Qunag." },
  { n: "Cala", cat: "town", x: 6642, y: 921, k: "The Uxridian Grand Duchy", d: "In the Uxridian Grand Duchy, about 325 mi north of Ociyaran, near Querceta and Port Volpa." },
  { n: "Cale", cat: "town", x: 2136, y: 1900, k: "The Tanan Grand Duchy", d: "In the Tanan Grand Duchy, about 350 mi northeast of Lajazer, near Aseri Oshana and Lovec." },
  { n: "Calyea", cat: "town", x: 4760, y: 2110, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 500 mi east of Baviet, near Amesa and Thelea." },
  { n: "Camrudar", cat: "town", x: 4680, y: 1201, k: "Hikai", d: "In Hikai, about 700 mi southeast of Osenki, near Inqua and Ridal." },
  { n: "Cardoric", cat: "town", x: 3704, y: 1451, k: "Hikai", d: "In Hikai, about 575 mi south of Osenki, near Selve and Oscana." },
  { n: "Caspara", cat: "town", x: 4276, y: 2305, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 200 mi southeast of Baviet, near Hevetane and Anjelea." },
  { n: "Casqen Zaeri", cat: "town", x: 2532, y: 1722, k: "The Tanan Grand Duchy", d: "In the Tanan Grand Duchy, about 675 mi northeast of Lajazer, near Uedena and Zagare." },
  { n: "Cerby", cat: "town", x: 4010, y: 2024, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 100 mi northwest of Baviet, near Asmeta and Lage." },
  { n: "Cesro", cat: "town", x: 2646, y: 2119, k: "Lingia", d: "In Lingia, about 500 mi northwest of Haleret, near Lorig and Drav Tari." },
  { n: "Chiavanto", cat: "town", x: 6994, y: 1056, k: "The Uxridian Grand Duchy", d: "In the Uxridian Grand Duchy, about 375 mi northeast of Ociyaran, near Riy and Doresi." },
  { n: "Chiozza", cat: "town", x: 6812, y: 808, k: "The Uxridian Grand Duchy", d: "In the Uxridian Grand Duchy, about 450 mi northeast of Ociyaran, near Latso and Tesora." },
  { n: "Cira", cat: "town", x: 6456, y: 1260, k: "The Uxridian Grand Duchy", d: "In the Uxridian Grand Duchy, about 125 mi west of Ociyaran, near Roi and Sarn." },
  { n: "Civer", cat: "town", x: 3243, y: 2495, k: "Lingia", d: "In Lingia, about 70 mi east of Haleret, near Sindber and Haleret." },
  { n: "Claieso", cat: "town", x: 6937, y: 1243, k: "The Uxridian Grand Duchy", d: "In the Uxridian Grand Duchy, about 275 mi east of Ociyaran, near Colle and Kanghol." },
  { n: "Coelys", cat: "town", x: 3120, y: 1601, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 900 mi northwest of Baviet, near Thevia and Iaga." },
  { n: "Colle", cat: "town", x: 6948, y: 1174, k: "The Uxridian Grand Duchy", d: "In the Uxridian Grand Duchy, about 300 mi east of Ociyaran, near Claieso and Riy." },
  { n: "Coloni", cat: "town", x: 3718, y: 1183, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 800 mi northwest of Baviet, near Masotom and Brielega." },
  { n: "Comei", cat: "town", x: 2278, y: 2018, k: "The Tanan Grand Duchy", d: "In the Tanan Grand Duchy, about 400 mi east of Lajazer, near Jani and Avege." },
  { n: "Corocco", cat: "town", x: 3600, y: 957, k: "Hikai", d: "In Hikai, about 300 mi southwest of Osenki, near Neaea and Port Theli." },
  { n: "Corsa", cat: "town", x: 6400, y: 1118, k: "The Uxridian Grand Duchy", d: "In the Uxridian Grand Duchy, about 225 mi northwest of Ociyaran, near Vigila and Lidresa." },
  { n: "Corvane", cat: "town", x: 2978, y: 1767, k: "Lingia", d: "In Lingia, about 575 mi north of Haleret, near Apric and Noju." },
  { n: "Cosar", cat: "town", x: 3620, y: 2144, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 400 mi west of Baviet, near Drin and The Pontesi." },
  { n: "Cresp", cat: "town", x: 6316, y: 1314, k: "The Uxridian Grand Duchy", d: "In the Uxridian Grand Duchy, about 225 mi west of Ociyaran, near Reda and Ilvo." },
  { n: "Croco", cat: "town", x: 3497, y: 1735, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 575 mi northwest of Baviet, near Olune and Ezon." },
  { n: "Cuola", cat: "town", x: 4344, y: 1809, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 275 mi northeast of Baviet, near Ostara and Malim." },
  { n: "Cymea", cat: "town", x: 3970, y: 1513, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 475 mi north of Baviet, near Nyes and Rietha." },
  { n: "Dahn", cat: "town", x: 5849, y: 2365, k: "Theolisseia", d: "In Theolisseia, about 750 mi west of Hadirel, near Sevq and Hauk." },
  { n: "Daltsen", cat: "town", x: 6815, y: 2224, k: "Theolisseia", d: "In Theolisseia, about 100 mi north of Hadirel, near Hadirel and Negiet." },
  { n: "Demia", cat: "town", x: 5202, y: 2505, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 925 mi east of Baviet, near Vagan and Demre." },
  { n: "Demre", cat: "town", x: 5277, y: 2652, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 1025 mi southeast of Baviet, near Mireb and Demia." },
  { n: "Denkay", cat: "town", x: 5712, y: 2041, k: "Theolisseia", d: "In Theolisseia, about 900 mi west of Hadirel, near Tusjin and Aspardo." },
  { n: "Dessane", cat: "town", x: 3174, y: 2582, k: "Lingia", d: "In Lingia, about 90 mi south of Haleret, near Sindber and Civer." },
  { n: "Deyare", cat: "town", x: 2187, y: 1748, k: "The Tanan Grand Duchy", d: "In the Tanan Grand Duchy, about 450 mi northeast of Lajazer, near Macerin and Jaserey." },
  { n: "Dira", cat: "town", x: 2207, y: 1975, k: "The Tanan Grand Duchy", d: "In the Tanan Grand Duchy, about 350 mi northeast of Lajazer, near Avege and Lovec." },
  { n: "Doka", cat: "town", x: 4142, y: 2135, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 40 mi south of Baviet, near Baviet and Keba." },
  { n: "Dordbin", cat: "town", x: 5184, y: 2832, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 1025 mi southeast of Baviet, near Port Linnos and Mireb." },
  { n: "Doresi", cat: "town", x: 6933, y: 1054, k: "The Uxridian Grand Duchy", d: "In the Uxridian Grand Duchy, about 350 mi northeast of Ociyaran, near Chiavanto and Riy." },
  { n: "Dragse", cat: "town", x: 7072, y: 1283, k: "Theolisseia", d: "In Theolisseia, about 875 mi north of Hadirel, near Burane and Kanghol." },
  { n: "Drav Tari", cat: "town", x: 2680, y: 2029, k: "Lingia", d: "In Lingia, about 525 mi northwest of Haleret, near Cesro and Lorig." },
  { n: "Dremk", cat: "town", x: 5228, y: 2076, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 875 mi east of Baviet, near Ledea and Menejela." },
  { n: "Drenia", cat: "town", x: 3571, y: 1609, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 575 mi northwest of Baviet, near Ezon and Lasten." },
  { n: "Drin", cat: "town", x: 3649, y: 2170, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 400 mi west of Baviet, near Cosar and Golana." },
  { n: "Drosk", cat: "town", x: 3024, y: 2457, k: "Lingia", d: "In Lingia, about 100 mi west of Haleret, near Tolm and Haleret." },
  { n: "Druun", cat: "town", x: 4511, y: 2619, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 525 mi southeast of Baviet, near Anye and Forea." },
  { n: "Dugwil", cat: "town", x: 5514, y: 2201, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 1100 mi east of Baviet, near Tsir and Rudeth." },
  { n: "Durisea", cat: "town", x: 3795, y: 1367, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 625 mi northwest of Baviet, near Selve and Gondes." },
  { n: "Durk", cat: "town", x: 3470, y: 2389, k: "Lingia", d: "In Lingia, about 250 mi east of Haleret, near The Pontesi and Gorst." },
  { n: "Dushre", cat: "town", x: 1897, y: 1836, k: "The Tanan Grand Duchy", d: "In the Tanan Grand Duchy, about 275 mi north of Lajazer, near Lene and Matsene." },
  { n: "Egodi", cat: "town", x: 3631, y: 1369, k: "Hikai", d: "In Hikai, about 525 mi southwest of Osenki, near Eloe and Gelona." },
  { n: "Elemea", cat: "town", x: 4727, y: 1753, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 550 mi northeast of Baviet, near Laaya and Vashonna." },
  { n: "Eloe", cat: "town", x: 3552, y: 1344, k: "Hikai", d: "In Hikai, about 550 mi southwest of Osenki, near Egodi and Mossima." },
  { n: "Erygal", cat: "town", x: 4328, y: 944, k: "Hikai", d: "In Hikai, about 350 mi southeast of Osenki, near Eskol and Negel." },
  { n: "Eryte", cat: "town", x: 4198, y: 532, k: "Hikai", d: "In Hikai, about 300 mi northeast of Osenki, near Slaia and Nisclair." },
  { n: "Eshae", cat: "town", x: 2500, y: 1552, k: "The Tanan Grand Duchy", d: "In the Tanan Grand Duchy, about 750 mi northeast of Lajazer, near Isece and Meliut." },
  { n: "Esio", cat: "town", x: 6809, y: 1123, k: "The Uxridian Grand Duchy", d: "In the Uxridian Grand Duchy, about 225 mi northeast of Ociyaran, near Pelefera and Neska." },
  { n: "Eskert", cat: "town", x: 4769, y: 718, k: "Hikai", d: "In Hikai, about 675 mi east of Osenki, near Ortuqil and Riyen." },
  { n: "Eskol", cat: "town", x: 4194, y: 869, k: "Hikai", d: "In Hikai, about 225 mi east of Osenki, near Erygal and Ilkane." },
  { n: "Eskua", cat: "town", x: 4702, y: 2735, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 700 mi southeast of Baviet, near Oskaba and Tagrima." },
  { n: "Etanda", cat: "town", x: 3336, y: 1013, k: "Hikai", d: "In Hikai, about 500 mi southwest of Osenki, near Port Vessar and Seppegiu." },
  { n: "Eynora", cat: "town", x: 3912, y: 100, k: "Hikai", d: "In Hikai, about 525 mi north of Osenki, near Skya and Lagora." },
  { n: "Ezon", cat: "town", x: 3482, y: 1601, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 650 mi northwest of Baviet, near Drenia and Lasten." },
  { n: "Fayede", cat: "town", x: 2066, y: 1782, k: "The Tanan Grand Duchy", d: "In the Tanan Grand Duchy, about 375 mi northeast of Lajazer, near Neribe and Macerin." },
  { n: "Foce", cat: "town", x: 6473, y: 974, k: "The Uxridian Grand Duchy", d: "In the Uxridian Grand Duchy, about 275 mi north of Ociyaran, near Malamo and Senna." },
  { n: "Fordei", cat: "town", x: 2296, y: 1458, k: "The Tanan Grand Duchy", d: "In the Tanan Grand Duchy, about 700 mi northeast of Lajazer, near Belei and Itara." },
  { n: "Forea", cat: "town", x: 4447, y: 2467, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 400 mi southeast of Baviet, near Druun and Nordos." },
  { n: "Gabbia", cat: "town", x: 6723, y: 1087, k: "The Uxridian Grand Duchy", d: "In the Uxridian Grand Duchy, about 200 mi northeast of Ociyaran, near Neska and Arona." },
  { n: "Gaedu", cat: "town", x: 6886, y: 2529, k: "Theolisseia", d: "In Theolisseia, about 175 mi southeast of Hadirel, near Yula and Zemel." },
  { n: "Gai", cat: "town", x: 5453, y: 2529, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 1100 mi east of Baviet, near Hagiore and Hagia Demre." },
  { n: "Galmun", cat: "town", x: 6599, y: 2643, k: "Theolisseia", d: "In Theolisseia, about 275 mi southwest of Hadirel, near Junjeo and Torad." },
  { n: "Garen", cat: "town", x: 4877, y: 1514, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 750 mi northeast of Baviet, near Tasfen and Oryur." },
  { n: "Gelona", cat: "town", x: 3618, y: 1278, k: "Hikai", d: "In Hikai, about 475 mi southwest of Osenki, near Masotom and Egodi." },
  { n: "Genga", cat: "town", x: 2670, y: 1714, k: "The Tanan Grand Duchy", d: "In the Tanan Grand Duchy, about 775 mi northeast of Lajazer, near Breston and Zagare." },
  { n: "Giagior", cat: "town", x: 3204, y: 1448, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 900 mi northwest of Baviet, near Mema and Anaan." },
  { n: "Gilsa", cat: "town", x: 5721, y: 2968, k: "Theolisseia", d: "In Theolisseia, about 975 mi southwest of Hadirel, near Limn and Selvet." },
  { n: "Gjen", cat: "town", x: 6893, y: 2944, k: "Theolisseia", d: "In Theolisseia, about 475 mi south of Hadirel, near Namilna and Zemel." },
  { n: "Gogla", cat: "town", x: 7012, y: 2118, k: "Theolisseia", d: "In Theolisseia, about 250 mi northeast of Hadirel, near Negiet and Daltsen." },
  { n: "Golana", cat: "town", x: 3823, y: 2152, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 250 mi west of Baviet, near Lage and Drin." },
  { n: "Gondes", cat: "town", x: 3845, y: 1306, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 675 mi north of Baviet, near The Duriaan and Durisea." },
  { n: "Gora", cat: "town", x: 6652, y: 1170, k: "The Uxridian Grand Duchy", d: "In the Uxridian Grand Duchy, about 125 mi north of Ociyaran, near Arona and Nelva." },
  { n: "Gorma", cat: "town", x: 4732, y: 520, k: "Hikai", d: "In Hikai, about 675 mi east of Osenki, near Ricna and Ortuqil." },
  { n: "Gorst", cat: "town", x: 3337, y: 2412, k: "Lingia", d: "In Lingia, about 150 mi east of Haleret, near Brannik and Civer." },
  { n: "Goteivane", cat: "town", x: 2289, y: 2275, k: "The Tanan Grand Duchy", d: "In the Tanan Grand Duchy, about 400 mi east of Lajazer, near The Santie and Meprie Teish." },
  { n: "Granosa", cat: "town", x: 4034, y: 2198, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 125 mi southwest of Baviet, near Doka and Tarl." },
  { n: "Grotta", cat: "town", x: 6201, y: 1554, k: "The Uxridian Grand Duchy", d: "In the Uxridian Grand Duchy, about 375 mi southwest of Ociyaran, near Pratesi and Ravia." },
  { n: "Hadber", cat: "town", x: 2187, y: 1635, k: "The Tanan Grand Duchy", d: "In the Tanan Grand Duchy, about 525 mi northeast of Lajazer, near Sarleiane and Hashren." },
  { n: "Hagia Demre", cat: "town", x: 5473, y: 2425, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 1100 mi east of Baviet, near Hagiore and Gai." },
  { n: "Hagiora", cat: "town", x: 5299, y: 1457, k: "Theolisseia", d: "In Theolisseia, about 1375 mi northwest of Hadirel, near Amberactserun and Nyedal." },
  { n: "Hagiore", cat: "town", x: 5506, y: 2514, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 1150 mi east of Baviet, near Gai and Hagia Demre." },
  { n: "Hagn", cat: "town", x: 5385, y: 2280, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 1025 mi east of Baviet, near Loria and Tsir." },
  { n: "Hanora", cat: "town", x: 6973, y: 1644, k: "The Uxridian Grand Duchy", d: "In the Uxridian Grand Duchy, about 400 mi southeast of Ociyaran, near Pelefer and Tsenmar." },
  { n: "Hashren", cat: "town", x: 2230, y: 1602, k: "The Tanan Grand Duchy", d: "In the Tanan Grand Duchy, about 575 mi northeast of Lajazer, near Sarleiane and Hadber." },
  { n: "Hauk", cat: "town", x: 5702, y: 2329, k: "Theolisseia", d: "In Theolisseia, about 875 mi west of Hadirel, near Sevq and Dahn." },
  { n: "Hepen", cat: "town", x: 2043, y: 2066, k: "The Tanan Grand Duchy", d: "In the Tanan Grand Duchy, about 200 mi northeast of Lajazer, near The Aonesse and Leyone." },
  { n: "Heusel", cat: "town", x: 2014, y: 1888, k: "The Tanan Grand Duchy", d: "In the Tanan Grand Duchy, about 275 mi northeast of Lajazer, near Leyone and Lene." },
  { n: "Hevetane", cat: "town", x: 4333, y: 2274, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 225 mi southeast of Baviet, near Caspara and Tanya Beka." },
  { n: "Hoab", cat: "town", x: 2942, y: 2125, k: "Lingia", d: "In Lingia, about 325 mi northwest of Haleret, near Rosk and Awq Tari." },
  { n: "Hoam", cat: "town", x: 4247, y: 1577, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 425 mi north of Baviet, near Malea and Aluun." },
  { n: "Holve", cat: "town", x: 2422, y: 1501, k: "The Tanan Grand Duchy", d: "In the Tanan Grand Duchy, about 725 mi northeast of Lajazer, near Itara and Isece." },
  { n: "Honet", cat: "town", x: 2188, y: 2207, k: "The Tanan Grand Duchy", d: "In the Tanan Grand Duchy, about 300 mi east of Lajazer, near Nayen and Loer." },
  { n: "Hulber", cat: "town", x: 2718, y: 2490, k: "Lingia", d: "In Lingia, about 350 mi west of Haleret, near Vask and Welk." },
  { n: "Iaga", cat: "town", x: 3034, y: 1540, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 975 mi northwest of Baviet, near Tellas and Coelys." },
  { n: "Iela", cat: "town", x: 4943, y: 1741, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 700 mi northeast of Baviet, near Belnara and Luja." },
  { n: "Ilkai", cat: "town", x: 4537, y: 1004, k: "Hikai", d: "In Hikai, about 525 mi east of Osenki, near Nalochl and Lagowyal." },
  { n: "Ilkane", cat: "town", x: 4352, y: 760, k: "Hikai", d: "In Hikai, about 350 mi east of Osenki, near Maharg and Erygal." },
  { n: "Ilvo", cat: "town", x: 6379, y: 1323, k: "The Uxridian Grand Duchy", d: "In the Uxridian Grand Duchy, about 175 mi west of Ociyaran, near Cresp and Sarn." },
  { n: "Inem", cat: "town", x: 4858, y: 1854, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 600 mi east of Baviet, near Laaya and Muuri." },
  { n: "Inke", cat: "town", x: 4482, y: 1474, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 575 mi northeast of Baviet, near Ralta and Inqua." },
  { n: "Inqua", cat: "town", x: 4658, y: 1322, k: "Hikai", d: "In Hikai, about 750 mi southeast of Osenki, near Oryur and Camrudar." },
  { n: "Isece", cat: "town", x: 2456, y: 1548, k: "The Tanan Grand Duchy", d: "In the Tanan Grand Duchy, about 725 mi northeast of Lajazer, near Eshae and Wisten." },
  { n: "Itara", cat: "town", x: 2397, y: 1487, k: "The Tanan Grand Duchy", d: "In the Tanan Grand Duchy, about 725 mi northeast of Lajazer, near Holve and Melerb." },
  { n: "Jani", cat: "town", x: 2334, y: 2049, k: "The Tanan Grand Duchy", d: "In the Tanan Grand Duchy, about 425 mi east of Lajazer, near Comei and Tineb." },
  { n: "Jaserey", cat: "town", x: 2276, y: 1695, k: "The Tanan Grand Duchy", d: "In the Tanan Grand Duchy, about 525 mi northeast of Lajazer, near Verne and The Razane." },
  { n: "Jhera", cat: "town", x: 7043, y: 920, k: "The Uxridian Grand Duchy", d: "In the Uxridian Grand Duchy, about 475 mi northeast of Ociyaran, near Muralto and Alpena." },
  { n: "Jiego", cat: "town", x: 2610, y: 1868, k: "Lingia", d: "In Lingia, about 650 mi northwest of Haleret, near Masen and Sarrod." },
  { n: "Junjeo", cat: "town", x: 6621, y: 2706, k: "Theolisseia", d: "In Theolisseia, about 325 mi southwest of Hadirel, near Galmun and Liaerton." },
  { n: "Jurva", cat: "town", x: 3157, y: 2090, k: "Lingia", d: "In Lingia, about 300 mi north of Haleret, near Rosk and Awq Tari." },
  { n: "Kanghol", cat: "town", x: 6984, y: 1318, k: "The Uxridian Grand Duchy", d: "In the Uxridian Grand Duchy, about 300 mi east of Ociyaran, near Pell'oro and Claieso." },
  { n: "Kanidon", cat: "town", x: 2590, y: 1586, k: "The Tanan Grand Duchy", d: "In the Tanan Grand Duchy, about 775 mi northeast of Lajazer, near Meliut and Eshae." },
  { n: "Keba", cat: "town", x: 4184, y: 2048, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 50 mi northeast of Baviet, near Tarmeda and Baviet." },
  { n: "Kessa", cat: "town", x: 4005, y: 1774, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 275 mi north of Baviet, near Tarmet and Shaer." },
  { n: "Kidaris", cat: "town", x: 5124, y: 1814, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 825 mi east of Baviet, near Medhuk and Anthela." },
  { n: "Kuldara", cat: "town", x: 4265, y: 2748, k: "Lingia", d: "In Lingia, about 900 mi east of Haleret, near Port Pontes and Riedra." },
  { n: "Kunes", cat: "town", x: 2746, y: 1278, k: "The Tanan Grand Duchy", d: "In the Tanan Grand Duchy, about 1025 mi northeast of Lajazer, near Bion and Baram." },
  { n: "Laaya", cat: "town", x: 4821, y: 1818, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 600 mi east of Baviet, near Inem and Ristea." },
  { n: "Lage", cat: "town", x: 3921, y: 2008, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 175 mi west of Baviet, near Cerby and Zerpe." },
  { n: "Lagora", cat: "town", x: 3724, y: 199, k: "Hikai", d: "In Hikai, about 475 mi north of Osenki, near Tilnyeau and Eynora." },
  { n: "Lagowyal", cat: "town", x: 4398, y: 1168, k: "Hikai", d: "In Hikai, about 500 mi southeast of Osenki, near Osenna and The Maadun." },
  { n: "Lanmi", cat: "town", x: 2730, y: 1592, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 1175 mi west of Baviet, near Noraho and Breston." },
  { n: "Laone", cat: "town", x: 2518, y: 2394, k: "Lingia", d: "In Lingia, about 525 mi west of Haleret, near Vask and Ledesca." },
  { n: "Larida", cat: "town", x: 6094, y: 1436, k: "The Uxridian Grand Duchy", d: "In the Uxridian Grand Duchy, about 400 mi west of Ociyaran, near Ombretta and Ravia." },
  { n: "Lasten", cat: "town", x: 3558, y: 1506, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 650 mi northwest of Baviet, near Drenia and Ezon." },
  { n: "Latso", cat: "town", x: 6862, y: 820, k: "The Uxridian Grand Duchy", d: "In the Uxridian Grand Duchy, about 450 mi northeast of Ociyaran, near Chiozza and Tesora." },
  { n: "Ledea", cat: "town", x: 5204, y: 2102, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 850 mi east of Baviet, near Dremk and Menejela." },
  { n: "Ledesca", cat: "town", x: 2368, y: 2340, k: "The Tanan Grand Duchy", d: "In the Tanan Grand Duchy, about 475 mi east of Lajazer, near Goteivane and Meprie Teish." },
  { n: "Lendara", cat: "town", x: 4291, y: 1962, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 175 mi northeast of Baviet, near Malim and Tarmeda." },
  { n: "Lene", cat: "town", x: 1954, y: 1812, k: "The Tanan Grand Duchy", d: "In the Tanan Grand Duchy, about 300 mi north of Lajazer, near Dushre and Heusel." },
  { n: "Lermea", cat: "town", x: 2222, y: 1376, k: "The Tanan Grand Duchy", d: "In the Tanan Grand Duchy, about 725 mi northeast of Lajazer, near Veris and Fordei." },
  { n: "Leyone", cat: "town", x: 2040, y: 1960, k: "The Tanan Grand Duchy", d: "In the Tanan Grand Duchy, about 250 mi northeast of Lajazer, near Heusel and The Aonesse." },
  { n: "Lezna", cat: "town", x: 6500, y: 1467, k: "The Uxridian Grand Duchy", d: "In the Uxridian Grand Duchy, about 150 mi southwest of Ociyaran, near Velu and Movo." },
  { n: "Liaerton", cat: "town", x: 6695, y: 2795, k: "Theolisseia", d: "In Theolisseia, about 375 mi south of Hadirel, near Junjeo and Galmun." },
  { n: "Liasen", cat: "town", x: 2181, y: 2092, k: "The Tanan Grand Duchy", d: "In the Tanan Grand Duchy, about 300 mi east of Lajazer, near Teyet and Mepren." },
  { n: "Lidresa", cat: "town", x: 6468, y: 1054, k: "The Uxridian Grand Duchy", d: "In the Uxridian Grand Duchy, about 225 mi northwest of Ociyaran, near Malamo and Foce." },
  { n: "Limn", cat: "town", x: 5616, y: 2784, k: "Theolisseia", d: "In Theolisseia, about 1000 mi west of Hadirel, near Selvet and Amba." },
  { n: "Linjet", cat: "town", x: 2764, y: 1206, k: "The Tanan Grand Duchy", d: "In the Tanan Grand Duchy, about 1075 mi northeast of Lajazer, near Bion and Baram." },
  { n: "Lioe", cat: "town", x: 3440, y: 1373, k: "Hikai", d: "In Hikai, about 625 mi southwest of Osenki, near Mossima and Eloe." },
  { n: "Liviao", cat: "town", x: 3023, y: 1403, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 1050 mi northwest of Baviet, near Tagre and Palere." },
  { n: "Loer", cat: "town", x: 2152, y: 2135, k: "The Tanan Grand Duchy", d: "In the Tanan Grand Duchy, about 275 mi east of Lajazer, near Teyet and Liasen." },
  { n: "Lokea", cat: "town", x: 4522, y: 1715, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 425 mi northeast of Baviet, near Ralta and Vashonna." },
  { n: "Loria", cat: "town", x: 5328, y: 2181, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 950 mi east of Baviet, near Rudeth and Hagn." },
  { n: "Lorig", cat: "town", x: 2627, y: 2154, k: "Lingia", d: "In Lingia, about 500 mi northwest of Haleret, near Cesro and Drav Tari." },
  { n: "Lovec", cat: "town", x: 2153, y: 1984, k: "The Tanan Grand Duchy", d: "In the Tanan Grand Duchy, about 325 mi northeast of Lajazer, near Boletre  Begai and Dira." },
  { n: "Luja", cat: "town", x: 4905, y: 1746, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 675 mi northeast of Baviet, near Iela and Belnara." },
  { n: "Lujian", cat: "town", x: 3673, y: 1549, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 575 mi northwest of Baviet, near Cardoric and Oscana." },
  { n: "Lun", cat: "town", x: 6272, y: 1129, k: "The Uxridian Grand Duchy", d: "In the Uxridian Grand Duchy, about 300 mi northwest of Ociyaran, near Oa and Brae." },
  { n: "Maadol", cat: "town", x: 3210, y: 1848, k: "Lingia", d: "In Lingia, about 500 mi north of Haleret, near Alsea and The Brack." },
  { n: "Maaru Maaru", cat: "town", x: 5141, y: 2294, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 825 mi east of Baviet, near Menejela and Vagan." },
  { n: "Macerin", cat: "town", x: 2176, y: 1758, k: "The Tanan Grand Duchy", d: "In the Tanan Grand Duchy, about 450 mi northeast of Lajazer, near Deyare and Aseri Oshana." },
  { n: "Madreu", cat: "town", x: 2378, y: 1760, k: "The Tanan Grand Duchy", d: "In the Tanan Grand Duchy, about 550 mi northeast of Lajazer, near Rewqo and Nyeo." },
  { n: "Maharg", cat: "town", x: 4408, y: 706, k: "Hikai", d: "In Hikai, about 400 mi east of Osenki, near Ilkane and Snurb." },
  { n: "Malamo", cat: "town", x: 6470, y: 1032, k: "The Uxridian Grand Duchy", d: "In the Uxridian Grand Duchy, about 250 mi northwest of Ociyaran, near Lidresa and Foce." },
  { n: "Malea", cat: "town", x: 4227, y: 1584, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 400 mi north of Baviet, near Hoam and Aluun." },
  { n: "Malim", cat: "town", x: 4332, y: 1955, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 200 mi northeast of Baviet, near Lendara and Tarmeda." },
  { n: "Maryos", cat: "town", x: 5468, y: 2898, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 1250 mi southeast of Baviet, near Limn and Gilsa." },
  { n: "Masen", cat: "town", x: 2636, y: 1872, k: "Lingia", d: "In Lingia, about 625 mi northwest of Haleret, near Jiego and Sarrod." },
  { n: "Masotom", cat: "town", x: 3708, y: 1264, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 750 mi northwest of Baviet, near Brielega and Coloni." },
  { n: "Matsene", cat: "town", x: 1837, y: 1930, k: "The Tanan Grand Duchy", d: "In the Tanan Grand Duchy, about 200 mi north of Lajazer, near Thalen and Melerte." },
  { n: "Medhuk", cat: "town", x: 5219, y: 1855, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 900 mi east of Baviet, near Kidaris and Anthela." },
  { n: "Melerb", cat: "town", x: 2458, y: 1449, k: "The Tanan Grand Duchy", d: "In the Tanan Grand Duchy, about 775 mi northeast of Lajazer, near Holve and Itara." },
  { n: "Melerte", cat: "town", x: 1854, y: 1998, k: "The Tanan Grand Duchy", d: "In the Tanan Grand Duchy, about 150 mi north of Lajazer, near Thalen and Ostoke." },
  { n: "Meliut", cat: "town", x: 2528, y: 1614, k: "The Tanan Grand Duchy", d: "In the Tanan Grand Duchy, about 725 mi northeast of Lajazer, near Eshae and Kanidon." },
  { n: "Mema", cat: "town", x: 3238, y: 1487, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 850 mi northwest of Baviet, near Giagior and Tophercris." },
  { n: "Menejela", cat: "town", x: 5127, y: 2172, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 800 mi east of Baviet, near Ledea and Maaru Maaru." },
  { n: "Menen", cat: "town", x: 2463, y: 1654, k: "The Tanan Grand Duchy", d: "In the Tanan Grand Duchy, about 675 mi northeast of Lajazer, near Valea and Wisten." },
  { n: "Mepren", cat: "town", x: 2204, y: 2048, k: "The Tanan Grand Duchy", d: "In the Tanan Grand Duchy, about 325 mi east of Lajazer, near Boletre  Begai and Liasen." },
  { n: "Meprie Teish", cat: "town", x: 2252, y: 2312, k: "The Tanan Grand Duchy", d: "In the Tanan Grand Duchy, about 375 mi east of Lajazer, near Goteivane and The Santie." },
  { n: "Mira", cat: "town", x: 7186, y: 1233, k: "The Uxridian Grand Duchy", d: "In the Uxridian Grand Duchy, about 475 mi east of Ociyaran, near Dragse and Burane." },
  { n: "Mireb", cat: "town", x: 5241, y: 2711, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 1025 mi southeast of Baviet, near Demre and Dordbin." },
  { n: "Mossima", cat: "town", x: 3469, y: 1309, k: "Hikai", d: "In Hikai, about 575 mi southwest of Osenki, near Lioe and Eloe." },
  { n: "Mother's hip", cat: "town", x: 4317, y: 2076, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 150 mi east of Baviet, near Tarmeda and Lendara." },
  { n: "Movo", cat: "town", x: 6449, y: 1387, k: "The Uxridian Grand Duchy", d: "In the Uxridian Grand Duchy, about 125 mi southwest of Ociyaran, near Sarn and Roi." },
  { n: "Muralto", cat: "town", x: 7041, y: 933, k: "The Uxridian Grand Duchy", d: "In the Uxridian Grand Duchy, about 475 mi northeast of Ociyaran, near Jhera and Alpena." },
  { n: "Murok", cat: "town", x: 6381, y: 2916, k: "Theolisseia", d: "In Theolisseia, about 550 mi southwest of Hadirel, near Verna Tari and Bohan." },
  { n: "Murra", cat: "town", x: 6310, y: 1438, k: "The Uxridian Grand Duchy", d: "In the Uxridian Grand Duchy, about 250 mi southwest of Ociyaran, near Rewalen and Reda." },
  { n: "Muuri", cat: "town", x: 4942, y: 1917, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 650 mi east of Baviet, near Inem and Laaya." },
  { n: "Nabuchan", cat: "town", x: 5099, y: 1059, k: "Theolisseia", d: "In Theolisseia, about 1700 mi northwest of Hadirel, near Sebrof and Ridal." },
  { n: "Nalchal", cat: "town", x: 4894, y: 897, k: "Hikai", d: "In Hikai, about 775 mi east of Osenki, near Noramec and Ridal." },
  { n: "Nalochl", cat: "town", x: 4633, y: 895, k: "Hikai", d: "In Hikai, about 575 mi east of Osenki, near Ilkai and Eskert." },
  { n: "Namilna", cat: "town", x: 6962, y: 2932, k: "Theolisseia", d: "In Theolisseia, about 475 mi south of Hadirel, near Gjen and Zemel." },
  { n: "Nayen", cat: "town", x: 2210, y: 2142, k: "The Tanan Grand Duchy", d: "In the Tanan Grand Duchy, about 325 mi east of Lajazer, near Teyet and Liasen." },
  { n: "Neaea", cat: "town", x: 3606, y: 999, k: "Hikai", d: "In Hikai, about 300 mi southwest of Osenki, near Corocco and Port Theli." },
  { n: "Negel", cat: "town", x: 4216, y: 1080, k: "Hikai", d: "In Hikai, about 350 mi southeast of Osenki, near Osenna and Erygal." },
  { n: "Negiet", cat: "town", x: 7032, y: 2200, k: "Theolisseia", d: "In Theolisseia, about 225 mi northeast of Hadirel, near Gogla and Daltsen." },
  { n: "Nelva", cat: "town", x: 6610, y: 1266, k: "The Uxridian Grand Duchy", d: "In the Uxridian Grand Duchy, about 40 mi north of Ociyaran, near Ociyaran and Gora." },
  { n: "Neribe", cat: "town", x: 2054, y: 1784, k: "The Tanan Grand Duchy", d: "In the Tanan Grand Duchy, about 375 mi northeast of Lajazer, near Fayede and Lene." },
  { n: "Neska", cat: "town", x: 6766, y: 1079, k: "The Uxridian Grand Duchy", d: "In the Uxridian Grand Duchy, about 225 mi northeast of Ociyaran, near Gabbia and Esio." },
  { n: "Niarn", cat: "town", x: 4913, y: 421, k: "Hikai", d: "In Hikai, about 850 mi east of Osenki, near Riyen and Gorma." },
  { n: "Nisclair", cat: "town", x: 4106, y: 652, k: "Hikai", d: "In Hikai, about 175 mi northeast of Osenki, near Eryte and Osenki." },
  { n: "Noju", cat: "town", x: 3002, y: 1641, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 975 mi west of Baviet, near Apric and Tellas." },
  { n: "Norabea", cat: "town", x: 5352, y: 1690, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 1025 mi east of Baviet, near Semhol and Bellaria." },
  { n: "Noraho", cat: "town", x: 2757, y: 1551, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 1175 mi west of Baviet, near Lanmi and Annagi." },
  { n: "Noramec", cat: "town", x: 5027, y: 826, k: "Hikai", d: "In Hikai, about 875 mi east of Osenki, near Nalchal and Nabuchan." },
  { n: "Nordos", cat: "town", x: 4476, y: 2288, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 325 mi southeast of Baviet, near Hevetane and Tanya Beka." },
  { n: "Nurida", cat: "town", x: 6394, y: 1642, k: "The Uxridian Grand Duchy", d: "In the Uxridian Grand Duchy, about 300 mi southwest of Ociyaran, near Uada and Velsa." },
  { n: "Nyedal", cat: "town", x: 5081, y: 1419, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 925 mi northeast of Baviet, near Tasfen and Amberactserun." },
  { n: "Nyeo", cat: "town", x: 2349, y: 1758, k: "The Tanan Grand Duchy", d: "In the Tanan Grand Duchy, about 550 mi northeast of Lajazer, near Madreu and Rewqo." },
  { n: "Nyes", cat: "town", x: 3971, y: 1554, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 450 mi north of Baviet, near Cymea and Rietha." },
  { n: "Oa", cat: "town", x: 6261, y: 1188, k: "The Uxridian Grand Duchy", d: "In the Uxridian Grand Duchy, about 275 mi west of Ociyaran, near Brae and Lun." },
  { n: "Oahat", cat: "town", x: 2786, y: 1904, k: "Lingia", d: "In Lingia, about 550 mi northwest of Haleret, near Olbe and Sarrod." },
  { n: "Oermada", cat: "town", x: 5409, y: 2005, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 1025 mi east of Baviet, near Vagust and Aspardo." },
  { n: "Olbe", cat: "town", x: 2806, y: 1963, k: "Lingia", d: "In Lingia, about 500 mi northwest of Haleret, near Oahat and Drav Tari." },
  { n: "Old Feacen", cat: "town", x: 2892, y: 2292, k: "Lingia", d: "In Lingia, about 250 mi northwest of Haleret, near Tolm and Hoab." },
  { n: "Olune", cat: "town", x: 3541, y: 1736, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 550 mi northwest of Baviet, near Croco and Oradi." },
  { n: "Ombretta", cat: "town", x: 6117, y: 1446, k: "The Uxridian Grand Duchy", d: "In the Uxridian Grand Duchy, about 400 mi west of Ociyaran, near Larida and Ravia." },
  { n: "Ompol", cat: "town", x: 6292, y: 2602, k: "Theolisseia", d: "In Theolisseia, about 450 mi southwest of Hadirel, near Torad and Verna Tari." },
  { n: "Onmore", cat: "town", x: 5300, y: 438, k: "Theolisseia", d: "In Theolisseia, about 1925 mi northwest of Hadirel, near Niarn and Riyen." },
  { n: "Oradi", cat: "town", x: 3643, y: 1799, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 450 mi northwest of Baviet, near Olune and Croco." },
  { n: "Orcan", cat: "town", x: 2304, y: 1895, k: "The Tanan Grand Duchy", d: "In the Tanan Grand Duchy, about 450 mi northeast of Lajazer, near Aseri Minqa and Avege." },
  { n: "Orim", cat: "town", x: 4758, y: 2369, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 550 mi southeast of Baviet, near Saltea and Thelea." },
  { n: "Orjin", cat: "town", x: 7217, y: 3166, k: "Theolisseia", d: "In Theolisseia, about 725 mi southeast of Hadirel, near Caelmu and Qunag." },
  { n: "Ortuqil", cat: "town", x: 4620, y: 621, k: "Hikai", d: "In Hikai, about 575 mi east of Osenki, near Snurb and Gorma." },
  { n: "Oryur", cat: "town", x: 4738, y: 1409, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 725 mi northeast of Baviet, near Inqua and Garen." },
  { n: "Oscana", cat: "town", x: 3773, y: 1518, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 525 mi northwest of Baviet, near The Seimaa and Selve." },
  { n: "Osegri", cat: "town", x: 3158, y: 1158, k: "Hikai", d: "In Hikai, about 675 mi southwest of Osenki, near Port Vessar and Raiye." },
  { n: "Osenna", cat: "town", x: 4285, y: 1146, k: "Hikai", d: "In Hikai, about 425 mi southeast of Osenki, near Negel and Lagowyal." },
  { n: "Oskaba", cat: "town", x: 4570, y: 2839, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 700 mi southeast of Baviet, near Tagrima and Eskua." },
  { n: "Ostara", cat: "town", x: 4353, y: 1688, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 375 mi northeast of Baviet, near Cuola and Ralta." },
  { n: "Ostoke", cat: "town", x: 1858, y: 2045, k: "The Tanan Grand Duchy", d: "In the Tanan Grand Duchy, about 100 mi north of Lajazer, near Melerte and Thalen." },
  { n: "Palere", cat: "town", x: 2921, y: 1328, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 1150 mi northwest of Baviet, near Rachia and Liviao." },
  { n: "Pampira", cat: "town", x: 6940, y: 867, k: "The Uxridian Grand Duchy", d: "In the Uxridian Grand Duchy, about 450 mi northeast of Ociyaran, near Paro and Tesora." },
  { n: "Pantar", cat: "town", x: 3196, y: 2356, k: "Lingia", d: "In Lingia, about 90 mi north of Haleret, near Haleret and Civer." },
  { n: "Paro", cat: "town", x: 6940, y: 805, k: "Theolisseia", d: "In Theolisseia, about 1225 mi north of Hadirel, near Tesora and Pampira." },
  { n: "Pelea", cat: "town", x: 4242, y: 2408, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 275 mi south of Baviet, near Anjelea and Riedra." },
  { n: "Pelefer", cat: "town", x: 6817, y: 1416, k: "The Uxridian Grand Duchy", d: "In the Uxridian Grand Duchy, about 200 mi southeast of Ociyaran, near Brentola and Pell'oro." },
  { n: "Pelefera", cat: "town", x: 6862, y: 1102, k: "The Uxridian Grand Duchy", d: "In the Uxridian Grand Duchy, about 275 mi northeast of Ociyaran, near Esio and Doresi." },
  { n: "Pelk", cat: "town", x: 3396, y: 2255, k: "Lingia", d: "In Lingia, about 250 mi northeast of Haleret, near Durk and The Pontesi." },
  { n: "Pell'oro", cat: "town", x: 6916, y: 1329, k: "The Uxridian Grand Duchy", d: "In the Uxridian Grand Duchy, about 250 mi east of Ociyaran, near Kanghol and Claieso." },
  { n: "Peske", cat: "town", x: 2442, y: 1738, k: "The Tanan Grand Duchy", d: "In the Tanan Grand Duchy, about 625 mi northeast of Lajazer, near Madreu and Rewqo." },
  { n: "Pondata", cat: "town", x: 3991, y: 2564, k: "Lingia", d: "In Lingia, about 675 mi east of Haleret, near Acin and Riedra." },
  { n: "Pratesi", cat: "town", x: 6229, y: 1600, k: "The Uxridian Grand Duchy", d: "In the Uxridian Grand Duchy, about 375 mi southwest of Ociyaran, near Grotta and Velsa." },
  { n: "Querceta", cat: "town", x: 6663, y: 954, k: "The Uxridian Grand Duchy", d: "In the Uxridian Grand Duchy, about 300 mi north of Ociyaran, near Cala and Port Volpa." },
  { n: "Qunag", cat: "town", x: 7190, y: 2883, k: "Theolisseia", d: "In Theolisseia, about 525 mi southeast of Hadirel, near Port Sael and Caelmu." },
  { n: "Rachia", cat: "town", x: 2816, y: 1314, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 1225 mi northwest of Baviet, near Kunes and Bion." },
  { n: "Raiye", cat: "town", x: 3038, y: 1249, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 1100 mi northwest of Baviet, near Tagre and Palere." },
  { n: "Ralta", cat: "town", x: 4480, y: 1617, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 475 mi northeast of Baviet, near Lokea and Inke." },
  { n: "Ravia", cat: "town", x: 6110, y: 1582, k: "The Uxridian Grand Duchy", d: "In the Uxridian Grand Duchy, about 450 mi southwest of Ociyaran, near Grotta and Pratesi." },
  { n: "Reda", cat: "town", x: 6299, y: 1353, k: "The Uxridian Grand Duchy", d: "In the Uxridian Grand Duchy, about 225 mi west of Ociyaran, near Cresp and Rewalen." },
  { n: "Renzolo", cat: "town", x: 3933, y: 1359, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 600 mi north of Baviet, near Gondes and The Duriaan." },
  { n: "Resate", cat: "town", x: 2891, y: 1626, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 1050 mi west of Baviet, near Tellas and Noju." },
  { n: "Resia", cat: "town", x: 4237, y: 1374, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 575 mi north of Baviet, near Adaani and The Maadun." },
  { n: "Reskt", cat: "town", x: 6617, y: 2130, k: "Theolisseia", d: "In Theolisseia, about 225 mi northwest of Hadirel, near Sehrok and Daltsen." },
  { n: "Rewalen", cat: "town", x: 6338, y: 1389, k: "The Uxridian Grand Duchy", d: "In the Uxridian Grand Duchy, about 200 mi west of Ociyaran, near Reda and Murra." },
  { n: "Rewqo", cat: "town", x: 2379, y: 1781, k: "The Tanan Grand Duchy", d: "In the Tanan Grand Duchy, about 550 mi northeast of Lajazer, near Madreu and Nyeo." },
  { n: "Ricna", cat: "town", x: 4651, y: 419, k: "Hikai", d: "In Hikai, about 650 mi northeast of Osenki, near Gorma and Snurb." },
  { n: "Ridal", cat: "town", x: 4865, y: 1106, k: "Hikai", d: "In Hikai, about 800 mi east of Osenki, near Sebrof and Camrudar." },
  { n: "Riedra", cat: "town", x: 4224, y: 2498, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 325 mi south of Baviet, near Pelea and Anjelea." },
  { n: "Rietha", cat: "town", x: 3909, y: 1616, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 425 mi northwest of Baviet, near Nyes and Cymea." },
  { n: "Rioda", cat: "town", x: 3580, y: 1139, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 875 mi northwest of Baviet, near Seppegiu and Tenda." },
  { n: "Ristea", cat: "town", x: 4747, y: 1898, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 525 mi east of Baviet, near Laaya and Inem." },
  { n: "Riy", cat: "town", x: 6980, y: 1110, k: "The Uxridian Grand Duchy", d: "In the Uxridian Grand Duchy, about 350 mi northeast of Ociyaran, near Chiavanto and Colle." },
  { n: "Riyen", cat: "town", x: 4919, y: 603, k: "Hikai", d: "In Hikai, about 800 mi east of Osenki, near Niarn and Eskert." },
  { n: "Roi", cat: "town", x: 6448, y: 1342, k: "The Uxridian Grand Duchy", d: "In the Uxridian Grand Duchy, about 125 mi west of Ociyaran, near Sarn and Movo." },
  { n: "Rosk", cat: "town", x: 3033, y: 2115, k: "Lingia", d: "In Lingia, about 300 mi north of Haleret, near Awq Tari and Hoab." },
  { n: "Rudeth", cat: "town", x: 5391, y: 2139, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 1000 mi east of Baviet, near Loria and Oermada." },
  { n: "Sahla", cat: "town", x: 6680, y: 2493, k: "Theolisseia", d: "In Theolisseia, about 150 mi southwest of Hadirel, near Sahlen and Galmun." },
  { n: "Sahlen", cat: "town", x: 6695, y: 2458, k: "Theolisseia", d: "In Theolisseia, about 125 mi southwest of Hadirel, near Sahla and Hadirel." },
  { n: "Saltea", cat: "town", x: 4757, y: 2252, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 525 mi east of Baviet, near Thelea and Orim." },
  { n: "Sarleiane", cat: "town", x: 2206, y: 1629, k: "The Tanan Grand Duchy", d: "In the Tanan Grand Duchy, about 550 mi northeast of Lajazer, near Hadber and Hashren." },
  { n: "Sarn", cat: "town", x: 6442, y: 1345, k: "The Uxridian Grand Duchy", d: "In the Uxridian Grand Duchy, about 125 mi west of Ociyaran, near Roi and Movo." },
  { n: "Sarrod", cat: "town", x: 2692, y: 1809, k: "Lingia", d: "In Lingia, about 650 mi northwest of Haleret, near Masen and Genga." },
  { n: "Sebrof", cat: "town", x: 5040, y: 1196, k: "Theolisseia", d: "In Theolisseia, about 1675 mi northwest of Hadirel, near Nabuchan and Ridal." },
  { n: "Sehrok", cat: "town", x: 6524, y: 2304, k: "Theolisseia", d: "In Theolisseia, about 225 mi west of Hadirel, near Byeola and Reskt." },
  { n: "Selve", cat: "town", x: 3796, y: 1429, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 600 mi northwest of Baviet, near Durisea and Oscana." },
  { n: "Selvet", cat: "town", x: 5676, y: 2722, k: "Theolisseia", d: "In Theolisseia, about 925 mi west of Hadirel, near Limn and Amba." },
  { n: "Semhol", cat: "town", x: 5330, y: 1724, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 1000 mi east of Baviet, near Norabea and Anthela." },
  { n: "Senalda", cat: "town", x: 6569, y: 840, k: "The Uxridian Grand Duchy", d: "In the Uxridian Grand Duchy, about 375 mi north of Ociyaran, near Cala and Zattera." },
  { n: "Senna", cat: "town", x: 6542, y: 988, k: "The Uxridian Grand Duchy", d: "In the Uxridian Grand Duchy, about 250 mi north of Ociyaran, near Sye and Foce." },
  { n: "Seppegiu", cat: "town", x: 3491, y: 1094, k: "Hikai", d: "In Hikai, about 425 mi southwest of Osenki, near Rioda and Tenda." },
  { n: "Sevq", cat: "town", x: 5821, y: 2286, k: "Theolisseia", d: "In Theolisseia, about 775 mi west of Hadirel, near Dahn and Hauk." },
  { n: "Shaer", cat: "town", x: 3903, y: 1871, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 250 mi northwest of Baviet, near Zerpe and Tarmet." },
  { n: "Sindber", cat: "town", x: 3179, y: 2552, k: "Lingia", d: "In Lingia, about 70 mi south of Haleret, near Dessane and Civer." },
  { n: "Skya", cat: "town", x: 4008, y: 162, k: "Hikai", d: "In Hikai, about 475 mi north of Osenki, near Eynora and Lagora." },
  { n: "Slaia", cat: "town", x: 4108, y: 433, k: "Hikai", d: "In Hikai, about 300 mi northeast of Osenki, near Eryte and Yleka." },
  { n: "Snurb", cat: "town", x: 4541, y: 523, k: "Hikai", d: "In Hikai, about 525 mi east of Osenki, near Ortuqil and Ricna." },
  { n: "Squero", cat: "town", x: 7048, y: 1142, k: "Theolisseia", d: "In Theolisseia, about 975 mi north of Hadirel, near Burane and Riy." },
  { n: "Sretan", cat: "town", x: 2330, y: 1295, k: "The Tanan Grand Duchy", d: "In the Tanan Grand Duchy, about 825 mi northeast of Lajazer, near Weca and Veris." },
  { n: "Stagna", cat: "town", x: 6120, y: 1267, k: "The Uxridian Grand Duchy", d: "In the Uxridian Grand Duchy, about 375 mi west of Ociyaran, near Breno and Brae." },
  { n: "Sye", cat: "town", x: 6558, y: 1050, k: "The Uxridian Grand Duchy", d: "In the Uxridian Grand Duchy, about 200 mi north of Ociyaran, near Vallaforta and Senna." },
  { n: "Tagre", cat: "town", x: 3054, y: 1378, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 1025 mi northwest of Baviet, near Liviao and Raiye." },
  { n: "Tagrima", cat: "town", x: 4721, y: 2910, k: "Lingia", d: "In Lingia, about 1300 mi east of Haleret, near Oskaba and Eskua." },
  { n: "Talu", cat: "town", x: 6059, y: 1754, k: "The Uxridian Grand Duchy", d: "In the Uxridian Grand Duchy, about 550 mi southwest of Ociyaran, near Ravia and Pratesi." },
  { n: "Tanya Beka", cat: "town", x: 4407, y: 2156, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 225 mi east of Baviet, near Mother's hip and Hevetane." },
  { n: "Tarask", cat: "town", x: 4879, y: 2674, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 750 mi southeast of Baviet, near Eskua and Anye." },
  { n: "Tarl", cat: "town", x: 4152, y: 2285, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 150 mi south of Baviet, near Anjelea and Caspara." },
  { n: "Tarmeda", cat: "town", x: 4241, y: 2016, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 100 mi northeast of Baviet, near Keba and Lendara." },
  { n: "Tarmet", cat: "town", x: 4026, y: 1902, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 175 mi northwest of Baviet, near Zerpe and Tereas." },
  { n: "Tasfen", cat: "town", x: 5039, y: 1515, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 850 mi northeast of Baviet, near Nyedal and Amberactserun." },
  { n: "Tehron", cat: "town", x: 5342, y: 1844, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 975 mi east of Baviet, near Semhol and Medhuk." },
  { n: "Teirenna", cat: "town", x: 4189, y: 1772, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 250 mi north of Baviet, near Bayen and Cuola." },
  { n: "Tellas", cat: "town", x: 2950, y: 1577, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 1025 mi northwest of Baviet, near Resate and Noju." },
  { n: "Tenda", cat: "town", x: 3507, y: 1220, k: "Hikai", d: "In Hikai, about 500 mi southwest of Osenki, near Mossima and Rioda." },
  { n: "Tereas", cat: "town", x: 4094, y: 1965, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 100 mi north of Baviet, near Asmeta and Tarmet." },
  { n: "Tericaer", cat: "town", x: 2092, y: 1648, k: "The Tanan Grand Duchy", d: "In the Tanan Grand Duchy, about 475 mi northeast of Lajazer, near Hadber and Sarleiane." },
  { n: "Tericaer", cat: "town", x: 1877, y: 2159, k: "The Tanan Grand Duchy", d: "In the Tanan Grand Duchy, about 60 mi east of Lajazer, near Lajazer and Port Qual." },
  { n: "Tesora", cat: "town", x: 6922, y: 780, k: "The Uxridian Grand Duchy", d: "In the Uxridian Grand Duchy, about 500 mi northeast of Ociyaran, near Paro and Latso." },
  { n: "Teyet", cat: "town", x: 2179, y: 2121, k: "The Tanan Grand Duchy", d: "In the Tanan Grand Duchy, about 300 mi east of Lajazer, near Liasen and Loer." },
  { n: "Thalen", cat: "town", x: 1860, y: 1964, k: "The Tanan Grand Duchy", d: "In the Tanan Grand Duchy, about 175 mi north of Lajazer, near Melerte and Matsene." },
  { n: "The Aonesse", cat: "town", x: 2023, y: 2054, k: "The Tanan Grand Duchy", d: "In the Tanan Grand Duchy, about 200 mi northeast of Lajazer, near Hepen and Leyone." },
  { n: "The Brack", cat: "town", x: 3378, y: 1984, k: "Lingia", d: "In Lingia, about 425 mi northeast of Haleret, near Maadol and Jurva." },
  { n: "The Duriaan", cat: "town", x: 3851, y: 1253, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 700 mi north of Baviet, near Gondes and Tiamma." },
  { n: "The Maadun", cat: "town", x: 4293, y: 1284, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 650 mi north of Baviet, near Resia and Osenna." },
  { n: "The Pontesi", cat: "town", x: 3540, y: 2310, k: "Lingia", d: "In Lingia, about 325 mi northeast of Haleret, near Durk and Pelk." },
  { n: "The Razane", cat: "town", x: 2313, y: 1777, k: "The Tanan Grand Duchy", d: "In the Tanan Grand Duchy, about 525 mi northeast of Lajazer, near Nyeo and Aseri Minqa." },
  { n: "The Santie", cat: "town", x: 2268, y: 2233, k: "The Tanan Grand Duchy", d: "In the Tanan Grand Duchy, about 375 mi east of Lajazer, near Goteivane and Meprie Teish." },
  { n: "The Seimaa", cat: "town", x: 3815, y: 1537, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 500 mi northwest of Baviet, near Oscana and Selve." },
  { n: "Thelea", cat: "town", x: 4752, y: 2216, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 500 mi east of Baviet, near Saltea and Calyea." },
  { n: "Thevia", cat: "town", x: 3202, y: 1626, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 825 mi northwest of Baviet, near Coelys and Mema." },
  { n: "Thya", cat: "town", x: 2461, y: 2600, k: "Lingia", d: "In Lingia, about 575 mi west of Haleret, near Basar Tari and Laone." },
  { n: "Tiamma", cat: "town", x: 3900, y: 1174, k: "Hikai", d: "In Hikai, about 325 mi south of Osenki, near The Duriaan and Gondes." },
  { n: "Tilnyeau", cat: "town", x: 3648, y: 252, k: "Hikai", d: "In Hikai, about 450 mi northwest of Osenki, near Lagora and Eynora." },
  { n: "Tineb", cat: "town", x: 2324, y: 2114, k: "The Tanan Grand Duchy", d: "In the Tanan Grand Duchy, about 425 mi east of Lajazer, near Jani and Comei." },
  { n: "Tolm", cat: "town", x: 3013, y: 2344, k: "Lingia", d: "In Lingia, about 150 mi northwest of Haleret, near Drosk and Old Feacen." },
  { n: "Tophercris", cat: "town", x: 3329, y: 1414, k: "Hikai", d: "In Hikai, about 700 mi southwest of Osenki, near Anaan and Mema." },
  { n: "Torad", cat: "town", x: 6518, y: 2556, k: "Theolisseia", d: "In Theolisseia, about 275 mi southwest of Hadirel, near Galmun and Sahla." },
  { n: "Tropie", cat: "town", x: 3381, y: 1218, k: "Hikai", d: "In Hikai, about 550 mi southwest of Osenki, near Tenda and Mossima." },
  { n: "Tsenmar", cat: "town", x: 6712, y: 1510, k: "The Uxridian Grand Duchy", d: "In the Uxridian Grand Duchy, about 175 mi southeast of Ociyaran, near Vin and Pelefer." },
  { n: "Tsir", cat: "town", x: 5506, y: 2214, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 1100 mi east of Baviet, near Dugwil and Rudeth." },
  { n: "Tusjin", cat: "town", x: 5580, y: 1976, k: "Theolisseia", d: "In Theolisseia, about 1000 mi west of Hadirel, near Aspardo and Vagust." },
  { n: "Uada", cat: "town", x: 6405, y: 1662, k: "The Uxridian Grand Duchy", d: "In the Uxridian Grand Duchy, about 325 mi southwest of Ociyaran, near Nurida and Velsa." },
  { n: "Uedena", cat: "town", x: 2576, y: 1690, k: "The Tanan Grand Duchy", d: "In the Tanan Grand Duchy, about 725 mi northeast of Lajazer, near Casqen Zaeri and Zagare." },
  { n: "Uvenza", cat: "town", x: 6856, y: 1013, k: "The Uxridian Grand Duchy", d: "In the Uxridian Grand Duchy, about 325 mi northeast of Ociyaran, near Vinalta and Doresi." },
  { n: "Vagan", cat: "town", x: 5110, y: 2444, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 825 mi east of Baviet, near Demia and Maaru Maaru." },
  { n: "Vagust", cat: "town", x: 5442, y: 1974, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 1050 mi east of Baviet, near Oermada and Aspardo." },
  { n: "Vaia", cat: "town", x: 2899, y: 1487, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 1100 mi northwest of Baviet, near Tellas and Resate." },
  { n: "Valea", cat: "town", x: 2448, y: 1626, k: "The Tanan Grand Duchy", d: "In the Tanan Grand Duchy, about 675 mi northeast of Lajazer, near Menen and Wisten." },
  { n: "Vallaforta", cat: "town", x: 6579, y: 1082, k: "The Uxridian Grand Duchy", d: "In the Uxridian Grand Duchy, about 175 mi north of Ociyaran, near Sye and Senna." },
  { n: "Vashonna", cat: "town", x: 4602, y: 1829, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 425 mi northeast of Baviet, near Lokea and Avaani." },
  { n: "Vask", cat: "town", x: 2665, y: 2454, k: "Lingia", d: "In Lingia, about 400 mi west of Haleret, near Hulber and Welk." },
  { n: "Velsa", cat: "town", x: 6289, y: 1619, k: "The Uxridian Grand Duchy", d: "In the Uxridian Grand Duchy, about 350 mi southwest of Ociyaran, near Pratesi and Nurida." },
  { n: "Velu", cat: "town", x: 6564, y: 1520, k: "The Uxridian Grand Duchy", d: "In the Uxridian Grand Duchy, about 175 mi south of Ociyaran, near Lezna and Tsenmar." },
  { n: "Veris", cat: "town", x: 2244, y: 1290, k: "The Tanan Grand Duchy", d: "In the Tanan Grand Duchy, about 775 mi northeast of Lajazer, near Sretan and Lermea." },
  { n: "Verna Tari", cat: "town", x: 6503, y: 2812, k: "Theolisseia", d: "In Theolisseia, about 425 mi southwest of Hadirel, near Junjeo and Murok." },
  { n: "Verne", cat: "town", x: 2263, y: 1661, k: "The Tanan Grand Duchy", d: "In the Tanan Grand Duchy, about 550 mi northeast of Lajazer, near Jaserey and Sarleiane." },
  { n: "Vigila", cat: "town", x: 6440, y: 1162, k: "The Uxridian Grand Duchy", d: "In the Uxridian Grand Duchy, about 175 mi northwest of Ociyaran, near Corsa and Cira." },
  { n: "Vin", cat: "town", x: 6674, y: 1418, k: "The Uxridian Grand Duchy", d: "In the Uxridian Grand Duchy, about 100 mi southeast of Ociyaran, near Brentola and Tsenmar." },
  { n: "Vinalta", cat: "town", x: 6928, y: 976, k: "The Uxridian Grand Duchy", d: "In the Uxridian Grand Duchy, about 375 mi northeast of Ociyaran, near Doresi and Uvenza." },
  { n: "Weca", cat: "town", x: 2403, y: 1282, k: "The Tanan Grand Duchy", d: "In the Tanan Grand Duchy, about 850 mi northeast of Lajazer, near Port Vente and Sretan." },
  { n: "Welk", cat: "town", x: 2718, y: 2369, k: "Lingia", d: "In Lingia, about 350 mi west of Haleret, near Vask and Hulber." },
  { n: "Wisten", cat: "town", x: 2436, y: 1596, k: "The Tanan Grand Duchy", d: "In the Tanan Grand Duchy, about 675 mi northeast of Lajazer, near Valea and Isece." },
  { n: "Yleka", cat: "town", x: 4248, y: 365, k: "Hikai", d: "In Hikai, about 400 mi northeast of Osenki, near Slaia and Eryte." },
  { n: "Ys", cat: "town", x: 7270, y: 973, k: "The Uxridian Grand Duchy", d: "In the Uxridian Grand Duchy, about 600 mi northeast of Ociyaran, near Alpena and Muralto." },
  { n: "Yula", cat: "town", x: 6840, y: 2600, k: "Theolisseia", d: "In Theolisseia, about 200 mi south of Hadirel, near Gaedu and Zemel." },
  { n: "Yvenna", cat: "town", x: 4930, y: 2171, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 650 mi east of Baviet, near Aanye and Calyea." },
  { n: "Zagare", cat: "town", x: 2595, y: 1756, k: "The Tanan Grand Duchy", d: "In the Tanan Grand Duchy, about 700 mi northeast of Lajazer, near Uedena and Casqen Zaeri." },
  { n: "Zattera", cat: "town", x: 6603, y: 716, k: "Theolisseia", d: "In Theolisseia, about 1300 mi north of Hadirel, near Senalda and Cala." },
  { n: "Zemel", cat: "town", x: 6898, y: 2718, k: "Theolisseia", d: "In Theolisseia, about 300 mi south of Hadirel, near Yula and Gaedu." },
  { n: "Zerpe", cat: "town", x: 3993, y: 1917, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 175 mi northwest of Baviet, near Tarmet and Shaer." },
  { n: "Honloor Lake", cat: "water", x: 4435, y: 1540, d: "A sea or lake of the known world." },
  { n: "Lake Bron", cat: "water", x: 3290, y: 2336, d: "A sea or lake of the known world." },
  { n: "Lake Trang", cat: "water", x: 4162, y: 805, d: "A sea or lake of the known world." },
  { n: "LakeDulve", cat: "water", x: 3135, y: 2518, d: "A sea or lake of the known world." },
  { n: "Rium Harbor", cat: "water", x: 4857, y: 718, d: "A sea or lake of the known world." },
  { n: "The Fetora Sea", cat: "water", x: 3192, y: 3184, d: "A sea or lake of the known world." },
  { n: "The Inei Bay", cat: "water", x: 4765, y: 270, d: "A sea or lake of the known world." },
  { n: "The Orburydon Sea", cat: "water", x: 7360, y: 868, d: "A sea or lake of the known world." },
  { n: "The Quather Sea", cat: "water", x: 2086, y: 562, d: "A sea or lake of the known world." },
  { n: "The Academy", cat: "island", x: 1794, y: 1423, d: "An island of the known world." },
  { n: "The Cidet", cat: "island", x: 1390, y: 2154, d: "An island of the known world." },
  { n: "Thult", cat: "island", x: 1327, y: 2718, d: "Southwestern island, formerly the Mystic Isles; claimed and renamed by the empire." },
  { n: "Abrenna Forest", cat: "forest", x: 3798, y: 1462, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 575 mi northwest of Baviet, near Selve and Oscana." },
  { n: "Aro Forest", cat: "forest", x: 6705, y: 1103, k: "The Uxridian Grand Duchy", d: "In the Uxridian Grand Duchy, about 200 mi northeast of Ociyaran, near Gabbia and Arona." },
  { n: "Nedi Forest", cat: "forest", x: 6075, y: 1706, k: "The Uxridian Grand Duchy", d: "In the Uxridian Grand Duchy, about 525 mi southwest of Ociyaran, near Talu and Ravia." },
  { n: "Silora forest", cat: "forest", x: 6730, y: 2538, k: "Theolisseia", d: "In Theolisseia, about 150 mi south of Hadirel, near Sahla and Sahlen." },
  { n: "The Caporiolan Forest", cat: "forest", x: 4870, y: 1575, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 725 mi northeast of Baviet, near Garen and Luja." },
  { n: "Tigrei Forest", cat: "forest", x: 3672, y: 1658, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 500 mi northwest of Baviet, near Lujian and Drenia." },
  { n: "Aryanara's territory", cat: "territory", x: 5329, y: 1794, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 975 mi east of Baviet, near Tehron and Semhol." },
  { n: "Dor Tari Naos", cat: "territory", x: 5316, y: 1886, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 950 mi east of Baviet, near Tehron and Medhuk." },
  { n: "Naos Adwe", cat: "territory", x: 5598, y: 2348, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 1200 mi east of Baviet, near Hauk and Hagia Demre." },
  { n: "Naosic", cat: "territory", x: 5300, y: 1756, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 975 mi east of Baviet, near Semhol and Anthela." },
  { n: "Nyeo Naos", cat: "territory", x: 2236, y: 1746, k: "The Tanan Grand Duchy", d: "In the Tanan Grand Duchy, about 475 mi northeast of Lajazer, near Deyare and Macerin." },
  { n: "Tehr Tari Naos", cat: "territory", x: 5235, y: 1385, k: "Theolisseia", d: "In Theolisseia, about 1450 mi northwest of Hadirel, near Hagiora and Nyedal." },
  { n: "Vekta's territory", cat: "territory", x: 5070, y: 1639, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 825 mi northeast of Baviet, near Amberactserun and Tasfen." },
  { n: "Mt. Aicren", cat: "landmark", x: 6672, y: 2438, k: "Theolisseia", d: "In Theolisseia, about 125 mi southwest of Hadirel, near Sahlen and Sahla." },
  { n: "Outer Walls", cat: "landmark", x: 4057, y: 2101, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 60 mi west of Baviet, near Baviet and Cerby." },
  { n: "The Magic Tower", cat: "landmark", x: 6767, y: 2410, k: "Theolisseia", d: "In Theolisseia, about 50 mi south of Hadirel, near Hadirel and Sahlen." }
];

const EMPIRE_STATES = [
  { n: "Lingia", capital: "Haleret", d: "Formerly the kingdom of Pireaynea, its warlord anarchy subdued by imperial troops. Capital: Haleret.", biomes: ["Grassland","Temperate deciduous forest","Taiga","Wetland"] },
  { n: "Hikai", capital: "Osenki", d: "Formerly the kingdom of Coelum, the bankrupt 'Forsaken Land'. Capital: Osenki.", biomes: ["Grassland","Temperate deciduous forest","Taiga","Wetland"] },
  { n: "The Uxridian Grand Duchy", capital: "Ociyaran", d: "Formerly the kingdom of Equateiy, the wealthy banking oligarchy that joined the empire by treaty. Capital: Ociyaran.", biomes: ["Grassland","Temperate deciduous forest","Taiga","Wetland"] },
  { n: "Theolisseia", capital: "Hadirel", d: "Formerly the kingdom of Vikitsv, the mountain magocracy of Mount Aicren. Capital: Hadirel.", biomes: ["Grassland","Temperate deciduous forest","Taiga","Wetland"] },
  { n: "The Caporiolan Kingdom", capital: "Baviet", d: "Formerly the kingdom of Gherci; the theocratic heartland and seat of the Solisian Empire. Capital: Baviet.", biomes: ["Grassland","Temperate deciduous forest","Taiga","Wetland"] },
  { n: "The Tanan Grand Duchy", capital: "Lajazer", d: "Formerly the kingdom of Aicruae, the western breadbasket. One of the great powers of the Early Empire. Capital: Lajazer.", biomes: ["Grassland","Temperate deciduous forest","Taiga","Wetland"] }
];
