// World gazetteer: the six kingdoms, 7,250 BR.
// Coordinates are pixels in the atlas image space (7680 x 3962), origin top-left.
// Names & lore cross-checked against "Map of the world during the 7,250 BR" (canon doc).
// cat: region | capital | city | town | water | river | island | forest | territory | landmark
// k: kingdom the place belongs to (omitted for open seas / neutral sites)

const PLACES = [
  { n: "Gherci", cat: "region", x: 4120, y: 1840, k: "Gherci", d: "\"The Land of Eternal Silence.\" The largest and most populous kingdom, a theocratic power where priests outranked kings. Capital: Tarmet. Later became the Caporiolan Kingdom, seat of the empire." },
  { n: "Coelum", cat: "region", x: 4235, y: 975, k: "Coelum", d: "\"The Forsaken Land.\" The bankrupt northern failed state, largely atheist after wars and plague emptied its villages. Capital: Atriki. Later became Hikai." },
  { n: "Vikitsv", cat: "region", x: 6055, y: 1830, k: "Vikitsv", d: "\"The Floating Land.\" A mountain magocracy atop Mount Aicren, home of the Magic Tower and its blue-haired people. Capital: Berlailia. Later became Theolisseia." },
  { n: "Equateiy", cat: "region", x: 6515, y: 1185, k: "Equateiy", d: "\"The Kingdom of Gold.\" The oldest and wealthiest nation, an oligarchy run by the banking houses of House Kivier. Capital: Ociyaran. Later became the Uxridian Grand Duchy." },
  { n: "Ociyaran", cat: "capital", x: 6605, y: 1245, k: "Equateiy", d: "Capital of Equateiy, in the central highlands." },
  { n: "Aicruae", cat: "region", x: 2170, y: 1920, k: "Aicruae", d: "\"The Land under the Sun.\" Westernmost of the six kingdoms; the continent's pious but unstable breadbasket, producing nearly half the world's food. Capital: Lajazer. Later became the Tanan Grand Duchy under the Solisian Empire." },
  { n: "Lajazer", cat: "capital", x: 2262, y: 1775, k: "Aicruae", d: "Capital of Aicruae, at the center of the kingdom." },
  { n: "Pireaynea", cat: "region", x: 3020, y: 2230, k: "Pireaynea", d: "\"The Demon's Pit.\" South-central kingdom of warlords and banditry, the continent's only monotheistic nation. Capital: Civer. Later became Lingia." },
  { n: "Berlailia", cat: "capital", x: 6793, y: 2293, k: "Vikitsv", d: "Capital of Vikitsv, on the shoulder of Mount Aicren." },
  { n: "Caduto", cat: "region", x: 6590, y: 1565, k: "Vikitsv", d: "Trade crossing on the Vikitsv-Equateiy border." },
  { n: "Atriki", cat: "capital", x: 3909, y: 704, k: "Coelum", d: "Capital of Coelum, beside Lake Trang." },
  { n: "Tarmet", cat: "capital", x: 4138, y: 2033, k: "Gherci", d: "Capital of Gherci, ringed by Greater Gherci, the Outer Walls, Asmeta, Tanya Beka and Mother's Hip." },
  { n: "Civer", cat: "capital", x: 3156, y: 2414, k: "Pireaynea", d: "Capital of Pireaynea, on its southern lake along the central river." },
  { n: "Greater Gherci", cat: "region", x: 4200, y: 2170, k: "Gherci", d: "Core province ringing the capital Tarmet." },
  { n: "Lower Gherci", cat: "region", x: 3775, y: 2390, k: "Gherci", d: "The southwestern river country of Gherci, draining to the Fetora Sea." },
  { n: "Melert", cat: "region", x: 1850, y: 1990, k: "Aicruae", d: "Western coastal province of Aicruae; export region." },
  { n: "Eynora", cat: "city", x: 3555, y: 102, k: "Coelum", d: "In the Kingdom of Coelum, about 575 mi northwest of Atriki, near Lagora and Tilnyeau." },
  { n: "Lagora", cat: "city", x: 3500, y: 205, k: "Coelum", d: "In the Kingdom of Coelum, about 525 mi northwest of Atriki, near Eynora and Tilnyeau." },
  { n: "Tilnyeau", cat: "city", x: 3665, y: 255, k: "Coelum", d: "In the Kingdom of Coelum, about 425 mi northwest of Atriki, near Skya and Lagora." },
  { n: "Port Rebadeen", cat: "city", x: 4535, y: 135, k: "Coelum", d: "In the Kingdom of Coelum, about 675 mi northeast of Atriki, near Niarn and Ricna." },
  { n: "Port Aresca", cat: "city", x: 3196, y: 871, k: "Gherci", d: "In the Kingdom of Gherci, about 1200 mi northwest of Tarmet, near Corocco and Etanda." },
  { n: "Port Theli", cat: "city", x: 3656, y: 910, k: "Coelum", d: "In the Kingdom of Coelum, about 300 mi southwest of Atriki, near Neaea and Seppegiu." },
  { n: "Port Vsar", cat: "city", x: 2911, y: 1114, k: "Aicruae", d: "In the Kingdom of Aicruae, about 725 mi northeast of Lajazer, near Raiya and Linjat." },
  { n: "Port Esery", cat: "city", x: 2625, y: 1115, k: "Aicruae", d: "In the Kingdom of Aicruae, about 600 mi northeast of Lajazer, near Linjat and Kunus." },
  { n: "Port Vento", cat: "city", x: 2399, y: 1222, k: "Aicruae", d: "In the Kingdom of Aicruae, about 450 mi north of Lajazer, near Sreton and Waeca." },
  { n: "Port Volpa", cat: "city", x: 6513, y: 895, k: "Equateiy", d: "In the Kingdom of Equateiy, about 275 mi north of Ociyaran, near Foce and Querceta." },
  { n: "Port Quale", cat: "city", x: 1893, y: 2231, k: "Aicruae", d: "In the Kingdom of Aicruae, about 475 mi southwest of Lajazer, near Teyetes and Bareta." },
  { n: "Port Ols", cat: "city", x: 2596, y: 2765, k: "Pireaynea", d: "In the Kingdom of Pireaynea, about 525 mi southwest of Civer, near Vasco and Sindbir." },
  { n: "Port Pontesa", cat: "city", x: 4020, y: 2771, k: "Gherci", d: "In the Kingdom of Gherci, about 600 mi south of Tarmet, near Aoin and Pontata." },
  { n: "Port Linnos", cat: "city", x: 4911, y: 2900, k: "the far-eastern territories", d: "In the far-eastern territories beyond Gherci's border, about 175 mi southwest of Mireb, near Dordbin and Limn." },
  { n: "Port Sael", cat: "city", x: 7218, y: 2778, k: "Vikitsv", d: "In the Kingdom of Vikitsv, about 500 mi southeast of Berlailia, near Qunag and Cael'mu." },
  { n: "Onmore", cat: "city", x: 5075, y: 443, k: "Coelum", d: "In the Kingdom of Coelum, about 950 mi east of Atriki, near Riyen and Niarn." },
  { n: "Gondes", cat: "city", x: 3866, y: 1311, k: "Gherci", d: "In the Kingdom of Gherci, about 625 mi north of Tarmet, near Adani and Resia." },
  { n: "Aishae", cat: "region", x: 2240, y: 1555, k: "Aicruae", d: "Northern port region of Aicruae." },
  { n: "Haleker", cat: "region", x: 2460, y: 1970, k: "Aicruae", d: "Eastern Aicruae, seat of House Vika, on the Pireaynea border." },
  { n: "Baeistic", cat: "region", x: 2920, y: 1895, k: "Pireaynea", d: "Northern region of Pireaynea." },
  { n: "Urdeio", cat: "region", x: 3390, y: 2105, k: "Pireaynea", d: "Eastern region of Pireaynea, toward the Lower Gherci." },
  { n: "Aseraga", cat: "region", x: 2520, y: 2215, k: "Pireaynea", d: "Southwestern region of Pireaynea." },
  { n: "Feacener", cat: "region", x: 2920, y: 2425, k: "Pireaynea", d: "Southern coastal region of Pireaynea." },
  { n: "Coelys", cat: "town", x: 3114, y: 1598, k: "Gherci", d: "In the Kingdom of Gherci, about 875 mi northwest of Tarmet, near Ezon and Croco. A town in Gherci (not to be confused with the northern kingdom of Coelum)." },
  { n: "Rietha", cat: "city", x: 3589, y: 1616, k: "Gherci", d: "In the Kingdom of Gherci, about 475 mi northwest of Tarmet, near Nyes and Kessa." },
  { n: "Kessa", cat: "city", x: 3708, y: 1779, k: "Gherci", d: "In the Kingdom of Gherci, about 400 mi northwest of Tarmet, near Rietha and Belune." },
  { n: "Loria", cat: "city", x: 5038, y: 2184, k: "Gherci", d: "In the Kingdom of Gherci, about 725 mi east of Tarmet, near Lethe and Maru." },
  { n: "Mireb", cat: "city", x: 5016, y: 2714, k: "the far-eastern territories", d: "In the far-eastern territories beyond Gherci's border, about 175 mi northeast of Port Linnos, near Dordbin and Demre." },
  { n: "Amba", cat: "city", x: 5454, y: 2640, k: "the far-eastern territories", d: "In the far-eastern territories beyond Gherci's border, about 350 mi east of Mireb, near Selvet and Hagiore." },
  { n: "Gai", cat: "city", x: 5145, y: 2530, k: "Gherci", d: "In the Kingdom of Gherci, about 900 mi southeast of Tarmet, near Demia and Maru." },
  { n: "Reskt", cat: "city", x: 6419, y: 2130, k: "Vikitsv", d: "In the Kingdom of Vikitsv, about 325 mi northwest of Berlailia, near Daltsen and Sehrok." },
  { n: "Qunag", cat: "city", x: 6987, y: 2883, k: "Vikitsv", d: "In the Kingdom of Vikitsv, about 500 mi south of Berlailia, near Gjen and Namilna." },
  { n: "Murok", cat: "city", x: 6359, y: 2918, k: "Vikitsv", d: "In the Kingdom of Vikitsv, about 600 mi southwest of Berlailia, near Junjeo and Bohan." },
  { n: "Tagrim", cat: "city", x: 4493, y: 2915, k: "Gherci", d: "In the Kingdom of Gherci, about 750 mi south of Tarmet, near Oskba and Esku." },
  { n: "Basar Tari", cat: "city", x: 2152, y: 2629, k: "Aicruae", d: "In the Kingdom of Aicruae, about 700 mi south of Lajazer, near Laona and Audin. The royal prison and unofficial UIB criminal hub, in the southern badlands." },
  { n: "Oscan", cat: "city", x: 3475, y: 1523, k: "Gherci", d: "In the Kingdom of Gherci, about 675 mi northwest of Tarmet, near Cardoric and Lujian." },
  { n: "Nabuchan", cat: "city", x: 4790, y: 1063, k: "Coelum", d: "In the Kingdom of Coelum, about 750 mi east of Atriki, near Sebrof and Nalchal." },
  { n: "Sebrof", cat: "city", x: 4809, y: 1199, k: "Coelum", d: "In the Kingdom of Coelum, about 800 mi southeast of Atriki, near Nabuchan and Ridal." },
  { n: "Bohan", cat: "city", x: 6006, y: 2882, k: "Vikitsv", d: "In the Kingdom of Vikitsv, about 775 mi southwest of Berlailia, near Gilsa and Ompol." },
  { n: "Kuldar", cat: "city", x: 4253, y: 2752, k: "Gherci", d: "In the Kingdom of Gherci, about 550 mi south of Tarmet, near Esku and Drun." },
  { n: "Hadiber", cat: "region", x: 2065, y: 1690, k: "Aicruae", d: "Western region of Aicruae." },
  { n: "The Quather Sea", cat: "water", x: 2081, y: 529, d: "The northwestern sea, off Aicruae's western coast; the primary fishing ground and trade route of the west." },
  { n: "The Oberya Sea", cat: "water", x: 7374, y: 852, d: "The northeastern sea, bordering Equateiy and Vikitsv; a long-distance trade route." },
  { n: "The Fetora Sea", cat: "water", x: 3190, y: 3169, d: "The southern sea; a shared coastline of Vikitsv, Pireaynea and Aicruae." },
  { n: "Henem Bay", cat: "water", x: 4793, y: 278, d: "Coelum's northern coast; also Gherci's northern port access." },
  { n: "Rium Harbor", cat: "water", x: 4860, y: 700, k: "Coelum", d: "In the Kingdom of Coelum, about 750 mi east of Atriki, near Noramec and Riyen. Coelum's northeastern harbor." },
  { n: "Lake Trang", cat: "water", x: 4110, y: 805, k: "Coelum", d: "In the Kingdom of Coelum, about 175 mi southeast of Atriki, near Maharg and Erygal. The great lake at Coelum's heart, beside the capital Atriki." },
  { n: "Honlo Lake", cat: "water", x: 4345, y: 1455, k: "Gherci", d: "In the Kingdom of Gherci, about 500 mi north of Tarmet, near Inqua and Hoan. The great lake of north-central Gherci, below the Coelum border." },
  { n: "The Quather Islands", cat: "island", x: 1851, y: 1437, d: "Island cluster off Aicruae's northwest; canon also calls these the Northern Isles." },
  { n: "The Cidet", cat: "island", x: 1395, y: 2128, d: "The temple of the gods: a sacred isle west of Aicruae, never colonized." },
  { n: "The Mystic Isles", cat: "island", x: 1300, y: 2730, d: "Far southwestern archipelago." },
  { n: "Gogla", cat: "town", x: 7020, y: 2125, k: "Vikitsv", d: "In the Kingdom of Vikitsv, about 225 mi northeast of Berlailia, near Negiet and Gaedu. Settlement of Vikitsv's eastern wall." },
  { n: "Tigrrei Forest", cat: "forest", x: 3320, y: 1670, k: "Gherci", d: "In the Kingdom of Gherci, about 725 mi northwest of Tarmet, near Olune and Shaer. Western border forest shared by Aicruae, Pireaynea and Gherci." },
  { n: "Abren Forest", cat: "forest", x: 3785, y: 1470, k: "Gherci", d: "In the Kingdom of Gherci, about 550 mi northwest of Tarmet, near Nyes and Adani. Woodland belt along Gherci's northern marches, below the Coelum border." },
  { n: "Aro Forest", cat: "forest", x: 6739, y: 1060, k: "Equateiy", d: "In the Kingdom of Equateiy, about 150 mi northeast of Ociyaran, near Doresi and Neska. The great forest belt along Equateiy's eastern reaches, by the Oberya cliffs." },
  { n: "Nedi Forest", cat: "forest", x: 6092, y: 1675, k: "Equateiy", d: "In the Kingdom of Equateiy, about 525 mi southwest of Ociyaran, near Esteraia and Velsa. Southwestern woodland of Equateiy, sloping toward the Vikitsv frontier." },
  { n: "Silora Forest", cat: "forest", x: 6717, y: 2558, k: "Vikitsv", d: "In the Kingdom of Vikitsv, about 200 mi south of Berlailia, near Sahla and Galmun. The Silora foothills of Vikitsv." },
  { n: "Tehr Tari Naos", cat: "territory", x: 5020, y: 1385, k: "the far-eastern territories", d: "In the far-eastern territories beyond Gherci's border, about 1050 mi north of Mireb, near Hagiora and Semhol." },
  { n: "Dor Tari Naos", cat: "territory", x: 5320, y: 1885, k: "the far-eastern territories", d: "In the far-eastern territories beyond Gherci's border, about 600 mi north of Amba, near Tehron and Tusjin." },
  { n: "Anthela Naosic", cat: "territory", x: 5320, y: 1760, k: "the far-eastern territories", d: "In the far-eastern territories beyond Gherci's border, about 700 mi north of Amba, near Bellaria and Tehron." },
  { n: "Aryanara's territory", cat: "territory", x: 5310, y: 1790, k: "the far-eastern territories", d: "In the far-eastern territories beyond Gherci's border, about 700 mi north of Amba, near Tehron and Bellaria. Far-eastern territory beyond Gherci's dashed border." },
  { n: "Vekta's territory", cat: "territory", x: 5065, y: 1650, k: "the far-eastern territories", d: "In the far-eastern territories beyond Gherci's border, about 850 mi north of Mireb, near Semhol and Belnara. Far-eastern territory beyond Gherci's dashed border." },
  { n: "Amberactserun", cat: "territory", x: 5150, y: 1560, k: "the far-eastern territories", d: "In the far-eastern territories beyond Gherci's border, about 900 mi north of Amba, near Hagiora and Semhol." },
  { n: "Naos Adwe", cat: "territory", x: 5345, y: 2345, k: "the far-eastern territories", d: "In the far-eastern territories beyond Gherci's border, about 250 mi north of Amba, near Hagn and Tsir." },
  { n: "Hagia Demre", cat: "territory", x: 5215, y: 2425, k: "the far-eastern territories", d: "In the far-eastern territories beyond Gherci's border, about 250 mi northwest of Amba, near Tsir and Demre." },
  { n: "The Magic Tower", cat: "landmark", x: 6768, y: 2400, k: "Vikitsv", d: "In the Kingdom of Vikitsv, about 90 mi south of Berlailia, near Sahla and Gaedu. On the terraces just below Berlailia." },
  { n: "Mount Aicren", cat: "landmark", x: 6693, y: 2424, k: "Vikitsv", d: "In the Kingdom of Vikitsv, about 150 mi southwest of Berlailia, near Sahla and Byeola. The central massif of Vikitsv; the whole kingdom radiates from it." },
  { n: "Mother's Hip", cat: "landmark", x: 4273, y: 2075, k: "Gherci", d: "In the Kingdom of Gherci, about 100 mi east of Tarmet, near Malin and Tanya Beka." },
  { n: "Outer Walls", cat: "landmark", x: 4081, y: 2094, k: "Gherci", d: "In the Kingdom of Gherci, about 60 mi southwest of Tarmet, near Asmeta and Lendara." },
  { n: "Skya", cat: "town", x: 3808, y: 162, k: "Coelum", d: "In the Kingdom of Coelum, about 450 mi north of Atriki, near Tilnyeau and Eynora." },
  { n: "Yleka", cat: "town", x: 4037, y: 365, k: "Coelum", d: "In the Kingdom of Coelum, about 275 mi north of Atriki, near Eryte and Slaia." },
  { n: "Ricna", cat: "town", x: 4340, y: 419, k: "Coelum", d: "In the Kingdom of Coelum, about 400 mi northeast of Atriki, near Snurb and Gorma." },
  { n: "Niarn", cat: "town", x: 4607, y: 422, k: "Coelum", d: "In the Kingdom of Coelum, about 600 mi east of Atriki, near Gorma and Riyen." },
  { n: "Eryte", cat: "town", x: 4011, y: 537, k: "Coelum", d: "In the Kingdom of Coelum, about 150 mi northeast of Atriki, near Yleka and Nisclair." },
  { n: "Snurb", cat: "town", x: 4278, y: 523, k: "Coelum", d: "In the Kingdom of Coelum, about 325 mi northeast of Atriki, near Ricna and Ortuqil." },
  { n: "Gorma", cat: "town", x: 4457, y: 522, k: "Coelum", d: "In the Kingdom of Coelum, about 450 mi east of Atriki, near Ortuqil and Ricna." },
  { n: "Ortuqil", cat: "town", x: 4420, y: 622, k: "Coelum", d: "In the Kingdom of Coelum, about 400 mi east of Atriki, near Gorma and Snurb." },
  { n: "Riyen", cat: "town", x: 4685, y: 603, k: "Coelum", d: "In the Kingdom of Coelum, about 600 mi east of Atriki, near Eskert and Niarn." },
  { n: "Nisclair", cat: "town", x: 3895, y: 652, k: "Coelum", d: "In the Kingdom of Coelum, about 50 mi northwest of Atriki, near Eryte and Eskol." },
  { n: "Maharg", cat: "town", x: 4210, y: 708, k: "Coelum", d: "In the Kingdom of Coelum, about 225 mi east of Atriki, near Snurb and Ortuqil." },
  { n: "Eskert", cat: "town", x: 4604, y: 718, k: "Coelum", d: "In the Kingdom of Coelum, about 550 mi east of Atriki, near Riyen and Noramec." },
  { n: "Noramec", cat: "town", x: 4779, y: 827, k: "Coelum", d: "In the Kingdom of Coelum, about 700 mi east of Atriki, near Nalchal and Eskert." },
  { n: "Eskol", cat: "town", x: 3891, y: 869, k: "Coelum", d: "In the Kingdom of Coelum, about 125 mi south of Atriki, near Erygal and Nisclair." },
  { n: "Nalochl", cat: "town", x: 4430, y: 897, k: "Coelum", d: "In the Kingdom of Coelum, about 425 mi east of Atriki, near Eskert and Ridal." },
  { n: "Nalchal", cat: "town", x: 4935, y: 897, k: "Coelum", d: "In the Kingdom of Coelum, about 825 mi east of Atriki, near Noramec and Nabuchan." },
  { n: "Erygal", cat: "town", x: 3988, y: 944, k: "Coelum", d: "In the Kingdom of Coelum, about 200 mi south of Atriki, near Eskol and Lagowyal." },
  { n: "Negel", cat: "town", x: 4204, y: 1081, k: "Coelum", d: "In the Kingdom of Coelum, about 375 mi southeast of Atriki, near Lagowyal and Camruthar." },
  { n: "Ridal", cat: "town", x: 4582, y: 1105, k: "Coelum", d: "In the Kingdom of Coelum, about 625 mi southeast of Atriki, near Camruthar and Nabuchan." },
  { n: "Lagowyal", cat: "town", x: 4080, y: 1172, k: "Coelum", d: "In the Kingdom of Coelum, about 375 mi south of Atriki, near Negel and Erygal." },
  { n: "Camruthar", cat: "town", x: 4446, y: 1203, k: "Coelum", d: "In the Kingdom of Coelum, about 575 mi southeast of Atriki, near Ridal and Negel." },
  { n: "Inqua", cat: "town", x: 4411, y: 1326, k: "Gherci", d: "In the Kingdom of Gherci, about 600 mi north of Tarmet, near Oryur and Garen." },
  { n: "Resia", cat: "town", x: 4033, y: 1376, k: "Gherci", d: "In the Kingdom of Gherci, about 550 mi north of Tarmet, near Adani and Inqwe." },
  { n: "Corocco", cat: "town", x: 3271, y: 957, k: "Gherci", d: "In the Kingdom of Gherci, about 1100 mi northwest of Tarmet, near Port Aresca and Neaea." },
  { n: "Etanda", cat: "town", x: 3115, y: 1013, k: "Gherci", d: "In the Kingdom of Gherci, about 1150 mi northwest of Tarmet, near Osegri and Port Aresca." },
  { n: "Neaea", cat: "town", x: 3415, y: 1000, k: "Gherci", d: "In the Kingdom of Gherci, about 1000 mi northwest of Tarmet, near Seppegiu and Corocco." },
  { n: "Seppegiu", cat: "town", x: 3469, y: 1098, k: "Gherci", d: "In the Kingdom of Gherci, about 925 mi northwest of Tarmet, near Coloni and Neaea." },
  { n: "Linjat", cat: "town", x: 2743, y: 1165, k: "Aicruae", d: "In the Kingdom of Aicruae, about 600 mi northeast of Lajazer, near Baramq and Port Esery." },
  { n: "Osegri", cat: "town", x: 3145, y: 1158, k: "Gherci", d: "In the Kingdom of Gherci, about 1075 mi northwest of Tarmet, near Rioda and Tenda." },
  { n: "Rioda", cat: "town", x: 3279, y: 1139, k: "Gherci", d: "In the Kingdom of Gherci, about 1000 mi northwest of Tarmet, near Tenda and Osegri." },
  { n: "Coloni", cat: "town", x: 3499, y: 1183, k: "Gherci", d: "In the Kingdom of Gherci, about 850 mi northwest of Tarmet, near Seppegiu and Tropie." },
  { n: "Tiamma", cat: "town", x: 3676, y: 1176, k: "Gherci", d: "In the Kingdom of Gherci, about 775 mi northwest of Tarmet, near Masotom and Coloni." },
  { n: "Tenda", cat: "town", x: 3263, y: 1220, k: "Gherci", d: "In the Kingdom of Gherci, about 950 mi northwest of Tarmet, near Gelona and Rioda." },
  { n: "Tropie", cat: "town", x: 3405, y: 1220, k: "Gherci", d: "In the Kingdom of Gherci, about 875 mi northwest of Tarmet, near Coloni and Gelona." },
  { n: "Buion", cat: "town", x: 2516, y: 1238, k: "Aicruae", d: "In the Kingdom of Aicruae, about 475 mi northeast of Lajazer, near Waeca and Birmya." },
  { n: "Kunus", cat: "town", x: 2655, y: 1255, k: "Aicruae", d: "In the Kingdom of Aicruae, about 525 mi northeast of Lajazer, near Baramq and Buion." },
  { n: "Baramq", cat: "town", x: 2725, y: 1253, k: "Aicruae", d: "In the Kingdom of Aicruae, about 550 mi northeast of Lajazer, near Linjat and Paler." },
  { n: "Raiya", cat: "town", x: 2829, y: 1239, k: "Aicruae", d: "In the Kingdom of Aicruae, about 625 mi northeast of Lajazer, near Baramq and Linjat." },
  { n: "Waeca", cat: "town", x: 2436, y: 1284, k: "Aicruae", d: "In the Kingdom of Aicruae, about 425 mi north of Lajazer, near Borgest and Buion." },
  { n: "Sreton", cat: "town", x: 2325, y: 1301, k: "Aicruae", d: "In the Kingdom of Aicruae, about 400 mi north of Lajazer, near Borgest and Port Vento." },
  { n: "Gelona", cat: "town", x: 3304, y: 1279, k: "Gherci", d: "In the Kingdom of Gherci, about 900 mi northwest of Tarmet, near Tenda and Eloe." },
  { n: "Brielega", cat: "town", x: 3511, y: 1281, k: "Gherci", d: "In the Kingdom of Gherci, about 775 mi northwest of Tarmet, near Coloni and Egodi." },
  { n: "Masotom", cat: "town", x: 3702, y: 1254, k: "Gherci", d: "In the Kingdom of Gherci, about 725 mi northwest of Tarmet, near Tiamma and Renzolo." },
  { n: "Birmya", cat: "town", x: 2549, y: 1343, k: "Aicruae", d: "In the Kingdom of Aicruae, about 425 mi northeast of Lajazer, near Buion and Kunus." },
  { n: "Borgest", cat: "town", x: 2381, y: 1348, k: "Aicruae", d: "In the Kingdom of Aicruae, about 350 mi north of Lajazer, near Sreton and Lera Mea." },
  { n: "Rachia", cat: "town", x: 2900, y: 1320, k: "Gherci", d: "In the Kingdom of Gherci, about 1150 mi northwest of Tarmet, near Tagre and Raiya." },
  { n: "Mossima", cat: "town", x: 3143, y: 1311, k: "Gherci", d: "In the Kingdom of Gherci, about 975 mi northwest of Tarmet, near Lioe and Anaan." },
  { n: "Anaan", cat: "town", x: 3019, y: 1339, k: "Gherci", d: "In the Kingdom of Gherci, about 1050 mi northwest of Tarmet, near Tophercris and Rachia." },
  { n: "Paler", cat: "town", x: 2728, y: 1333, k: "Aicruae", d: "In the Kingdom of Aicruae, about 500 mi northeast of Lajazer, near Liviao and Baramq." },
  { n: "Eloe", cat: "town", x: 3349, y: 1344, k: "Gherci", d: "In the Kingdom of Gherci, about 850 mi northwest of Tarmet, near Vannigio and Gelona." },
  { n: "Lioe", cat: "town", x: 3231, y: 1373, k: "Gherci", d: "In the Kingdom of Gherci, about 900 mi northwest of Tarmet, near Mossima and Gelona." },
  { n: "Egodi", cat: "town", x: 3449, y: 1369, k: "Gherci", d: "In the Kingdom of Gherci, about 775 mi northwest of Tarmet, near Cardoric and Eloe." },
  { n: "Renzolo", cat: "town", x: 3644, y: 1361, k: "Gherci", d: "In the Kingdom of Gherci, about 675 mi northwest of Tarmet, near Selve and Masotom." },
  { n: "Tagre", cat: "town", x: 2830, y: 1381, k: "Gherci", d: "In the Kingdom of Gherci, about 1175 mi northwest of Tarmet, near Rachia and Giagior." },
  { n: "Veric", cat: "town", x: 2230, y: 1298, k: "Aicruae", d: "In the Kingdom of Aicruae, about 375 mi north of Lajazer, near Sreton and Lera Mea." },
  { n: "Lera Mea", cat: "town", x: 2303, y: 1381, k: "Aicruae", d: "In the Kingdom of Aicruae, about 325 mi north of Lajazer, near Fordege and Borgest." },
  { n: "Senalda", cat: "town", x: 6397, y: 834, k: "Equateiy", d: "In the Kingdom of Equateiy, about 350 mi northwest of Ociyaran, near Cala and Port Volpa." },
  { n: "Cala", cat: "town", x: 6291, y: 921, k: "Equateiy", d: "In the Kingdom of Equateiy, about 350 mi northwest of Ociyaran, near Senna and Senalda." },
  { n: "Senna", cat: "town", x: 6299, y: 988, k: "Equateiy", d: "In the Kingdom of Equateiy, about 325 mi northwest of Ociyaran, near Cala and Sye." },
  { n: "Lidresa", cat: "town", x: 6197, y: 1054, k: "Equateiy", d: "In the Kingdom of Equateiy, about 350 mi northwest of Ociyaran, near Breno and Vallaforta." },
  { n: "Vallaforta", cat: "town", x: 6300, y: 1082, k: "Equateiy", d: "In the Kingdom of Equateiy, about 275 mi northwest of Ociyaran, near Lun and Sye." },
  { n: "Breno", cat: "town", x: 6149, y: 1138, k: "Equateiy", d: "In the Kingdom of Equateiy, about 375 mi west of Ociyaran, near Oa and Lidresa." },
  { n: "Brae", cat: "town", x: 6052, y: 1233, k: "Equateiy", d: "In the Kingdom of Equateiy, about 425 mi west of Ociyaran, near Stagna and Oa." },
  { n: "Stagna", cat: "town", x: 6125, y: 1270, k: "Equateiy", d: "In the Kingdom of Equateiy, about 375 mi west of Ociyaran, near Ilvo and Brae." },
  { n: "Ilvo", cat: "town", x: 6151, y: 1324, k: "Equateiy", d: "In the Kingdom of Equateiy, about 375 mi west of Ociyaran, near Stagna and Movo." },
  { n: "Reda", cat: "town", x: 6039, y: 1353, k: "Equateiy", d: "In the Kingdom of Equateiy, about 450 mi west of Ociyaran, near Larida and Ilvo." },
  { n: "Cira", cat: "town", x: 6262, y: 1261, k: "Equateiy", d: "In the Kingdom of Equateiy, about 275 mi west of Ociyaran, near Roi and Cresp." },
  { n: "Roi", cat: "town", x: 6241, y: 1343, k: "Equateiy", d: "In the Kingdom of Equateiy, about 300 mi west of Ociyaran, near Cira and Movo." },
  { n: "Lun", cat: "town", x: 6270, y: 1131, k: "Equateiy", d: "In the Kingdom of Equateiy, about 275 mi west of Ociyaran, near Vigila and Vallaforta." },
  { n: "Oa", cat: "town", x: 6169, y: 1194, k: "Equateiy", d: "In the Kingdom of Equateiy, about 350 mi west of Ociyaran, near Breno and Stagna." },
  { n: "Vigila", cat: "town", x: 6265, y: 1170, k: "Equateiy", d: "In the Kingdom of Equateiy, about 275 mi west of Ociyaran, near Lun and Gora." },
  { n: "Sye", cat: "town", x: 6348, y: 1050, k: "Equateiy", d: "In the Kingdom of Equateiy, about 250 mi northwest of Ociyaran, near Vallaforta and Senna." },
  { n: "Zattera", cat: "town", x: 6697, y: 735, k: "Equateiy", d: "In the Kingdom of Equateiy, about 400 mi north of Ociyaran, near Latso and Paro." },
  { n: "Tesora", cat: "town", x: 6925, y: 776, k: "Equateiy", d: "In the Kingdom of Equateiy, about 450 mi northeast of Ociyaran, near Chiozza and Muralto." },
  { n: "Chiozza", cat: "town", x: 6818, y: 802, k: "Equateiy", d: "In the Kingdom of Equateiy, about 400 mi northeast of Ociyaran, near Tesora and Latso." },
  { n: "Paro", cat: "town", x: 6623, y: 805, k: "Equateiy", d: "In the Kingdom of Equateiy, about 350 mi north of Ociyaran, near Pampira and Latso." },
  { n: "Latso", cat: "town", x: 6698, y: 820, k: "Equateiy", d: "In the Kingdom of Equateiy, about 350 mi north of Ociyaran, near Pampira and Paro." },
  { n: "Pampira", cat: "town", x: 6648, y: 867, k: "Equateiy", d: "In the Kingdom of Equateiy, about 300 mi north of Ociyaran, near Paro and Latso." },
  { n: "Jhera", cat: "town", x: 6743, y: 922, k: "Equateiy", d: "In the Kingdom of Equateiy, about 275 mi northeast of Ociyaran, near Vinalta and Alpena." },
  { n: "Muralto", cat: "town", x: 6885, y: 933, k: "Equateiy", d: "In the Kingdom of Equateiy, about 325 mi northeast of Ociyaran, near Alpena and Ys." },
  { n: "Querceta", cat: "town", x: 6585, y: 954, k: "Equateiy", d: "In the Kingdom of Equateiy, about 225 mi north of Ociyaran, near Uvenza and Vinalta." },
  { n: "Foce", cat: "town", x: 6457, y: 975, k: "Equateiy", d: "In the Kingdom of Equateiy, about 250 mi northwest of Ociyaran, near Malamo and Port Volpa." },
  { n: "Vinalta", cat: "town", x: 6682, y: 976, k: "Equateiy", d: "In the Kingdom of Equateiy, about 225 mi north of Ociyaran, near Doresi and Uvenza." },
  { n: "Alpena", cat: "town", x: 6873, y: 995, k: "Equateiy", d: "In the Kingdom of Equateiy, about 275 mi northeast of Ociyaran, near Muralto and Jhera." },
  { n: "Ys", cat: "town", x: 7005, y: 980, k: "Equateiy", d: "In the Kingdom of Equateiy, about 375 mi northeast of Ociyaran, near Chiavanto and Muralto." },
  { n: "Malamo", cat: "town", x: 6473, y: 1031, k: "Equateiy", d: "In the Kingdom of Equateiy, about 200 mi northwest of Ociyaran, near Gabbia and Foce." },
  { n: "Uvenza", cat: "town", x: 6600, y: 1013, k: "Equateiy", d: "In the Kingdom of Equateiy, about 175 mi north of Ociyaran, near Querceta and Neska." },
  { n: "Doresi", cat: "town", x: 6687, y: 1054, k: "Equateiy", d: "In the Kingdom of Equateiy, about 175 mi northeast of Ociyaran, near Vinalta and Neska." },
  { n: "Chiavanto", cat: "town", x: 6955, y: 1053, k: "Equateiy", d: "In the Kingdom of Equateiy, about 325 mi northeast of Ociyaran, near Riy and Ys." },
  { n: "Gabbia", cat: "town", x: 6498, y: 1087, k: "Equateiy", d: "In the Kingdom of Equateiy, about 150 mi northwest of Ociyaran, near Malamo and Esio." },
  { n: "Neska", cat: "town", x: 6612, y: 1073, k: "Equateiy", d: "In the Kingdom of Equateiy, about 125 mi north of Ociyaran, near Uvenza and Esio." },
  { n: "Corsa", cat: "town", x: 6417, y: 1118, k: "Equateiy", d: "In the Kingdom of Equateiy, about 175 mi northwest of Ociyaran, near Gabbia and Gora." },
  { n: "Esio", cat: "town", x: 6588, y: 1123, k: "Equateiy", d: "In the Kingdom of Equateiy, about 100 mi northwest of Ociyaran, near Gabbia and Neska." },
  { n: "Riy", cat: "town", x: 6969, y: 1111, k: "Equateiy", d: "In the Kingdom of Equateiy, about 325 mi east of Ociyaran, near Chiavanto and Colle." },
  { n: "Squero", cat: "town", x: 6895, y: 1142, k: "Equateiy", d: "In the Kingdom of Equateiy, about 200 mi east of Ociyaran, near Burane and Mira." },
  { n: "Colle", cat: "town", x: 6951, y: 1175, k: "Equateiy", d: "In the Kingdom of Equateiy, about 275 mi east of Ociyaran, near Riy and Mira." },
  { n: "Gora", cat: "town", x: 6373, y: 1170, k: "Equateiy", d: "In the Kingdom of Equateiy, about 225 mi west of Ociyaran, near Nelva and Vigila." },
  { n: "Burane", cat: "town", x: 6859, y: 1208, k: "Equateiy", d: "In the Kingdom of Equateiy, about 200 mi east of Ociyaran, near Mira and Squero." },
  { n: "Nelva", cat: "town", x: 6371, y: 1266, k: "Equateiy", d: "In the Kingdom of Equateiy, about 200 mi west of Ociyaran, near Cresp and Gora." },
  { n: "Claieso", cat: "town", x: 6749, y: 1243, k: "Equateiy", d: "In the Kingdom of Equateiy, about 100 mi east of Ociyaran, near Dragse and Burane." },
  { n: "Mira", cat: "town", x: 6920, y: 1233, k: "Equateiy", d: "In the Kingdom of Equateiy, about 250 mi east of Ociyaran, near Burane and Colle." },
  { n: "Dragse", cat: "town", x: 6783, y: 1286, k: "Equateiy", d: "In the Kingdom of Equateiy, about 150 mi east of Ociyaran, near Claieso and Brentola." },
  { n: "Cresp", cat: "town", x: 6340, y: 1322, k: "Equateiy", d: "In the Kingdom of Equateiy, about 225 mi west of Ociyaran, near Nelva and Roi." },
  { n: "Sarn", cat: "town", x: 6477, y: 1336, k: "Equateiy", d: "In the Kingdom of Equateiy, about 125 mi southwest of Ociyaran, near Vin and Nelva." },
  { n: "Pell'oro", cat: "town", x: 6646, y: 1329, k: "Equateiy", d: "In the Kingdom of Equateiy, about 80 mi southeast of Ociyaran, near Brentola and Pelefer." },
  { n: "Kanghol", cat: "town", x: 6980, y: 1316, k: "Vikitsv", d: "In the Kingdom of Vikitsv, about 800 mi north of Berlailia, near Hanora and Tsenmar." },
  { n: "Brentola", cat: "town", x: 6734, y: 1368, k: "Equateiy", d: "In the Kingdom of Equateiy, about 150 mi southeast of Ociyaran, near Pell'oro and Dragse." },
  { n: "Yitara", cat: "town", x: 2187, y: 1485, k: "Aicruae", d: "In the Kingdom of Aicruae, about 250 mi north of Lajazer, near Fordege and Belei." },
  { n: "Fordege", cat: "town", x: 2307, y: 1459, k: "Aicruae", d: "In the Kingdom of Aicruae, about 275 mi north of Lajazer, near Belei and Lera Mea." },
  { n: "Belei", cat: "town", x: 2304, y: 1521, k: "Aicruae", d: "In the Kingdom of Aicruae, about 225 mi north of Lajazer, near Alben and Fordege." },
  { n: "Alben", cat: "town", x: 2350, y: 1561, k: "Aicruae", d: "In the Kingdom of Aicruae, about 200 mi north of Lajazer, near Belei and Valea." },
  { n: "Atanio", cat: "town", x: 2158, y: 1601, k: "Aicruae", d: "In the Kingdom of Aicruae, about 175 mi northwest of Lajazer, near Tericaer and Hashrin." },
  { n: "Hashrin", cat: "town", x: 2295, y: 1618, k: "Aicruae", d: "In the Kingdom of Aicruae, about 150 mi north of Lajazer, near Vern and Valea." },
  { n: "Tericaer", cat: "town", x: 2096, y: 1644, k: "Aicruae", d: "In the Kingdom of Aicruae, about 175 mi northwest of Lajazer, near Atanio and Deyara. Future capital of Tanan." },
  { n: "Vern", cat: "town", x: 2260, y: 1658, k: "Aicruae", d: "In the Kingdom of Aicruae, about 100 mi north of Lajazer, near Hashrin and Uiedenai." },
  { n: "Jasereiey", cat: "region", x: 2295, y: 1700, k: "Aicruae", d: "Central heartland province of Aicruae." },
  { n: "Deyara", cat: "town", x: 2118, y: 1730, k: "Aicruae", d: "In the Kingdom of Aicruae, about 125 mi west of Lajazer, near Macerino and Neribec." },
  { n: "Nyeo", cat: "town", x: 2297, y: 1736, k: "Aicruae", d: "In the Kingdom of Aicruae, about 40 mi northeast of Lajazer, near Uiedenai and Vern. Site of Harnua's betrayal." },
  { n: "Fayedi", cat: "town", x: 1974, y: 1755, k: "Aicruae", d: "In the Kingdom of Aicruae, about 250 mi west of Lajazer, near Rewqo and Lene." },
  { n: "Neribec", cat: "town", x: 2040, y: 1772, k: "Aicruae", d: "In the Kingdom of Aicruae, about 175 mi west of Lajazer, near Rewqo and Deyara." },
  { n: "Macerino", cat: "town", x: 2150, y: 1780, k: "Aicruae", d: "In the Kingdom of Aicruae, about 100 mi west of Lajazer, near Deyara and Aseri Gai Oshana." },
  { n: "Lene", cat: "town", x: 1947, y: 1812, k: "Aicruae", d: "In the Kingdom of Aicruae, about 250 mi west of Lajazer, near Rewqo and Fayedi." },
  { n: "Aseri Gai Oshana", cat: "town", x: 2196, y: 1854, k: "Aicruae", d: "In the Kingdom of Aicruae, about 70 mi southwest of Lajazer, near Orcon and Macerino." },
  { n: "Dushrer", cat: "town", x: 1909, y: 1803, k: "Aicruae", d: "In the Kingdom of Aicruae, about 300 mi west of Lajazer, near Lene and Fayedi." },
  { n: "Caleo", cat: "town", x: 1899, y: 1881, k: "Aicruae", d: "In the Kingdom of Aicruae, about 325 mi west of Lajazer, near Dushrer and Dira." },
  { n: "Heusal", cat: "town", x: 1988, y: 1878, k: "Aicruae", d: "In the Kingdom of Aicruae, about 250 mi west of Lajazer, near Leyoni and Lene." },
  { n: "Thalyn", cat: "town", x: 1790, y: 1955, k: "Aicruae", d: "In the Kingdom of Aicruae, about 375 mi west of Lajazer, near Caleo and Hepeno." },
  { n: "Dira", cat: "town", x: 1944, y: 1975, k: "Aicruae", d: "In the Kingdom of Aicruae, about 300 mi southwest of Lajazer, near Ostoki and Bosletero." },
  { n: "Leyoni", cat: "town", x: 2064, y: 1946, k: "Aicruae", d: "In the Kingdom of Aicruae, about 225 mi southwest of Lajazer, near Bosletero and Heusal." },
  { n: "Lowec", cat: "town", x: 2117, y: 1958, k: "Aicruae", d: "In the Kingdom of Aicruae, about 200 mi southwest of Lajazer, near Begai and Leyoni." },
  { n: "Avego", cat: "town", x: 2275, y: 1958, k: "Aicruae", d: "In the Kingdom of Aicruae, about 150 mi south of Lajazer, near Comej and Orcon." },
  { n: "Comej", cat: "town", x: 2267, y: 2009, k: "Aicruae", d: "In the Kingdom of Aicruae, about 175 mi south of Lajazer, near Avego and Meprin." },
  { n: "Bosletero", cat: "town", x: 1987, y: 2015, k: "Aicruae", d: "In the Kingdom of Aicruae, about 275 mi southwest of Lajazer, near Leyoni and Dira." },
  { n: "Begai", cat: "town", x: 2146, y: 2032, k: "Aicruae", d: "In the Kingdom of Aicruae, about 225 mi southwest of Lajazer, near Lowec and Meprin." },
  { n: "Meprin", cat: "town", x: 2243, y: 2033, k: "Aicruae", d: "In the Kingdom of Aicruae, about 200 mi south of Lajazer, near Comej and Tineb." },
  { n: "Ostoki", cat: "town", x: 1935, y: 2020, k: "Aicruae", d: "In the Kingdom of Aicruae, about 350 mi southwest of Lajazer, near Dira and Hepeno." },
  { n: "Hepeno", cat: "town", x: 1853, y: 2066, k: "Aicruae", d: "In the Kingdom of Aicruae, about 425 mi southwest of Lajazer, near Teyetes and Ostoki." },
  { n: "Jani", cat: "town", x: 2356, y: 2048, k: "Aicruae", d: "In the Kingdom of Aicruae, about 225 mi south of Lajazer, near Caesro and Comej." },
  { n: "Tineb", cat: "town", x: 2264, y: 2111, k: "Aicruae", d: "In the Kingdom of Aicruae, about 250 mi south of Lajazer, near Meprin and Nayen." },
  { n: "Caesro", cat: "town", x: 2376, y: 2119, k: "Aicruae", d: "In the Kingdom of Aicruae, about 275 mi south of Lajazer, near Jani and Tineb." },
  { n: "Teyetes", cat: "town", x: 1900, y: 2135, k: "Aicruae", d: "In the Kingdom of Aicruae, about 400 mi southwest of Lajazer, near Port Quale and Hepeno." },
  { n: "Loeru", cat: "town", x: 2078, y: 2141, k: "Aicruae", d: "In the Kingdom of Aicruae, about 325 mi southwest of Lajazer, near Bareta and Nayen." },
  { n: "Nayen", cat: "town", x: 2169, y: 2133, k: "Aicruae", d: "In the Kingdom of Aicruae, about 300 mi south of Lajazer, near Honete and Loeru." },
  { n: "Bareta", cat: "town", x: 1989, y: 2172, k: "Aicruae", d: "In the Kingdom of Aicruae, about 375 mi southwest of Lajazer, near Loeru and Teyetes." },
  { n: "Honete", cat: "town", x: 2142, y: 2208, k: "Aicruae", d: "In the Kingdom of Aicruae, about 350 mi south of Lajazer, near Nayen and Mepria." },
  { n: "The Santie", cat: "town", x: 2251, y: 2234, k: "Aicruae", d: "In the Kingdom of Aicruae, about 350 mi south of Lajazer, near Teisho and Honete." },
  { n: "Liazen", cat: "region", x: 2005, y: 2085, k: "Aicruae", d: "Southern province of Aicruae, toward the badlands." },
  { n: "The Aoner", cat: "region", x: 2010, y: 1845, k: "Aicruae", d: "The 'Granary of the West': Aicruae's western granary coast." },
  { n: "Mepria", cat: "town", x: 2195, y: 2304, k: "Aicruae", d: "In the Kingdom of Aicruae, about 425 mi south of Lajazer, near Honete and Teisho." },
  { n: "Teisho", cat: "town", x: 2242, y: 2298, k: "Aicruae", d: "In the Kingdom of Aicruae, about 400 mi south of Lajazer, near The Santie and Laona." },
  { n: "Audin", cat: "town", x: 1989, y: 2344, k: "Aicruae", d: "In the Kingdom of Aicruae, about 500 mi southwest of Lajazer, near Mepria and Bareta." },
  { n: "Laona", cat: "town", x: 2268, y: 2394, k: "Aicruae", d: "In the Kingdom of Aicruae, about 475 mi south of Lajazer, near Teisho and Mepria." },
  { n: "Loriga", cat: "town", x: 2626, y: 2162, k: "Pireaynea", d: "In the Kingdom of Pireaynea, about 475 mi northwest of Civer, near Olbi and Vasco." },
  { n: "Rosca", cat: "town", x: 3013, y: 2150, k: "Pireaynea", d: "In the Kingdom of Pireaynea, about 250 mi northwest of Civer, near Pantari and Olbi." },
  { n: "Drino", cat: "town", x: 3404, y: 2172, k: "Pireaynea", d: "In the Kingdom of Pireaynea, about 275 mi northeast of Civer, near Pantari and Rosca." },
  { n: "Pantari", cat: "town", x: 3173, y: 2369, k: "Pireaynea", d: "In the Kingdom of Pireaynea, about 50 mi northeast of Civer, near Rosca and Sindbir." },
  { n: "Vasco", cat: "town", x: 2454, y: 2458, k: "Pireaynea", d: "In the Kingdom of Pireaynea, about 575 mi west of Civer, near Port Ols and Loriga." },
  { n: "Sindbir", cat: "town", x: 2996, y: 2555, k: "Pireaynea", d: "In the Kingdom of Pireaynea, about 175 mi southwest of Civer, near Pantari and Rosca." },
  { n: "Croco", cat: "town", x: 3204, y: 1737, k: "Gherci", d: "In the Kingdom of Gherci, about 775 mi west of Tarmet, near Ezon and Coelys." },
  { n: "Alsea", cat: "town", x: 3393, y: 1743, k: "Gherci", d: "In the Kingdom of Gherci, about 650 mi west of Tarmet, near Oradi and Drenia." },
  { n: "Oradi", cat: "town", x: 3354, y: 1800, k: "Gherci", d: "In the Kingdom of Gherci, about 650 mi west of Tarmet, near Alsea and Croco." },
  { n: "Ezon", cat: "town", x: 3270, y: 1603, k: "Gherci", d: "In the Kingdom of Gherci, about 775 mi northwest of Tarmet, near Lasten and Lujian." },
  { n: "Drenia", cat: "town", x: 3393, y: 1611, k: "Gherci", d: "In the Kingdom of Gherci, about 700 mi northwest of Tarmet, near Lujian and Oscan." },
  { n: "Lujian", cat: "town", x: 3375, y: 1553, k: "Gherci", d: "In the Kingdom of Gherci, about 725 mi northwest of Tarmet, near Drenia and Oscan." },
  { n: "Lasten", cat: "town", x: 3263, y: 1506, k: "Gherci", d: "In the Kingdom of Gherci, about 825 mi northwest of Tarmet, near Ezon and Lujian." },
  { n: "Olune", cat: "town", x: 3553, y: 1736, k: "Gherci", d: "In the Kingdom of Gherci, about 550 mi northwest of Tarmet, near Rietha and Shaer." },
  { n: "Nyes", cat: "town", x: 3665, y: 1554, k: "Gherci", d: "In the Kingdom of Gherci, about 525 mi northwest of Tarmet, near Rietha and Belune." },
  { n: "Shaer", cat: "town", x: 3543, y: 1872, k: "Gherci", d: "In the Kingdom of Gherci, about 500 mi west of Tarmet, near Lage and Zerpe." },
  { n: "Zerpe", cat: "town", x: 3700, y: 1920, k: "Gherci", d: "In the Kingdom of Gherci, about 375 mi west of Tarmet, near Cerby and Lage." },
  { n: "Lage", cat: "town", x: 3599, y: 2008, k: "Gherci", d: "In the Kingdom of Gherci, about 425 mi west of Tarmet, near Zerpe and Cerby." },
  { n: "Cerby", cat: "town", x: 3755, y: 2026, k: "Gherci", d: "In the Kingdom of Gherci, about 325 mi west of Tarmet, near Zerpe and Keba." },
  { n: "Golan", cat: "town", x: 3662, y: 2159, k: "Gherci", d: "In the Kingdom of Gherci, about 400 mi west of Tarmet, near Lage and Cerby." },
  { n: "Vaia", cat: "town", x: 2585, y: 1487, k: "Gherci", d: "In the Kingdom of Gherci, about 1300 mi west of Tarmet, near Tellas and Annagi." },
  { n: "Liviao", cat: "town", x: 2716, y: 1405, k: "Gherci", d: "In the Kingdom of Gherci, about 1250 mi northwest of Tarmet, near Paler and Annagi." },
  { n: "Annagi", cat: "town", x: 2723, y: 1499, k: "Gherci", d: "In the Kingdom of Gherci, about 1225 mi west of Tarmet, near Noraho and Liviao." },
  { n: "Giagior", cat: "town", x: 2897, y: 1451, k: "Gherci", d: "In the Kingdom of Gherci, about 1100 mi northwest of Tarmet, near Iaga and Tagre." },
  { n: "Mema", cat: "town", x: 3014, y: 1488, k: "Gherci", d: "In the Kingdom of Gherci, about 1000 mi northwest of Tarmet, near Tophercris and Giagior." },
  { n: "Tophercris", cat: "town", x: 3067, y: 1414, k: "Gherci", d: "In the Kingdom of Gherci, about 1000 mi northwest of Tarmet, near Mema and Anaan." },
  { n: "Vannigio", cat: "town", x: 3365, y: 1429, k: "Gherci", d: "In the Kingdom of Gherci, about 800 mi northwest of Tarmet, near Eloe and Egodi." },
  { n: "Selve", cat: "town", x: 3569, y: 1430, k: "Gherci", d: "In the Kingdom of Gherci, about 675 mi northwest of Tarmet, near Renzolo and Cardoric." },
  { n: "Cardoric", cat: "town", x: 3397, y: 1451, k: "Gherci", d: "In the Kingdom of Gherci, about 725 mi northwest of Tarmet, near Oscan and Egodi." },
  { n: "Noraho", cat: "town", x: 2754, y: 1552, k: "Gherci", d: "In the Kingdom of Gherci, about 1175 mi west of Tarmet, near Lanmi and Annagi." },
  { n: "Tellas", cat: "town", x: 2665, y: 1577, k: "Gherci", d: "In the Kingdom of Gherci, about 1225 mi west of Tarmet, near Resate and Noraho." },
  { n: "Lanmi", cat: "town", x: 2771, y: 1592, k: "Gherci", d: "In the Kingdom of Gherci, about 1150 mi west of Tarmet, near Noraho and Noju." },
  { n: "Resate", cat: "town", x: 2694, y: 1626, k: "Gherci", d: "In the Kingdom of Gherci, about 1200 mi west of Tarmet, near Tellas and Noju." },
  { n: "Noju", cat: "town", x: 2781, y: 1641, k: "Gherci", d: "In the Kingdom of Gherci, about 1125 mi west of Tarmet, near Lanmi and Apric." },
  { n: "Thevia", cat: "town", x: 2892, y: 1626, k: "Gherci", d: "In the Kingdom of Gherci, about 1050 mi west of Tarmet, near Apric and Iaga." },
  { n: "Apric", cat: "town", x: 2839, y: 1682, k: "Gherci", d: "In the Kingdom of Gherci, about 1075 mi west of Tarmet, near Noju and Thevia." },
  { n: "Iaga", cat: "town", x: 2856, y: 1540, k: "Gherci", d: "In the Kingdom of Gherci, about 1100 mi west of Tarmet, near Lanmi and Thevia." },
  { n: "Meliwit", cat: "town", x: 2596, y: 1619, k: "Aicruae", d: "In the Kingdom of Aicruae, about 275 mi northeast of Lajazer, near Braiston and Casqen Gai Zaeri." },
  { n: "Braiston", cat: "town", x: 2534, y: 1665, k: "Aicruae", d: "In the Kingdom of Aicruae, about 225 mi east of Lajazer, near Casqen Gai Zaeri and Meliwit." },
  { n: "Maenen", cat: "town", x: 2454, y: 1657, k: "Aicruae", d: "In the Kingdom of Aicruae, about 175 mi northeast of Lajazer, near Wistin and Peisk." },
  { n: "Casqen Gai Zaeri", cat: "town", x: 2534, y: 1718, k: "Aicruae", d: "In the Kingdom of Aicruae, about 250 mi east of Lajazer, near Braiston and Zagaro." },
  { n: "Zagaro", cat: "town", x: 2532, y: 1778, k: "Aicruae", d: "In the Kingdom of Aicruae, about 225 mi east of Lajazer, near Casqen Gai Zaeri and Masein." },
  { n: "Masein", cat: "town", x: 2480, y: 1871, k: "Aicruae", d: "In the Kingdom of Aicruae, about 175 mi east of Lajazer, near Oahiat and Jiegoa." },
  { n: "Jiegoa", cat: "town", x: 2400, y: 1896, k: "Aicruae", d: "In the Kingdom of Aicruae, about 150 mi southeast of Lajazer, near Masein and Oahiat." },
  { n: "Oahiat", cat: "town", x: 2506, y: 1914, k: "Aicruae", d: "In the Kingdom of Aicruae, about 225 mi southeast of Lajazer, near Masein and Jiegoa." },
  { n: "Benalo", cat: "town", x: 2471, y: 2053, k: "Aicruae", d: "In the Kingdom of Aicruae, about 275 mi southeast of Lajazer, near Jani and Caesro." },
  { n: "Kanidon", cat: "river", x: 2540, y: 1535, k: "Aicruae", d: "In the Kingdom of Aicruae, about 300 mi northeast of Lajazer, near Isecia and Meliwit. River on Aicruae's northeastern frontier." },
  { n: "Gengo", cat: "river", x: 2655, y: 1680, k: "Aicruae", d: "In the Kingdom of Aicruae, about 325 mi east of Lajazer, near Casqen Gai Zaeri and Meliwit. River on Aicruae's northeastern frontier." },
  { n: "Holwe", cat: "town", x: 2422, y: 1500, k: "Aicruae", d: "In the Kingdom of Aicruae, about 250 mi northeast of Lajazer, near Melerbo and Isecia." },
  { n: "Isecia", cat: "town", x: 2454, y: 1547, k: "Aicruae", d: "In the Kingdom of Aicruae, about 250 mi northeast of Lajazer, near Wistin and Holwe." },
  { n: "Wistin", cat: "town", x: 2425, y: 1594, k: "Aicruae", d: "In the Kingdom of Aicruae, about 200 mi northeast of Lajazer, near Isecia and Maenen." },
  { n: "Olbi", cat: "town", x: 2808, y: 1965, k: "Pireaynea", d: "In the Kingdom of Pireaynea, about 450 mi northwest of Civer, near Loriga and Rosca." },
  { n: "Uiedenai", cat: "town", x: 2398, y: 1690, k: "Aicruae", d: "In the Kingdom of Aicruae, about 80 mi northeast of Lajazer, near Vern and Nyeo." },
  { n: "Peisk", cat: "town", x: 2405, y: 1730, k: "Aicruae", d: "In the Kingdom of Aicruae, about 125 mi east of Lajazer, near Madu and Maenen." },
  { n: "Madu", cat: "town", x: 2363, y: 1745, k: "Aicruae", d: "In the Kingdom of Aicruae, about 75 mi northeast of Lajazer, near Rewqo and Peisk.", alt: "Madreu Madrewqo" },
  { n: "Rewqo", cat: "town", x: 2413, y: 1823, k: "Aicruae", d: "In the Kingdom of Aicruae, about 125 mi east of Lajazer, near Madu and Masein.", alt: "Madrewqo" },
  { n: "Adani", cat: "town", x: 3914, y: 1411, k: "Gherci", d: "In the Kingdom of Gherci, about 525 mi north of Tarmet, near Cyme and Gondes." },
  { n: "Inqwe", cat: "town", x: 4112, y: 1482, k: "Gherci", d: "In the Kingdom of Gherci, about 450 mi north of Tarmet, near Resia and Malie." },
  { n: "Cyme", cat: "town", x: 3930, y: 1495, k: "Gherci", d: "In the Kingdom of Gherci, about 450 mi north of Tarmet, near Malie and Adani." },
  { n: "Oryur", cat: "town", x: 4542, y: 1412, k: "Gherci", d: "In the Kingdom of Gherci, about 600 mi northeast of Tarmet, near Garen and Inqua." },
  { n: "Nyedal", cat: "town", x: 4749, y: 1420, k: "Gherci", d: "In the Kingdom of Gherci, about 700 mi northeast of Tarmet, near Tasfen and Garen." },
  { n: "Hagiora", cat: "town", x: 5074, y: 1460, k: "the far-eastern territories", d: "In the far-eastern territories beyond Gherci's border, about 1000 mi north of Amba, near Semhol and Belnara." },
  { n: "Garen", cat: "town", x: 4633, y: 1516, k: "Gherci", d: "In the Kingdom of Gherci, about 575 mi northeast of Tarmet, near Oryur and Nyedal." },
  { n: "Tasfen", cat: "town", x: 4812, y: 1515, k: "Gherci", d: "In the Kingdom of Gherci, about 675 mi northeast of Tarmet, near Nyedal and Garen." },
  { n: "Malie", cat: "town", x: 3969, y: 1588, k: "Gherci", d: "In the Kingdom of Gherci, about 375 mi north of Tarmet, near Cyme and Ostra." },
  { n: "Hoan", cat: "town", x: 4273, y: 1587, k: "Gherci", d: "In the Kingdom of Gherci, about 375 mi north of Tarmet, near Lokea and Inqwe." },
  { n: "Belune", cat: "town", x: 3845, y: 1619, k: "Gherci", d: "In the Kingdom of Gherci, about 375 mi northwest of Tarmet, near Kessa and Rietha." },
  { n: "Ostra", cat: "town", x: 4032, y: 1705, k: "Gherci", d: "In the Kingdom of Gherci, about 300 mi north of Tarmet, near Malie and Bayen." },
  { n: "Ralt", cat: "town", x: 4529, y: 1632, k: "Gherci", d: "In the Kingdom of Gherci, about 450 mi northeast of Tarmet, near Elemie and Iel." },
  { n: "Iel", cat: "town", x: 4637, y: 1698, k: "Gherci", d: "In the Kingdom of Gherci, about 500 mi northeast of Tarmet, near Lujia and Ralt." },
  { n: "Lokea", cat: "town", x: 4263, y: 1716, k: "Gherci", d: "In the Kingdom of Gherci, about 275 mi north of Tarmet, near Cula and Hoan." },
  { n: "Cula", cat: "town", x: 4293, y: 1796, k: "Gherci", d: "In the Kingdom of Gherci, about 225 mi northeast of Tarmet, near Lokea and Vashon." },
  { n: "Elemie", cat: "town", x: 4472, y: 1728, k: "Gherci", d: "In the Kingdom of Gherci, about 350 mi northeast of Tarmet, near Vashon and Ralt." },
  { n: "Lujia", cat: "town", x: 4819, y: 1764, k: "Gherci", d: "In the Kingdom of Gherci, about 575 mi northeast of Tarmet, near Inen and Iel." },
  { n: "Kidaris", cat: "town", x: 5107, y: 1814, k: "the far-eastern territories", d: "In the far-eastern territories beyond Gherci's border, about 725 mi northwest of Amba, near Semhol and Medhuk." },
  { n: "Vashon", cat: "town", x: 4441, y: 1836, k: "Gherci", d: "In the Kingdom of Gherci, about 275 mi northeast of Tarmet, near Elemie and Laiya." },
  { n: "Laiya", cat: "town", x: 4622, y: 1818, k: "Gherci", d: "In the Kingdom of Gherci, about 375 mi northeast of Tarmet, near Vashon and Iel." },
  { n: "Inen", cat: "town", x: 4764, y: 1871, k: "Gherci", d: "In the Kingdom of Gherci, about 500 mi east of Tarmet, near Avani and Lujia." },
  { n: "Muri", cat: "town", x: 4946, y: 1919, k: "Gherci", d: "In the Kingdom of Gherci, about 375 mi east of Tarmet, near Inen and Avani." },
  { n: "Bayen", cat: "town", x: 3895, y: 1838, k: "Gherci", d: "In the Kingdom of Gherci, about 275 mi northwest of Tarmet, near Treas and Belune." },
  { n: "Treas", cat: "town", x: 3899, y: 1966, k: "Gherci", d: "In the Kingdom of Gherci, about 200 mi west of Tarmet, near Keba and Bayen." },
  { n: "Lendara", cat: "town", x: 4132, y: 1962, k: "Gherci", d: "In the Kingdom of Gherci, about 60 mi north of Tarmet, near Asmeta and Malin." },
  { n: "Malin", cat: "town", x: 4258, y: 1952, k: "Gherci", d: "In the Kingdom of Gherci, about 125 mi northeast of Tarmet, near Lendara and Cula." },
  { n: "Ristia", cat: "town", x: 4565, y: 1899, k: "Gherci", d: "In the Kingdom of Gherci, about 300 mi east of Tarmet, near Vashon and Calye." },
  { n: "Avani", cat: "town", x: 4709, y: 1965, k: "Gherci", d: "In the Kingdom of Gherci, about 450 mi east of Tarmet, near Inen and Amies." },
  { n: "Asmeta", cat: "town", x: 4054, y: 2010, k: "Gherci", d: "In the Kingdom of Gherci, about 70 mi west of Tarmet, near Lendara and Treas." },
  { n: "Keba", cat: "town", x: 3891, y: 2048, k: "Gherci", d: "In the Kingdom of Gherci, about 200 mi west of Tarmet, near Treas and Doka." },
  { n: "Amies", cat: "town", x: 4819, y: 2040, k: "Gherci", d: "In the Kingdom of Gherci, about 550 mi east of Tarmet, near Avani and Menejel." },
  { n: "Oermat", cat: "town", x: 5075, y: 2007, k: "Gherci", d: "In the Kingdom of Gherci, about 750 mi east of Tarmet, near Lethe and Loria." },
  { n: "Calye", cat: "town", x: 4430, y: 2115, k: "Gherci", d: "In the Kingdom of Gherci, about 250 mi east of Tarmet, near Thelia and Ristia." },
  { n: "Lethe", cat: "town", x: 4983, y: 2102, k: "Gherci", d: "In the Kingdom of Gherci, about 675 mi east of Tarmet, near Loria and Oermat." },
  { n: "Doka", cat: "town", x: 3880, y: 2135, k: "Gherci", d: "In the Kingdom of Gherci, about 225 mi west of Tarmet, near Keba and Granosa." },
  { n: "Tanya Beka", cat: "town", x: 4237, y: 2157, k: "Gherci", d: "In the Kingdom of Gherci, about 125 mi southeast of Tarmet, near Nords and Malin." },
  { n: "Yvenna", cat: "town", x: 4664, y: 2171, k: "Gherci", d: "In the Kingdom of Gherci, about 425 mi east of Tarmet, near Saltie and Anye." },
  { n: "Menejel", cat: "town", x: 4831, y: 2177, k: "Gherci", d: "In the Kingdom of Gherci, about 575 mi east of Tarmet, near Saltie and Amies." },
  { n: "Granosa", cat: "town", x: 3959, y: 2214, k: "Gherci", d: "In the Kingdom of Gherci, about 200 mi southwest of Tarmet, near Doka and Tarl." },
  { n: "Thelia", cat: "town", x: 4483, y: 2219, k: "Gherci", d: "In the Kingdom of Gherci, about 300 mi southeast of Tarmet, near Calye and Orin." },
  { n: "Cosar", cat: "river", x: 3745, y: 2200, k: "Gherci", d: "In the Kingdom of Gherci, about 350 mi west of Tarmet, near Golan and Tarl. River of the Lower Gherci system, draining to the Fetora Sea." },
  { n: "Saltie", cat: "town", x: 4740, y: 2257, k: "Gherci", d: "In the Kingdom of Gherci, about 500 mi east of Tarmet, near Yvenna and Menejel." },
  { n: "Tarl", cat: "town", x: 3874, y: 2285, k: "Gherci", d: "In the Kingdom of Gherci, about 300 mi southwest of Tarmet, near Anjelie and Granosa." },
  { n: "Caspra", cat: "town", x: 4033, y: 2311, k: "Gherci", d: "In the Kingdom of Gherci, about 225 mi south of Tarmet, near Granosa and Nords." },
  { n: "Nords", cat: "town", x: 4187, y: 2288, k: "Gherci", d: "In the Kingdom of Gherci, about 200 mi south of Tarmet, near Pelia and Tanya Beka." },
  { n: "Maru", cat: "town", x: 4935, y: 2295, k: "Gherci", d: "In the Kingdom of Gherci, about 675 mi east of Tarmet, near Loria and Menejel." },
  { n: "Anye", cat: "town", x: 4620, y: 2326, k: "Gherci", d: "The eastern of the two Anyes. In the Kingdom of Gherci, about 450 mi southeast of Tarmet, near Saltie and Orin." },
  { n: "Anye", cat: "town", x: 4293, y: 2555, k: "Gherci", d: "The southwestern of the two Anyes. In the Kingdom of Gherci, about 425 mi south of Tarmet, near Pelia and Drun." },
  { n: "Anjelie", cat: "town", x: 3896, y: 2398, k: "Gherci", d: "In the Kingdom of Gherci, about 350 mi southwest of Tarmet, near Rietra and Tarl." },
  { n: "Orin", cat: "town", x: 4434, y: 2370, k: "Gherci", d: "In the Kingdom of Gherci, about 350 mi southeast of Tarmet, near Thelia and Pelia." },
  { n: "Vagn", cat: "town", x: 4754, y: 2450, k: "Gherci", d: "In the Kingdom of Gherci, about 575 mi southeast of Tarmet, near Anye and Saltie." },
  { n: "Pelia", cat: "town", x: 4265, y: 2407, k: "Gherci", d: "In the Kingdom of Gherci, about 300 mi south of Tarmet, near Nords and Orin." },
  { n: "Forea", cat: "town", x: 4085, y: 2468, k: "Gherci", d: "In the Kingdom of Gherci, about 350 mi south of Tarmet, near Pontata and Rietra." },
  { n: "Rietra", cat: "town", x: 3917, y: 2496, k: "Gherci", d: "In the Kingdom of Gherci, about 400 mi southwest of Tarmet, near Pontata and Anjelie." },
  { n: "Demia", cat: "town", x: 4976, y: 2507, k: "Gherci", d: "In the Kingdom of Gherci, about 750 mi southeast of Tarmet, near Gai and Maru." },
  { n: "Pontata", cat: "town", x: 3979, y: 2568, k: "Gherci", d: "In the Kingdom of Gherci, about 450 mi south of Tarmet, near Rietra and Aoin." },
  { n: "Aoin", cat: "town", x: 3909, y: 2651, k: "Gherci", d: "In the Kingdom of Gherci, about 500 mi south of Tarmet, near Pontata and Rietra." },
  { n: "Drun", cat: "town", x: 4446, y: 2623, k: "Gherci", d: "In the Kingdom of Gherci, about 525 mi southeast of Tarmet, near Esku and Trask." },
  { n: "Trask", cat: "town", x: 4627, y: 2674, k: "Gherci", d: "In the Kingdom of Gherci, about 650 mi southeast of Tarmet, near Oskba and Drun." },
  { n: "Esku", cat: "town", x: 4443, y: 2736, k: "Gherci", d: "In the Kingdom of Gherci, about 600 mi south of Tarmet, near Drun and Kuldar." },
  { n: "Talu", cat: "town", x: 6063, y: 1755, k: "Equateiy", d: "In the Kingdom of Equateiy, about 600 mi southwest of Ociyaran, near Esteraia and Velsa. Town at the edge of the Nedi Forest." },
  { n: "Ombretta", cat: "town", x: 5922, y: 1447, k: "Equateiy", d: "In the Kingdom of Equateiy, about 550 mi west of Ociyaran, near Reda and Larida." },
  { n: "Larida", cat: "town", x: 6077, y: 1439, k: "Equateiy", d: "In the Kingdom of Equateiy, about 450 mi west of Ociyaran, near Reda and Movo." },
  { n: "Movo", cat: "town", x: 6176, y: 1388, k: "Equateiy", d: "In the Kingdom of Equateiy, about 350 mi west of Ociyaran, near Ilvo and Lezna." },
  { n: "Murra", cat: "town", x: 6307, y: 1440, k: "Equateiy", d: "In the Kingdom of Equateiy, about 275 mi southwest of Ociyaran, near Velo and Lezna." },
  { n: "Lezna", cat: "town", x: 6206, y: 1469, k: "Equateiy", d: "In the Kingdom of Equateiy, about 375 mi southwest of Ociyaran, near Movo and Grotta." },
  { n: "Velo", cat: "town", x: 6374, y: 1519, k: "Equateiy", d: "In the Kingdom of Equateiy, about 275 mi southwest of Ociyaran, near Murra and Lezna." },
  { n: "Grotta", cat: "town", x: 6172, y: 1550, k: "Equateiy", d: "In the Kingdom of Equateiy, about 425 mi southwest of Ociyaran, near Pratesi and Ravia." },
  { n: "Ravia", cat: "town", x: 6096, y: 1575, k: "Equateiy", d: "In the Kingdom of Equateiy, about 475 mi southwest of Ociyaran, near Velsa and Grotta." },
  { n: "Pratesi", cat: "town", x: 6218, y: 1601, k: "Equateiy", d: "In the Kingdom of Equateiy, about 425 mi southwest of Ociyaran, near Grotta and Uada." },
  { n: "Velsa", cat: "town", x: 6059, y: 1619, k: "Equateiy", d: "In the Kingdom of Equateiy, about 525 mi southwest of Ociyaran, near Ravia and Esteraia." },
  { n: "Uada", cat: "town", x: 6181, y: 1662, k: "Equateiy", d: "In the Kingdom of Equateiy, about 475 mi southwest of Ociyaran, near Aslwal and Esteraia. Town of the Nedi Forest reaches; the smaller towns Aslwal and Esteraia sit within it." },
  { n: "Nurida", cat: "town", x: 6386, y: 1642, k: "Vikitsv", d: "In the Kingdom of Vikitsv, about 625 mi northwest of Berlailia, near Tsenmar and Reskt." },
  { n: "Bellaria", cat: "town", x: 5273, y: 1705, k: "the far-eastern territories", d: "In the far-eastern territories beyond Gherci's border, about 750 mi north of Amba, near Norabea and Tehron." },
  { n: "Norabea", cat: "town", x: 5347, y: 1677, k: "the far-eastern territories", d: "In the far-eastern territories beyond Gherci's border, about 775 mi north of Amba, near Bellaria and Tehron." },
  { n: "Semhol", cat: "town", x: 5109, y: 1724, k: "the far-eastern territories", d: "In the far-eastern territories beyond Gherci's border, about 775 mi north of Amba, near Kidaris and Belnara." },
  { n: "Medhuk", cat: "town", x: 5214, y: 1853, k: "the far-eastern territories", d: "In the far-eastern territories beyond Gherci's border, about 650 mi north of Amba, near Tehron and Kidaris." },
  { n: "Tehron", cat: "town", x: 5333, y: 1837, k: "the far-eastern territories", d: "In the far-eastern territories beyond Gherci's border, about 650 mi north of Amba, near Medhuk and Tusjin." },
  { n: "Tusjin", cat: "town", x: 5280, y: 1979, k: "the far-eastern territories", d: "In the far-eastern territories beyond Gherci's border, about 550 mi north of Amba, near Dremk and Denkay." },
  { n: "Vagust", cat: "town", x: 5450, y: 1979, k: "the far-eastern territories", d: "In the far-eastern territories beyond Gherci's border, about 525 mi north of Amba, near Denkay and Aspardo." },
  { n: "Denkay", cat: "town", x: 5389, y: 2041, k: "the far-eastern territories", d: "In the far-eastern territories beyond Gherci's border, about 475 mi north of Amba, near Vagust and Rudeth." },
  { n: "Aspardo", cat: "town", x: 5523, y: 2036, k: "the far-eastern territories", d: "In the far-eastern territories beyond Gherci's border, about 475 mi north of Amba, near Vagust and Allisto." },
  { n: "Dremk", cat: "town", x: 5222, y: 2079, k: "the far-eastern territories", d: "In the far-eastern territories beyond Gherci's border, about 475 mi north of Amba, near Tusjin and Tsir." },
  { n: "Allisto", cat: "town", x: 5583, y: 2111, k: "the far-eastern territories", d: "In the far-eastern territories beyond Gherci's border, about 425 mi north of Amba, near Brall and Aspardo." },
  { n: "Rudeth", cat: "town", x: 5412, y: 2138, k: "the far-eastern territories", d: "In the far-eastern territories beyond Gherci's border, about 400 mi north of Amba, near Denkay and Dugwil." },
  { n: "Bralk", cat: "town", x: 5607, y: 2160, k: "the far-eastern territories", d: "In the far-eastern territories beyond Gherci's border, about 400 mi north of Amba, near Allisto and Dugwil." },
  { n: "Tsir", cat: "town", x: 5230, y: 2214, k: "the far-eastern territories", d: "In the far-eastern territories beyond Gherci's border, about 375 mi northwest of Amba, near Dremk and Rudeth." },
  { n: "Dugwil", cat: "town", x: 5510, y: 2202, k: "the far-eastern territories", d: "In the far-eastern territories beyond Gherci's border, about 350 mi north of Amba, near Brall and Allisto." },
  { n: "Hagn", cat: "town", x: 5404, y: 2287, k: "the far-eastern territories", d: "In the far-eastern territories beyond Gherci's border, about 275 mi north of Amba, near Hauk and Dugwil." },
  { n: "Sevq", cat: "town", x: 5616, y: 2289, k: "the far-eastern territories", d: "In the far-eastern territories beyond Gherci's border, about 300 mi northeast of Amba, near Dahn and Hauk." },
  { n: "Hauk", cat: "town", x: 5529, y: 2329, k: "the far-eastern territories", d: "In the far-eastern territories beyond Gherci's border, about 250 mi north of Amba, near Sevq and Dahn." },
  { n: "Dahn", cat: "town", x: 5621, y: 2365, k: "the far-eastern territories", d: "In the far-eastern territories beyond Gherci's border, about 250 mi northeast of Amba, near Sevq and Hauk." },
  { n: "Hagiore", cat: "town", x: 5540, y: 2512, k: "the far-eastern territories", d: "In the far-eastern territories beyond Gherci's border, about 125 mi northeast of Amba, near Dahn and Hauk." },
  { n: "Ompol", cat: "town", x: 6116, y: 2602, k: "Vikitsv", d: "In the Kingdom of Vikitsv, about 600 mi southwest of Berlailia, near Bohan and Torad." },
  { n: "Demre", cat: "town", x: 5294, y: 2655, k: "the far-eastern territories", d: "In the far-eastern territories beyond Gherci's border, about 125 mi west of Amba, near Limn and Dordbin." },
  { n: "Selvet", cat: "town", x: 5504, y: 2722, k: "the far-eastern territories", d: "In the far-eastern territories beyond Gherci's border, about 90 mi southeast of Amba, near Maryos and Limn." },
  { n: "Tsenmar", cat: "town", x: 6705, y: 1509, k: "Vikitsv", d: "In the Kingdom of Vikitsv, about 650 mi north of Berlailia, near Hanora and Kanghol." },
  { n: "Hanora", cat: "town", x: 6979, y: 1647, k: "Vikitsv", d: "In the Kingdom of Vikitsv, about 550 mi north of Berlailia, near Tsenmar and Kanghol." },
  { n: "Daltsen", cat: "town", x: 6596, y: 2223, k: "Vikitsv", d: "In the Kingdom of Vikitsv, about 175 mi west of Berlailia, near Sehrok and Byeola." },
  { n: "Negiet", cat: "town", x: 6765, y: 2200, k: "Vikitsv", d: "In the Kingdom of Vikitsv, about 90 mi north of Berlailia, near Daltsen and Sehrok." },
  { n: "Sehrok", cat: "town", x: 6540, y: 2304, k: "Vikitsv", d: "In the Kingdom of Vikitsv, about 200 mi west of Berlailia, near Byeola and Daltsen." },
  { n: "Byeola", cat: "town", x: 6558, y: 2378, k: "Vikitsv", d: "In the Kingdom of Vikitsv, about 200 mi west of Berlailia, near Sehrok and Sahlen." },
  { n: "Sahlen", cat: "town", x: 6520, y: 2456, k: "Vikitsv", d: "In the Kingdom of Vikitsv, about 250 mi southwest of Berlailia, near Byeola and Torad." },
  { n: "Sahla", cat: "town", x: 6688, y: 2494, k: "Vikitsv", d: "In the Kingdom of Vikitsv, about 175 mi southwest of Berlailia, near Sahlen and Byeola." },
  { n: "Gaedu", cat: "town", x: 6878, y: 2529, k: "Vikitsv", d: "In the Kingdom of Vikitsv, about 200 mi south of Berlailia, near Yula and Sahla." },
  { n: "Torad", cat: "town", x: 6530, y: 2559, k: "Vikitsv", d: "In the Kingdom of Vikitsv, about 300 mi southwest of Berlailia, near Galmun and Sahlen." },
  { n: "Yula", cat: "town", x: 6858, y: 2601, k: "Vikitsv", d: "In the Kingdom of Vikitsv, about 225 mi south of Berlailia, near Gaedu and Sahla." },
  { n: "Galmun", cat: "town", x: 6574, y: 2634, k: "Vikitsv", d: "In the Kingdom of Vikitsv, about 325 mi southwest of Berlailia, near Junjeo and Torad." },
  { n: "Junjeo", cat: "town", x: 6620, y: 2709, k: "Vikitsv", d: "In the Kingdom of Vikitsv, about 350 mi southwest of Berlailia, near Vekit and Galmun. Town of the Torad valleys; the smaller town Vekit sits within it." },
  { n: "Oskba", cat: "town", x: 4609, y: 2843, k: "Gherci", d: "In the Kingdom of Gherci, about 725 mi southeast of Tarmet, near Tagrim and Trask." },
  { n: "Limn", cat: "town", x: 5327, y: 2785, k: "the far-eastern territories", d: "In the far-eastern territories beyond Gherci's border, about 150 mi southwest of Amba, near Demre and Dordbin." },
  { n: "Dordbin", cat: "town", x: 5180, y: 2834, k: "the far-eastern territories", d: "In the far-eastern territories beyond Gherci's border, about 175 mi southeast of Mireb, near Limn and Demre." },
  { n: "Maryos", cat: "town", x: 5439, y: 2901, k: "the far-eastern territories", d: "In the far-eastern territories beyond Gherci's border, about 200 mi south of Amba, near Limn and Selvet." },
  { n: "Gilsa", cat: "town", x: 5710, y: 2969, k: "Vikitsv", d: "In the Kingdom of Vikitsv, about 1025 mi southwest of Berlailia, near Bohan and Ompol." },
  { n: "Namilna", cat: "town", x: 6747, y: 2936, k: "Vikitsv", d: "In the Kingdom of Vikitsv, about 500 mi south of Berlailia, near Gjen and Vekit." },
  { n: "Gjen", cat: "town", x: 6895, y: 2944, k: "Vikitsv", d: "In the Kingdom of Vikitsv, about 525 mi south of Berlailia, near Qunag and Namilna." },
  { n: "Cael'mu", cat: "town", x: 7239, y: 3072, k: "Vikitsv", d: "In the Kingdom of Vikitsv, about 700 mi southeast of Berlailia, near Orjin and Port Sael." },
  { n: "Orjin", cat: "town", x: 6972, y: 3169, k: "Vikitsv", d: "In the Kingdom of Vikitsv, about 700 mi south of Berlailia, near Gjen and Qunag." },
  { n: "Vin Pelefer", cat: "town", x: 6595, y: 1416, k: "Equateiy", d: "In the Kingdom of Equateiy, about 150 mi south of Ociyaran, near Sarn and Pell'oro. Southern reaches of Equateiy." },
  { n: "Orcon", cat: "town", x: 2258, y: 1909, k: "Aicruae", d: "In the Kingdom of Aicruae, about 90 mi south of Lajazer, near Avego and Aseri Gai Oshana. Haleker frontier town." },
  { n: "Valea", cat: "town", x: 2370, y: 1638, k: "Aicruae", d: "In the Kingdom of Aicruae, about 125 mi northeast of Lajazer, near Uiedenai and Hashrin." },
  { n: "Melerbo", cat: "town", x: 2447, y: 1448, k: "Aicruae", d: "In the Kingdom of Aicruae, about 300 mi northeast of Lajazer, near Holwe and Isecia." },
  { n: "Slaia", cat: "town", x: 3783, y: 433, k: "Coelum", d: "In the Kingdom of Coelum, about 250 mi northwest of Atriki, near Tilnyeau and Nisclair. Henem Bay coast." },
  { n: "Belnara", cat: "town", x: 4980, y: 1739, k: "the far-eastern territories", d: "In the far-eastern territories beyond Gherci's border, about 775 mi north of Mireb, near Semhol and Kidaris. Far-eastern band, beyond Gherci's border." },
  { n: "Vekit", cat: "town", x: 6620, y: 2709, k: "Vikitsv", d: "In the Kingdom of Vikitsv, about 350 mi south of Berlailia, near Junjeo and Galmun. A smaller town inside Junjeo. (Approximate placement.)" },
  { n: "Aslwal", cat: "town", x: 6184, y: 1686, k: "Equateiy", d: "In the Kingdom of Equateiy, about 475 mi southwest of Ociyaran, near Uada and Esteraia. A smaller town inside Uada. (Approximate placement.)" },
  { n: "Esteraia", cat: "town", x: 6155, y: 1685, k: "Equateiy", d: "In the Kingdom of Equateiy, about 500 mi southwest of Ociyaran, near Uada and Aslwal. A smaller town inside Uada. (Approximate placement.)" },
  { n: "Loedesca", cat: "river", x: 2370, y: 2210, k: "Aicruae", d: "In the Kingdom of Aicruae, about 350 mi south of Lajazer, near Caesro and The Santie. River of southeastern Aicruae, near the southern Pireaynea border." },
  { n: "The Demon's Pit", cat: "landmark", x: 2654, y: 2164, k: "Aicruae", d: "In the Kingdom of Aicruae, about 450 mi southeast of Lajazer, near Benalo and Oahiat. Canon name for the Aicruae-Pireaynea border. (Approximate placement.)" },
];

const KINGDOMS = [
  { n: "Aicruae", capital: "Lajazer", d: "Westernmost of the six kingdoms of the pre-Empire era.", biomes: ["Grassland", "Cold desert (dry interior)", "Temperate deciduous forest", "Temperate rainforest (west coast)"] },
  { n: "Pireaynea", capital: "Civer", d: "South-central kingdom directly east of Aicruae, across the Demon's Pit.", biomes: ["Grassland", "Savanna", "Tropical seasonal forest (Fetora coast)", "Wetland (river lowlands)"] },
  { n: "Gherci", capital: "Tarmet", d: "Largest and most central kingdom of the pre-Empire era.", biomes: ["Grassland", "Savanna (dry central plains)", "Temperate deciduous forest", "Wetland (Honlo shores)"] },
  { n: "Coelum", capital: "Atriki", d: "The northern 'Forsaken Land'.", biomes: ["Taiga", "Tundra (far north)", "Temperate deciduous forest", "Grassland"] },
  { n: "Equateiy", capital: "Ociyaran", d: "Highland kingdom of the northeast.", biomes: ["Grassland", "Temperate deciduous forest", "Temperate rainforest (Oberya cliffs)", "Taiga (highlands)"] },
  { n: "Vikitsv", capital: "Berlailia", d: "Mountain kingdom of the eastern peninsula, radiating from Mount Aicren.", biomes: ["Tundra", "Glacier (high massif)", "Taiga", "Temperate rainforest (coastal slopes)"] }
];

const BIOMES = [
  { name: "Hot desert", color: "#fbe79f" },
  { name: "Cold desert", color: "#b5b887" },
  { name: "Savanna", color: "#d2d082" },
  { name: "Grassland", color: "#c8d68f" },
  { name: "Tropical seasonal forest", color: "#b6d95d" },
  { name: "Temperate deciduous forest", color: "#29bc56" },
  { name: "Tropical rainforest", color: "#7dcb35" },
  { name: "Temperate rainforest", color: "#409c43" },
  { name: "Taiga", color: "#4b6b32" },
  { name: "Tundra", color: "#96784b" },
  { name: "Glacier", color: "#d5e7eb" },
  { name: "Wetland", color: "#0b9131" }
];
