// Empire-era gazetteer (Early Empire -> Golden Millennia, ~7160 BR - ~1852 AR).
// Extracted from the Azgaar SVG "Bela 2026-08-23-23-09"; coordinates are atlas pixels (SVG x5).
// Names taken verbatim from the SVG label text; countries assigned by point-in-polygon of state borders.
// cat: region | capital | city | town | water | river | island | forest | territory | landmark

const PLACES_EMPIRE = [
  { n: "Aoim", cat: "region", x: 4826, y: 1655, k: "The Caporiolan Kingdom", d: "A region in the Caporiolan Kingdom." },
  { n: "Aserag", cat: "region", x: 2513, y: 2211, k: "Lingia", d: "A region in Lingia." },
  { n: "Baest", cat: "region", x: 2918, y: 1897, k: "Lingia", d: "A region in Lingia." },
  { n: "Bavienna", cat: "region", x: 4170, y: 2201, k: "The Caporiolan Kingdom", d: "A region in the Caporiolan Kingdom." },
  { n: "Caduto", cat: "region", x: 6594, y: 1569, k: "Theolisseia", d: "A region in Theolisseia." },
  { n: "Feacen", cat: "region", x: 2913, y: 2425, k: "Lingia", d: "A region in Lingia." },
  { n: "Halkere", cat: "region", x: 2458, y: 1983, k: "The Tanan Grand Duchy", d: "A region in the Tanan Grand Duchy." },
  { n: "Hikai", cat: "region", x: 4228, y: 982, k: "Hikai", d: "Formerly the kingdom of Coelum, the bankrupt 'Forsaken Land'. Capital: Osenki." },
  { n: "Lingia", cat: "region", x: 3010, y: 2222, k: "Lingia", d: "Formerly the kingdom of Pireaynea, its warlord anarchy subdued by imperial troops. Capital: Haleret." },
  { n: "Lower Cosar", cat: "region", x: 3807, y: 2378, k: "The Caporiolan Kingdom", d: "A region in the Caporiolan Kingdom." },
  { n: "The Aoner", cat: "region", x: 2001, y: 1847, k: "The Tanan Grand Duchy", d: "A region in the Tanan Grand Duchy." },
  { n: "The Caporiolan Kingdom", cat: "region", x: 4111, y: 1854, k: "The Caporiolan Kingdom", d: "Formerly the kingdom of Gherci; the theocratic heartland and seat of the Solisian Empire. Capital: Baviet." },
  { n: "The Senagai", cat: "region", x: 1615, y: 2236, k: "The Tanan Grand Duchy", d: "A region in the Tanan Grand Duchy." },
  { n: "The Tanan Grand Duchy", cat: "region", x: 2190, y: 1923, k: "The Tanan Grand Duchy", d: "Formerly the kingdom of Aicruae, the western breadbasket. One of the great powers of the Early Empire. Capital: Lajazer." },
  { n: "The Uxridian Grand Duchy", cat: "region", x: 6475, y: 1216, k: "The Uxridian Grand Duchy", d: "Formerly the kingdom of Equateiy, the wealthy banking oligarchy that joined the empire by treaty. Capital: Ociyaran." },
  { n: "Theolisseia", cat: "region", x: 5950, y: 1893, k: "Theolisseia", d: "Formerly the kingdom of Vikitsv, the mountain magocracy of Mount Aicren. Capital: Hadirel." },
  { n: "Urdey", cat: "region", x: 3382, y: 2104, k: "Lingia", d: "A region in Lingia." },
  { n: "Baviet", cat: "capital", x: 4130, y: 2087, k: "The Caporiolan Kingdom", d: "Capital of the Caporiolan Kingdom." },
  { n: "Hadirel", cat: "capital", x: 6790, y: 2348, k: "Theolisseia", d: "Capital of Theolisseia." },
  { n: "Haleret", cat: "capital", x: 3160, y: 2468, k: "Lingia", d: "Capital of Lingia." },
  { n: "Lajazer", cat: "capital", x: 2262, y: 1836, k: "The Tanan Grand Duchy", d: "Capital of the Tanan Grand Duchy." },
  { n: "Ociyaran", cat: "capital", x: 6593, y: 1313, k: "The Uxridian Grand Duchy", d: "Capital of the Uxridian Grand Duchy." },
  { n: "Osenki", cat: "capital", x: 3918, y: 763, k: "Hikai", d: "Capital of Hikai." },
  { n: "Port Absey", cat: "city", x: 3614, y: 2616, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 600 mi southwest of Baviet, near Durk and Acin." },
  { n: "Port Aresca", cat: "city", x: 3196, y: 871, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 1225 mi northwest of Baviet, near Corocco and Etanda." },
  { n: "Port Esserey", cat: "city", x: 2627, y: 1113, k: "The Tanan Grand Duchy", d: "In the Tanan Grand Duchy, about 650 mi northeast of Lajazer, near Linjet and Kunes." },
  { n: "Port Linnos", cat: "city", x: 4916, y: 2894, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 900 mi southeast of Baviet, near Mireb and Dordbin." },
  { n: "Port Naole", cat: "city", x: 1777, y: 2048, k: "The Tanan Grand Duchy", d: "In the Tanan Grand Duchy, about 425 mi southwest of Lajazer, near Ostoke and Hepen." },
  { n: "Port Ols", cat: "city", x: 2596, y: 2764, k: "Lingia", d: "In Lingia, about 500 mi southwest of Haleret, near Thya and Hulber." },
  { n: "Port Pontes", cat: "city", x: 3996, y: 2776, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 550 mi south of Baviet, near Acin and Pondata." },
  { n: "Port Qual", cat: "city", x: 1852, y: 2224, k: "The Tanan Grand Duchy", d: "In the Tanan Grand Duchy, about 450 mi southwest of Lajazer, near Tericaer and Teyet." },
  { n: "Port Rebadeen", cat: "city", x: 4530, y: 134, k: "Hikai", d: "In Hikai, about 700 mi northeast of Osenki, near Niarn and Ricna." },
  { n: "Port Sael", cat: "city", x: 7214, y: 2772, k: "Theolisseia", d: "In Theolisseia, about 475 mi southeast of Hadirel, near Qunag and Caelmu." },
  { n: "Port Theli", cat: "city", x: 3656, y: 899, k: "Hikai", d: "In Hikai, about 225 mi southwest of Osenki, near Eskol and Neaea." },
  { n: "Port Vente", cat: "city", x: 2365, y: 1217, k: "The Tanan Grand Duchy", d: "In the Tanan Grand Duchy, about 500 mi north of Lajazer, near Sretan and Weca." },
  { n: "Port Vessar", cat: "city", x: 2901, y: 1111, k: "The Tanan Grand Duchy", d: "In the Tanan Grand Duchy, about 775 mi northeast of Lajazer, near Raiye and Linjet." },
  { n: "Port Volpa", cat: "city", x: 6506, y: 898, k: "The Uxridian Grand Duchy", d: "In the Uxridian Grand Duchy, about 350 mi north of Ociyaran, near Foce and Querceta." },
  { n: "Aanye", cat: "town", x: 4621, y: 2322, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 425 mi southeast of Baviet, near Saltea and Yvenna." },
  { n: "Acin", cat: "town", x: 3918, y: 2624, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 450 mi south of Baviet, near Pondata and Riedra." },
  { n: "Adaani", cat: "town", x: 3916, y: 1409, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 575 mi north of Baviet, near Durisea and Gondes." },
  { n: "Alben", cat: "town", x: 2348, y: 1562, k: "The Tanan Grand Duchy", d: "In the Tanan Grand Duchy, about 225 mi north of Lajazer, near Belei and Hashren." },
  { n: "Allisto", cat: "town", x: 5585, y: 2111, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 1150 mi east of Baviet, near Bralk and Aspardo." },
  { n: "Alpena", cat: "town", x: 6872, y: 995, k: "The Uxridian Grand Duchy", d: "In the Uxridian Grand Duchy, about 325 mi northeast of Ociyaran, near Muralto and Chiavanto." },
  { n: "Alsea", cat: "town", x: 3396, y: 1739, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 650 mi northwest of Baviet, near Oradi and Drenia." },
  { n: "Aluun", cat: "town", x: 4128, y: 1554, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 425 mi north of Baviet, near Inke and Malea." },
  { n: "Amba", cat: "town", x: 5454, y: 2638, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 1150 mi southeast of Baviet, near Selvet and Hagiore." },
  { n: "Amberactserun", cat: "town", x: 5142, y: 1584, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 900 mi northeast of Baviet, near Hagiora and Semhol." },
  { n: "Amesa", cat: "town", x: 4822, y: 2038, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 550 mi east of Baviet, near Avaani and Menejela." },
  { n: "Anaan", cat: "town", x: 3019, y: 1339, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 1075 mi northwest of Baviet, near Tophercris and Rachia." },
  { n: "Anjelea", cat: "town", x: 3901, y: 2374, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 300 mi southwest of Baviet, near Tarl and Riedra." },
  { n: "Annagi", cat: "town", x: 2721, y: 1495, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 1225 mi northwest of Baviet, near Noraho and Liviao." },
  { n: "Anthela", cat: "town", x: 5251, y: 1755, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 925 mi east of Baviet, near Bellaria and Medhuk." },
  { n: "Anye", cat: "town", x: 4294, y: 2548, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 400 mi south of Baviet, near Pelea and Druun." },
  { n: "Apric", cat: "town", x: 2838, y: 1682, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 1075 mi west of Baviet, near Noju and Thevia." },
  { n: "Arona", cat: "town", x: 6727, y: 1134, k: "The Uxridian Grand Duchy", d: "In the Uxridian Grand Duchy, about 175 mi northeast of Ociyaran, near Doresi and Claieso." },
  { n: "Aseri Minqa", cat: "town", x: 2313, y: 1841, k: "The Tanan Grand Duchy", d: "In the Tanan Grand Duchy, about 40 mi east of Lajazer, near Lajazer and Orcan." },
  { n: "Aseri Oshana", cat: "town", x: 2161, y: 1850, k: "The Tanan Grand Duchy", d: "In the Tanan Grand Duchy, about 80 mi west of Lajazer, near Macerin and Lajazer." },
  { n: "Asmeta", cat: "town", x: 4053, y: 2010, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 90 mi northwest of Baviet, near Lendara and Baviet." },
  { n: "Aspardo", cat: "town", x: 5521, y: 2034, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 1100 mi east of Baviet, near Vagust and Allisto." },
  { n: "Atanie", cat: "town", x: 2155, y: 1592, k: "The Tanan Grand Duchy", d: "In the Tanan Grand Duchy, about 200 mi northwest of Lajazer, near Sarleiane and Tericaer." },
  { n: "Audine", cat: "town", x: 1990, y: 2342, k: "The Tanan Grand Duchy", d: "In the Tanan Grand Duchy, about 450 mi southwest of Lajazer, near Barete and Port Qual." },
  { n: "Avaani", cat: "town", x: 4712, y: 1960, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 475 mi east of Baviet, near Inem and Amesa." },
  { n: "Avege", cat: "town", x: 2277, y: 1965, k: "The Tanan Grand Duchy", d: "In the Tanan Grand Duchy, about 100 mi south of Lajazer, near Comei and Orcan." },
  { n: "Awq Tari", cat: "town", x: 3042, y: 2036, k: "Lingia", d: "In Lingia, about 350 mi north of Haleret, near Rosk and Jurva." },
  { n: "Baram", cat: "town", x: 2728, y: 1250, k: "The Tanan Grand Duchy", d: "In the Tanan Grand Duchy, about 600 mi northeast of Lajazer, near Palere and Linjet." },
  { n: "Barete", cat: "town", x: 1993, y: 2172, k: "The Tanan Grand Duchy", d: "In the Tanan Grand Duchy, about 350 mi southwest of Lajazer, near Liasen and Loer." },
  { n: "Basar Tari", cat: "town", x: 2164, y: 2629, k: "The Tanan Grand Duchy", d: "In the Tanan Grand Duchy, about 625 mi south of Lajazer, near Laone and Thya." },
  { n: "Bayen", cat: "town", x: 3894, y: 1838, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 275 mi northwest of Baviet, near Tereas and Tarmet." },
  { n: "Belei", cat: "town", x: 2308, y: 1512, k: "The Tanan Grand Duchy", d: "In the Tanan Grand Duchy, about 250 mi north of Lajazer, near Fordei and Alben." },
  { n: "Bellaria", cat: "town", x: 5270, y: 1706, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 950 mi east of Baviet, near Anthela and Norabea." },
  { n: "Belnara", cat: "town", x: 4979, y: 1741, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 725 mi east of Baviet, near Semhol and Kidaris." },
  { n: "Belune", cat: "town", x: 3844, y: 1619, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 425 mi northwest of Baviet, near The Seimaa and Malea." },
  { n: "Benale", cat: "town", x: 2475, y: 2051, k: "The Tanan Grand Duchy", d: "In the Tanan Grand Duchy, about 250 mi southeast of Lajazer, near Cesro and Jani." },
  { n: "Bion", cat: "town", x: 2513, y: 1252, k: "The Tanan Grand Duchy", d: "In the Tanan Grand Duchy, about 500 mi northeast of Lajazer, near Weca and Birme." },
  { n: "Birme", cat: "town", x: 2553, y: 1343, k: "The Tanan Grand Duchy", d: "In the Tanan Grand Duchy, about 450 mi northeast of Lajazer, near Bion and Kunes." },
  { n: "Bohan", cat: "town", x: 6006, y: 2882, k: "Theolisseia", d: "In Theolisseia, about 750 mi southwest of Hadirel, near Ompol and Gilsa." },
  { n: "Boletre  Begai", cat: "town", x: 2035, y: 2013, k: "The Tanan Grand Duchy", d: "In the Tanan Grand Duchy, about 225 mi southwest of Lajazer, near The Aonesse and Leyone." },
  { n: "Borgeste", cat: "town", x: 2371, y: 1348, k: "The Tanan Grand Duchy", d: "In the Tanan Grand Duchy, about 400 mi north of Lajazer, near Sretan and Lermea." },
  { n: "Brae", cat: "town", x: 6058, y: 1232, k: "The Uxridian Grand Duchy", d: "In the Uxridian Grand Duchy, about 425 mi west of Ociyaran, near Oa and Stagna." },
  { n: "Bralk", cat: "town", x: 5609, y: 2160, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 1175 mi east of Baviet, near Allisto and Dugwil." },
  { n: "Brannik", cat: "town", x: 3337, y: 2490, k: "Lingia", d: "In Lingia, about 150 mi east of Haleret, near Gorst and Civer." },
  { n: "Breno", cat: "town", x: 6149, y: 1138, k: "The Uxridian Grand Duchy", d: "In the Uxridian Grand Duchy, about 375 mi west of Ociyaran, near Lidresa and Lun." },
  { n: "Brentola", cat: "town", x: 6735, y: 1367, k: "The Uxridian Grand Duchy", d: "In the Uxridian Grand Duchy, about 125 mi east of Ociyaran, near Pell'oro and Dragse." },
  { n: "Breston", cat: "town", x: 2539, y: 1679, k: "The Tanan Grand Duchy", d: "In the Tanan Grand Duchy, about 250 mi northeast of Lajazer, near Casqen Zaeri and Meliut." },
  { n: "Brielega", cat: "town", x: 3514, y: 1278, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 800 mi northwest of Baviet, near Coloni and Egodi." },
  { n: "Burane", cat: "town", x: 6858, y: 1208, k: "The Uxridian Grand Duchy", d: "In the Uxridian Grand Duchy, about 225 mi east of Ociyaran, near Mira and Squero." },
  { n: "Byeola", cat: "town", x: 6550, y: 2379, k: "Theolisseia", d: "In Theolisseia, about 200 mi west of Hadirel, near Sehrok and Sahlen." },
  { n: "Caelmu", cat: "town", x: 7247, y: 3068, k: "Theolisseia", d: "In Theolisseia, about 675 mi southeast of Hadirel, near Orjin and Port Sael." },
  { n: "Cala", cat: "town", x: 6294, y: 921, k: "The Uxridian Grand Duchy", d: "In the Uxridian Grand Duchy, about 400 mi northwest of Ociyaran, near Senna and Senalda." },
  { n: "Cale", cat: "town", x: 1888, y: 1900, k: "The Tanan Grand Duchy", d: "In the Tanan Grand Duchy, about 300 mi west of Lajazer, near Matsene and Dushre." },
  { n: "Calyea", cat: "town", x: 4432, y: 2110, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 250 mi east of Baviet, near Thelea and Mother's hip." },
  { n: "Camrudar", cat: "town", x: 4445, y: 1201, k: "Hikai", d: "In Hikai, about 550 mi southeast of Osenki, near Inqua and Ridal." },
  { n: "Cardoric", cat: "town", x: 3396, y: 1451, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 775 mi northwest of Baviet, near Egodi and Lujian." },
  { n: "Caspara", cat: "town", x: 4035, y: 2305, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 200 mi southwest of Baviet, near Granosa and Anjelea." },
  { n: "Casqen Zaeri", cat: "town", x: 2534, y: 1722, k: "The Tanan Grand Duchy", d: "In the Tanan Grand Duchy, about 225 mi northeast of Lajazer, near Breston and Zagare." },
  { n: "Cerby", cat: "town", x: 3755, y: 2024, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 300 mi west of Baviet, near Zerpe and Keba." },
  { n: "Cesro", cat: "town", x: 2380, y: 2119, k: "The Tanan Grand Duchy", d: "In the Tanan Grand Duchy, about 250 mi southeast of Lajazer, near Jani and Benale." },
  { n: "Chiavanto", cat: "town", x: 6949, y: 1049, k: "The Uxridian Grand Duchy", d: "In the Uxridian Grand Duchy, about 350 mi northeast of Ociyaran, near Riy and Ys." },
  { n: "Chiozza", cat: "town", x: 6819, y: 808, k: "The Uxridian Grand Duchy", d: "In the Uxridian Grand Duchy, about 450 mi northeast of Ociyaran, near Tesora and Latso." },
  { n: "Cira", cat: "town", x: 6265, y: 1260, k: "The Uxridian Grand Duchy", d: "In the Uxridian Grand Duchy, about 275 mi west of Ociyaran, near Roi and Cresp." },
  { n: "Civer", cat: "town", x: 3231, y: 2496, k: "Lingia", d: "In Lingia, about 60 mi east of Haleret, near Haleret and Dessane." },
  { n: "Claieso", cat: "town", x: 6749, y: 1243, k: "The Uxridian Grand Duchy", d: "In the Uxridian Grand Duchy, about 125 mi northeast of Ociyaran, near Dragse and Arona." },
  { n: "Coelys", cat: "town", x: 3120, y: 1601, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 900 mi northwest of Baviet, near Mema and Ezon." },
  { n: "Colle", cat: "town", x: 6950, y: 1175, k: "The Uxridian Grand Duchy", d: "In the Uxridian Grand Duchy, about 300 mi east of Ociyaran, near Squero and Mira." },
  { n: "Coloni", cat: "town", x: 3497, y: 1183, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 875 mi northwest of Baviet, near Seppegiu and Tropie." },
  { n: "Comei", cat: "town", x: 2265, y: 2011, k: "The Tanan Grand Duchy", d: "In the Tanan Grand Duchy, about 150 mi south of Lajazer, near Avege and Mepren." },
  { n: "Corocco", cat: "town", x: 3271, y: 957, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 1125 mi northwest of Baviet, near Port Aresca and Neaea." },
  { n: "Corsa", cat: "town", x: 6416, y: 1118, k: "The Uxridian Grand Duchy", d: "In the Uxridian Grand Duchy, about 200 mi northwest of Ociyaran, near Gora and Vigila." },
  { n: "Corvane", cat: "town", x: 2978, y: 1767, k: "Lingia", d: "In Lingia, about 575 mi north of Haleret, near Apric and Thevia." },
  { n: "Cosar", cat: "town", x: 3757, y: 2229, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 325 mi west of Baviet, near Tarl and Golana." },
  { n: "Cresp", cat: "town", x: 6341, y: 1327, k: "The Uxridian Grand Duchy", d: "In the Uxridian Grand Duchy, about 200 mi west of Ociyaran, near Rewalen and Nelva." },
  { n: "Croco", cat: "town", x: 3207, y: 1735, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 800 mi west of Baviet, near Maadol and Ezon." },
  { n: "Cuola", cat: "town", x: 4295, y: 1807, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 250 mi northeast of Baviet, near Lokea and Teirenna." },
  { n: "Cymea", cat: "town", x: 3959, y: 1512, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 475 mi north of Baviet, near Malea and Adaani." },
  { n: "Dahn", cat: "town", x: 5625, y: 2365, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 1225 mi east of Baviet, near Sevq and Hauk." },
  { n: "Daltsen", cat: "town", x: 6601, y: 2224, k: "Theolisseia", d: "In Theolisseia, about 175 mi northwest of Hadirel, near Sehrok and Byeola." },
  { n: "Demia", cat: "town", x: 4981, y: 2505, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 750 mi southeast of Baviet, near Gai and Mireb." },
  { n: "Demre", cat: "town", x: 5300, y: 2653, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 1025 mi southeast of Baviet, near Limn and Amba." },
  { n: "Denkay", cat: "town", x: 5389, y: 2041, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 1000 mi east of Baviet, near Vagust and Rudeth." },
  { n: "Dessane", cat: "town", x: 3174, y: 2582, k: "Lingia", d: "In Lingia, about 90 mi south of Haleret, near Civer and Haleret." },
  { n: "Deyare", cat: "town", x: 2108, y: 1730, k: "The Tanan Grand Duchy", d: "In the Tanan Grand Duchy, about 150 mi northwest of Lajazer, near Macerin and Neribe." },
  { n: "Dira", cat: "town", x: 1944, y: 1975, k: "The Tanan Grand Duchy", d: "In the Tanan Grand Duchy, about 275 mi southwest of Lajazer, near Melerte and Leyone." },
  { n: "Doka", cat: "town", x: 3884, y: 2135, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 200 mi west of Baviet, near Keba and Granosa." },
  { n: "Dordbin", cat: "town", x: 5183, y: 2832, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 1025 mi southeast of Baviet, near Limn and Mireb." },
  { n: "Doresi", cat: "town", x: 6685, y: 1054, k: "The Uxridian Grand Duchy", d: "In the Uxridian Grand Duchy, about 225 mi north of Ociyaran, near Vinalta and Neska." },
  { n: "Dragse", cat: "town", x: 6788, y: 1283, k: "The Uxridian Grand Duchy", d: "In the Uxridian Grand Duchy, about 150 mi east of Ociyaran, near Claieso and Brentola." },
  { n: "Drav Tari", cat: "town", x: 2680, y: 2029, k: "The Tanan Grand Duchy", d: "In the Tanan Grand Duchy, about 375 mi southeast of Lajazer, near Hoab and Lorig." },
  { n: "Dremk", cat: "town", x: 5225, y: 2077, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 875 mi east of Baviet, near Tusjin and Tsir." },
  { n: "Drenia", cat: "town", x: 3398, y: 1609, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 700 mi northwest of Baviet, near Lujian and Oscana." },
  { n: "Drin", cat: "town", x: 3409, y: 2170, k: "Lingia", d: "In Lingia, about 300 mi northeast of Haleret, near Pelk and The Brack." },
  { n: "Drosk", cat: "town", x: 3024, y: 2457, k: "Lingia", d: "In Lingia, about 100 mi west of Haleret, near Sindber and Tolm." },
  { n: "Druun", cat: "town", x: 4450, y: 2622, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 500 mi southeast of Baviet, near Eskua and Anye." },
  { n: "Dugwil", cat: "town", x: 5511, y: 2201, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 1100 mi east of Baviet, near Bralk and Allisto." },
  { n: "Durisea", cat: "town", x: 3849, y: 1362, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 625 mi north of Baviet, near Gondes and Adaani." },
  { n: "Durk", cat: "town", x: 3470, y: 2389, k: "Lingia", d: "In Lingia, about 250 mi east of Haleret, near The Pontesi and Gorst." },
  { n: "Dushre", cat: "town", x: 1895, y: 1825, k: "The Tanan Grand Duchy", d: "In the Tanan Grand Duchy, about 300 mi west of Lajazer, near Lene and Cale." },
  { n: "Egodi", cat: "town", x: 3447, y: 1369, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 800 mi northwest of Baviet, near Cardoric and Eloe." },
  { n: "Elemea", cat: "town", x: 4458, y: 1753, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 375 mi northeast of Baviet, near Vashonna and Ralta." },
  { n: "Eloe", cat: "town", x: 3348, y: 1344, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 850 mi northwest of Baviet, near Gelona and Egodi." },
  { n: "Erygal", cat: "town", x: 3986, y: 944, k: "Hikai", d: "In Hikai, about 150 mi south of Osenki, near Eskol and Osenki." },
  { n: "Eryte", cat: "town", x: 4014, y: 532, k: "Hikai", d: "In Hikai, about 200 mi northeast of Osenki, near Yleka and Nisclair." },
  { n: "Eshae", cat: "town", x: 2230, y: 1552, k: "The Tanan Grand Duchy", d: "In the Tanan Grand Duchy, about 225 mi north of Lajazer, near Sarleiane and Hashren." },
  { n: "Esio", cat: "town", x: 6588, y: 1123, k: "The Uxridian Grand Duchy", d: "In the Uxridian Grand Duchy, about 150 mi north of Ociyaran, near Neska and Gabbia." },
  { n: "Eskert", cat: "town", x: 4607, y: 718, k: "Hikai", d: "In Hikai, about 550 mi east of Osenki, near Riyen and Noramec." },
  { n: "Eskol", cat: "town", x: 3889, y: 869, k: "Hikai", d: "In Hikai, about 90 mi south of Osenki, near Osenki and Erygal." },
  { n: "Eskua", cat: "town", x: 4446, y: 2735, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 575 mi southeast of Baviet, near Druun and Oskaba." },
  { n: "Etanda", cat: "town", x: 3114, y: 1013, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 1175 mi northwest of Baviet, near Osegri and Port Aresca." },
  { n: "Eynora", cat: "town", x: 3555, y: 100, k: "Hikai", d: "In Hikai, about 600 mi northwest of Osenki, near Lagora and Tilnyeau." },
  { n: "Ezon", cat: "town", x: 3274, y: 1601, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 775 mi northwest of Baviet, near Lasten and Lujian." },
  { n: "Fayede", cat: "town", x: 1968, y: 1762, k: "The Tanan Grand Duchy", d: "In the Tanan Grand Duchy, about 250 mi west of Lajazer, near Lene and Hadber." },
  { n: "Foce", cat: "town", x: 6455, y: 975, k: "The Uxridian Grand Duchy", d: "In the Uxridian Grand Duchy, about 300 mi north of Ociyaran, near Malamo and Port Volpa." },
  { n: "Fordei", cat: "town", x: 2310, y: 1459, k: "The Tanan Grand Duchy", d: "In the Tanan Grand Duchy, about 300 mi north of Lajazer, near Belei and Lermea." },
  { n: "Forea", cat: "town", x: 4090, y: 2467, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 300 mi south of Baviet, near Pondata and Riedra." },
  { n: "Gabbia", cat: "town", x: 6497, y: 1087, k: "The Uxridian Grand Duchy", d: "In the Uxridian Grand Duchy, about 200 mi northwest of Ociyaran, near Malamo and Vigila." },
  { n: "Gaedu", cat: "town", x: 6877, y: 2529, k: "Theolisseia", d: "In Theolisseia, about 150 mi southeast of Hadirel, near Yula and Sahla." },
  { n: "Gai", cat: "town", x: 5148, y: 2529, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 875 mi southeast of Baviet, near Hagia Demre and Demia." },
  { n: "Galmun", cat: "town", x: 6580, y: 2633, k: "Theolisseia", d: "In Theolisseia, about 275 mi southwest of Hadirel, near Junjeo and Torad." },
  { n: "Garen", cat: "town", x: 4638, y: 1514, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 600 mi northeast of Baviet, near Oryur and Nyedal." },
  { n: "Gelona", cat: "town", x: 3309, y: 1278, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 925 mi northwest of Baviet, near Tenda and Eloe." },
  { n: "Genga", cat: "town", x: 2666, y: 1689, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 1200 mi west of Baviet, near Resate and Tellas." },
  { n: "Giagior", cat: "town", x: 2902, y: 1448, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 1100 mi northwest of Baviet, near Tagre and Iaga." },
  { n: "Gilsa", cat: "town", x: 5713, y: 2969, k: "Theolisseia", d: "In Theolisseia, about 1000 mi southwest of Hadirel, near Maryos and Bohan." },
  { n: "Gjen", cat: "town", x: 6893, y: 2944, k: "Theolisseia", d: "In Theolisseia, about 475 mi south of Hadirel, near Qunag and Namilna." },
  { n: "Gogla", cat: "town", x: 7018, y: 2118, k: "Theolisseia", d: "In Theolisseia, about 250 mi northeast of Hadirel, near Negiet and Hadirel." },
  { n: "Golana", cat: "town", x: 3646, y: 2152, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 400 mi west of Baviet, near Cosar and Lage." },
  { n: "Gondes", cat: "town", x: 3866, y: 1310, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 650 mi north of Baviet, near Durisea and The Duriaan." },
  { n: "Gora", cat: "town", x: 6372, y: 1170, k: "The Uxridian Grand Duchy", d: "In the Uxridian Grand Duchy, about 200 mi northwest of Ociyaran, near Corsa and Nelva." },
  { n: "Gorma", cat: "town", x: 4461, y: 520, k: "Hikai", d: "In Hikai, about 475 mi northeast of Osenki, near Ortuqil and Ricna." },
  { n: "Gorst", cat: "town", x: 3337, y: 2412, k: "Lingia", d: "In Lingia, about 150 mi east of Haleret, near Brannik and Durk." },
  { n: "Goteivane", cat: "town", x: 2289, y: 2275, k: "The Tanan Grand Duchy", d: "In the Tanan Grand Duchy, about 350 mi south of Lajazer, near The Santie and Ledesca." },
  { n: "Granosa", cat: "town", x: 3960, y: 2221, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 175 mi southwest of Baviet, near Tarl and Caspara." },
  { n: "Grotta", cat: "town", x: 6174, y: 1546, k: "The Uxridian Grand Duchy", d: "In the Uxridian Grand Duchy, about 375 mi southwest of Ociyaran, near Pratesi and Ravia." },
  { n: "Hadber", cat: "town", x: 2029, y: 1701, k: "The Tanan Grand Duchy", d: "In the Tanan Grand Duchy, about 225 mi northwest of Lajazer, near Tericaer and Deyare." },
  { n: "Hagia Demre", cat: "town", x: 5211, y: 2425, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 900 mi east of Baviet, near Gai and Tsir." },
  { n: "Hagiora", cat: "town", x: 5080, y: 1457, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 900 mi northeast of Baviet, near Amberactserun and Semhol." },
  { n: "Hagiore", cat: "town", x: 5539, y: 2512, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 1175 mi east of Baviet, near Amba and Dahn." },
  { n: "Hagn", cat: "town", x: 5408, y: 2287, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 1025 mi east of Baviet, near Hauk and Dugwil." },
  { n: "Hanora", cat: "town", x: 6986, y: 1645, k: "Theolisseia", d: "In Theolisseia, about 575 mi north of Hadirel, near Tsenmar and Kanghol." },
  { n: "Hashren", cat: "town", x: 2290, y: 1610, k: "The Tanan Grand Duchy", d: "In the Tanan Grand Duchy, about 175 mi north of Lajazer, near Verne and Alben." },
  { n: "Hauk", cat: "town", x: 5532, y: 2329, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 1125 mi east of Baviet, near Sevq and Dahn." },
  { n: "Hepen", cat: "town", x: 1851, y: 2066, k: "The Tanan Grand Duchy", d: "In the Tanan Grand Duchy, about 375 mi southwest of Lajazer, near Ostoke and Melerte." },
  { n: "Heusel", cat: "town", x: 1987, y: 1886, k: "The Tanan Grand Duchy", d: "In the Tanan Grand Duchy, about 225 mi west of Lajazer, near Lene and Leyone." },
  { n: "Hevetane", cat: "town", x: 4333, y: 2274, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 225 mi southeast of Baviet, near Orim and Nordos." },
  { n: "Hoab", cat: "town", x: 2773, y: 2125, k: "The Tanan Grand Duchy", d: "In the Tanan Grand Duchy, about 475 mi southeast of Lajazer, near Drav Tari and Lorig." },
  { n: "Hoam", cat: "town", x: 4280, y: 1581, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 425 mi north of Baviet, near Lokea and Aluun." },
  { n: "Holve", cat: "town", x: 2426, y: 1502, k: "The Tanan Grand Duchy", d: "In the Tanan Grand Duchy, about 300 mi northeast of Lajazer, near Isece and Melerb." },
  { n: "Honet", cat: "town", x: 2145, y: 2213, k: "The Tanan Grand Duchy", d: "In the Tanan Grand Duchy, about 325 mi south of Lajazer, near Loer and Nayen." },
  { n: "Hulber", cat: "town", x: 2718, y: 2490, k: "Lingia", d: "In Lingia, about 350 mi west of Haleret, near Welk and Old Feacen." },
  { n: "Iaga", cat: "town", x: 2855, y: 1540, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 1100 mi northwest of Baviet, near Thevia and Lanmi." },
  { n: "Iela", cat: "town", x: 4689, y: 1741, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 525 mi northeast of Baviet, near Laaya and Luja." },
  { n: "Ilkai", cat: "town", x: 4537, y: 1004, k: "Hikai", d: "In Hikai, about 525 mi east of Osenki, near Ridal and Nalochl." },
  { n: "Ilkane", cat: "town", x: 4352, y: 760, k: "Hikai", d: "In Hikai, about 350 mi east of Osenki, near Maharg and Ortuqil." },
  { n: "Ilvo", cat: "town", x: 6155, y: 1323, k: "The Uxridian Grand Duchy", d: "In the Uxridian Grand Duchy, about 350 mi west of Ociyaran, near Stagna and Movo." },
  { n: "Inem", cat: "town", x: 4766, y: 1868, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 525 mi east of Baviet, near Avaani and Luja." },
  { n: "Inke", cat: "town", x: 4132, y: 1474, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 500 mi north of Baviet, near Aluun and Resia." },
  { n: "Inqua", cat: "town", x: 4414, y: 1322, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 650 mi north of Baviet, near Camrudar and Oryur." },
  { n: "Isece", cat: "town", x: 2456, y: 1549, k: "The Tanan Grand Duchy", d: "In the Tanan Grand Duchy, about 275 mi northeast of Lajazer, near Wisten and Holve." },
  { n: "Itara", cat: "town", x: 2167, y: 1487, k: "The Tanan Grand Duchy", d: "In the Tanan Grand Duchy, about 300 mi north of Lajazer, near Eshae and Atanie." },
  { n: "Jani", cat: "town", x: 2342, y: 2049, k: "The Tanan Grand Duchy", d: "In the Tanan Grand Duchy, about 175 mi south of Lajazer, near Cesro and Comei." },
  { n: "Jaserey", cat: "town", x: 2284, y: 1695, k: "The Tanan Grand Duchy", d: "In the Tanan Grand Duchy, about 125 mi north of Lajazer, near Verne and Nyeo." },
  { n: "Jhera", cat: "town", x: 6747, y: 920, k: "The Uxridian Grand Duchy", d: "In the Uxridian Grand Duchy, about 325 mi north of Ociyaran, near Vinalta and Latso." },
  { n: "Jiego", cat: "town", x: 2396, y: 1868, k: "The Tanan Grand Duchy", d: "In the Tanan Grand Duchy, about 100 mi east of Lajazer, near Rewqo and Aseri Minqa." },
  { n: "Junjeo", cat: "town", x: 6622, y: 2705, k: "Theolisseia", d: "In Theolisseia, about 325 mi southwest of Hadirel, near Galmun and Liaerton." },
  { n: "Jurva", cat: "town", x: 3157, y: 2090, k: "Lingia", d: "In Lingia, about 300 mi north of Haleret, near Awq Tari and Rosk." },
  { n: "Kanghol", cat: "town", x: 6980, y: 1317, k: "Theolisseia", d: "In Theolisseia, about 825 mi north of Hadirel, near Mira and Colle." },
  { n: "Kanidon", cat: "town", x: 2554, y: 1525, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 1325 mi west of Baviet, near Vaia and Meliut." },
  { n: "Keba", cat: "town", x: 3895, y: 2048, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 200 mi west of Baviet, near Tereas and Doka." },
  { n: "Kessa", cat: "town", x: 3712, y: 1774, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 425 mi northwest of Baviet, near Zerpe and Olune." },
  { n: "Kidaris", cat: "town", x: 5106, y: 1814, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 800 mi east of Baviet, near Semhol and Medhuk." },
  { n: "Kuldara", cat: "town", x: 4255, y: 2749, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 525 mi south of Baviet, near Eskua and Anye." },
  { n: "Kunes", cat: "town", x: 2637, y: 1254, k: "The Tanan Grand Duchy", d: "In the Tanan Grand Duchy, about 550 mi northeast of Lajazer, near Baram and Palere." },
  { n: "Laaya", cat: "town", x: 4621, y: 1818, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 450 mi northeast of Baviet, near Ristea and Iela." },
  { n: "Lage", cat: "town", x: 3599, y: 2008, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 425 mi west of Baviet, near Zerpe and Shaer." },
  { n: "Lagora", cat: "town", x: 3496, y: 199, k: "Hikai", d: "In Hikai, about 550 mi northwest of Osenki, near Eynora and Tilnyeau." },
  { n: "Lagowyal", cat: "town", x: 4080, y: 1168, k: "Hikai", d: "In Hikai, about 350 mi south of Osenki, near The Maadun and Negel." },
  { n: "Lanmi", cat: "town", x: 2770, y: 1591, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 1150 mi west of Baviet, near Noraho and Noju." },
  { n: "Laone", cat: "town", x: 2271, y: 2394, k: "The Tanan Grand Duchy", d: "In the Tanan Grand Duchy, about 450 mi south of Lajazer, near Meprie Teish and Goteivane." },
  { n: "Larida", cat: "town", x: 6077, y: 1438, k: "The Uxridian Grand Duchy", d: "In the Uxridian Grand Duchy, about 425 mi west of Ociyaran, near Reda and Movo." },
  { n: "Lasten", cat: "town", x: 3263, y: 1506, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 825 mi northwest of Baviet, near Ezon and Lujian." },
  { n: "Latso", cat: "town", x: 6698, y: 820, k: "The Uxridian Grand Duchy", d: "In the Uxridian Grand Duchy, about 400 mi north of Ociyaran, near Pampira and Paro." },
  { n: "Ledea", cat: "town", x: 4985, y: 2102, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 675 mi east of Baviet, near Loria and Oermada." },
  { n: "Ledesca", cat: "town", x: 2384, y: 2248, k: "The Tanan Grand Duchy", d: "In the Tanan Grand Duchy, about 350 mi south of Lajazer, near Goteivane and Cesro." },
  { n: "Lendara", cat: "town", x: 4131, y: 1962, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 100 mi north of Baviet, near Asmeta and Tarmet." },
  { n: "Lene", cat: "town", x: 1946, y: 1811, k: "The Tanan Grand Duchy", d: "In the Tanan Grand Duchy, about 250 mi west of Lajazer, near Dushre and Fayede." },
  { n: "Lermea", cat: "town", x: 2314, y: 1393, k: "The Tanan Grand Duchy", d: "In the Tanan Grand Duchy, about 350 mi north of Lajazer, near Fordei and Borgeste." },
  { n: "Leyone", cat: "town", x: 2036, y: 1960, k: "The Tanan Grand Duchy", d: "In the Tanan Grand Duchy, about 200 mi southwest of Lajazer, near Boletre  Begai and Heusel." },
  { n: "Lezna", cat: "town", x: 6208, y: 1467, k: "The Uxridian Grand Duchy", d: "In the Uxridian Grand Duchy, about 325 mi west of Ociyaran, near Movo and Grotta." },
  { n: "Liaerton", cat: "town", x: 6695, y: 2795, k: "Theolisseia", d: "In Theolisseia, about 375 mi south of Hadirel, near Junjeo and Namilna." },
  { n: "Liasen", cat: "town", x: 2005, y: 2092, k: "The Tanan Grand Duchy", d: "In the Tanan Grand Duchy, about 300 mi southwest of Lajazer, near The Aonesse and Barete." },
  { n: "Lidresa", cat: "town", x: 6196, y: 1054, k: "The Uxridian Grand Duchy", d: "In the Uxridian Grand Duchy, about 375 mi northwest of Ociyaran, near Breno and Vallaforta." },
  { n: "Limn", cat: "town", x: 5330, y: 2784, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 1100 mi southeast of Baviet, near Demre and Dordbin." },
  { n: "Linjet", cat: "town", x: 2734, y: 1168, k: "The Tanan Grand Duchy", d: "In the Tanan Grand Duchy, about 650 mi northeast of Lajazer, near Baram and Port Esserey." },
  { n: "Lioe", cat: "town", x: 3230, y: 1373, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 925 mi northwest of Baviet, near Mossima and Eloe." },
  { n: "Liviao", cat: "town", x: 2718, y: 1403, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 1250 mi northwest of Baviet, near Palere and Annagi." },
  { n: "Loer", cat: "town", x: 2079, y: 2142, k: "The Tanan Grand Duchy", d: "In the Tanan Grand Duchy, about 275 mi southwest of Lajazer, near Liasen and Barete." },
  { n: "Lokea", cat: "town", x: 4266, y: 1715, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 325 mi north of Baviet, near Teirenna and Cuola." },
  { n: "Loria", cat: "town", x: 5039, y: 2181, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 725 mi east of Baviet, near Ledea and Maaru Maaru." },
  { n: "Lorig", cat: "town", x: 2625, y: 2154, k: "Lingia", d: "In Lingia, about 500 mi northwest of Haleret, near Drav Tari and Hoab." },
  { n: "Lovec", cat: "town", x: 2135, y: 1982, k: "The Tanan Grand Duchy", d: "In the Tanan Grand Duchy, about 150 mi southwest of Lajazer, near Leyone and Mepren." },
  { n: "Luja", cat: "town", x: 4818, y: 1762, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 600 mi northeast of Baviet, near Inem and Iela." },
  { n: "Lujian", cat: "town", x: 3377, y: 1549, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 750 mi northwest of Baviet, near Drenia and Cardoric." },
  { n: "Lun", cat: "town", x: 6272, y: 1129, k: "The Uxridian Grand Duchy", d: "In the Uxridian Grand Duchy, about 300 mi northwest of Ociyaran, near Vallaforta and Lidresa." },
  { n: "Maadol", cat: "town", x: 3210, y: 1848, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 750 mi west of Baviet, near Croco and Oradi." },
  { n: "Maaru Maaru", cat: "town", x: 4940, y: 2294, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 675 mi east of Baviet, near Loria and Menejela." },
  { n: "Macerin", cat: "town", x: 2152, y: 1773, k: "The Tanan Grand Duchy", d: "In the Tanan Grand Duchy, about 100 mi northwest of Lajazer, near Deyare and Aseri Oshana." },
  { n: "Madreu", cat: "town", x: 2365, y: 1743, k: "The Tanan Grand Duchy", d: "In the Tanan Grand Duchy, about 100 mi northeast of Lajazer, near Peske and Uedena." },
  { n: "Maharg", cat: "town", x: 4212, y: 706, k: "Hikai", d: "In Hikai, about 250 mi east of Osenki, near Ilkane and Snurb." },
  { n: "Malamo", cat: "town", x: 6473, y: 1032, k: "The Uxridian Grand Duchy", d: "In the Uxridian Grand Duchy, about 250 mi northwest of Ociyaran, near Foce and Gabbia." },
  { n: "Malea", cat: "town", x: 3986, y: 1584, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 425 mi north of Baviet, near Cymea and Ostara." },
  { n: "Malim", cat: "town", x: 4258, y: 1971, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 150 mi northeast of Baviet, near Tarmeda and Mother's hip." },
  { n: "Maryos", cat: "town", x: 5444, y: 2898, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 1225 mi southeast of Baviet, near Limn and Selvet." },
  { n: "Masen", cat: "town", x: 2485, y: 1872, k: "The Tanan Grand Duchy", d: "In the Tanan Grand Duchy, about 175 mi east of Lajazer, near Oahat and Rewqo." },
  { n: "Masotom", cat: "town", x: 3698, y: 1264, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 750 mi northwest of Baviet, near Tiamma and Renzolo." },
  { n: "Matsene", cat: "town", x: 1837, y: 1930, k: "The Tanan Grand Duchy", d: "In the Tanan Grand Duchy, about 350 mi west of Lajazer, near Thalen and Cale." },
  { n: "Medhuk", cat: "town", x: 5211, y: 1854, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 875 mi east of Baviet, near Anthela and Kidaris." },
  { n: "Melerb", cat: "town", x: 2449, y: 1448, k: "The Tanan Grand Duchy", d: "In the Tanan Grand Duchy, about 350 mi northeast of Lajazer, near Holve and Isece." },
  { n: "Melerte", cat: "town", x: 1855, y: 1996, k: "The Tanan Grand Duchy", d: "In the Tanan Grand Duchy, about 350 mi west of Lajazer, near Ostoke and Thalen." },
  { n: "Meliut", cat: "town", x: 2581, y: 1614, k: "The Tanan Grand Duchy", d: "In the Tanan Grand Duchy, about 300 mi northeast of Lajazer, near Breston and Tellas." },
  { n: "Mema", cat: "town", x: 3019, y: 1487, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 1000 mi northwest of Baviet, near Tophercris and Giagior." },
  { n: "Menejela", cat: "town", x: 4841, y: 2172, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 575 mi east of Baviet, near Saltea and Amesa." },
  { n: "Menen", cat: "town", x: 2456, y: 1654, k: "The Tanan Grand Duchy", d: "In the Tanan Grand Duchy, about 200 mi northeast of Lajazer, near Wisten and Uedena." },
  { n: "Mepren", cat: "town", x: 2215, y: 2047, k: "The Tanan Grand Duchy", d: "In the Tanan Grand Duchy, about 175 mi south of Lajazer, near Comei and Nayen." },
  { n: "Meprie Teish", cat: "town", x: 2192, y: 2304, k: "The Tanan Grand Duchy", d: "In the Tanan Grand Duchy, about 375 mi south of Lajazer, near The Santie and Goteivane." },
  { n: "Mira", cat: "town", x: 6919, y: 1233, k: "The Uxridian Grand Duchy", d: "In the Uxridian Grand Duchy, about 275 mi east of Ociyaran, near Colle and Burane." },
  { n: "Mireb", cat: "town", x: 5021, y: 2711, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 875 mi southeast of Baviet, near Dordbin and Demia." },
  { n: "Mossima", cat: "town", x: 3149, y: 1309, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 1000 mi northwest of Baviet, near Lioe and Tophercris." },
  { n: "Mother's hip", cat: "town", x: 4318, y: 2073, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 150 mi east of Baviet, near Tarmeda and Malim." },
  { n: "Movo", cat: "town", x: 6182, y: 1387, k: "The Uxridian Grand Duchy", d: "In the Uxridian Grand Duchy, about 325 mi west of Ociyaran, near Ilvo and Roi." },
  { n: "Muralto", cat: "town", x: 6885, y: 933, k: "The Uxridian Grand Duchy", d: "In the Uxridian Grand Duchy, about 375 mi northeast of Ociyaran, near Alpena and Ys." },
  { n: "Murok", cat: "town", x: 6356, y: 2919, k: "Theolisseia", d: "In Theolisseia, about 575 mi southwest of Hadirel, near Verna Tari and Junjeo." },
  { n: "Murra", cat: "town", x: 6312, y: 1438, k: "The Uxridian Grand Duchy", d: "In the Uxridian Grand Duchy, about 250 mi southwest of Ociyaran, near Rewalen and Velu." },
  { n: "Muuri", cat: "town", x: 4951, y: 1917, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 675 mi east of Baviet, near Oermada and Amesa." },
  { n: "Nabuchan", cat: "town", x: 4791, y: 1059, k: "Hikai", d: "In Hikai, about 725 mi east of Osenki, near Sebrof and Ridal." },
  { n: "Nalchal", cat: "town", x: 4937, y: 898, k: "Hikai", d: "In Hikai, about 825 mi east of Osenki, near Noramec and Nabuchan." },
  { n: "Nalochl", cat: "town", x: 4428, y: 895, k: "Hikai", d: "In Hikai, about 425 mi east of Osenki, near Ilkai and Ilkane." },
  { n: "Namilna", cat: "town", x: 6749, y: 2932, k: "Theolisseia", d: "In Theolisseia, about 475 mi south of Hadirel, near Gjen and Liaerton." },
  { n: "Nayen", cat: "town", x: 2177, y: 2116, k: "The Tanan Grand Duchy", d: "In the Tanan Grand Duchy, about 225 mi south of Lajazer, near Mepren and Tineb." },
  { n: "Neaea", cat: "town", x: 3420, y: 999, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 1025 mi northwest of Baviet, near Seppegiu and Corocco." },
  { n: "Negel", cat: "town", x: 4202, y: 1081, k: "Hikai", d: "In Hikai, about 350 mi southeast of Osenki, near Osenna and Lagowyal." },
  { n: "Negiet", cat: "town", x: 6765, y: 2200, k: "Theolisseia", d: "In Theolisseia, about 125 mi north of Hadirel, near Hadirel and Daltsen." },
  { n: "Nelva", cat: "town", x: 6370, y: 1266, k: "The Uxridian Grand Duchy", d: "In the Uxridian Grand Duchy, about 175 mi west of Ociyaran, near Cresp and Gora." },
  { n: "Neribe", cat: "town", x: 2052, y: 1783, k: "The Tanan Grand Duchy", d: "In the Tanan Grand Duchy, about 175 mi west of Lajazer, near Deyare and Hadber." },
  { n: "Neska", cat: "town", x: 6606, y: 1079, k: "The Uxridian Grand Duchy", d: "In the Uxridian Grand Duchy, about 175 mi north of Ociyaran, near Esio and Uvenza." },
  { n: "Niarn", cat: "town", x: 4612, y: 421, k: "Hikai", d: "In Hikai, about 625 mi northeast of Osenki, near Gorma and Riyen." },
  { n: "Nisclair", cat: "town", x: 3894, y: 652, k: "Hikai", d: "In Hikai, about 90 mi north of Osenki, near Osenki and Eryte." },
  { n: "Noju", cat: "town", x: 2781, y: 1641, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 1125 mi west of Baviet, near Lanmi and Apric." },
  { n: "Norabea", cat: "town", x: 5347, y: 1681, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 1025 mi east of Baviet, near Bellaria and Anthela." },
  { n: "Noraho", cat: "town", x: 2754, y: 1551, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 1175 mi west of Baviet, near Lanmi and Annagi." },
  { n: "Noramec", cat: "town", x: 4784, y: 826, k: "Hikai", d: "In Hikai, about 700 mi east of Osenki, near Nalchal and Eskert." },
  { n: "Nordos", cat: "town", x: 4190, y: 2288, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 175 mi south of Baviet, near Tanya Beka and Pelea." },
  { n: "Nurida", cat: "town", x: 6389, y: 1641, k: "Theolisseia", d: "In Theolisseia, about 650 mi northwest of Hadirel, near Velu and Pratesi." },
  { n: "Nyedal", cat: "town", x: 4751, y: 1419, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 725 mi northeast of Baviet, near Tasfen and Garen." },
  { n: "Nyeo", cat: "town", x: 2297, y: 1735, k: "The Tanan Grand Duchy", d: "In the Tanan Grand Duchy, about 90 mi north of Lajazer, near Jaserey and The Razane." },
  { n: "Nyes", cat: "town", x: 3665, y: 1554, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 575 mi northwest of Baviet, near Rietha and The Seimaa." },
  { n: "Oa", cat: "town", x: 6013, y: 1188, k: "The Uxridian Grand Duchy", d: "In the Uxridian Grand Duchy, about 475 mi west of Ociyaran, near Brae and Stagna." },
  { n: "Oahat", cat: "town", x: 2528, y: 1904, k: "The Tanan Grand Duchy", d: "In the Tanan Grand Duchy, about 225 mi east of Lajazer, near Masen and Zagare." },
  { n: "Oermada", cat: "town", x: 5078, y: 2005, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 750 mi east of Baviet, near Ledea and Muuri." },
  { n: "Olbe", cat: "town", x: 2811, y: 1963, k: "Lingia", d: "In Lingia, about 500 mi northwest of Haleret, near Drav Tari and Hoab." },
  { n: "Old Feacen", cat: "town", x: 2892, y: 2292, k: "Lingia", d: "In Lingia, about 250 mi northwest of Haleret, near Tolm and Welk." },
  { n: "Olune", cat: "town", x: 3554, y: 1736, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 550 mi northwest of Baviet, near Rietha and Shaer." },
  { n: "Ombretta", cat: "town", x: 5922, y: 1446, k: "The Uxridian Grand Duchy", d: "In the Uxridian Grand Duchy, about 550 mi west of Ociyaran, near Reda and Larida." },
  { n: "Ompol", cat: "town", x: 6117, y: 2602, k: "Theolisseia", d: "In Theolisseia, about 575 mi west of Hadirel, near Bohan and Murok." },
  { n: "Onmore", cat: "town", x: 5073, y: 438, k: "Hikai", d: "In Hikai, about 950 mi east of Osenki, near Riyen and Niarn." },
  { n: "Oradi", cat: "town", x: 3352, y: 1799, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 650 mi west of Baviet, near Alsea and Maadol." },
  { n: "Orcan", cat: "town", x: 2296, y: 1896, k: "The Tanan Grand Duchy", d: "In the Tanan Grand Duchy, about 50 mi southeast of Lajazer, near Aseri Minqa and Lajazer." },
  { n: "Orim", cat: "town", x: 4437, y: 2369, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 325 mi southeast of Baviet, near Hevetane and Thelea." },
  { n: "Orjin", cat: "town", x: 6979, y: 3166, k: "Theolisseia", d: "In Theolisseia, about 675 mi south of Hadirel, near Gjen and Qunag." },
  { n: "Ortuqil", cat: "town", x: 4419, y: 621, k: "Hikai", d: "In Hikai, about 425 mi east of Osenki, near Gorma and Ilkane." },
  { n: "Oryur", cat: "town", x: 4547, y: 1409, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 625 mi northeast of Baviet, near Garen and Inqua." },
  { n: "Oscana", cat: "town", x: 3478, y: 1518, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 700 mi northwest of Baviet, near Lujian and Cardoric." },
  { n: "Osegri", cat: "town", x: 3142, y: 1157, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 1075 mi northwest of Baviet, near Tenda and Rioda." },
  { n: "Osenna", cat: "town", x: 4285, y: 1146, k: "Hikai", d: "In Hikai, about 425 mi southeast of Osenki, near Negel and Camrudar." },
  { n: "Oskaba", cat: "town", x: 4594, y: 2837, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 700 mi southeast of Baviet, near Tagrima and Tarask." },
  { n: "Ostara", cat: "town", x: 4048, y: 1688, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 325 mi north of Baviet, near Malea and Aluun." },
  { n: "Ostoke", cat: "town", x: 1852, y: 2045, k: "The Tanan Grand Duchy", d: "In the Tanan Grand Duchy, about 375 mi southwest of Lajazer, near Hepen and Melerte." },
  { n: "Palere", cat: "town", x: 2715, y: 1328, k: "The Tanan Grand Duchy", d: "In the Tanan Grand Duchy, about 550 mi northeast of Lajazer, near Liviao and Baram." },
  { n: "Pampira", cat: "town", x: 6647, y: 867, k: "The Uxridian Grand Duchy", d: "In the Uxridian Grand Duchy, about 350 mi north of Ociyaran, near Paro and Latso." },
  { n: "Pantar", cat: "town", x: 3189, y: 2357, k: "Lingia", d: "In Lingia, about 90 mi north of Haleret, near Haleret and Civer." },
  { n: "Paro", cat: "town", x: 6623, y: 805, k: "The Uxridian Grand Duchy", d: "In the Uxridian Grand Duchy, about 400 mi north of Ociyaran, near Pampira and Latso." },
  { n: "Pelea", cat: "town", x: 4267, y: 2404, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 275 mi southeast of Baviet, near Nordos and Hevetane." },
  { n: "Pelefer", cat: "town", x: 6603, y: 1416, k: "The Uxridian Grand Duchy", d: "In the Uxridian Grand Duchy, about 80 mi south of Ociyaran, near Pell'oro and Ociyaran." },
  { n: "Pelefera", cat: "town", x: 6862, y: 1102, k: "The Uxridian Grand Duchy", d: "In the Uxridian Grand Duchy, about 275 mi northeast of Ociyaran, near Squero and Chiavanto." },
  { n: "Pelk", cat: "town", x: 3396, y: 2255, k: "Lingia", d: "In Lingia, about 250 mi northeast of Haleret, near Drin and Durk." },
  { n: "Pell'oro", cat: "town", x: 6651, y: 1329, k: "The Uxridian Grand Duchy", d: "In the Uxridian Grand Duchy, about 50 mi east of Ociyaran, near Ociyaran and Brentola." },
  { n: "Peske", cat: "town", x: 2418, y: 1739, k: "The Tanan Grand Duchy", d: "In the Tanan Grand Duchy, about 150 mi northeast of Lajazer, near Madreu and Uedena." },
  { n: "Pondata", cat: "town", x: 3981, y: 2563, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 400 mi south of Baviet, near Riedra and Acin." },
  { n: "Pratesi", cat: "town", x: 6215, y: 1601, k: "The Uxridian Grand Duchy", d: "In the Uxridian Grand Duchy, about 375 mi southwest of Ociyaran, near Grotta and Uada." },
  { n: "Querceta", cat: "town", x: 6583, y: 956, k: "The Uxridian Grand Duchy", d: "In the Uxridian Grand Duchy, about 275 mi north of Ociyaran, near Uvenza and Port Volpa." },
  { n: "Qunag", cat: "town", x: 6986, y: 2883, k: "Theolisseia", d: "In Theolisseia, about 450 mi south of Hadirel, near Gjen and Zemel." },
  { n: "Rachia", cat: "town", x: 2900, y: 1322, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 1150 mi northwest of Baviet, near Tagre and Raiye." },
  { n: "Raiye", cat: "town", x: 2823, y: 1249, k: "The Tanan Grand Duchy", d: "In the Tanan Grand Duchy, about 650 mi northeast of Lajazer, near Baram and Rachia." },
  { n: "Ralta", cat: "town", x: 4520, y: 1614, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 500 mi northeast of Baviet, near Elemea and Garen." },
  { n: "Ravia", cat: "town", x: 6098, y: 1577, k: "The Uxridian Grand Duchy", d: "In the Uxridian Grand Duchy, about 450 mi southwest of Ociyaran, near Velsa and Grotta." },
  { n: "Reda", cat: "town", x: 6042, y: 1353, k: "The Uxridian Grand Duchy", d: "In the Uxridian Grand Duchy, about 450 mi west of Ociyaran, near Larida and Ilvo." },
  { n: "Renzolo", cat: "town", x: 3642, y: 1359, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 700 mi northwest of Baviet, near Selve and Masotom." },
  { n: "Resate", cat: "town", x: 2693, y: 1626, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 1200 mi west of Baviet, near Tellas and Genga." },
  { n: "Resia", cat: "town", x: 4038, y: 1374, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 575 mi north of Baviet, near The Maadun and Adaani." },
  { n: "Reskt", cat: "town", x: 6420, y: 2130, k: "Theolisseia", d: "In Theolisseia, about 350 mi northwest of Hadirel, near Daltsen and Sehrok." },
  { n: "Rewalen", cat: "town", x: 6338, y: 1389, k: "The Uxridian Grand Duchy", d: "In the Uxridian Grand Duchy, about 200 mi west of Ociyaran, near Murra and Cresp." },
  { n: "Rewqo", cat: "town", x: 2405, y: 1834, k: "The Tanan Grand Duchy", d: "In the Tanan Grand Duchy, about 125 mi east of Lajazer, near Jiego and Masen." },
  { n: "Ricna", cat: "town", x: 4339, y: 419, k: "Hikai", d: "In Hikai, about 425 mi northeast of Osenki, near Snurb and Gorma." },
  { n: "Ridal", cat: "town", x: 4584, y: 1106, k: "Hikai", d: "In Hikai, about 600 mi southeast of Osenki, near Ilkai and Camrudar." },
  { n: "Riedra", cat: "town", x: 3945, y: 2498, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 350 mi southwest of Baviet, near Pondata and Acin." },
  { n: "Rietha", cat: "town", x: 3587, y: 1616, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 575 mi northwest of Baviet, near Nyes and Olune." },
  { n: "Rioda", cat: "town", x: 3282, y: 1139, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 1025 mi northwest of Baviet, near Tenda and Osegri." },
  { n: "Ristea", cat: "town", x: 4563, y: 1898, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 375 mi northeast of Baviet, near Laaya and Vashonna." },
  { n: "Riy", cat: "town", x: 6970, y: 1112, k: "The Uxridian Grand Duchy", d: "In the Uxridian Grand Duchy, about 350 mi northeast of Ociyaran, near Colle and Chiavanto." },
  { n: "Riyen", cat: "town", x: 4685, y: 603, k: "Hikai", d: "In Hikai, about 625 mi east of Osenki, near Eskert and Niarn." },
  { n: "Roi", cat: "town", x: 6245, y: 1342, k: "The Uxridian Grand Duchy", d: "In the Uxridian Grand Duchy, about 275 mi west of Ociyaran, near Movo and Cira." },
  { n: "Rosk", cat: "town", x: 3018, y: 2118, k: "Lingia", d: "In Lingia, about 300 mi north of Haleret, near Awq Tari and Jurva." },
  { n: "Rudeth", cat: "town", x: 5413, y: 2135, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 1025 mi east of Baviet, near Denkay and Dugwil." },
  { n: "Sahla", cat: "town", x: 6691, y: 2493, k: "Theolisseia", d: "In Theolisseia, about 150 mi southwest of Hadirel, near Sahlen and Hadirel." },
  { n: "Sahlen", cat: "town", x: 6523, y: 2458, k: "Theolisseia", d: "In Theolisseia, about 225 mi west of Hadirel, near Byeola and Torad." },
  { n: "Saltea", cat: "town", x: 4741, y: 2253, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 500 mi east of Baviet, near Yvenna and Menejela." },
  { n: "Sarleiane", cat: "town", x: 2206, y: 1629, k: "The Tanan Grand Duchy", d: "In the Tanan Grand Duchy, about 175 mi north of Lajazer, near Atanie and Verne." },
  { n: "Sarn", cat: "town", x: 6479, y: 1331, k: "The Uxridian Grand Duchy", d: "In the Uxridian Grand Duchy, about 90 mi west of Ociyaran, near Vin and Ociyaran." },
  { n: "Sarrod", cat: "town", x: 2692, y: 1809, k: "The Tanan Grand Duchy", d: "In the Tanan Grand Duchy, about 350 mi east of Lajazer, near Genga and Zagare." },
  { n: "Sebrof", cat: "town", x: 4810, y: 1196, k: "Hikai", d: "In Hikai, about 800 mi southeast of Osenki, near Nabuchan and Nyedal." },
  { n: "Sehrok", cat: "town", x: 6544, y: 2304, k: "Theolisseia", d: "In Theolisseia, about 200 mi west of Hadirel, near Byeola and Daltsen." },
  { n: "Selve", cat: "town", x: 3574, y: 1429, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 675 mi northwest of Baviet, near Renzolo and Oscana." },
  { n: "Selvet", cat: "town", x: 5507, y: 2722, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 1200 mi southeast of Baviet, near Amba and Maryos." },
  { n: "Semhol", cat: "town", x: 5108, y: 1724, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 825 mi east of Baviet, near Kidaris and Belnara." },
  { n: "Senalda", cat: "town", x: 6391, y: 840, k: "The Uxridian Grand Duchy", d: "In the Uxridian Grand Duchy, about 400 mi northwest of Ociyaran, near Cala and Port Volpa." },
  { n: "Senna", cat: "town", x: 6298, y: 988, k: "The Uxridian Grand Duchy", d: "In the Uxridian Grand Duchy, about 350 mi northwest of Ociyaran, near Cala and Sye." },
  { n: "Seppegiu", cat: "town", x: 3472, y: 1094, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 950 mi northwest of Baviet, near Coloni and Neaea." },
  { n: "Sevq", cat: "town", x: 5617, y: 2286, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 1200 mi east of Baviet, near Dahn and Hauk." },
  { n: "Shaer", cat: "town", x: 3548, y: 1871, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 500 mi west of Baviet, near Olune and Lage." },
  { n: "Sindber", cat: "town", x: 3000, y: 2552, k: "Lingia", d: "In Lingia, about 150 mi southwest of Haleret, near Drosk and Dessane." },
  { n: "Skya", cat: "town", x: 3807, y: 162, k: "Hikai", d: "In Hikai, about 475 mi north of Osenki, near Tilnyeau and Eynora." },
  { n: "Slaia", cat: "town", x: 3781, y: 433, k: "Hikai", d: "In Hikai, about 275 mi northwest of Osenki, near Tilnyeau and Nisclair." },
  { n: "Snurb", cat: "town", x: 4278, y: 523, k: "Hikai", d: "In Hikai, about 350 mi northeast of Osenki, near Ricna and Ortuqil." },
  { n: "Squero", cat: "town", x: 6895, y: 1142, k: "The Uxridian Grand Duchy", d: "In the Uxridian Grand Duchy, about 275 mi northeast of Ociyaran, near Pelefera and Colle." },
  { n: "Sretan", cat: "town", x: 2328, y: 1295, k: "The Tanan Grand Duchy", d: "In the Tanan Grand Duchy, about 425 mi north of Lajazer, near Borgeste and Veris." },
  { n: "Stagna", cat: "town", x: 6130, y: 1267, k: "The Uxridian Grand Duchy", d: "In the Uxridian Grand Duchy, about 375 mi west of Ociyaran, near Ilvo and Brae." },
  { n: "Sye", cat: "town", x: 6347, y: 1050, k: "The Uxridian Grand Duchy", d: "In the Uxridian Grand Duchy, about 275 mi northwest of Ociyaran, near Vallaforta and Senna." },
  { n: "Tagre", cat: "town", x: 2832, y: 1378, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 1175 mi northwest of Baviet, near Rachia and Giagior." },
  { n: "Tagrima", cat: "town", x: 4498, y: 2910, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 725 mi southeast of Baviet, near Oskaba and Eskua." },
  { n: "Talu", cat: "town", x: 6063, y: 1755, k: "The Uxridian Grand Duchy", d: "In the Uxridian Grand Duchy, about 550 mi southwest of Ociyaran, near Velsa and Uada." },
  { n: "Tanya Beka", cat: "town", x: 4231, y: 2156, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 100 mi southeast of Baviet, near Mother's hip and Baviet." },
  { n: "Tarask", cat: "town", x: 4628, y: 2674, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 625 mi southeast of Baviet, near Oskaba and Druun." },
  { n: "Tarl", cat: "town", x: 3872, y: 2285, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 250 mi southwest of Baviet, near Anjelea and Granosa." },
  { n: "Tarmeda", cat: "town", x: 4241, y: 2016, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 100 mi northeast of Baviet, near Malim and Mother's hip." },
  { n: "Tarmet", cat: "town", x: 4026, y: 1902, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 175 mi northwest of Baviet, near Asmeta and Lendara." },
  { n: "Tasfen", cat: "town", x: 4812, y: 1515, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 700 mi northeast of Baviet, near Nyedal and Garen." },
  { n: "Tehron", cat: "town", x: 5334, y: 1838, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 975 mi east of Baviet, near Anthela and Medhuk." },
  { n: "Teirenna", cat: "town", x: 4189, y: 1772, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 250 mi north of Baviet, near Lokea and Cuola." },
  { n: "Tellas", cat: "town", x: 2665, y: 1577, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 1225 mi west of Baviet, near Resate and Meliut." },
  { n: "Tenda", cat: "town", x: 3263, y: 1220, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 975 mi northwest of Baviet, near Gelona and Rioda." },
  { n: "Tereas", cat: "town", x: 3901, y: 1965, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 200 mi northwest of Baviet, near Keba and Bayen." },
  { n: "Tericaer", cat: "town", x: 2094, y: 1648, k: "The Tanan Grand Duchy", d: "In the Tanan Grand Duchy, about 200 mi northwest of Lajazer, near Atanie and Deyare." },
  { n: "Tericaer", cat: "town", x: 1877, y: 2159, k: "The Tanan Grand Duchy", d: "In the Tanan Grand Duchy, about 400 mi southwest of Lajazer, near Teyet and Port Qual." },
  { n: "Tesora", cat: "town", x: 6919, y: 780, k: "The Uxridian Grand Duchy", d: "In the Uxridian Grand Duchy, about 500 mi northeast of Ociyaran, near Chiozza and Muralto." },
  { n: "Teyet", cat: "town", x: 1917, y: 2121, k: "The Tanan Grand Duchy", d: "In the Tanan Grand Duchy, about 350 mi southwest of Lajazer, near Tericaer and Hepen." },
  { n: "Thalen", cat: "town", x: 1807, y: 1958, k: "The Tanan Grand Duchy", d: "In the Tanan Grand Duchy, about 375 mi west of Lajazer, near Matsene and Melerte." },
  { n: "The Aonesse", cat: "town", x: 2023, y: 2054, k: "The Tanan Grand Duchy", d: "In the Tanan Grand Duchy, about 250 mi southwest of Lajazer, near Liasen and Boletre  Begai." },
  { n: "The Brack", cat: "town", x: 3378, y: 1984, k: "Lingia", d: "In Lingia, about 425 mi northeast of Haleret, near Oradi and Drin." },
  { n: "The Duriaan", cat: "town", x: 3851, y: 1253, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 700 mi north of Baviet, near Gondes and Durisea." },
  { n: "The Maadun", cat: "town", x: 4115, y: 1292, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 625 mi north of Baviet, near Resia and Lagowyal." },
  { n: "The Pontesi", cat: "town", x: 3540, y: 2310, k: "Lingia", d: "In Lingia, about 325 mi northeast of Haleret, near Durk and Pelk." },
  { n: "The Razane", cat: "town", x: 2313, y: 1777, k: "The Tanan Grand Duchy", d: "In the Tanan Grand Duchy, about 60 mi northeast of Lajazer, near Nyeo and Madreu." },
  { n: "The Santie", cat: "town", x: 2249, y: 2234, k: "The Tanan Grand Duchy", d: "In the Tanan Grand Duchy, about 325 mi south of Lajazer, near Goteivane and Meprie Teish." },
  { n: "The Seimaa", cat: "town", x: 3815, y: 1537, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 500 mi northwest of Baviet, near Belune and Cymea." },
  { n: "Thelea", cat: "town", x: 4483, y: 2216, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 300 mi east of Baviet, near Calyea and Orim." },
  { n: "Thevia", cat: "town", x: 2891, y: 1626, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 1050 mi west of Baviet, near Apric and Iaga." },
  { n: "Thya", cat: "town", x: 2461, y: 2600, k: "Lingia", d: "In Lingia, about 575 mi west of Haleret, near Vask and Port Ols." },
  { n: "Tiamma", cat: "town", x: 3679, y: 1174, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 800 mi northwest of Baviet, near Masotom and Coloni." },
  { n: "Tilnyeau", cat: "town", x: 3659, y: 252, k: "Hikai", d: "In Hikai, about 450 mi northwest of Osenki, near Lagora and Skya." },
  { n: "Tineb", cat: "town", x: 2262, y: 2111, k: "The Tanan Grand Duchy", d: "In the Tanan Grand Duchy, about 225 mi south of Lajazer, near Mepren and Nayen." },
  { n: "Tolm", cat: "town", x: 3013, y: 2344, k: "Lingia", d: "In Lingia, about 150 mi northwest of Haleret, near Drosk and Old Feacen." },
  { n: "Tophercris", cat: "town", x: 3067, y: 1414, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 1000 mi northwest of Baviet, near Mema and Anaan." },
  { n: "Torad", cat: "town", x: 6524, y: 2558, k: "Theolisseia", d: "In Theolisseia, about 275 mi southwest of Hadirel, near Galmun and Sahlen." },
  { n: "Tropie", cat: "town", x: 3407, y: 1217, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 900 mi northwest of Baviet, near Coloni and Gelona." },
  { n: "Tsenmar", cat: "town", x: 6708, y: 1510, k: "Theolisseia", d: "In Theolisseia, about 675 mi north of Hadirel, near Pelefer and Brentola." },
  { n: "Tsir", cat: "town", x: 5232, y: 2214, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 875 mi east of Baviet, near Dremk and Hagn." },
  { n: "Tusjin", cat: "town", x: 5282, y: 1976, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 925 mi east of Baviet, near Dremk and Denkay." },
  { n: "Uada", cat: "town", x: 6180, y: 1662, k: "The Uxridian Grand Duchy", d: "In the Uxridian Grand Duchy, about 425 mi southwest of Ociyaran, near Pratesi and Grotta." },
  { n: "Uedena", cat: "town", x: 2397, y: 1690, k: "The Tanan Grand Duchy", d: "In the Tanan Grand Duchy, about 150 mi northeast of Lajazer, near Valea and Peske." },
  { n: "Uvenza", cat: "town", x: 6599, y: 1013, k: "The Uxridian Grand Duchy", d: "In the Uxridian Grand Duchy, about 250 mi north of Ociyaran, near Querceta and Neska." },
  { n: "Vagan", cat: "town", x: 4754, y: 2444, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 575 mi southeast of Baviet, near Aanye and Saltea." },
  { n: "Vagust", cat: "town", x: 5452, y: 1977, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 1050 mi east of Baviet, near Aspardo and Denkay." },
  { n: "Vaia", cat: "town", x: 2587, y: 1487, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 1325 mi west of Baviet, near Kanidon and Tellas." },
  { n: "Valea", cat: "town", x: 2368, y: 1649, k: "The Tanan Grand Duchy", d: "In the Tanan Grand Duchy, about 175 mi northeast of Lajazer, near Uedena and Wisten." },
  { n: "Vallaforta", cat: "town", x: 6299, y: 1082, k: "The Uxridian Grand Duchy", d: "In the Uxridian Grand Duchy, about 300 mi northwest of Ociyaran, near Lun and Sye." },
  { n: "Vashonna", cat: "town", x: 4440, y: 1829, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 325 mi northeast of Baviet, near Elemea and Ristea." },
  { n: "Vask", cat: "town", x: 2456, y: 2454, k: "Lingia", d: "In Lingia, about 550 mi west of Haleret, near Thya and Laone." },
  { n: "Velsa", cat: "town", x: 6058, y: 1619, k: "The Uxridian Grand Duchy", d: "In the Uxridian Grand Duchy, about 500 mi southwest of Ociyaran, near Ravia and Uada." },
  { n: "Velu", cat: "town", x: 6375, y: 1520, k: "The Uxridian Grand Duchy", d: "In the Uxridian Grand Duchy, about 250 mi southwest of Ociyaran, near Murra and Nurida." },
  { n: "Veris", cat: "town", x: 2258, y: 1301, k: "The Tanan Grand Duchy", d: "In the Tanan Grand Duchy, about 425 mi north of Lajazer, near Sretan and Lermea." },
  { n: "Verna Tari", cat: "town", x: 6505, y: 2812, k: "Theolisseia", d: "In Theolisseia, about 425 mi southwest of Hadirel, near Junjeo and Murok." },
  { n: "Verne", cat: "town", x: 2262, y: 1661, k: "The Tanan Grand Duchy", d: "In the Tanan Grand Duchy, about 150 mi north of Lajazer, near Jaserey and Hashren." },
  { n: "Vigila", cat: "town", x: 6474, y: 1166, k: "The Uxridian Grand Duchy", d: "In the Uxridian Grand Duchy, about 150 mi northwest of Ociyaran, near Corsa and Gabbia." },
  { n: "Vin", cat: "town", x: 6485, y: 1418, k: "The Uxridian Grand Duchy", d: "In the Uxridian Grand Duchy, about 125 mi southwest of Ociyaran, near Sarn and Pelefer." },
  { n: "Vinalta", cat: "town", x: 6680, y: 976, k: "The Uxridian Grand Duchy", d: "In the Uxridian Grand Duchy, about 275 mi north of Ociyaran, near Doresi and Jhera." },
  { n: "Weca", cat: "town", x: 2440, y: 1285, k: "The Tanan Grand Duchy", d: "In the Tanan Grand Duchy, about 450 mi north of Lajazer, near Bion and Borgeste." },
  { n: "Welk", cat: "town", x: 2718, y: 2369, k: "Lingia", d: "In Lingia, about 350 mi west of Haleret, near Hulber and Old Feacen." },
  { n: "Wisten", cat: "town", x: 2427, y: 1596, k: "The Tanan Grand Duchy", d: "In the Tanan Grand Duchy, about 225 mi northeast of Lajazer, near Isece and Menen." },
  { n: "Yleka", cat: "town", x: 4035, y: 365, k: "Hikai", d: "In Hikai, about 325 mi north of Osenki, near Eryte and Slaia." },
  { n: "Ys", cat: "town", x: 7002, y: 973, k: "The Uxridian Grand Duchy", d: "In the Uxridian Grand Duchy, about 425 mi northeast of Ociyaran, near Chiavanto and Muralto." },
  { n: "Yula", cat: "town", x: 6858, y: 2602, k: "Theolisseia", d: "In Theolisseia, about 200 mi south of Hadirel, near Gaedu and Zemel." },
  { n: "Yvenna", cat: "town", x: 4663, y: 2171, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 425 mi east of Baviet, near Saltea and Aanye." },
  { n: "Zagare", cat: "town", x: 2534, y: 1781, k: "The Tanan Grand Duchy", d: "In the Tanan Grand Duchy, about 225 mi east of Lajazer, near Casqen Zaeri and Breston." },
  { n: "Zattera", cat: "town", x: 6707, y: 726, k: "The Uxridian Grand Duchy", d: "In the Uxridian Grand Duchy, about 475 mi north of Ociyaran, near Latso and Paro." },
  { n: "Zemel", cat: "town", x: 6898, y: 2718, k: "Theolisseia", d: "In Theolisseia, about 300 mi south of Hadirel, near Yula and Qunag." },
  { n: "Zerpe", cat: "town", x: 3703, y: 1917, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 375 mi west of Baviet, near Cerby and Lage." },
  { n: "Honloor Lake", cat: "water", x: 4336, y: 1456, d: "A sea or lake of the known world." },
  { n: "Lake Bron", cat: "water", x: 3295, y: 2336, d: "A sea or lake of the known world." },
  { n: "Lake Trang", cat: "water", x: 4107, y: 807, d: "A sea or lake of the known world." },
  { n: "LakeDulve", cat: "water", x: 3128, y: 2519, d: "A sea or lake of the known world." },
  { n: "Rium Harbor", cat: "water", x: 4860, y: 717, d: "A sea or lake of the known world." },
  { n: "The Fetora Sea", cat: "water", x: 3189, y: 3183, d: "A sea or lake of the known world." },
  { n: "The Inei Bay", cat: "water", x: 4765, y: 270, d: "A sea or lake of the known world." },
  { n: "The Orburydon Sea", cat: "water", x: 7366, y: 868, d: "A sea or lake of the known world." },
  { n: "The Quather Sea", cat: "water", x: 2116, y: 544, d: "A sea or lake of the known world." },
  { n: "The Academy", cat: "island", x: 1844, y: 1434, d: "An island of the known world." },
  { n: "The Cidet", cat: "island", x: 1391, y: 2154, d: "An island of the known world." },
  { n: "Thult", cat: "island", x: 1315, y: 2707, d: "Southwestern island, formerly the Mystic Isles; claimed and renamed by the empire." },
  { n: "Abrenna Forest", cat: "forest", x: 3778, y: 1462, k: "The Caporiolan Kingdom", d: "A forest in the Caporiolan Kingdom." },
  { n: "Aro Forest", cat: "forest", x: 6736, y: 1063, k: "The Uxridian Grand Duchy", d: "A forest in the Uxridian Grand Duchy." },
  { n: "Nedi Forest", cat: "forest", x: 6084, y: 1704, k: "The Uxridian Grand Duchy", d: "A forest in the Uxridian Grand Duchy." },
  { n: "Silora forest", cat: "forest", x: 6715, y: 2540, k: "Theolisseia", d: "A forest in Theolisseia." },
  { n: "The Caporiolan Forest", cat: "forest", x: 4870, y: 1575, k: "The Caporiolan Kingdom", d: "A forest in the Caporiolan Kingdom." },
  { n: "Tigrei Forest", cat: "forest", x: 3313, y: 1669, k: "The Caporiolan Kingdom", d: "A forest in the Caporiolan Kingdom." },
  { n: "Aryanara's territory", cat: "territory", x: 5310, y: 1792, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 975 mi east of Baviet, near Tehron and Anthela." },
  { n: "Dor Tari Naos", cat: "territory", x: 5318, y: 1886, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 950 mi east of Baviet, near Tehron and Tusjin." },
  { n: "Naos Adwe", cat: "territory", x: 5343, y: 2348, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 1000 mi east of Baviet, near Hagn and Hagia Demre." },
  { n: "Naosic", cat: "territory", x: 5402, y: 1756, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 1050 mi east of Baviet, near Norabea and Tehron." },
  { n: "Nyeo Naos", cat: "territory", x: 2257, y: 1749, k: "The Tanan Grand Duchy", d: "In the Tanan Grand Duchy, about 70 mi north of Lajazer, near Nyeo and Jaserey." },
  { n: "Tehr Tari Naos", cat: "territory", x: 5022, y: 1385, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 900 mi northeast of Baviet, near Hagiora and Amberactserun." },
  { n: "Vekta's territory", cat: "territory", x: 5068, y: 1639, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 825 mi northeast of Baviet, near Amberactserun and Semhol." },
  { n: "Mt. Aicren", cat: "landmark", x: 6679, y: 2437, k: "Theolisseia", d: "In Theolisseia, about 125 mi southwest of Hadirel, near Sahla and Byeola." },
  { n: "Outer Walls", cat: "landmark", x: 4085, y: 2101, k: "The Caporiolan Kingdom", d: "In the Caporiolan Kingdom, about 40 mi west of Baviet, near Baviet and Asmeta." },
  { n: "The Magic Tower", cat: "landmark", x: 6768, y: 2410, k: "Theolisseia", d: "In Theolisseia, about 50 mi south of Hadirel, near Hadirel and Sahla." }
];

const EMPIRE_STATES = [
  { n: "Lingia", capital: "Haleret", d: "Formerly the kingdom of Pireaynea, its warlord anarchy subdued by imperial troops. Capital: Haleret.", biomes: ["Grassland","Temperate deciduous forest","Taiga","Wetland"] },
  { n: "Hikai", capital: "Osenki", d: "Formerly the kingdom of Coelum, the bankrupt 'Forsaken Land'. Capital: Osenki.", biomes: ["Grassland","Temperate deciduous forest","Taiga","Wetland"] },
  { n: "The Uxridian Grand Duchy", capital: "Ociyaran", d: "Formerly the kingdom of Equateiy, the wealthy banking oligarchy that joined the empire by treaty. Capital: Ociyaran.", biomes: ["Grassland","Temperate deciduous forest","Taiga","Wetland"] },
  { n: "Theolisseia", capital: "Hadirel", d: "Formerly the kingdom of Vikitsv, the mountain magocracy of Mount Aicren. Capital: Hadirel.", biomes: ["Grassland","Temperate deciduous forest","Taiga","Wetland"] },
  { n: "The Caporiolan Kingdom", capital: "Baviet", d: "Formerly the kingdom of Gherci; the theocratic heartland and seat of the Solisian Empire. Capital: Baviet.", biomes: ["Grassland","Temperate deciduous forest","Taiga","Wetland"] },
  { n: "The Tanan Grand Duchy", capital: "Lajazer", d: "Formerly the kingdom of Aicruae, the western breadbasket. One of the great powers of the Early Empire. Capital: Lajazer.", biomes: ["Grassland","Temperate deciduous forest","Taiga","Wetland"] }
];
