// Present-era gazetteer (~1,852 AR onward, "the present age").
// Extracted from the Azgaar SVG "Bela 2026-08-24-01-59"; coordinates are atlas pixels (SVG x5).
// Names taken verbatim from the SVG label text; kingdoms assigned by point-in-polygon of state
// borders and by island geometry. The Cidet, The Academy and Thult are sacred-neutral western
// landmasses, not kingdoms. Present kingdoms are named for the old Six Kingdoms capitals but keep
// their own current capitals (Lajazer: Vellin; Tarmet: Bela; Civer: Lorne; Atriki: Elgan;
// Ociyaran: Zada; Berlailia: Hadirel).
// cat: region | capital | city | town | water | river | island | forest | territory | landmark

const PLACES_PRESENT = [
  { n: "The Eriata District", cat: "region", x: 4416, y: 697, k: "The Kingdom of Atriki", d: "A district of The Kingdom of Atriki." },
  { n: "The Kingdom of Atriki", cat: "region", x: 4237, y: 950, k: "The Kingdom of Atriki", d: "Once Coelum, the 'Forsaken Land,' later Hikai. Capital: Elgan." },
  { n: "The Kingdom of Berlailia", cat: "region", x: 5955, y: 1917, k: "The Kingdom of Berlailia", d: "Once Vikitsv, the mountain magocracy of Mount Aicren, later Theolisseia. Capital: Hadirel." },
  { n: "The Kingdom of Civer", cat: "region", x: 3025, y: 2197, k: "The Kingdom of Civer", d: "Once Pireaynea, the 'Demon's Pit,' later Lingia. Capital: Lorne." },
  { n: "The Kingdom of Lajazer", cat: "region", x: 2205, y: 1920, k: "The Kingdom of Lajazer", d: "The western kingdom; once the sun-kingdom of Aicruae, later the Tanan Grand Duchy. Capital: Vellin." },
  { n: "The Kingdom of Ociyaran", cat: "region", x: 6494, y: 1174, k: "The Kingdom of Ociyaran", d: "Once Equateiy, the banking 'Kingdom of Gold,' later the Uxridian Grand Duchy. Capital: Zada." },
  { n: "The Kingdom of Tarmet", cat: "region", x: 4126, y: 1846, k: "The Kingdom of Tarmet", d: "The old theocratic heartland; once Gherci, later the Caporiolan Kingdom and seat of the empire. Capital: Bela." },
  { n: "The Kuhymes District", cat: "region", x: 4585, y: 1164, k: "The Kingdom of Atriki", d: "A district of The Kingdom of Atriki." },
  { n: "The Senagai", cat: "region", x: 1615, y: 2242, k: "The Cidet", d: "A region of the Cidet, the holy island." },
  { n: "The Tieiko District", cat: "region", x: 3961, y: 448, k: "The Kingdom of Atriki", d: "A district of The Kingdom of Atriki." },
  { n: "Bela", cat: "capital", x: 4133, y: 2060, k: "The Kingdom of Tarmet", d: "Capital of The Kingdom of Tarmet." },
  { n: "Elgan", cat: "capital", x: 3922, y: 737, k: "The Kingdom of Atriki", d: "Capital of The Kingdom of Atriki." },
  { n: "Hadirel", cat: "capital", x: 6793, y: 2322, k: "The Kingdom of Berlailia", d: "Capital of The Kingdom of Berlailia." },
  { n: "Lorne", cat: "capital", x: 3162, y: 2438, k: "The Kingdom of Civer", d: "Capital of The Kingdom of Civer." },
  { n: "Vellin", cat: "capital", x: 1879, y: 2161, k: "The Kingdom of Lajazer", d: "Capital of The Kingdom of Lajazer." },
  { n: "Zada", cat: "capital", x: 6605, y: 1292, k: "The Kingdom of Ociyaran", d: "Capital of The Kingdom of Ociyaran." },
  { n: "Lajazer", cat: "city", x: 2264, y: 1810, k: "The Kingdom of Lajazer", d: "A city in the Kingdom of Lajazer; the ancient capital of Aicruae, for which the kingdom is named." },
  { n: "Port Absey", cat: "city", x: 3614, y: 2626, k: "", d: "In the borderlands, near Durk and Acin." },
  { n: "Port Aresca", cat: "city", x: 3196, y: 871, k: "", d: "In the borderlands, near Corocco and Etanda." },
  { n: "Port Asen", cat: "city", x: 1984, y: 1225, k: "The Academy", d: "In The Academy, near Veris and Itara." },
  { n: "Port Besk", cat: "city", x: 1746, y: 1622, k: "The Academy", d: "In The Academy, near Bordei and Tiren." },
  { n: "Port Esserey", cat: "city", x: 2623, y: 1106, k: "The Kingdom of Lajazer", d: "In The Kingdom of Lajazer, about 1025 mi northeast of Vellin, near Linjet and Kunes." },
  { n: "Port Linnos", cat: "city", x: 4916, y: 2894, k: "The Kingdom of Tarmet", d: "In The Kingdom of Tarmet, about 900 mi southeast of Bela, near Mireb and Dordbin." },
  { n: "Port Naole", cat: "city", x: 1785, y: 2053, k: "The Kingdom of Lajazer", d: "In The Kingdom of Lajazer, about 125 mi northwest of Vellin, near Hepen and Melerte." },
  { n: "Port Ols", cat: "city", x: 2596, y: 2764, k: "The Kingdom of Civer", d: "In The Kingdom of Civer, about 525 mi southwest of Lorne, near Thya and Hulber." },
  { n: "Port Pontes", cat: "city", x: 3996, y: 2776, k: "", d: "In the borderlands, near Acin and Pondata." },
  { n: "Port Qual", cat: "city", x: 1851, y: 2220, k: "The Kingdom of Lajazer", d: "In The Kingdom of Lajazer, about 50 mi southwest of Vellin, near Vellin and Teyet." },
  { n: "Port Rebadeen", cat: "city", x: 4530, y: 134, k: "The Kingdom of Atriki", d: "In The Kingdom of Atriki, about 675 mi northeast of Elgan, near Aresada and Niarn." },
  { n: "Port Sael", cat: "city", x: 7213, y: 2774, k: "The Kingdom of Berlailia", d: "In The Kingdom of Berlailia, about 500 mi southeast of Hadirel, near Qunag and Caelmu." },
  { n: "Port Theli", cat: "city", x: 3656, y: 910, k: "", d: "In the borderlands, near Yuaveka and Eskol." },
  { n: "Port Vente", cat: "city", x: 2362, y: 1208, k: "The Kingdom of Lajazer", d: "In The Kingdom of Lajazer, about 850 mi northeast of Vellin, near Sretan and Weca." },
  { n: "Port Vessar", cat: "city", x: 2903, y: 1111, k: "", d: "In the borderlands, near Raiye and Linjet." },
  { n: "Port Volpa", cat: "city", x: 6506, y: 898, k: "The Kingdom of Ociyaran", d: "In The Kingdom of Ociyaran, about 325 mi north of Zada, near Foce and Querceta." },
  { n: "Port Yure", cat: "city", x: 1350, y: 2409, k: "The Cidet", d: "The pilgrim harbour of the Cidet, where sea travellers make landfall, on the Ospe." },
  { n: "Aanye", cat: "town", x: 4622, y: 2322, k: "The Kingdom of Tarmet", d: "In The Kingdom of Tarmet, about 450 mi southeast of Bela, near Saltea and Yvenna." },
  { n: "Acin", cat: "town", x: 3919, y: 2634, k: "The Kingdom of Tarmet", d: "In The Kingdom of Tarmet, about 500 mi south of Bela, near Pondata and Riedra." },
  { n: "Adaani", cat: "town", x: 3918, y: 1409, k: "The Kingdom of Tarmet", d: "In The Kingdom of Tarmet, about 550 mi north of Bela, near Gondes and Cymea." },
  { n: "Alben", cat: "town", x: 2350, y: 1561, k: "The Kingdom of Lajazer", d: "In The Kingdom of Lajazer, about 600 mi northeast of Vellin, near Belei and Hashren." },
  { n: "Allisto", cat: "town", x: 5585, y: 2111, k: "The Kingdom of Tarmet", d: "In The Kingdom of Tarmet, about 1150 mi east of Bela, near Bralk and Aspardo." },
  { n: "Alpena", cat: "town", x: 6873, y: 995, k: "The Kingdom of Ociyaran", d: "In The Kingdom of Ociyaran, about 325 mi northeast of Zada, near Muralto and Chiavanto." },
  { n: "Alsea", cat: "town", x: 3397, y: 1738, k: "The Kingdom of Tarmet", d: "In The Kingdom of Tarmet, about 650 mi northwest of Bela, near Oradi and Drenia." },
  { n: "Aluun", cat: "town", x: 4128, y: 1555, k: "The Kingdom of Tarmet", d: "In The Kingdom of Tarmet, about 400 mi north of Bela, near Inke and Malea." },
  { n: "Amba", cat: "town", x: 5454, y: 2638, k: "The Kingdom of Tarmet", d: "In The Kingdom of Tarmet, about 1150 mi southeast of Bela, near Selvet and Hagiore." },
  { n: "Amberactserun", cat: "town", x: 5147, y: 1558, k: "The Kingdom of Tarmet", d: "In The Kingdom of Tarmet, about 900 mi northeast of Bela, near Vekta's territory and Hagiora." },
  { n: "Amesa", cat: "town", x: 4825, y: 2036, k: "The Kingdom of Tarmet", d: "In The Kingdom of Tarmet, about 550 mi east of Bela, near Avaani and Menejela." },
  { n: "Anaan", cat: "town", x: 3019, y: 1339, k: "The Kingdom of Tarmet", d: "In The Kingdom of Tarmet, about 1050 mi northwest of Bela, near Tophercris and Rachia." },
  { n: "Anjelea", cat: "town", x: 3902, y: 2374, k: "The Kingdom of Tarmet", d: "In The Kingdom of Tarmet, about 300 mi southwest of Bela, near Lower Cosar and Tarl." },
  { n: "Annagi", cat: "town", x: 2723, y: 1495, k: "The Kingdom of Tarmet", d: "In The Kingdom of Tarmet, about 1200 mi west of Bela, near Noraho and Liviao." },
  { n: "Anthela", cat: "town", x: 5252, y: 1754, k: "The Kingdom of Tarmet", d: "In The Kingdom of Tarmet, about 925 mi east of Bela, near Bellaria and Aryanara's territory." },
  { n: "Anye", cat: "town", x: 4294, y: 2548, k: "The Kingdom of Tarmet", d: "In The Kingdom of Tarmet, about 400 mi south of Bela, near Pelea and Druun." },
  { n: "Aoim", cat: "town", x: 4827, y: 1656, k: "The Kingdom of Tarmet", d: "In The Kingdom of Tarmet, about 650 mi northeast of Bela, near Luja and Tasfen." },
  { n: "Apric", cat: "town", x: 2839, y: 1682, k: "The Kingdom of Tarmet", d: "In The Kingdom of Tarmet, about 1075 mi west of Bela, near Noju and Thevia." },
  { n: "Aresada", cat: "town", x: 4461, y: 400, k: "The Kingdom of Atriki", d: "In The Kingdom of Atriki, about 500 mi northeast of Elgan, near Gorma and Ricna." },
  { n: "Argu", cat: "town", x: 6270, y: 1500, k: "The Kingdom of Ociyaran", d: "In The Kingdom of Ociyaran, about 325 mi southwest of Zada, near Lezna and Murra." },
  { n: "Arona", cat: "town", x: 6728, y: 1135, k: "The Kingdom of Ociyaran", d: "In The Kingdom of Ociyaran, about 150 mi northeast of Zada, near Doresi and Claieso." },
  { n: "Aryanara's territory", cat: "town", x: 5311, y: 1787, k: "The Kingdom of Tarmet", d: "In The Kingdom of Tarmet, about 975 mi east of Bela, near Tehron and Anthela." },
  { n: "Aserag", cat: "town", x: 2513, y: 2211, k: "The Kingdom of Civer", d: "In The Kingdom of Civer, about 550 mi west of Lorne, near Lorig and Ledesca." },
  { n: "Asmeta", cat: "town", x: 4054, y: 2010, k: "The Kingdom of Tarmet", d: "In The Kingdom of Tarmet, about 75 mi northwest of Bela, near Outer Walls and Lendara." },
  { n: "Aspardo", cat: "town", x: 5523, y: 2036, k: "The Kingdom of Tarmet", d: "In The Kingdom of Tarmet, about 1100 mi east of Bela, near Vagust and Allisto." },
  { n: "Atanie", cat: "town", x: 2155, y: 1592, k: "The Kingdom of Lajazer", d: "In The Kingdom of Lajazer, about 500 mi northeast of Vellin, near Sarleiane and Tericaer." },
  { n: "Audine", cat: "town", x: 1990, y: 2345, k: "The Kingdom of Lajazer", d: "In The Kingdom of Lajazer, about 175 mi southeast of Vellin, near Barete and Port Qual." },
  { n: "Avaani", cat: "town", x: 4714, y: 1961, k: "The Kingdom of Tarmet", d: "In The Kingdom of Tarmet, about 475 mi east of Bela, near Inem and Amesa." },
  { n: "Avege", cat: "town", x: 2282, y: 1982, k: "The Kingdom of Lajazer", d: "In The Kingdom of Lajazer, about 350 mi northeast of Vellin, near Comei and Orcan." },
  { n: "Awq Tari", cat: "town", x: 3044, y: 2038, k: "The Kingdom of Civer", d: "In The Kingdom of Civer, about 325 mi north of Lorne, near Rosk and Jurva." },
  { n: "Baest", cat: "town", x: 2918, y: 1897, k: "The Kingdom of Civer", d: "In The Kingdom of Civer, about 475 mi northwest of Lorne, near Olbe and Corvane." },
  { n: "Baram", cat: "town", x: 2727, y: 1250, k: "The Kingdom of Lajazer", d: "In The Kingdom of Lajazer, about 1000 mi northeast of Vellin, near Linjet and Palere." },
  { n: "Barete", cat: "town", x: 1994, y: 2173, k: "The Kingdom of Lajazer", d: "In The Kingdom of Lajazer, about 100 mi east of Vellin, near Liasen and Teyet." },
  { n: "Basar Tari", cat: "town", x: 2152, y: 2629, k: "The Kingdom of Lajazer", d: "In The Kingdom of Lajazer, about 425 mi southeast of Vellin, near Laone and Thya." },
  { n: "Bavienna", cat: "town", x: 4165, y: 2197, k: "The Kingdom of Tarmet", d: "In The Kingdom of Tarmet, about 100 mi south of Bela, near Tanya Beka and Nordos." },
  { n: "Bayen", cat: "town", x: 3895, y: 1838, k: "The Kingdom of Tarmet", d: "In The Kingdom of Tarmet, about 250 mi northwest of Bela, near Tereas and Tarmet." },
  { n: "Belei", cat: "town", x: 2304, y: 1521, k: "The Kingdom of Lajazer", d: "In The Kingdom of Lajazer, about 625 mi northeast of Vellin, near Alben and Fordei." },
  { n: "Bellaria", cat: "town", x: 5273, y: 1705, k: "The Kingdom of Tarmet", d: "In The Kingdom of Tarmet, about 950 mi east of Bela, near Anthela and Norabea." },
  { n: "Belnara", cat: "town", x: 4980, y: 1739, k: "The Kingdom of Tarmet", d: "In The Kingdom of Tarmet, about 725 mi east of Bela, near Vekta's territory and Semhol." },
  { n: "Belune", cat: "town", x: 3845, y: 1619, k: "The Kingdom of Tarmet", d: "In The Kingdom of Tarmet, about 425 mi northwest of Bela, near The Seimaa and Malea." },
  { n: "Benale", cat: "town", x: 2474, y: 2053, k: "The Kingdom of Lajazer", d: "In The Kingdom of Lajazer, about 475 mi east of Vellin, near Halkere and Cesro." },
  { n: "Bion", cat: "town", x: 2515, y: 1252, k: "The Kingdom of Lajazer", d: "In The Kingdom of Lajazer, about 875 mi northeast of Vellin, near Weca and Birme." },
  { n: "Birme", cat: "town", x: 2553, y: 1343, k: "The Kingdom of Lajazer", d: "In The Kingdom of Lajazer, about 850 mi northeast of Vellin, near Bion and Kunes." },
  { n: "Bohan", cat: "town", x: 6006, y: 2882, k: "The Kingdom of Berlailia", d: "In The Kingdom of Berlailia, about 775 mi southwest of Hadirel, near Ompol and Gilsa." },
  { n: "Boletre  Begai", cat: "town", x: 2047, y: 2017, k: "The Kingdom of Lajazer", d: "In The Kingdom of Lajazer, about 175 mi northeast of Vellin, near The Aonesse and Leyone." },
  { n: "Bordei", cat: "town", x: 1798, y: 1584, k: "The Academy", d: "In The Academy, near Port Besk and Tiren." },
  { n: "Borgeste", cat: "town", x: 2385, y: 1346, k: "The Kingdom of Lajazer", d: "In The Kingdom of Lajazer, about 775 mi northeast of Vellin, near Sretan and Weca." },
  { n: "Brae", cat: "town", x: 6059, y: 1232, k: "The Kingdom of Ociyaran", d: "In The Kingdom of Ociyaran, about 450 mi west of Zada, near Oa and Stagna." },
  { n: "Bralk", cat: "town", x: 5611, y: 2160, k: "The Kingdom of Tarmet", d: "In The Kingdom of Tarmet, about 1175 mi east of Bela, near Allisto and Dugwil." },
  { n: "Brandhal", cat: "town", x: 4132, y: 1101, k: "The Kingdom of Atriki", d: "In The Kingdom of Atriki, about 325 mi southeast of Elgan, near Lagowyal and Negel." },
  { n: "Brannik", cat: "town", x: 3339, y: 2491, k: "The Kingdom of Civer", d: "In The Kingdom of Civer, about 150 mi east of Lorne, near Gorst and Civer." },
  { n: "Breno", cat: "town", x: 6149, y: 1138, k: "The Kingdom of Ociyaran", d: "In The Kingdom of Ociyaran, about 375 mi west of Zada, near Lidresa and Lun." },
  { n: "Brentola", cat: "town", x: 6737, y: 1367, k: "The Kingdom of Ociyaran", d: "In The Kingdom of Ociyaran, about 125 mi southeast of Zada, near Dragse and Pell'oro." },
  { n: "Breston", cat: "town", x: 2541, y: 1679, k: "The Kingdom of Lajazer", d: "In The Kingdom of Lajazer, about 650 mi northeast of Vellin, near Casqen Zaeri and Meliut." },
  { n: "Brielega", cat: "town", x: 3515, y: 1278, k: "The Kingdom of Tarmet", d: "In The Kingdom of Tarmet, about 800 mi northwest of Bela, near Coloni and Egodi." },
  { n: "Burane", cat: "town", x: 6859, y: 1208, k: "The Kingdom of Ociyaran", d: "In The Kingdom of Ociyaran, about 225 mi east of Zada, near Mira and Squero." },
  { n: "Byeola", cat: "town", x: 6551, y: 2377, k: "The Kingdom of Berlailia", d: "In The Kingdom of Berlailia, about 200 mi west of Hadirel, near Sehrok and Sahlen." },
  { n: "Caduto", cat: "town", x: 6598, y: 1558, k: "The Kingdom of Berlailia", d: "In The Kingdom of Berlailia, about 625 mi north of Hadirel, near Tsenmar and Pelefer." },
  { n: "Caelmu", cat: "town", x: 7246, y: 3068, k: "The Kingdom of Berlailia", d: "In The Kingdom of Berlailia, about 700 mi southeast of Hadirel, near Orjin and Port Sael." },
  { n: "Cala", cat: "town", x: 6295, y: 921, k: "The Kingdom of Ociyaran", d: "In The Kingdom of Ociyaran, about 375 mi northwest of Zada, near Senna and Senalda." },
  { n: "Cale", cat: "town", x: 1888, y: 1900, k: "The Kingdom of Lajazer", d: "In The Kingdom of Lajazer, about 200 mi north of Vellin, near Matsene and Dushre." },
  { n: "Calyea", cat: "town", x: 4433, y: 2110, k: "The Kingdom of Tarmet", d: "In The Kingdom of Tarmet, about 250 mi east of Bela, near Thelea and Mother's hip." },
  { n: "Camrudar", cat: "town", x: 4485, y: 1220, k: "The Kingdom of Atriki", d: "In The Kingdom of Atriki, about 600 mi southeast of Elgan, near Inqua and Ridal." },
  { n: "Cardoric", cat: "town", x: 3397, y: 1451, k: "The Kingdom of Tarmet", d: "In The Kingdom of Tarmet, about 750 mi northwest of Bela, near Egodi and Lujian." },
  { n: "Caspara", cat: "town", x: 4037, y: 2305, k: "The Kingdom of Tarmet", d: "In The Kingdom of Tarmet, about 200 mi south of Bela, near Granosa and Anjelea." },
  { n: "Casqen Zaeri", cat: "town", x: 2534, y: 1718, k: "The Kingdom of Lajazer", d: "In The Kingdom of Lajazer, about 625 mi northeast of Vellin, near Breston and Zagare." },
  { n: "Cerby", cat: "town", x: 3755, y: 2024, k: "The Kingdom of Tarmet", d: "In The Kingdom of Tarmet, about 300 mi west of Bela, near Zerpe and Keba." },
  { n: "Cesro", cat: "town", x: 2380, y: 2119, k: "The Kingdom of Lajazer", d: "In The Kingdom of Lajazer, about 400 mi east of Vellin, near Jani and Benale." },
  { n: "Chiavanto", cat: "town", x: 6951, y: 1049, k: "The Kingdom of Ociyaran", d: "In The Kingdom of Ociyaran, about 325 mi northeast of Zada, near Riy and Ys." },
  { n: "Chiozza", cat: "town", x: 6818, y: 802, k: "The Kingdom of Ociyaran", d: "In The Kingdom of Ociyaran, about 425 mi northeast of Zada, near Tesora and Latso." },
  { n: "Cira", cat: "town", x: 6266, y: 1260, k: "The Kingdom of Ociyaran", d: "In The Kingdom of Ociyaran, about 275 mi west of Zada, near Roi and Cresp." },
  { n: "Civer", cat: "town", x: 3234, y: 2496, k: "The Kingdom of Civer", d: "In The Kingdom of Civer, about 75 mi southeast of Lorne, near Lorne and Brannik." },
  { n: "Claieso", cat: "town", x: 6765, y: 1261, k: "The Kingdom of Ociyaran", d: "In The Kingdom of Ociyaran, about 125 mi east of Zada, near Dragse and Burane." },
  { n: "Coelys", cat: "town", x: 3121, y: 1601, k: "The Kingdom of Tarmet", d: "In The Kingdom of Tarmet, about 875 mi northwest of Bela, near Mema and Ezon." },
  { n: "Colle", cat: "town", x: 6951, y: 1175, k: "The Kingdom of Ociyaran", d: "In The Kingdom of Ociyaran, about 300 mi east of Zada, near Squero and Mira." },
  { n: "Coloni", cat: "town", x: 3499, y: 1183, k: "The Kingdom of Tarmet", d: "In The Kingdom of Tarmet, about 875 mi northwest of Bela, near Seppegiu and Brielega." },
  { n: "Comei", cat: "town", x: 2234, y: 2009, k: "The Kingdom of Lajazer", d: "In The Kingdom of Lajazer, about 300 mi northeast of Vellin, near Mepren and Avege." },
  { n: "Corocco", cat: "town", x: 3271, y: 957, k: "The Kingdom of Tarmet", d: "In The Kingdom of Tarmet, about 1125 mi northwest of Bela, near Port Aresca and Neaea." },
  { n: "Corsa", cat: "town", x: 6417, y: 1118, k: "The Kingdom of Ociyaran", d: "In The Kingdom of Ociyaran, about 200 mi northwest of Zada, near Gora and Vigila." },
  { n: "Corvane", cat: "town", x: 2979, y: 1768, k: "The Kingdom of Civer", d: "In The Kingdom of Civer, about 550 mi north of Lorne, near Baest and Apric." },
  { n: "Cosar", cat: "town", x: 3756, y: 2196, k: "The Kingdom of Tarmet", d: "In The Kingdom of Tarmet, about 325 mi west of Bela, near Golana and Doka." },
  { n: "Cresp", cat: "town", x: 6345, y: 1321, k: "The Kingdom of Ociyaran", d: "In The Kingdom of Ociyaran, about 200 mi west of Zada, near Nelva and Rewalen." },
  { n: "Croco", cat: "town", x: 3207, y: 1735, k: "The Kingdom of Tarmet", d: "In The Kingdom of Tarmet, about 775 mi west of Bela, near Maadol and Ezon." },
  { n: "Cuola", cat: "town", x: 4296, y: 1808, k: "The Kingdom of Tarmet", d: "In The Kingdom of Tarmet, about 250 mi northeast of Bela, near Lokea and Teirenna." },
  { n: "Cymea", cat: "town", x: 3960, y: 1512, k: "The Kingdom of Tarmet", d: "In The Kingdom of Tarmet, about 450 mi north of Bela, near Malea and Adaani." },
  { n: "Dahn", cat: "town", x: 5625, y: 2365, k: "The Kingdom of Tarmet", d: "In The Kingdom of Tarmet, about 1225 mi east of Bela, near Sevq and Hauk." },
  { n: "Daltsen", cat: "town", x: 6603, y: 2224, k: "The Kingdom of Berlailia", d: "In The Kingdom of Berlailia, about 175 mi northwest of Hadirel, near Sehrok and Byeola." },
  { n: "Demia", cat: "town", x: 4982, y: 2505, k: "The Kingdom of Tarmet", d: "In The Kingdom of Tarmet, about 775 mi southeast of Bela, near Gai and Mireb." },
  { n: "Demre", cat: "town", x: 5300, y: 2653, k: "The Kingdom of Tarmet", d: "In The Kingdom of Tarmet, about 1050 mi southeast of Bela, near Limn and Amba." },
  { n: "Denkay", cat: "town", x: 5389, y: 2041, k: "The Kingdom of Tarmet", d: "In The Kingdom of Tarmet, about 1000 mi east of Bela, near Vagust and Rudeth." },
  { n: "Dessane", cat: "town", x: 3175, y: 2584, k: "The Kingdom of Civer", d: "In The Kingdom of Civer, about 125 mi south of Lorne, near LakeDulve and Civer." },
  { n: "Deyare", cat: "town", x: 2117, y: 1734, k: "The Kingdom of Lajazer", d: "In The Kingdom of Lajazer, about 400 mi northeast of Vellin, near Macerin and Hadber." },
  { n: "Dira", cat: "town", x: 1944, y: 1975, k: "The Kingdom of Lajazer", d: "In The Kingdom of Lajazer, about 150 mi north of Vellin, near Ostoke and Melerte." },
  { n: "Doka", cat: "town", x: 3885, y: 2135, k: "The Kingdom of Tarmet", d: "In The Kingdom of Tarmet, about 200 mi west of Bela, near Keba and Granosa." },
  { n: "Dordbin", cat: "town", x: 5183, y: 2833, k: "The Kingdom of Tarmet", d: "In The Kingdom of Tarmet, about 1050 mi southeast of Bela, near Limn and Mireb." },
  { n: "Doresi", cat: "town", x: 6687, y: 1054, k: "The Kingdom of Ociyaran", d: "In The Kingdom of Ociyaran, about 200 mi north of Zada, near Vinalta and Neska." },
  { n: "Dragse", cat: "town", x: 6801, y: 1304, k: "The Kingdom of Ociyaran", d: "In The Kingdom of Ociyaran, about 150 mi east of Zada, near Claieso and Brentola." },
  { n: "Drav Tari", cat: "town", x: 2682, y: 2031, k: "The Kingdom of Civer", d: "In The Kingdom of Civer, about 500 mi northwest of Lorne, near Lorig and Hoab." },
  { n: "Dremk", cat: "town", x: 5227, y: 2078, k: "The Kingdom of Tarmet", d: "In The Kingdom of Tarmet, about 875 mi east of Bela, near Tusjin and Tsir." },
  { n: "Drenia", cat: "town", x: 3399, y: 1609, k: "The Kingdom of Tarmet", d: "In The Kingdom of Tarmet, about 675 mi northwest of Bela, near Lujian and Oscana." },
  { n: "Drin", cat: "town", x: 3409, y: 2170, k: "The Kingdom of Civer", d: "In The Kingdom of Civer, about 300 mi northeast of Lorne, near Urdey and Pelk." },
  { n: "Drosk", cat: "town", x: 3026, y: 2458, k: "The Kingdom of Civer", d: "In The Kingdom of Civer, about 100 mi west of Lorne, near Sindber and Tolm." },
  { n: "Druun", cat: "town", x: 4450, y: 2621, k: "The Kingdom of Tarmet", d: "In The Kingdom of Tarmet, about 525 mi southeast of Bela, near Eskua and Anye." },
  { n: "Dugwil", cat: "town", x: 5513, y: 2200, k: "The Kingdom of Tarmet", d: "In The Kingdom of Tarmet, about 1100 mi east of Bela, near Bralk and Allisto." },
  { n: "Durk", cat: "town", x: 3471, y: 2390, k: "The Kingdom of Civer", d: "In The Kingdom of Civer, about 250 mi east of Lorne, near The Pontesi and Gorst." },
  { n: "Dushre", cat: "town", x: 1893, y: 1824, k: "The Kingdom of Lajazer", d: "In The Kingdom of Lajazer, about 275 mi north of Vellin, near Lene and Cale." },
  { n: "Egodi", cat: "town", x: 3449, y: 1369, k: "The Kingdom of Tarmet", d: "In The Kingdom of Tarmet, about 775 mi northwest of Bela, near Cardoric and Eloe." },
  { n: "Elemea", cat: "town", x: 4459, y: 1753, k: "The Kingdom of Tarmet", d: "In The Kingdom of Tarmet, about 350 mi northeast of Bela, near Vashonna and Ralta." },
  { n: "Eloe", cat: "town", x: 3349, y: 1344, k: "The Kingdom of Tarmet", d: "In The Kingdom of Tarmet, about 850 mi northwest of Bela, near Gelona and Egodi." },
  { n: "Eryd", cat: "town", x: 4014, y: 532, k: "The Kingdom of Atriki", d: "In The Kingdom of Atriki, about 175 mi northeast of Elgan, near Yleka and Nisclair." },
  { n: "Erygal", cat: "town", x: 3973, y: 923, k: "The Kingdom of Atriki", d: "In The Kingdom of Atriki, about 150 mi south of Elgan, near Eskol and Elgan." },
  { n: "Eshae", cat: "town", x: 2230, y: 1552, k: "The Kingdom of Lajazer", d: "In The Kingdom of Lajazer, about 550 mi northeast of Vellin, near Itara and Belei." },
  { n: "Esio", cat: "town", x: 6588, y: 1123, k: "The Kingdom of Ociyaran", d: "In The Kingdom of Ociyaran, about 125 mi north of Zada, near Neska and Gabbia." },
  { n: "Eskert", cat: "town", x: 4617, y: 706, k: "The Kingdom of Atriki", d: "In The Kingdom of Atriki, about 550 mi east of Elgan, near Riyen and Ortuqil." },
  { n: "Eskol", cat: "town", x: 3891, y: 869, k: "The Kingdom of Atriki", d: "In The Kingdom of Atriki, about 100 mi south of Elgan, near Erygal and Elgan." },
  { n: "Eskua", cat: "town", x: 4447, y: 2735, k: "The Kingdom of Tarmet", d: "In The Kingdom of Tarmet, about 600 mi southeast of Bela, near Druun and Oskaba." },
  { n: "Etanda", cat: "town", x: 3115, y: 1013, k: "The Kingdom of Tarmet", d: "In The Kingdom of Tarmet, about 1175 mi northwest of Bela, near Osegri and Port Aresca." },
  { n: "Eynora", cat: "town", x: 3555, y: 102, k: "The Kingdom of Atriki", d: "In The Kingdom of Atriki, about 575 mi northwest of Elgan, near Lagora and Tilnyeau." },
  { n: "Ezon", cat: "town", x: 3274, y: 1601, k: "The Kingdom of Tarmet", d: "In The Kingdom of Tarmet, about 775 mi northwest of Bela, near Lasten and Lujian." },
  { n: "Fayede", cat: "town", x: 1968, y: 1762, k: "The Kingdom of Lajazer", d: "In The Kingdom of Lajazer, about 325 mi north of Vellin, near Lene and Neribe." },
  { n: "Feacen", cat: "town", x: 2915, y: 2425, k: "The Kingdom of Civer", d: "In The Kingdom of Civer, about 200 mi west of Lorne, near Drosk and Tolm." },
  { n: "Fesso", cat: "town", x: 2871, y: 2054, k: "The Kingdom of Civer", d: "In The Kingdom of Civer, about 375 mi northwest of Lorne, near Hoab and Olbe." },
  { n: "Foce", cat: "town", x: 6457, y: 975, k: "The Kingdom of Ociyaran", d: "In The Kingdom of Ociyaran, about 275 mi northwest of Zada, near Malamo and Port Volpa." },
  { n: "Fordei", cat: "town", x: 2310, y: 1459, k: "The Kingdom of Lajazer", d: "In The Kingdom of Lajazer, about 650 mi northeast of Vellin, near Belei and Lermea." },
  { n: "Forea", cat: "town", x: 4091, y: 2467, k: "The Kingdom of Tarmet", d: "In The Kingdom of Tarmet, about 325 mi south of Bela, near Pondata and Riedra." },
  { n: "Gabbia", cat: "town", x: 6498, y: 1087, k: "The Kingdom of Ociyaran", d: "In The Kingdom of Ociyaran, about 175 mi northwest of Zada, near Malamo and Vigila." },
  { n: "Gaedu", cat: "town", x: 6878, y: 2529, k: "The Kingdom of Berlailia", d: "In The Kingdom of Berlailia, about 175 mi south of Hadirel, near Yula and The Magic Tower." },
  { n: "Gai", cat: "town", x: 5148, y: 2529, k: "The Kingdom of Tarmet", d: "In The Kingdom of Tarmet, about 900 mi southeast of Bela, near Hagia Demre and Demia." },
  { n: "Galmun", cat: "town", x: 6579, y: 2633, k: "The Kingdom of Berlailia", d: "In The Kingdom of Berlailia, about 300 mi southwest of Hadirel, near Junjeo and Torad." },
  { n: "Garen", cat: "town", x: 4638, y: 1514, k: "The Kingdom of Tarmet", d: "In The Kingdom of Tarmet, about 600 mi northeast of Bela, near Oryur and Nyedal." },
  { n: "Gelona", cat: "town", x: 3310, y: 1278, k: "The Kingdom of Tarmet", d: "In The Kingdom of Tarmet, about 900 mi northwest of Bela, near Tenda and Eloe." },
  { n: "Genga", cat: "town", x: 2660, y: 1695, k: "The Kingdom of Lajazer", d: "In The Kingdom of Lajazer, about 725 mi northeast of Vellin, near Resate and Meliut." },
  { n: "Giagior", cat: "town", x: 2903, y: 1448, k: "The Kingdom of Tarmet", d: "In The Kingdom of Tarmet, about 1100 mi northwest of Bela, near Tagre and Iaga." },
  { n: "Gilsa", cat: "town", x: 5714, y: 2969, k: "The Kingdom of Berlailia", d: "In The Kingdom of Berlailia, about 1000 mi southwest of Hadirel, near Maryos and Bohan." },
  { n: "Gjen", cat: "town", x: 6895, y: 2944, k: "The Kingdom of Berlailia", d: "In The Kingdom of Berlailia, about 500 mi south of Hadirel, near Qunag and Namilna." },
  { n: "Gogla", cat: "town", x: 7016, y: 2123, k: "The Kingdom of Berlailia", d: "In The Kingdom of Berlailia, about 250 mi northeast of Hadirel, near Verna Tari and Negiet." },
  { n: "Golana", cat: "town", x: 3648, y: 2152, k: "The Kingdom of Tarmet", d: "In The Kingdom of Tarmet, about 400 mi west of Bela, near Cosar and Lage." },
  { n: "Gondes", cat: "town", x: 3866, y: 1311, k: "The Kingdom of Tarmet", d: "In The Kingdom of Tarmet, about 625 mi north of Bela, near The Duriaan and Adaani." },
  { n: "Gora", cat: "town", x: 6373, y: 1170, k: "The Kingdom of Ociyaran", d: "In The Kingdom of Ociyaran, about 200 mi northwest of Zada, near Corsa and Vigila." },
  { n: "Gorma", cat: "town", x: 4462, y: 520, k: "The Kingdom of Atriki", d: "In The Kingdom of Atriki, about 475 mi east of Elgan, near Ortuqil and Aresada." },
  { n: "Gorst", cat: "town", x: 3338, y: 2413, k: "The Kingdom of Civer", d: "In The Kingdom of Civer, about 150 mi east of Lorne, near Brannik and Civer." },
  { n: "Goteivane", cat: "town", x: 2290, y: 2276, k: "The Kingdom of Lajazer", d: "In The Kingdom of Lajazer, about 350 mi east of Vellin, near The Santie and Ledesca." },
  { n: "Granosa", cat: "town", x: 3959, y: 2211, k: "The Kingdom of Tarmet", d: "In The Kingdom of Tarmet, about 175 mi southwest of Bela, near Doka and Tarl." },
  { n: "Grotta", cat: "town", x: 6174, y: 1547, k: "The Kingdom of Ociyaran", d: "In The Kingdom of Ociyaran, about 400 mi southwest of Zada, near Yemasera and Pratesi." },
  { n: "Hadber", cat: "town", x: 2048, y: 1703, k: "The Kingdom of Lajazer", d: "In The Kingdom of Lajazer, about 400 mi north of Vellin, near Deyare and Tericaer." },
  { n: "Hagia Demre", cat: "town", x: 5212, y: 2425, k: "The Kingdom of Tarmet", d: "In The Kingdom of Tarmet, about 900 mi east of Bela, near Gai and Tsir." },
  { n: "Hagiora", cat: "town", x: 5081, y: 1457, k: "The Kingdom of Tarmet", d: "In The Kingdom of Tarmet, about 900 mi northeast of Bela, near Amberactserun and Vekta's territory." },
  { n: "Hagiore", cat: "town", x: 5540, y: 2512, k: "The Kingdom of Tarmet", d: "In The Kingdom of Tarmet, about 1175 mi east of Bela, near Amba and Dahn." },
  { n: "Hagn", cat: "town", x: 5410, y: 2285, k: "The Kingdom of Tarmet", d: "In The Kingdom of Tarmet, about 1025 mi east of Bela, near Hauk and Dugwil." },
  { n: "Halkere", cat: "town", x: 2459, y: 1983, k: "The Kingdom of Lajazer", d: "In The Kingdom of Lajazer, about 475 mi east of Vellin, near Benale and Oahat." },
  { n: "Hanora", cat: "town", x: 6986, y: 1645, k: "The Kingdom of Berlailia", d: "In The Kingdom of Berlailia, about 550 mi north of Hadirel, near Tsenmar and Kanghol." },
  { n: "Hashren", cat: "town", x: 2292, y: 1607, k: "The Kingdom of Lajazer", d: "In The Kingdom of Lajazer, about 550 mi northeast of Vellin, near Verne and Alben." },
  { n: "Hauk", cat: "town", x: 5534, y: 2329, k: "The Kingdom of Tarmet", d: "In The Kingdom of Tarmet, about 1150 mi east of Bela, near Sevq and Dahn." },
  { n: "Hepen", cat: "town", x: 1853, y: 2066, k: "The Kingdom of Lajazer", d: "In The Kingdom of Lajazer, about 75 mi north of Vellin, near Port Naole and Melerte." },
  { n: "Heusel", cat: "town", x: 1987, y: 1886, k: "The Kingdom of Lajazer", d: "In The Kingdom of Lajazer, about 225 mi north of Vellin, near The Aoner and Lene." },
  { n: "Hevetane", cat: "town", x: 4334, y: 2275, k: "The Kingdom of Tarmet", d: "In The Kingdom of Tarmet, about 225 mi southeast of Bela, near Orim and Nordos." },
  { n: "Hoab", cat: "town", x: 2793, y: 2123, k: "The Kingdom of Civer", d: "In The Kingdom of Civer, about 375 mi northwest of Lorne, near Fesso and Drav Tari." },
  { n: "Hoam", cat: "town", x: 4279, y: 1583, k: "The Kingdom of Tarmet", d: "In The Kingdom of Tarmet, about 400 mi north of Bela, near Lokea and Aluun." },
  { n: "Holve", cat: "town", x: 2426, y: 1502, k: "The Kingdom of Lajazer", d: "In The Kingdom of Lajazer, about 675 mi northeast of Vellin, near Isece and Melerb." },
  { n: "Honet", cat: "town", x: 2146, y: 2209, k: "The Kingdom of Lajazer", d: "In The Kingdom of Lajazer, about 225 mi east of Vellin, near Nayen and Loer." },
  { n: "Hulber", cat: "town", x: 2720, y: 2492, k: "The Kingdom of Civer", d: "In The Kingdom of Civer, about 350 mi west of Lorne, near Welk and Feacen." },
  { n: "Iaga", cat: "town", x: 2856, y: 1540, k: "The Kingdom of Tarmet", d: "In The Kingdom of Tarmet, about 1100 mi west of Bela, near Thevia and Lanmi." },
  { n: "Iela", cat: "town", x: 4690, y: 1741, k: "The Kingdom of Tarmet", d: "In The Kingdom of Tarmet, about 500 mi northeast of Bela, near Laaya and Luja." },
  { n: "Ilkane", cat: "town", x: 4353, y: 761, k: "The Kingdom of Atriki", d: "In The Kingdom of Atriki, about 350 mi east of Elgan, near Nalochl and Maharg." },
  { n: "Ilvo", cat: "town", x: 6155, y: 1323, k: "The Kingdom of Ociyaran", d: "In The Kingdom of Ociyaran, about 350 mi west of Zada, near Stagna and Movo." },
  { n: "Inem", cat: "town", x: 4768, y: 1868, k: "The Kingdom of Tarmet", d: "In The Kingdom of Tarmet, about 525 mi east of Bela, near Avaani and Luja." },
  { n: "Inke", cat: "town", x: 4133, y: 1474, k: "The Kingdom of Tarmet", d: "In The Kingdom of Tarmet, about 475 mi north of Bela, near Aluun and Resia." },
  { n: "Inqua", cat: "town", x: 4416, y: 1322, k: "The Kingdom of Tarmet", d: "In The Kingdom of Tarmet, about 625 mi north of Bela, near Camrudar and Oryur." },
  { n: "Isece", cat: "town", x: 2456, y: 1548, k: "The Kingdom of Lajazer", d: "In The Kingdom of Lajazer, about 675 mi northeast of Vellin, near Holve and Wisten." },
  { n: "Itara", cat: "town", x: 2190, y: 1487, k: "The Kingdom of Lajazer", d: "In The Kingdom of Lajazer, about 600 mi northeast of Vellin, near Eshae and Atanie." },
  { n: "Jani", cat: "town", x: 2359, y: 2049, k: "The Kingdom of Lajazer", d: "In The Kingdom of Lajazer, about 400 mi east of Vellin, near Cesro and Avege." },
  { n: "Jaserey", cat: "town", x: 2277, y: 1695, k: "The Kingdom of Lajazer", d: "In The Kingdom of Lajazer, about 500 mi northeast of Vellin, near Verne and Nyeo." },
  { n: "Jhera", cat: "town", x: 6748, y: 920, k: "The Kingdom of Ociyaran", d: "In The Kingdom of Ociyaran, about 325 mi north of Zada, near Vinalta and Latso." },
  { n: "Jiego", cat: "town", x: 2396, y: 1868, k: "The Kingdom of Lajazer", d: "In The Kingdom of Lajazer, about 475 mi northeast of Vellin, near Rewqo and Orcan." },
  { n: "Junjeo", cat: "town", x: 6622, y: 2705, k: "The Kingdom of Berlailia", d: "In The Kingdom of Berlailia, about 325 mi southwest of Hadirel, near Galmun and Liaerton." },
  { n: "Jurva", cat: "town", x: 3158, y: 2091, k: "The Kingdom of Civer", d: "In The Kingdom of Civer, about 275 mi north of Lorne, near Awq Tari and Rosk." },
  { n: "Kanghol", cat: "town", x: 6981, y: 1316, k: "The Kingdom of Berlailia", d: "In The Kingdom of Berlailia, about 825 mi north of Hadirel, near Mira and Colle." },
  { n: "Kanidon", cat: "town", x: 2547, y: 1539, k: "The Kingdom of Lajazer", d: "In The Kingdom of Lajazer, about 725 mi northeast of Vellin, near Vaia and Meliut." },
  { n: "Keba", cat: "town", x: 3896, y: 2048, k: "The Kingdom of Tarmet", d: "In The Kingdom of Tarmet, about 200 mi west of Bela, near Tereas and Doka." },
  { n: "Kessa", cat: "town", x: 3714, y: 1774, k: "The Kingdom of Tarmet", d: "In The Kingdom of Tarmet, about 400 mi northwest of Bela, near Zerpe and Olune." },
  { n: "Kidaris", cat: "town", x: 5107, y: 1814, k: "The Kingdom of Tarmet", d: "In The Kingdom of Tarmet, about 800 mi east of Bela, near Semhol and Medhuk." },
  { n: "Kuldara", cat: "town", x: 4256, y: 2749, k: "The Kingdom of Tarmet", d: "In The Kingdom of Tarmet, about 550 mi south of Bela, near Eskua and Anye." },
  { n: "Kunes", cat: "town", x: 2638, y: 1260, k: "The Kingdom of Lajazer", d: "In The Kingdom of Lajazer, about 950 mi northeast of Vellin, near Baram and Palere." },
  { n: "Laaya", cat: "town", x: 4622, y: 1818, k: "The Kingdom of Tarmet", d: "In The Kingdom of Tarmet, about 425 mi northeast of Bela, near Ristea and Iela." },
  { n: "Lage", cat: "town", x: 3599, y: 2008, k: "The Kingdom of Tarmet", d: "In The Kingdom of Tarmet, about 425 mi west of Bela, near Zerpe and Shaer." },
  { n: "Lagora", cat: "town", x: 3496, y: 202, k: "The Kingdom of Atriki", d: "In The Kingdom of Atriki, about 550 mi northwest of Elgan, near Eynora and Tilnyeau." },
  { n: "Lagowyal", cat: "town", x: 4082, y: 1168, k: "The Kingdom of Atriki", d: "In The Kingdom of Atriki, about 375 mi south of Elgan, near Brandhal and The Maadun." },
  { n: "LakeDulve", cat: "town", x: 3128, y: 2519, k: "The Kingdom of Civer", d: "In The Kingdom of Civer, about 75 mi southwest of Lorne, near Dessane and Lorne." },
  { n: "Lanmi", cat: "town", x: 2771, y: 1592, k: "The Kingdom of Tarmet", d: "In The Kingdom of Tarmet, about 1150 mi west of Bela, near Noraho and Noju." },
  { n: "Laone", cat: "town", x: 2272, y: 2394, k: "The Kingdom of Lajazer", d: "In The Kingdom of Lajazer, about 375 mi southeast of Vellin, near Meprie Teish and Goteivane." },
  { n: "Larida", cat: "town", x: 6077, y: 1437, k: "The Kingdom of Ociyaran", d: "In The Kingdom of Ociyaran, about 425 mi west of Zada, near Yemasera and Reda." },
  { n: "Lasten", cat: "town", x: 3263, y: 1506, k: "The Kingdom of Tarmet", d: "In The Kingdom of Tarmet, about 825 mi northwest of Bela, near Ezon and Lujian." },
  { n: "Latso", cat: "town", x: 6698, y: 820, k: "The Kingdom of Ociyaran", d: "In The Kingdom of Ociyaran, about 375 mi north of Zada, near Pampira and Paro." },
  { n: "Ledea", cat: "town", x: 4986, y: 2102, k: "The Kingdom of Tarmet", d: "In The Kingdom of Tarmet, about 675 mi east of Bela, near Loria and Oermada." },
  { n: "Ledesca", cat: "town", x: 2369, y: 2255, k: "The Kingdom of Lajazer", d: "In The Kingdom of Lajazer, about 400 mi east of Vellin, near Goteivane and The Santie." },
  { n: "Lefa", cat: "town", x: 5039, y: 827, k: "The Kingdom of Atriki", d: "In The Kingdom of Atriki, about 900 mi east of Elgan, near Nalchal and Noramec." },
  { n: "Lendara", cat: "town", x: 4132, y: 1962, k: "The Kingdom of Tarmet", d: "In The Kingdom of Tarmet, about 75 mi north of Bela, near Asmeta and Bela." },
  { n: "Lene", cat: "town", x: 1947, y: 1812, k: "The Kingdom of Lajazer", d: "In The Kingdom of Lajazer, about 275 mi north of Vellin, near Fayede and Dushre." },
  { n: "Lermea", cat: "town", x: 2313, y: 1386, k: "The Kingdom of Lajazer", d: "In The Kingdom of Lajazer, about 700 mi northeast of Vellin, near Fordei and Borgeste." },
  { n: "Leyone", cat: "town", x: 2037, y: 1961, k: "The Kingdom of Lajazer", d: "In The Kingdom of Lajazer, about 200 mi northeast of Vellin, near Boletre  Begai and Heusel." },
  { n: "Lezna", cat: "town", x: 6210, y: 1467, k: "The Kingdom of Ociyaran", d: "In The Kingdom of Ociyaran, about 350 mi southwest of Zada, near Argu and Movo." },
  { n: "Liaerton", cat: "town", x: 6695, y: 2797, k: "The Kingdom of Berlailia", d: "In The Kingdom of Berlailia, about 375 mi south of Hadirel, near Junjeo and Namilna." },
  { n: "Liasen", cat: "town", x: 2005, y: 2092, k: "The Kingdom of Lajazer", d: "In The Kingdom of Lajazer, about 125 mi northeast of Vellin, near The Aonesse and Barete." },
  { n: "Lidresa", cat: "town", x: 6197, y: 1054, k: "The Kingdom of Ociyaran", d: "In The Kingdom of Ociyaran, about 375 mi northwest of Zada, near Breno and Lun." },
  { n: "Limn", cat: "town", x: 5330, y: 2784, k: "The Kingdom of Tarmet", d: "In The Kingdom of Tarmet, about 1125 mi southeast of Bela, near Demre and Dordbin." },
  { n: "Linjet", cat: "town", x: 2729, y: 1178, k: "The Kingdom of Lajazer", d: "In The Kingdom of Lajazer, about 1025 mi northeast of Vellin, near Baram and Raiye." },
  { n: "Lioe", cat: "town", x: 3231, y: 1373, k: "The Kingdom of Tarmet", d: "In The Kingdom of Tarmet, about 900 mi northwest of Bela, near Mossima and Eloe." },
  { n: "Liviao", cat: "town", x: 2718, y: 1403, k: "The Kingdom of Tarmet", d: "In The Kingdom of Tarmet, about 1250 mi northwest of Bela, near Palere and Annagi." },
  { n: "Loer", cat: "town", x: 2082, y: 2140, k: "The Kingdom of Lajazer", d: "In The Kingdom of Lajazer, about 175 mi east of Vellin, near Liasen and Nayen." },
  { n: "Lokea", cat: "town", x: 4267, y: 1715, k: "The Kingdom of Tarmet", d: "In The Kingdom of Tarmet, about 300 mi north of Bela, near Teirenna and Cuola." },
  { n: "Loria", cat: "town", x: 5039, y: 2181, k: "The Kingdom of Tarmet", d: "In The Kingdom of Tarmet, about 725 mi east of Bela, near Ledea and Maaru Maaru." },
  { n: "Lorig", cat: "town", x: 2598, y: 2097, k: "The Kingdom of Civer", d: "In The Kingdom of Civer, about 525 mi northwest of Lorne, near Drav Tari and Benale." },
  { n: "Lovec", cat: "town", x: 2136, y: 1982, k: "The Kingdom of Lajazer", d: "In The Kingdom of Lajazer, about 250 mi northeast of Vellin, near Boletre  Begai and Leyone." },
  { n: "Lower Cosar", cat: "town", x: 3822, y: 2376, k: "The Kingdom of Tarmet", d: "In The Kingdom of Tarmet, about 350 mi southwest of Bela, near Anjelea and Tarl." },
  { n: "Luja", cat: "town", x: 4820, y: 1759, k: "The Kingdom of Tarmet", d: "In The Kingdom of Tarmet, about 600 mi northeast of Bela, near Aoim and Inem." },
  { n: "Lujian", cat: "town", x: 3377, y: 1549, k: "The Kingdom of Tarmet", d: "In The Kingdom of Tarmet, about 725 mi northwest of Bela, near Drenia and Cardoric." },
  { n: "Lun", cat: "town", x: 6272, y: 1129, k: "The Kingdom of Ociyaran", d: "In The Kingdom of Ociyaran, about 300 mi northwest of Zada, near Vallaforta and Lidresa." },
  { n: "Maadol", cat: "town", x: 3212, y: 1850, k: "The Kingdom of Civer", d: "In The Kingdom of Civer, about 475 mi north of Lorne, near Croco and Oradi." },
  { n: "Maaru Maaru", cat: "town", x: 4940, y: 2294, k: "The Kingdom of Tarmet", d: "In The Kingdom of Tarmet, about 675 mi east of Bela, near Loria and Menejela." },
  { n: "Macerin", cat: "town", x: 2157, y: 1775, k: "The Kingdom of Lajazer", d: "In The Kingdom of Lajazer, about 375 mi northeast of Vellin, near Deyare and Neribe." },
  { n: "Madreu", cat: "town", x: 2363, y: 1745, k: "The Kingdom of Lajazer", d: "In The Kingdom of Lajazer, about 500 mi northeast of Vellin, near Peske and The Razane.", alt: "Madu" },
  { n: "Maharg", cat: "town", x: 4212, y: 706, k: "The Kingdom of Atriki", d: "In The Kingdom of Atriki, about 225 mi east of Elgan, near Ilkane and Snurb." },
  { n: "Malamo", cat: "town", x: 6473, y: 1031, k: "The Kingdom of Ociyaran", d: "In The Kingdom of Ociyaran, about 225 mi northwest of Zada, near Foce and Gabbia." },
  { n: "Malea", cat: "town", x: 3987, y: 1584, k: "The Kingdom of Tarmet", d: "In The Kingdom of Tarmet, about 400 mi north of Bela, near Cymea and Ostara." },
  { n: "Malim", cat: "town", x: 4276, y: 1960, k: "The Kingdom of Tarmet", d: "In The Kingdom of Tarmet, about 150 mi northeast of Bela, near Tarmeda and Mother's hip." },
  { n: "Maryos", cat: "town", x: 5446, y: 2898, k: "The Kingdom of Tarmet", d: "In The Kingdom of Tarmet, about 1250 mi southeast of Bela, near Limn and Selvet." },
  { n: "Masen", cat: "town", x: 2499, y: 1862, k: "The Kingdom of Lajazer", d: "In The Kingdom of Lajazer, about 550 mi northeast of Vellin, near Oahat and Zagare." },
  { n: "Masotom", cat: "town", x: 3702, y: 1254, k: "The Kingdom of Tarmet", d: "In The Kingdom of Tarmet, about 725 mi northwest of Bela, near Tiamma and Renzolo." },
  { n: "Matsene", cat: "town", x: 1838, y: 1931, k: "The Kingdom of Lajazer", d: "In The Kingdom of Lajazer, about 175 mi north of Vellin, near Thalen and Cale." },
  { n: "Medhuk", cat: "town", x: 5214, y: 1853, k: "The Kingdom of Tarmet", d: "In The Kingdom of Tarmet, about 875 mi east of Bela, near Anthela and Kidaris." },
  { n: "Melerb", cat: "town", x: 2451, y: 1443, k: "The Kingdom of Lajazer", d: "In The Kingdom of Lajazer, about 725 mi northeast of Vellin, near Holve and Isece." },
  { n: "Melerte", cat: "town", x: 1853, y: 1992, k: "The Kingdom of Lajazer", d: "In The Kingdom of Lajazer, about 125 mi north of Vellin, near Thalen and Matsene." },
  { n: "Meliut", cat: "town", x: 2580, y: 1618, k: "The Kingdom of Lajazer", d: "In The Kingdom of Lajazer, about 700 mi northeast of Vellin, near Breston and Kanidon." },
  { n: "Mema", cat: "town", x: 3020, y: 1487, k: "The Kingdom of Tarmet", d: "In The Kingdom of Tarmet, about 1000 mi northwest of Bela, near Tophercris and Giagior." },
  { n: "Menejela", cat: "town", x: 4842, y: 2172, k: "The Kingdom of Tarmet", d: "In The Kingdom of Tarmet, about 575 mi east of Bela, near Saltea and Amesa." },
  { n: "Menen", cat: "town", x: 2458, y: 1654, k: "The Kingdom of Lajazer", d: "In The Kingdom of Lajazer, about 625 mi northeast of Vellin, near Wisten and Uedena." },
  { n: "Mepren", cat: "town", x: 2216, y: 2047, k: "The Kingdom of Lajazer", d: "In The Kingdom of Lajazer, about 275 mi east of Vellin, near Comei and Tineb." },
  { n: "Meprie Teish", cat: "town", x: 2195, y: 2304, k: "The Kingdom of Lajazer", d: "In The Kingdom of Lajazer, about 275 mi southeast of Vellin, near The Santie and Goteivane." },
  { n: "Minska", cat: "town", x: 3133, y: 2309, k: "The Kingdom of Civer", d: "In The Kingdom of Civer, about 100 mi north of Lorne, near Pantar and Tolm." },
  { n: "Mira", cat: "town", x: 6920, y: 1233, k: "The Kingdom of Ociyaran", d: "In The Kingdom of Ociyaran, about 250 mi east of Zada, near Colle and Burane." },
  { n: "Mireb", cat: "town", x: 5021, y: 2711, k: "The Kingdom of Tarmet", d: "In The Kingdom of Tarmet, about 875 mi southeast of Bela, near Dordbin and Demia." },
  { n: "Mossima", cat: "town", x: 3150, y: 1309, k: "The Kingdom of Tarmet", d: "In The Kingdom of Tarmet, about 975 mi northwest of Bela, near Lioe and Tophercris." },
  { n: "Mother's hip", cat: "town", x: 4299, y: 2068, k: "The Kingdom of Tarmet", d: "In The Kingdom of Tarmet, about 125 mi east of Bela, near The Inner City and Tarmeda." },
  { n: "Movo", cat: "town", x: 6182, y: 1387, k: "The Kingdom of Ociyaran", d: "In The Kingdom of Ociyaran, about 350 mi west of Zada, near Ilvo and Roi." },
  { n: "Mt. Aicren", cat: "town", x: 6678, y: 2432, k: "The Kingdom of Berlailia", d: "In The Kingdom of Berlailia, about 125 mi southwest of Hadirel, near Sahla and The Magic Tower." },
  { n: "Muralto", cat: "town", x: 6885, y: 933, k: "The Kingdom of Ociyaran", d: "In The Kingdom of Ociyaran, about 375 mi northeast of Zada, near Alpena and Ys." },
  { n: "Murok", cat: "town", x: 6359, y: 2918, k: "The Kingdom of Berlailia", d: "In The Kingdom of Berlailia, about 600 mi southwest of Hadirel, near Verna Tari and Junjeo." },
  { n: "Murra", cat: "town", x: 6313, y: 1438, k: "The Kingdom of Ociyaran", d: "In The Kingdom of Ociyaran, about 250 mi southwest of Zada, near Rewalen and Argu." },
  { n: "Muuri", cat: "town", x: 4953, y: 1917, k: "The Kingdom of Tarmet", d: "In The Kingdom of Tarmet, about 675 mi east of Bela, near Oermada and Amesa." },
  { n: "Nabuchan", cat: "town", x: 4791, y: 1059, k: "The Kingdom of Atriki", d: "In The Kingdom of Atriki, about 750 mi east of Elgan, near Sebrof and Ridal." },
  { n: "Nalchal", cat: "town", x: 4939, y: 897, k: "The Kingdom of Atriki", d: "In The Kingdom of Atriki, about 825 mi east of Elgan, near Noramec and Lefa." },
  { n: "Nalochl", cat: "town", x: 4413, y: 856, k: "The Kingdom of Atriki", d: "In The Kingdom of Atriki, about 400 mi east of Elgan, near Ilkane and Ortuqil." },
  { n: "Namilna", cat: "town", x: 6749, y: 2932, k: "The Kingdom of Berlailia", d: "In The Kingdom of Berlailia, about 500 mi south of Hadirel, near Liaerton and Gjen." },
  { n: "Nayen", cat: "town", x: 2174, y: 2132, k: "The Kingdom of Lajazer", d: "In The Kingdom of Lajazer, about 225 mi east of Vellin, near Honet and Tineb." },
  { n: "Neaea", cat: "town", x: 3422, y: 999, k: "The Kingdom of Tarmet", d: "In The Kingdom of Tarmet, about 1025 mi northwest of Bela, near Seppegiu and Corocco." },
  { n: "Negel", cat: "town", x: 4264, y: 1057, k: "The Kingdom of Atriki", d: "In The Kingdom of Atriki, about 375 mi southeast of Elgan, near Osenne and Brandhal." },
  { n: "Negiet", cat: "town", x: 6765, y: 2200, k: "The Kingdom of Berlailia", d: "In The Kingdom of Berlailia, about 100 mi north of Hadirel, near Verna Tari and Hadirel." },
  { n: "Nelva", cat: "town", x: 6385, y: 1286, k: "The Kingdom of Ociyaran", d: "In The Kingdom of Ociyaran, about 175 mi west of Zada, near Cresp and Sarn." },
  { n: "Neribe", cat: "town", x: 2053, y: 1781, k: "The Kingdom of Lajazer", d: "In The Kingdom of Lajazer, about 325 mi northeast of Vellin, near Hadber and Deyare." },
  { n: "Neska", cat: "town", x: 6607, y: 1079, k: "The Kingdom of Ociyaran", d: "In The Kingdom of Ociyaran, about 175 mi north of Zada, near Esio and Uvenza." },
  { n: "Niarn", cat: "town", x: 4612, y: 421, k: "The Kingdom of Atriki", d: "In The Kingdom of Atriki, about 600 mi northeast of Elgan, near Aresada and Gorma." },
  { n: "Nisclair", cat: "town", x: 3895, y: 652, k: "The Kingdom of Atriki", d: "In The Kingdom of Atriki, about 75 mi north of Elgan, near Elgan and Eryd." },
  { n: "Noju", cat: "town", x: 2781, y: 1641, k: "The Kingdom of Tarmet", d: "In The Kingdom of Tarmet, about 1125 mi west of Bela, near Lanmi and Apric." },
  { n: "Norabea", cat: "town", x: 5350, y: 1678, k: "The Kingdom of Tarmet", d: "In The Kingdom of Tarmet, about 1025 mi east of Bela, near Bellaria and Aryanara's territory." },
  { n: "Noraho", cat: "town", x: 2754, y: 1552, k: "The Kingdom of Tarmet", d: "In The Kingdom of Tarmet, about 1175 mi west of Bela, near Lanmi and Annagi." },
  { n: "Noramec", cat: "town", x: 4864, y: 814, k: "The Kingdom of Atriki", d: "In The Kingdom of Atriki, about 750 mi east of Elgan, near Nalchal and Lefa." },
  { n: "Nordos", cat: "town", x: 4190, y: 2288, k: "The Kingdom of Tarmet", d: "In The Kingdom of Tarmet, about 175 mi south of Bela, near Bavienna and Tanya Beka." },
  { n: "Nurida", cat: "town", x: 6390, y: 1640, k: "The Kingdom of Berlailia", d: "In The Kingdom of Berlailia, about 625 mi northwest of Hadirel, near Velu and Pratesi." },
  { n: "Nyedal", cat: "town", x: 4753, y: 1419, k: "The Kingdom of Tarmet", d: "In The Kingdom of Tarmet, about 700 mi northeast of Bela, near Tasfen and Osenk." },
  { n: "Nyeo", cat: "town", x: 2297, y: 1736, k: "The Kingdom of Lajazer", d: "In The Kingdom of Lajazer, about 475 mi northeast of Vellin, near Jaserey and The Razane." },
  { n: "Nyes", cat: "town", x: 3665, y: 1554, k: "The Kingdom of Tarmet", d: "In The Kingdom of Tarmet, about 550 mi northwest of Bela, near Rietha and The Seimaa." },
  { n: "Oa", cat: "town", x: 6014, y: 1188, k: "The Kingdom of Ociyaran", d: "In The Kingdom of Ociyaran, about 475 mi west of Zada, near Brae and Zada Patto." },
  { n: "Oahat", cat: "town", x: 2529, y: 1896, k: "The Kingdom of Lajazer", d: "In The Kingdom of Lajazer, about 550 mi east of Vellin, near Masen and Halkere." },
  { n: "Oermada", cat: "town", x: 5079, y: 2005, k: "The Kingdom of Tarmet", d: "In The Kingdom of Tarmet, about 750 mi east of Bela, near Ledea and Muuri." },
  { n: "Olbe", cat: "town", x: 2811, y: 1963, k: "The Kingdom of Civer", d: "In The Kingdom of Civer, about 475 mi northwest of Lorne, near Fesso and Baest." },
  { n: "Old Feacen", cat: "town", x: 2894, y: 2295, k: "The Kingdom of Civer", d: "In The Kingdom of Civer, about 250 mi northwest of Lorne, near Tolm and Feacen." },
  { n: "Oleji", cat: "town", x: 1653, y: 1432, k: "The Academy", d: "In The Academy, near Reo and Bordei." },
  { n: "Olune", cat: "town", x: 3553, y: 1736, k: "The Kingdom of Tarmet", d: "In The Kingdom of Tarmet, about 525 mi northwest of Bela, near Rietha and Shaer." },
  { n: "Ombretta", cat: "town", x: 5923, y: 1446, k: "The Kingdom of Ociyaran", d: "In The Kingdom of Ociyaran, about 550 mi west of Zada, near Zada Patto and Reda." },
  { n: "Ompol", cat: "town", x: 6118, y: 2602, k: "The Kingdom of Berlailia", d: "In The Kingdom of Berlailia, about 575 mi southwest of Hadirel, near Bohan and Murok." },
  { n: "Onmore", cat: "town", x: 5073, y: 438, k: "The Kingdom of Atriki", d: "In The Kingdom of Atriki, about 950 mi east of Elgan, near Lefa and Riyen." },
  { n: "Oradi", cat: "town", x: 3354, y: 1800, k: "The Kingdom of Tarmet", d: "In The Kingdom of Tarmet, about 650 mi west of Bela, near Alsea and Maadol." },
  { n: "Orcan", cat: "town", x: 2300, y: 1897, k: "The Kingdom of Lajazer", d: "In The Kingdom of Lajazer, about 400 mi northeast of Vellin, near Avege and Lajazer." },
  { n: "Orim", cat: "town", x: 4439, y: 2369, k: "The Kingdom of Tarmet", d: "In The Kingdom of Tarmet, about 350 mi southeast of Bela, near Hevetane and Thelea." },
  { n: "Orjin", cat: "town", x: 6979, y: 3166, k: "The Kingdom of Berlailia", d: "In The Kingdom of Berlailia, about 700 mi south of Hadirel, near Gjen and Qunag." },
  { n: "Ortuqil", cat: "town", x: 4421, y: 622, k: "The Kingdom of Atriki", d: "In The Kingdom of Atriki, about 400 mi east of Elgan, near Gorma and Ilkane." },
  { n: "Oryur", cat: "town", x: 4547, y: 1409, k: "The Kingdom of Tarmet", d: "In The Kingdom of Tarmet, about 625 mi northeast of Bela, near Garen and Inqua." },
  { n: "Oscana", cat: "town", x: 3480, y: 1518, k: "The Kingdom of Tarmet", d: "In The Kingdom of Tarmet, about 675 mi northwest of Bela, near Cardoric and Lujian." },
  { n: "Osegri", cat: "town", x: 3145, y: 1158, k: "The Kingdom of Tarmet", d: "In The Kingdom of Tarmet, about 1075 mi northwest of Bela, near Tenda and Rioda." },
  { n: "Osenk", cat: "town", x: 4717, y: 1293, k: "The Kingdom of Atriki", d: "In The Kingdom of Atriki, about 775 mi southeast of Elgan, near Nyedal and Sebrof." },
  { n: "Osenne", cat: "town", x: 4306, y: 1120, k: "The Kingdom of Atriki", d: "In The Kingdom of Atriki, about 425 mi southeast of Elgan, near Negel and Brandhal." },
  { n: "Oskaba", cat: "town", x: 4596, y: 2837, k: "The Kingdom of Tarmet", d: "In The Kingdom of Tarmet, about 725 mi southeast of Bela, near Tagrima and Tarask." },
  { n: "Ostara", cat: "town", x: 4049, y: 1688, k: "The Kingdom of Tarmet", d: "In The Kingdom of Tarmet, about 300 mi north of Bela, near Malea and Aluun." },
  { n: "Ostoke", cat: "town", x: 1924, y: 2025, k: "The Kingdom of Lajazer", d: "In The Kingdom of Lajazer, about 125 mi north of Vellin, near Dira and Melerte." },
  { n: "Outer Walls", cat: "town", x: 4068, y: 2092, k: "The Kingdom of Tarmet", d: "In The Kingdom of Tarmet, about 50 mi southwest of Bela, near Bela and Asmeta." },
  { n: "Palere", cat: "town", x: 2715, y: 1328, k: "The Kingdom of Lajazer", d: "In The Kingdom of Lajazer, about 950 mi northeast of Vellin, near Liviao and Baram." },
  { n: "Pampira", cat: "town", x: 6648, y: 867, k: "The Kingdom of Ociyaran", d: "In The Kingdom of Ociyaran, about 350 mi north of Zada, near Paro and Latso." },
  { n: "Pantar", cat: "town", x: 3191, y: 2357, k: "The Kingdom of Civer", d: "In The Kingdom of Civer, about 75 mi north of Lorne, near Minska and Lorne." },
  { n: "Paro", cat: "town", x: 6623, y: 805, k: "The Kingdom of Ociyaran", d: "In The Kingdom of Ociyaran, about 400 mi north of Zada, near Pampira and Latso." },
  { n: "Pelea", cat: "town", x: 4269, y: 2406, k: "The Kingdom of Tarmet", d: "In The Kingdom of Tarmet, about 300 mi south of Bela, near Nordos and Anye." },
  { n: "Pelefer", cat: "town", x: 6604, y: 1416, k: "The Kingdom of Ociyaran", d: "In The Kingdom of Ociyaran, about 100 mi south of Zada, near Pell'oro and Vin." },
  { n: "Pelefera", cat: "town", x: 6863, y: 1103, k: "The Kingdom of Ociyaran", d: "In The Kingdom of Ociyaran, about 250 mi northeast of Zada, near Squero and Chiavanto." },
  { n: "Pelk", cat: "town", x: 3398, y: 2256, k: "The Kingdom of Civer", d: "In The Kingdom of Civer, about 250 mi northeast of Lorne, near Drin and Urdey." },
  { n: "Pell'oro", cat: "town", x: 6651, y: 1329, k: "The Kingdom of Ociyaran", d: "In The Kingdom of Ociyaran, about 50 mi southeast of Zada, near Zada and Brentola." },
  { n: "Peske", cat: "town", x: 2418, y: 1738, k: "The Kingdom of Lajazer", d: "In The Kingdom of Lajazer, about 550 mi northeast of Vellin, near Uedena and Madreu." },
  { n: "Pondata", cat: "town", x: 3983, y: 2563, k: "The Kingdom of Tarmet", d: "In The Kingdom of Tarmet, about 425 mi south of Bela, near Riedra and Acin." },
  { n: "Pratesi", cat: "town", x: 6218, y: 1601, k: "The Kingdom of Ociyaran", d: "In The Kingdom of Ociyaran, about 400 mi southwest of Zada, near Grotta and Uada." },
  { n: "Querceta", cat: "town", x: 6585, y: 954, k: "The Kingdom of Ociyaran", d: "In The Kingdom of Ociyaran, about 275 mi north of Zada, near Uvenza and Port Volpa." },
  { n: "Qunag", cat: "town", x: 6987, y: 2883, k: "The Kingdom of Berlailia", d: "In The Kingdom of Berlailia, about 475 mi south of Hadirel, near Gjen and Zemel." },
  { n: "Rachia", cat: "town", x: 2900, y: 1320, k: "The Kingdom of Tarmet", d: "In The Kingdom of Tarmet, about 1150 mi northwest of Bela, near Tagre and Raiye." },
  { n: "Raiye", cat: "town", x: 2824, y: 1250, k: "The Kingdom of Tarmet", d: "In The Kingdom of Tarmet, about 1225 mi northwest of Bela, near Baram and Rachia." },
  { n: "Ralta", cat: "town", x: 4521, y: 1616, k: "The Kingdom of Tarmet", d: "In The Kingdom of Tarmet, about 475 mi northeast of Bela, near Elemea and Garen." },
  { n: "Ravia", cat: "town", x: 6096, y: 1575, k: "The Kingdom of Ociyaran", d: "In The Kingdom of Ociyaran, about 475 mi southwest of Zada, near Velsa and Yemasera." },
  { n: "Reda", cat: "town", x: 6043, y: 1353, k: "The Kingdom of Ociyaran", d: "In The Kingdom of Ociyaran, about 450 mi west of Zada, near Zada Patto and Larida." },
  { n: "Renzolo", cat: "town", x: 3642, y: 1359, k: "The Kingdom of Tarmet", d: "In The Kingdom of Tarmet, about 675 mi northwest of Bela, near Selve and Masotom." },
  { n: "Reo", cat: "town", x: 1718, y: 1474, k: "The Academy", d: "In The Academy, near Oleji and Bordei." },
  { n: "Resate", cat: "town", x: 2694, y: 1626, k: "The Kingdom of Tarmet", d: "In The Kingdom of Tarmet, about 1200 mi west of Bela, near Tellas and Genga." },
  { n: "Resia", cat: "town", x: 4039, y: 1374, k: "The Kingdom of Tarmet", d: "In The Kingdom of Tarmet, about 550 mi north of Bela, near The Maadun and Adaani." },
  { n: "Reskt", cat: "town", x: 6422, y: 2130, k: "The Kingdom of Berlailia", d: "In The Kingdom of Berlailia, about 325 mi northwest of Hadirel, near Daltsen and Sehrok." },
  { n: "Rewalen", cat: "town", x: 6338, y: 1391, k: "The Kingdom of Ociyaran", d: "In The Kingdom of Ociyaran, about 225 mi west of Zada, near Murra and Cresp." },
  { n: "Rewqo", cat: "town", x: 2413, y: 1823, k: "The Kingdom of Lajazer", d: "In The Kingdom of Lajazer, about 500 mi northeast of Vellin, near Jiego and Peske." },
  { n: "Ricna", cat: "town", x: 4340, y: 419, k: "The Kingdom of Atriki", d: "In The Kingdom of Atriki, about 425 mi northeast of Elgan, near Snurb and Aresada." },
  { n: "Ridal", cat: "town", x: 4586, y: 1083, k: "The Kingdom of Atriki", d: "In The Kingdom of Atriki, about 600 mi southeast of Elgan, near Camrudar and Nabuchan." },
  { n: "Riedra", cat: "town", x: 3946, y: 2498, k: "The Kingdom of Tarmet", d: "In The Kingdom of Tarmet, about 375 mi southwest of Bela, near Pondata and Anjelea." },
  { n: "Rietha", cat: "town", x: 3589, y: 1616, k: "The Kingdom of Tarmet", d: "In The Kingdom of Tarmet, about 550 mi northwest of Bela, near Nyes and Olune." },
  { n: "Rioda", cat: "town", x: 3283, y: 1139, k: "The Kingdom of Tarmet", d: "In The Kingdom of Tarmet, about 1000 mi northwest of Bela, near Tenda and Osegri." },
  { n: "Ristea", cat: "town", x: 4565, y: 1899, k: "The Kingdom of Tarmet", d: "In The Kingdom of Tarmet, about 375 mi east of Bela, near Laaya and Vashonna." },
  { n: "Riy", cat: "town", x: 6969, y: 1111, k: "The Kingdom of Ociyaran", d: "In The Kingdom of Ociyaran, about 325 mi northeast of Zada, near Chiavanto and Colle." },
  { n: "Riyen", cat: "town", x: 4685, y: 603, k: "The Kingdom of Atriki", d: "In The Kingdom of Atriki, about 625 mi east of Elgan, near Eskert and Niarn." },
  { n: "Roi", cat: "town", x: 6247, y: 1342, k: "The Kingdom of Ociyaran", d: "In The Kingdom of Ociyaran, about 300 mi west of Zada, near Movo and Cira." },
  { n: "Rosk", cat: "town", x: 3019, y: 2117, k: "The Kingdom of Civer", d: "In The Kingdom of Civer, about 275 mi northwest of Lorne, near Awq Tari and Jurva." },
  { n: "Rudeth", cat: "town", x: 5414, y: 2136, k: "The Kingdom of Tarmet", d: "In The Kingdom of Tarmet, about 1025 mi east of Bela, near Denkay and Dugwil." },
  { n: "Sahla", cat: "town", x: 6692, y: 2493, k: "The Kingdom of Berlailia", d: "In The Kingdom of Berlailia, about 150 mi southwest of Hadirel, near Mt. Aicren and The Magic Tower." },
  { n: "Sahlen", cat: "town", x: 6525, y: 2458, k: "The Kingdom of Berlailia", d: "In The Kingdom of Berlailia, about 250 mi southwest of Hadirel, near Byeola and Torad." },
  { n: "Saltea", cat: "town", x: 4745, y: 2253, k: "The Kingdom of Tarmet", d: "In The Kingdom of Tarmet, about 500 mi east of Bela, near Yvenna and Menejela." },
  { n: "Sarleiane", cat: "town", x: 2207, y: 1631, k: "The Kingdom of Lajazer", d: "In The Kingdom of Lajazer, about 500 mi northeast of Vellin, near Verne and Atanie." },
  { n: "Sarn", cat: "town", x: 6479, y: 1333, k: "The Kingdom of Ociyaran", d: "In The Kingdom of Ociyaran, about 100 mi west of Zada, near Vin and Nelva." },
  { n: "Sarrod", cat: "town", x: 2693, y: 1811, k: "The Kingdom of Civer", d: "In The Kingdom of Civer, about 625 mi northwest of Lorne, near Genga and Zagare." },
  { n: "Sebrof", cat: "town", x: 4824, y: 1216, k: "The Kingdom of Atriki", d: "In The Kingdom of Atriki, about 825 mi southeast of Elgan, near Osenk and Nabuchan." },
  { n: "Sehrok", cat: "town", x: 6545, y: 2304, k: "The Kingdom of Berlailia", d: "In The Kingdom of Berlailia, about 200 mi west of Hadirel, near Byeola and Daltsen." },
  { n: "Selve", cat: "town", x: 3575, y: 1429, k: "The Kingdom of Tarmet", d: "In The Kingdom of Tarmet, about 675 mi northwest of Bela, near Renzolo and Oscana." },
  { n: "Selvet", cat: "town", x: 5509, y: 2722, k: "The Kingdom of Tarmet", d: "In The Kingdom of Tarmet, about 1225 mi southeast of Bela, near Amba and Maryos." },
  { n: "Semhol", cat: "town", x: 5109, y: 1724, k: "The Kingdom of Tarmet", d: "In The Kingdom of Tarmet, about 825 mi east of Bela, near Vekta's territory and Kidaris." },
  { n: "Senalda", cat: "town", x: 6392, y: 840, k: "The Kingdom of Ociyaran", d: "In The Kingdom of Ociyaran, about 400 mi northwest of Zada, near Cala and Port Volpa." },
  { n: "Senna", cat: "town", x: 6299, y: 988, k: "The Kingdom of Ociyaran", d: "In The Kingdom of Ociyaran, about 350 mi northwest of Zada, near Cala and Sye." },
  { n: "Seppegiu", cat: "town", x: 3473, y: 1094, k: "The Kingdom of Tarmet", d: "In The Kingdom of Tarmet, about 925 mi northwest of Bela, near Coloni and Neaea." },
  { n: "Sevq", cat: "town", x: 5617, y: 2286, k: "The Kingdom of Tarmet", d: "In The Kingdom of Tarmet, about 1200 mi east of Bela, near Dahn and Hauk." },
  { n: "Shaer", cat: "town", x: 3549, y: 1871, k: "The Kingdom of Tarmet", d: "In The Kingdom of Tarmet, about 500 mi west of Bela, near Olune and Lage." },
  { n: "Sindber", cat: "town", x: 3002, y: 2552, k: "The Kingdom of Civer", d: "In The Kingdom of Civer, about 150 mi southwest of Lorne, near Drosk and LakeDulve." },
  { n: "Skya", cat: "town", x: 3808, y: 162, k: "The Kingdom of Atriki", d: "In The Kingdom of Atriki, about 475 mi north of Elgan, near Tilnyeau and Eynora." },
  { n: "Slaia", cat: "town", x: 3783, y: 433, k: "The Kingdom of Atriki", d: "In The Kingdom of Atriki, about 275 mi northwest of Elgan, near Tilnyeau and Nisclair." },
  { n: "Snurb", cat: "town", x: 4278, y: 523, k: "The Kingdom of Atriki", d: "In The Kingdom of Atriki, about 325 mi northeast of Elgan, near Ricna and Ortuqil." },
  { n: "Squero", cat: "town", x: 6895, y: 1142, k: "The Kingdom of Ociyaran", d: "In The Kingdom of Ociyaran, about 250 mi northeast of Zada, near Pelefera and Colle." },
  { n: "Sretan", cat: "town", x: 2329, y: 1295, k: "The Kingdom of Lajazer", d: "In The Kingdom of Lajazer, about 775 mi northeast of Vellin, near Veris and Borgeste." },
  { n: "Stagna", cat: "town", x: 6131, y: 1267, k: "The Kingdom of Ociyaran", d: "In The Kingdom of Ociyaran, about 375 mi west of Zada, near Ilvo and Brae." },
  { n: "Sye", cat: "town", x: 6348, y: 1050, k: "The Kingdom of Ociyaran", d: "In The Kingdom of Ociyaran, about 275 mi northwest of Zada, near Vallaforta and Senna." },
  { n: "Tagre", cat: "town", x: 2834, y: 1378, k: "The Kingdom of Tarmet", d: "In The Kingdom of Tarmet, about 1175 mi northwest of Bela, near Rachia and Giagior." },
  { n: "Tagrima", cat: "town", x: 4498, y: 2910, k: "The Kingdom of Tarmet", d: "In The Kingdom of Tarmet, about 750 mi southeast of Bela, near Oskaba and Eskua." },
  { n: "Talu", cat: "town", x: 6063, y: 1755, k: "The Kingdom of Ociyaran", d: "In The Kingdom of Ociyaran, about 575 mi southwest of Zada, near Velsa and Uada." },
  { n: "Tanya Beka", cat: "town", x: 4232, y: 2156, k: "The Kingdom of Tarmet", d: "In The Kingdom of Tarmet, about 100 mi southeast of Bela, near Bavienna and The Inner City." },
  { n: "Tarask", cat: "town", x: 4630, y: 2674, k: "The Kingdom of Tarmet", d: "In The Kingdom of Tarmet, about 625 mi southeast of Bela, near Oskaba and Druun." },
  { n: "Tarl", cat: "town", x: 3874, y: 2285, k: "The Kingdom of Tarmet", d: "In The Kingdom of Tarmet, about 275 mi southwest of Bela, near Anjelea and Lower Cosar." },
  { n: "Tarmeda", cat: "town", x: 4243, y: 2007, k: "The Kingdom of Tarmet", d: "In The Kingdom of Tarmet, about 100 mi northeast of Bela, near Malim and The Inner City." },
  { n: "Tarmet", cat: "town", x: 4027, y: 1904, k: "The Kingdom of Tarmet", d: "In The Kingdom of Tarmet, about 150 mi northwest of Bela, near Asmeta and Lendara." },
  { n: "Tasfen", cat: "town", x: 4812, y: 1515, k: "The Kingdom of Tarmet", d: "In The Kingdom of Tarmet, about 700 mi northeast of Bela, near Nyedal and Aoim." },
  { n: "Tehron", cat: "town", x: 5333, y: 1837, k: "The Kingdom of Tarmet", d: "In The Kingdom of Tarmet, about 975 mi east of Bela, near Aryanara's territory and Anthela." },
  { n: "Teirenna", cat: "town", x: 4190, y: 1774, k: "The Kingdom of Tarmet", d: "In The Kingdom of Tarmet, about 225 mi north of Bela, near Lokea and Cuola." },
  { n: "Tellas", cat: "town", x: 2665, y: 1577, k: "The Kingdom of Tarmet", d: "In The Kingdom of Tarmet, about 1225 mi west of Bela, near Resate and Noraho." },
  { n: "Tenda", cat: "town", x: 3265, y: 1220, k: "The Kingdom of Tarmet", d: "In The Kingdom of Tarmet, about 975 mi northwest of Bela, near Gelona and Rioda." },
  { n: "Tereas", cat: "town", x: 3901, y: 1965, k: "The Kingdom of Tarmet", d: "In The Kingdom of Tarmet, about 200 mi west of Bela, near Keba and Bayen." },
  { n: "Tericaer", cat: "town", x: 2096, y: 1644, k: "The Kingdom of Lajazer", d: "In The Kingdom of Lajazer, about 450 mi northeast of Vellin, near Hadber and Atanie." },
  { n: "Tesora", cat: "town", x: 6920, y: 781, k: "The Kingdom of Ociyaran", d: "In The Kingdom of Ociyaran, about 475 mi northeast of Zada, near Chiozza and Muralto." },
  { n: "Teyet", cat: "town", x: 1917, y: 2121, k: "The Kingdom of Lajazer", d: "In The Kingdom of Lajazer, about 50 mi northeast of Vellin, near Vellin and Hepen." },
  { n: "Thalen", cat: "town", x: 1809, y: 1961, k: "The Kingdom of Lajazer", d: "In The Kingdom of Lajazer, about 175 mi north of Vellin, near Matsene and Melerte." },
  { n: "Thatcke", cat: "town", x: 1028, y: 1162, k: "The Academy", d: "In The Academy, near Oleji and Reo." },
  { n: "The Aoner", cat: "town", x: 2001, y: 1854, k: "The Kingdom of Lajazer", d: "In The Kingdom of Lajazer, about 275 mi north of Vellin, near Heusel and Lene." },
  { n: "The Aonesse", cat: "town", x: 2023, y: 2056, k: "The Kingdom of Lajazer", d: "In The Kingdom of Lajazer, about 150 mi northeast of Vellin, near Liasen and Boletre  Begai." },
  { n: "The Brack", cat: "town", x: 3380, y: 1987, k: "The Kingdom of Civer", d: "In The Kingdom of Civer, about 400 mi northeast of Lorne, near Urdey and Drin." },
  { n: "The Duriaan", cat: "town", x: 3853, y: 1256, k: "The Kingdom of Tarmet", d: "In The Kingdom of Tarmet, about 675 mi north of Bela, near Gondes and Masotom." },
  { n: "The Inner City", cat: "town", x: 4226, y: 2072, k: "The Kingdom of Tarmet", d: "In The Kingdom of Tarmet, about 75 mi east of Bela, near Tarmeda and Mother's hip." },
  { n: "The Maadun", cat: "town", x: 4115, y: 1292, k: "The Kingdom of Tarmet", d: "In The Kingdom of Tarmet, about 625 mi north of Bela, near Resia and Lagowyal." },
  { n: "The Magic Tower", cat: "town", x: 6768, y: 2400, k: "The Kingdom of Berlailia", d: "In The Kingdom of Berlailia, about 75 mi south of Hadirel, near Hadirel and Mt. Aicren." },
  { n: "The Pontesi", cat: "town", x: 3541, y: 2314, k: "The Kingdom of Civer", d: "In The Kingdom of Civer, about 325 mi east of Lorne, near Durk and Pelk." },
  { n: "The Razane", cat: "town", x: 2313, y: 1779, k: "The Kingdom of Lajazer", d: "In The Kingdom of Lajazer, about 450 mi northeast of Vellin, near Nyeo and Lajazer." },
  { n: "The Santie", cat: "town", x: 2252, y: 2232, k: "The Kingdom of Lajazer", d: "In The Kingdom of Lajazer, about 300 mi east of Vellin, near Goteivane and Meprie Teish." },
  { n: "The Seimaa", cat: "town", x: 3815, y: 1539, k: "The Kingdom of Tarmet", d: "In The Kingdom of Tarmet, about 475 mi northwest of Bela, near Belune and Cymea." },
  { n: "Thelea", cat: "town", x: 4485, y: 2216, k: "The Kingdom of Tarmet", d: "In The Kingdom of Tarmet, about 300 mi southeast of Bela, near Calyea and Orim." },
  { n: "Thevia", cat: "town", x: 2892, y: 1626, k: "The Kingdom of Tarmet", d: "In The Kingdom of Tarmet, about 1050 mi west of Bela, near Apric and Iaga." },
  { n: "Thya", cat: "town", x: 2462, y: 2600, k: "The Kingdom of Civer", d: "In The Kingdom of Civer, about 575 mi west of Lorne, near Vask and Port Ols." },
  { n: "Tiamma", cat: "town", x: 3680, y: 1174, k: "The Kingdom of Tarmet", d: "In The Kingdom of Tarmet, about 800 mi northwest of Bela, near Masotom and Yuaveka." },
  { n: "Tilnyeau", cat: "town", x: 3660, y: 252, k: "The Kingdom of Atriki", d: "In The Kingdom of Atriki, about 450 mi northwest of Elgan, near Lagora and Skya." },
  { n: "Tineb", cat: "town", x: 2263, y: 2112, k: "The Kingdom of Lajazer", d: "In The Kingdom of Lajazer, about 300 mi east of Vellin, near Mepren and Nayen." },
  { n: "Tiren", cat: "town", x: 1838, y: 1636, k: "The Academy", d: "In The Academy, near Bordei and Port Besk." },
  { n: "Tolm", cat: "town", x: 3013, y: 2345, k: "The Kingdom of Civer", d: "In The Kingdom of Civer, about 150 mi northwest of Lorne, near Drosk and Minska." },
  { n: "Tophercris", cat: "town", x: 3067, y: 1414, k: "The Kingdom of Tarmet", d: "In The Kingdom of Tarmet, about 1000 mi northwest of Bela, near Mema and Anaan." },
  { n: "Torad", cat: "town", x: 6530, y: 2559, k: "The Kingdom of Berlailia", d: "In The Kingdom of Berlailia, about 275 mi southwest of Hadirel, near Galmun and Sahlen." },
  { n: "Tropie", cat: "town", x: 3408, y: 1217, k: "The Kingdom of Tarmet", d: "In The Kingdom of Tarmet, about 875 mi northwest of Bela, near Coloni and Gelona." },
  { n: "Tsenmar", cat: "town", x: 6711, y: 1510, k: "The Kingdom of Berlailia", d: "In The Kingdom of Berlailia, about 650 mi north of Hadirel, near Caduto and Pelefer." },
  { n: "Tsir", cat: "town", x: 5233, y: 2214, k: "The Kingdom of Tarmet", d: "In The Kingdom of Tarmet, about 875 mi east of Bela, near Dremk and Hagn." },
  { n: "Tusjin", cat: "town", x: 5282, y: 1976, k: "The Kingdom of Tarmet", d: "In The Kingdom of Tarmet, about 925 mi east of Bela, near Dremk and Denkay." },
  { n: "Uada", cat: "town", x: 6181, y: 1662, k: "The Kingdom of Ociyaran", d: "In The Kingdom of Ociyaran, about 450 mi southwest of Zada, near Pratesi and Grotta." },
  { n: "Uedena", cat: "town", x: 2398, y: 1690, k: "The Kingdom of Lajazer", d: "In The Kingdom of Lajazer, about 550 mi northeast of Vellin, near Peske and Valea." },
  { n: "Urdey", cat: "town", x: 3385, y: 2104, k: "The Kingdom of Civer", d: "In The Kingdom of Civer, about 325 mi northeast of Lorne, near Drin and The Brack." },
  { n: "Uvenza", cat: "town", x: 6600, y: 1013, k: "The Kingdom of Ociyaran", d: "In The Kingdom of Ociyaran, about 225 mi north of Zada, near Querceta and Neska." },
  { n: "Vagan", cat: "town", x: 4754, y: 2444, k: "The Kingdom of Tarmet", d: "In The Kingdom of Tarmet, about 575 mi southeast of Bela, near Aanye and Saltea." },
  { n: "Vagust", cat: "town", x: 5455, y: 1978, k: "The Kingdom of Tarmet", d: "In The Kingdom of Tarmet, about 1050 mi east of Bela, near Aspardo and Denkay." },
  { n: "Vaia", cat: "town", x: 2588, y: 1487, k: "The Kingdom of Tarmet", d: "In The Kingdom of Tarmet, about 1325 mi west of Bela, near Kanidon and Tellas." },
  { n: "Valea", cat: "town", x: 2370, y: 1638, k: "The Kingdom of Lajazer", d: "In The Kingdom of Lajazer, about 575 mi northeast of Vellin, near Uedena and Wisten." },
  { n: "Vallaforta", cat: "town", x: 6300, y: 1082, k: "The Kingdom of Ociyaran", d: "In The Kingdom of Ociyaran, about 300 mi northwest of Zada, near Lun and Sye." },
  { n: "Vashonna", cat: "town", x: 4442, y: 1829, k: "The Kingdom of Tarmet", d: "In The Kingdom of Tarmet, about 300 mi northeast of Bela, near Elemea and Ristea." },
  { n: "Vask", cat: "town", x: 2434, y: 2428, k: "The Kingdom of Civer", d: "In The Kingdom of Civer, about 575 mi west of Lorne, near Laone and Thya." },
  { n: "Vekta's territory", cat: "town", x: 5069, y: 1645, k: "The Kingdom of Tarmet", d: "In The Kingdom of Tarmet, about 825 mi northeast of Bela, near Semhol and Amberactserun." },
  { n: "Velsa", cat: "town", x: 6059, y: 1619, k: "The Kingdom of Ociyaran", d: "In The Kingdom of Ociyaran, about 500 mi southwest of Zada, near Ravia and Yemasera." },
  { n: "Velu", cat: "town", x: 6375, y: 1520, k: "The Kingdom of Ociyaran", d: "In The Kingdom of Ociyaran, about 250 mi southwest of Zada, near Murra and Argu." },
  { n: "Veris", cat: "town", x: 2255, y: 1308, k: "The Kingdom of Lajazer", d: "In The Kingdom of Lajazer, about 750 mi northeast of Vellin, near Sretan and Lermea." },
  { n: "Verna Tari", cat: "town", x: 6505, y: 2813, k: "The Kingdom of Berlailia", d: "In The Kingdom of Berlailia, about 450 mi southwest of Hadirel, near Junjeo and Murok." },
  { n: "Verna Tari", cat: "town", x: 6879, y: 2160, k: "The Kingdom of Berlailia", d: "In The Kingdom of Berlailia, about 150 mi northeast of Hadirel, near Negiet and Gogla." },
  { n: "Verne", cat: "town", x: 2262, y: 1661, k: "The Kingdom of Lajazer", d: "In The Kingdom of Lajazer, about 500 mi northeast of Vellin, near Jaserey and Hashren." },
  { n: "Vigila", cat: "town", x: 6476, y: 1164, k: "The Kingdom of Ociyaran", d: "In The Kingdom of Ociyaran, about 150 mi northwest of Zada, near Corsa and Gabbia." },
  { n: "Vin", cat: "town", x: 6486, y: 1418, k: "The Kingdom of Ociyaran", d: "In The Kingdom of Ociyaran, about 150 mi southwest of Zada, near Sarn and Pelefer." },
  { n: "Vinalta", cat: "town", x: 6682, y: 976, k: "The Kingdom of Ociyaran", d: "In The Kingdom of Ociyaran, about 250 mi north of Zada, near Doresi and Jhera." },
  { n: "Weca", cat: "town", x: 2440, y: 1285, k: "The Kingdom of Lajazer", d: "In The Kingdom of Lajazer, about 825 mi northeast of Vellin, near Bion and Borgeste." },
  { n: "Welk", cat: "town", x: 2720, y: 2369, k: "The Kingdom of Civer", d: "In The Kingdom of Civer, about 350 mi west of Lorne, near Hulber and Old Feacen." },
  { n: "Wisten", cat: "town", x: 2429, y: 1596, k: "The Kingdom of Lajazer", d: "In The Kingdom of Lajazer, about 625 mi northeast of Vellin, near Isece and Menen." },
  { n: "Yemasera", cat: "town", x: 6124, y: 1508, k: "The Kingdom of Ociyaran", d: "In The Kingdom of Ociyaran, about 425 mi southwest of Zada, near Grotta and Ravia." },
  { n: "Yleka", cat: "town", x: 4037, y: 365, k: "The Kingdom of Atriki", d: "In The Kingdom of Atriki, about 300 mi north of Elgan, near Eryd and Slaia." },
  { n: "Ys", cat: "town", x: 7002, y: 973, k: "The Kingdom of Ociyaran", d: "In The Kingdom of Ociyaran, about 400 mi northeast of Zada, near Chiavanto and Muralto." },
  { n: "Yuaveka", cat: "town", x: 3635, y: 1056, k: "The Kingdom of Atriki", d: "In The Kingdom of Atriki, about 350 mi southwest of Elgan, near Tiamma and Port Theli." },
  { n: "Yula", cat: "town", x: 6858, y: 2601, k: "The Kingdom of Berlailia", d: "In The Kingdom of Berlailia, about 225 mi south of Hadirel, near Gaedu and Zemel." },
  { n: "Yvenna", cat: "town", x: 4664, y: 2171, k: "The Kingdom of Tarmet", d: "In The Kingdom of Tarmet, about 425 mi east of Bela, near Saltea and Aanye." },
  { n: "Zada Patto", cat: "town", x: 5988, y: 1310, k: "The Kingdom of Ociyaran", d: "In The Kingdom of Ociyaran, about 500 mi west of Zada, near Reda and Brae." },
  { n: "Zagare", cat: "town", x: 2535, y: 1776, k: "The Kingdom of Lajazer", d: "In The Kingdom of Lajazer, about 600 mi northeast of Vellin, near Casqen Zaeri and Masen." },
  { n: "Zattera", cat: "town", x: 6697, y: 735, k: "The Kingdom of Ociyaran", d: "In The Kingdom of Ociyaran, about 450 mi north of Zada, near Latso and Paro." },
  { n: "Zemel", cat: "town", x: 6900, y: 2719, k: "The Kingdom of Berlailia", d: "In The Kingdom of Berlailia, about 325 mi south of Hadirel, near Yula and Qunag." },
  { n: "Zerpe", cat: "town", x: 3704, y: 1917, k: "The Kingdom of Tarmet", d: "In The Kingdom of Tarmet, about 350 mi west of Bela, near Cerby and Lage." },
  { n: "Durisea", cat: "water", x: 3844, y: 1361, k: "The Kingdom of Tarmet", d: "A body of water off The Kingdom of Tarmet." },
  { n: "Honloor Lake", cat: "water", x: 4338, y: 1468, k: "The Kingdom of Tarmet", d: "A body of water off The Kingdom of Tarmet." },
  { n: "Lake Bron", cat: "water", x: 3309, y: 2333, k: "The Kingdom of Civer", d: "A body of water off The Kingdom of Civer." },
  { n: "Lake Dulbron", cat: "water", x: 2546, y: 2494, k: "The Kingdom of Civer", d: "A body of water off The Kingdom of Civer." },
  { n: "Lake Oshei", cat: "water", x: 1432, y: 1972, k: "The Cidet", d: "The sacred lake in the north of the Cidet; its purifying waters feed the temple's ritual-bathing pools." },
  { n: "Lake Traan", cat: "water", x: 4109, y: 807, k: "The Kingdom of Atriki", d: "A body of water off The Kingdom of Atriki." },
  { n: "Rium Harbor", cat: "water", x: 4862, y: 695, k: "", d: "A body of water." },
  { n: "The Fetora Sea", cat: "water", x: 3190, y: 3169, k: "", d: "The southern sea, along the continent's southern coast." },
  { n: "The Henem Bay", cat: "water", x: 4793, y: 278, k: "The Kingdom of Atriki", d: "The northern bay, off the Kingdom of Atriki; the north's access to the sea." },
  { n: "The Oberya Sea", cat: "water", x: 7374, y: 852, k: "", d: "The northeastern sea, off the Kingdoms of Ociyaran and Berlailia; a long-distance trade route." },
  { n: "The Ospe Bay", cat: "water", x: 1450, y: 2477, k: "The Cidet", d: "The bay Port Yure sits on; the pilgrim-landing coast of the Cidet." },
  { n: "The Quather Sea", cat: "water", x: 2081, y: 529, k: "", d: "The northwestern sea, off the western coast of the Kingdom of Lajazer; a primary fishing ground and trade route." },
  { n: "The Academy", cat: "island", x: 1842, y: 1452, k: "The Academy", d: "The island academy off the western coast; its grounds are ringed by the Barriers." },
  { n: "Abrenna Forest", cat: "forest", x: 3780, y: 1467, k: "The Kingdom of Tarmet", d: "A forest in The Kingdom of Tarmet." },
  { n: "Aro Forest", cat: "forest", x: 6739, y: 1060, k: "The Kingdom of Ociyaran", d: "A forest in The Kingdom of Ociyaran." },
  { n: "Hersa Forest", cat: "forest", x: 2005, y: 1506, k: "The Academy", d: "A forest in The Academy." },
  { n: "Ilmae Forest", cat: "forest", x: 1441, y: 2061, k: "The Cidet", d: "The sacred grove of the Cidet." },
  { n: "Nedi Forest", cat: "forest", x: 6092, y: 1675, k: "The Kingdom of Ociyaran", d: "A forest in The Kingdom of Ociyaran." },
  { n: "Omhan Forest", cat: "forest", x: 2023, y: 2235, k: "The Kingdom of Lajazer", d: "A forest in The Kingdom of Lajazer." },
  { n: "Seldan Forest", cat: "forest", x: 4750, y: 993, k: "The Kingdom of Atriki", d: "A forest in The Kingdom of Atriki." },
  { n: "Silora forest", cat: "forest", x: 6717, y: 2559, k: "The Kingdom of Berlailia", d: "A forest in The Kingdom of Berlailia." },
  { n: "The Caporiolan Forest", cat: "forest", x: 4872, y: 1586, k: "The Kingdom of Tarmet", d: "A forest in The Kingdom of Tarmet." },
  { n: "Tigrei Forest", cat: "forest", x: 3317, y: 1671, k: "The Kingdom of Tarmet", d: "A forest in The Kingdom of Tarmet." },
  { n: "Aseri Minqa", cat: "territory", x: 2315, y: 1842, k: "The Kingdom of Lajazer", d: "A sacred site (aseri) in The Kingdom of Lajazer." },
  { n: "Aseri Oshana", cat: "territory", x: 2162, y: 1863, k: "The Kingdom of Lajazer", d: "A sacred site (aseri) in The Kingdom of Lajazer." },
  { n: "Aseri Oshei", cat: "territory", x: 1377, y: 2295, k: "The Cidet", d: "The holy city of the Cidet; the pilgrim settlement that grew up around the Temple of the Gods." },
  { n: "The Cidet", cat: "territory", x: 1395, y: 2128, k: "The Cidet", d: "The holy island: a sacred-neutral territory governed by the Danepelie; a holy city and temple ringed by sacred wilds." },
  { n: "Thult", cat: "territory", x: 1313, y: 2705, k: "Thult", d: "A sacred, neutral island of the far southwest; once the Mystic Isles, renamed Thult." },
  { n: "Academy Building", cat: "landmark", x: 1958, y: 1374, k: "The Academy", d: "On the grounds of the Academy." },
  { n: "Cafe Iri", cat: "landmark", x: 1742, y: 1502, k: "The Academy", d: "On the grounds of the Academy." },
  { n: "Dor Tari Naos", cat: "landmark", x: 5319, y: 1887, k: "The Kingdom of Tarmet", d: "A temple (naos) in The Kingdom of Tarmet." },
  { n: "Female Dorms", cat: "landmark", x: 2023, y: 1338, k: "The Academy", d: "On the grounds of the Academy." },
  { n: "Fourth Barrier", cat: "landmark", x: 1988, y: 1272, k: "The Academy", d: "One of the Barriers that ring the Academy." },
  { n: "Ilkai Naos", cat: "landmark", x: 4546, y: 1013, k: "The Kingdom of Atriki", d: "A temple (naos) in The Kingdom of Atriki." },
  { n: "Library", cat: "landmark", x: 1898, y: 1306, k: "The Academy", d: "On the grounds of the Academy." },
  { n: "Main Barrier", cat: "landmark", x: 1952, y: 1404, k: "The Academy", d: "One of the Barriers that ring the Academy." },
  { n: "Male Dorms", cat: "landmark", x: 2008, y: 1308, k: "The Academy", d: "On the grounds of the Academy." },
  { n: "Naos Adwe", cat: "landmark", x: 5344, y: 2348, k: "The Kingdom of Tarmet", d: "A temple (naos) in The Kingdom of Tarmet." },
  { n: "Naosic", cat: "landmark", x: 5403, y: 1756, k: "The Kingdom of Tarmet", d: "A temple (naos) in The Kingdom of Tarmet." },
  { n: "Nyeo Naos", cat: "landmark", x: 2256, y: 1749, k: "The Kingdom of Lajazer", d: "A temple (naos) in The Kingdom of Lajazer." },
  { n: "Oshei Naos", cat: "landmark", x: 1362, y: 2237, k: "The Cidet", d: "The Temple of the Gods itself, on the Cidet; it holds the Hall of Twelve, the Room of Glory, the Hero's Hall, the shrines, the priests' quarters, the pilgrim hostels and the private royal chambers." },
  { n: "Second Barrier", cat: "landmark", x: 1842, y: 1497, k: "The Academy", d: "One of the Barriers that ring the Academy." },
  { n: "Tehr Tari Naos", cat: "landmark", x: 5022, y: 1385, k: "The Kingdom of Tarmet", d: "A temple (naos) in The Kingdom of Tarmet." },
  { n: "Third Barrier", cat: "landmark", x: 1661, y: 1388, k: "The Academy", d: "One of the Barriers that ring the Academy." },
  { n: "Training Grounds", cat: "landmark", x: 1974, y: 1589, k: "The Academy", d: "On the grounds of the Academy." },
  { n: "World Portal", cat: "landmark", x: 1212, y: 2564, k: "Thult", d: "A world portal on Thult, the mystic isle." },
  { n: "World Portal", cat: "landmark", x: 1543, y: 2778, k: "Thult", d: "A world portal on Thult, the mystic isle." },
  { n: "Zopha Naos", cat: "landmark", x: 6917, y: 848, k: "The Kingdom of Ociyaran", d: "A temple (naos) in The Kingdom of Ociyaran." },
];

const PRESENT_STATES = [
  { n: "The Kingdom of Lajazer", capital: "Vellin", d: "The western kingdom; once the sun-kingdom of Aicruae, later the Tanan Grand Duchy. Capital: Vellin.", biomes: ["Grassland","Temperate deciduous forest","Taiga","Wetland"] },
  { n: "The Kingdom of Civer", capital: "Lorne", d: "Once Pireaynea, the 'Demon's Pit,' later Lingia. Capital: Lorne.", biomes: ["Grassland","Temperate deciduous forest","Taiga","Wetland"] },
  { n: "The Kingdom of Atriki", capital: "Elgan", d: "Once Coelum, the 'Forsaken Land,' later Hikai. Capital: Elgan.", biomes: ["Grassland","Temperate deciduous forest","Taiga","Wetland"] },
  { n: "The Kingdom of Tarmet", capital: "Bela", d: "The old theocratic heartland; once Gherci, later the Caporiolan Kingdom and seat of the empire. Capital: Bela.", biomes: ["Grassland","Temperate deciduous forest","Taiga","Wetland"] },
  { n: "The Kingdom of Ociyaran", capital: "Zada", d: "Once Equateiy, the banking 'Kingdom of Gold,' later the Uxridian Grand Duchy. Capital: Zada.", biomes: ["Grassland","Temperate deciduous forest","Taiga","Wetland"] },
  { n: "The Kingdom of Berlailia", capital: "Hadirel", d: "Once Vikitsv, the mountain magocracy of Mount Aicren, later Theolisseia. Capital: Hadirel.", biomes: ["Grassland","Temperate deciduous forest","Taiga","Wetland"] },
];
